### ISSUE TITLE
filmon plugin issue still there

### ISSUE THREAD

**Issue by maanich** [streamlink/streamlink#1870] opened 2018-06-28 15:42 UTC
```
[hls muxer @ 0x5ced280] failed to delete old segment /mnt/hls/bbc71.ts: No such file or directory
[hls @ 0x5ce7d40] Opening '/mnt/hls/bbc79.ts' for writing
[hls @ 0x5ce7d40] Opening '/mnt/hls/bbc.m3u8.tmp' for writing
/usr/local/lib/python2.7/dist-packages/urllib3-1.22-py2.7.egg/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings InsecureRequestWarning)
/usr/local/lib/python2.7/dist-packages/urllib3-1.22-py2.7.egg/urllib3/connectionp  ool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings InsecureRequestWarning)
/usr/local/lib/python2.7/dist-packages/urllib3-1.22-py2.7.egg/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings InsecureRequestWarning)
/usr/local/lib/python2.7/dist-packages/urllib3-1.22-py2.7.egg/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings InsecureRequestWarning)
error: Error when reading from stream: Read timeout, exiting
[cli][info] Stream ended
[cli][info] Closing currently open stream...
[hls muxer @ 0x5ced280] failed to delete old segment /mnt/hls/bbc72.ts: No such f  ile or directory
[hls @ 0x5ce7d40] Opening '/mnt/hls/bbc.m3u8.tmp' for writing
frame=20047 fps= 26 q=-1.0 Lsize=N/A time=00:13:22.01 bitrate=N/A speed=1.02x
video:96480kB audio:12
```
improved time for 3 min to 6 mins n then crashed

**Comment by beardypig** [comment] 2018-06-28 15:53
> time=00:13:22.01

Looks like it ran for 13 minutes before failing.

**Comment by maanich** [comment] 2018-06-28 15:55
some time times is not fixed of nowi tried and it not last 2 min bbcone  football match  max i saw was 8 mi beofre it fails

**Comment by back-to** [comment] 2018-06-28 17:30
there **server** was probably **overloaded**,

could it only reproduce once

```
streamlink.exceptions.PluginError: Unable to open URL:
http://www.filmon.com/api-v2/channel/XX?protocol=hls
(504 Server Error: Gateway Time-out for url:
http://www.filmon.com/api-v2/channel/XX?protocol=hls)
```

so not a real issue of streamlink.

**Comment by beardypig** [comment] 2018-06-28 17:55
I also experienced that error @back-to

**Comment by maanich** [comment] 2018-06-28 18:14
a friend of mine using a php script n its worki g perfect  only issue i hv no access to it  .looxxx

**Comment by bastimeyer** [comment] 2018-07-23 11:40
> so not a real issue of streamlink.

Well, then let's close this thread.

**Closed by bastimeyer** 2018-07-23 11:40 UTC
Labels: more info required
