### ISSUE TITLE
cli: --output and --player-external-http

### ISSUE THREAD

**Issue by kkm** [streamlink/streamlink#5031] opened 2022-12-15 09:20 UTC
### Checklist

- [X] This is a feature request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Description

Is it possible to record and player-external-http at the time?

**Comment by bastimeyer** [comment] 2022-12-15 09:48
No, it's not.
Duplicate of #4371

**Closed by bastimeyer** 2022-12-15 09:48 UTC
Labels: feature request
