### ISSUE TITLE
Streamlink misdetects this youtube video as protected

### ISSUE THREAD

**Issue by LoneFox78** [streamlink/streamlink#584] opened 2017-02-15 08:33 UTC
```
streamlink https://www.youtube.com/watch?v=PCWyP_qL16g best
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=PCWyP_qL16g
error: This plugin does not support protected videos, try youtube-dl instead
```
The web page doesn't say it is protected. Also, youtube-dl is able to download it without any problems, no need to login or anything.

**Comment by bastimeyer** [comment] 2017-02-15 10:48
Duplicate of #203 
Also see https://github.com/streamlink/streamlink/issues/564#issuecomment-278980948

**Comment by LoneFox78** [comment] 2017-02-15 11:08
Oops, sorry about the duplicate...

Anyway, I think the error message is misleading and should be changed. To me "protected" means that youtube shows the big red error message that says you cannot watch the video because it is protected (which I believe means that you need to be logged in to see it and possibly the uploader needs to whitelist you). If streamlink can't handle it for some other reason, then the error message should tell that reason.

**Comment by gravyboat** [comment] 2017-09-09 02:42
Closing since it's a duplicate.

**Closed by gravyboat** 2017-09-09 02:42 UTC
Labels: duplicate
