### ISSUE TITLE
plugins.rtve: Failed to create decryptor: Unable to decrypt cipher SAMPLE-AES

### ISSUE THREAD

**Issue by va2dim** [streamlink/streamlink#5612] opened 2023-10-14 12:55 UTC
### Checklist

- [X] This is a [plugin issue](https://streamlink.github.io/plugins.html) and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

streamlink 6.2.1

### Description

**support for m4s (rtve.es)**

fail with
$ streamlink -l debug https://www.rtve.es/play/videos/cuentame-como-paso/cuentame-como-paso-t1-capitulo-7/385850/ best

(under MacOS Sonoma, streamlink, ffmpeg installed through brew)
with m3u8 from this site work fine

### Debug log

```text
[cli][debug] OS:         macOS 14.0
[cli][debug] Python:     3.11.6
[cli][debug] OpenSSL:    OpenSSL 3.1.3 19 Sep 2023
[cli][debug] Streamlink: 6.2.1
[cli][debug] Dependencies:
[cli][debug]  certifi: 2023.7.22
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.3
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.19.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.31.0
[cli][debug]  trio: 0.22.2
[cli][debug]  trio-websocket: 0.11.1
[cli][debug]  typing-extensions: 4.8.0
[cli][debug]  urllib3: 2.0.6
[cli][debug]  websocket-client: 1.6.3
[cli][debug] Arguments:
[cli][debug]  url=https://www.rtve.es/play/videos/cuentame-como-paso/cuentame-como-paso-t1-capitulo-7/385850/
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][info] Found matching plugin rtve for URL https://www.rtve.es/play/videos/cuentame-como-paso/cuentame-como-paso-t1-capitulo-7/385850/
[utils.l10n][debug] Language code: ru_RU
[stream.ffmpegmux][debug] ffmpeg version 6.0 Copyright (c) 2000-2023 the FFmpeg developers
[stream.ffmpegmux][debug]  built with Apple clang version 15.0.0 (clang-1500.0.40.1)
[stream.ffmpegmux][debug]  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/6.0_1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon
[stream.ffmpegmux][debug]  libavutil      58.  2.100 / 58.  2.100
[stream.ffmpegmux][debug]  libavcodec     60.  3.100 / 60.  3.100
[stream.ffmpegmux][debug]  libavformat    60.  3.100 / 60.  3.100
[stream.ffmpegmux][debug]  libavdevice    60.  1.100 / 60.  1.100
[stream.ffmpegmux][debug]  libavfilter     9.  3.100 /  9.  3.100
[stream.ffmpegmux][debug]  libswscale      7.  1.100 /  7.  1.100
[stream.ffmpegmux][debug]  libswresample   4. 10.100 /  4. 10.100
[stream.ffmpegmux][debug]  libpostproc    57.  1.100 / 57.  1.100
[stream.hls][debug] Using external audio tracks for stream 720p (language=es, name=Español)
[stream.hls][debug] Using external audio tracks for stream 576p (language=es, name=Español)
[stream.hls][debug] Using external audio tracks for stream 360p (language=es, name=Español)
[cli][info] Available streams: 360p (worst), 576p, 720p (best)
[cli][info] Opening stream: 720p (hls-multi)
[cli][info] Starting player: /opt/homebrew/Caskroom/vlc/3.0.18/vlc.wrapper.sh
[stream.ffmpegmux][debug] Opening hls substream
[stream.hls][debug] Reloading playlist
[stream.ffmpegmux][debug] Opening hls substream
[stream.hls][debug] Reloading playlist
[utils.named_pipe][info] Creating pipe streamlinkpipe-60157-1-4734
[utils.named_pipe][info] Creating pipe streamlinkpipe-60157-2-910
[stream.ffmpegmux][debug] ffmpeg command: /opt/homebrew/bin/ffmpeg -nostats -y -i /var/folders/sf/dzsgw4ms36z529dv8nds0b280000gn/T/streamlinkpipe-60157-1-4734 -i /var/folders/sf/dzsgw4ms36z529dv8nds0b280000gn/T/streamlinkpipe-60157-2-910 -c:v copy -c:a copy -map 0:v? -map 0:a? -map 1:a -f mpegts pipe:1
[stream.ffmpegmux][debug] Starting copy to pipe: /var/folders/sf/dzsgw4ms36z529dv8nds0b280000gn/T/streamlinkpipe-60157-1-4734
[stream.ffmpegmux][debug] Starting copy to pipe: /var/folders/sf/dzsgw4ms36z529dv8nds0b280000gn/T/streamlinkpipe-60157-2-910
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] First Sequence: 0; Last Sequence: 732
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 0; End Sequence: 732
[stream.hls][debug] Adding segment 0 to queue
[stream.hls][debug] Adding segment 1 to queue
[stream.hls][debug] Adding segment 2 to queue
[stream.hls][debug] Adding segment 3 to queue
[stream.hls][debug] Adding segment 4 to queue
[stream.hls][debug] Adding segment 5 to queue
[stream.hls][debug] Adding segment 6 to queue
[stream.hls][debug] Adding segment 7 to queue
[stream.hls][debug] Adding segment 8 to queue
[stream.hls][debug] Adding segment 9 to queue
[stream.hls][debug] Adding segment 10 to queue
[stream.hls][debug] Adding segment 11 to queue
[stream.hls][debug] Adding segment 12 to queue
[stream.hls][debug] Adding segment 13 to queue
[stream.hls][debug] Adding segment 14 to queue
[stream.hls][debug] Adding segment 15 to queue
[stream.hls][debug] Adding segment 16 to queue
[stream.hls][debug] Adding segment 17 to queue
[stream.hls][debug] Adding segment 18 to queue
[stream.hls][debug] Adding segment 19 to queue
[stream.hls][debug] Adding segment 20 to queue
[stream.hls][debug] Adding segment 21 to queue
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] First Sequence: 0; Last Sequence: 732
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 0; End Sequence: 732
[stream.hls][debug] Adding segment 0 to queue
[stream.hls][debug] Adding segment 1 to queue
[stream.hls][debug] Adding segment 2 to queue
[stream.hls][debug] Adding segment 3 to queue
[stream.hls][debug] Adding segment 4 to queue
[stream.hls][debug] Adding segment 5 to queue
[stream.hls][debug] Adding segment 6 to queue
[stream.hls][debug] Adding segment 7 to queue
[stream.hls][debug] Adding segment 8 to queue
[stream.hls][debug] Adding segment 9 to queue
[stream.hls][debug] Adding segment 10 to queue
[stream.hls][debug] Adding segment 11 to queue
[stream.hls][debug] Adding segment 12 to queue
[stream.hls][debug] Adding segment 13 to queue
[stream.hls][debug] Adding segment 14 to queue
[stream.hls][debug] Adding segment 15 to queue
[stream.hls][debug] Adding segment 16 to queue
[stream.hls][debug] Adding segment 17 to queue
[stream.hls][debug] Adding segment 18 to queue
[stream.hls][debug] Adding segment 19 to queue
[stream.hls][debug] Adding segment 20 to queue
[stream.hls][debug] Adding segment 21 to queue
[stream.hls][debug] Writing segment 0 to output
[stream.hls][error] Failed to create decryptor: Unable to decrypt cipher SAMPLE-AES
[stream.segmented][debug] Closing writer thread
[stream.segmented][debug] Closing worker thread
[stream.hls][debug] Writing segment 0 to output
[stream.hls][error] Failed to create decryptor: Unable to decrypt cipher SAMPLE-AES
[stream.segmented][debug] Closing writer thread
[stream.segmented][debug] Closing worker thread
[stream.ffmpegmux][debug] Pipe copy complete: /var/folders/sf/dzsgw4ms36z529dv8nds0b280000gn/T/streamlinkpipe-60157-1-4734
[stream.ffmpegmux][debug] Closing ffmpeg thread
[stream.ffmpegmux][debug] Closed all the substreams

[cli][error] Try 1/1: Could not open stream <MuxedHLSStream ['hls-multi', 'https://rtvedrmstaging.rtve.es/50/58/385850/385850_drm.m3u8?idasset=385850']> (No data returned from stream)
error: Could not open stream <MuxedHLSStream ['hls-multi', 'https://rtvedrmstaging.rtve.es/50/58/385850/385850_drm.m3u8?idasset=385850']>, tried 1 times, exiting
[cli][info] Closing currently open stream...
```

**Comment by bastimeyer** [comment] 2023-10-14 12:57
Duplicate of #5283

> [stream.hls][error] Failed to create decryptor: Unable to decrypt cipher SAMPLE-AES

Encrypted HLS streams using SAMPLE-AES are unsupported.
https://github.com/streamlink/streamlink/issues/5283#issuecomment-1502090339

**Closed by bastimeyer** 2023-10-14 12:57 UTC
Labels: plugin issue
