### ISSUE TITLE
BTSport broken

### ISSUE THREAD

**Issue by whittinghamj** [streamlink/streamlink#3162] opened 2020-09-10 05:08 UTC
## Bug Report

- [ x] This is a bug report and I have read the contribution guidelines.

### Description

btsport plugin fails login

### Expected / Actual behavior

login should work but does not

### Reproduction steps / Explicit stream URLs to test

streamlink --hls-live-restart --player-external-http --player-external-http-port '1372' --btsports-email 'xxxx@hotmail.co.uk' --btsports-password 'xxxxxx' --url 'https://sport.bt.com/btsportplayer/bt-sportespn-01363810201883' --default-stream '1080p,720p,480p,best' --loglevel debug
[cli][info] streamlink is running as root! Be careful!
[cli][debug] OS:         Linux-4.15.0-117-generic-x86_64-with-Ubuntu-18.04-bionic
[cli][debug] Python:     3.6.9
[cli][debug] Streamlink: 1.5.0
[cli][debug] Requests(2.18.4), Socks(1.6.5), Websocket(0.44.0)
[cli][info] Found matching plugin btsports for URL https://sport.bt.com/btsportplayer/bt-sportespn-01363810201883
[cli][debug] Plugin specific arguments:
[cli][debug]  --btsports-email=xxxxx@hotmail.co.uk (email)
[cli][debug]  --btsports-password=******** (password)
[plugin.btsports][debug] Logging in as xxxxx@hotmail.co.uk
error: Unable to open URL: https://signin1.bt.com/siteminderagent/forms/login.fcc (('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',)))

### Log output

streamlink --hls-live-restart --player-external-http --player-external-http-port '1372' --btsports-email 'xxxx@hotmail.co.uk' --btsports-password 'arsenal1983' --url 'https://sport.bt.com/btsportplayer/bt-sportespn-01363810201883' --default-stream '1080p,720p,480p,best,admin1372' --loglevel debug
[cli][info] streamlink is running as root! Be careful!
[cli][debug] OS:         Linux-4.15.0-117-generic-x86_64-with-Ubuntu-18.04-bionic
[cli][debug] Python:     3.6.9
[cli][debug] Streamlink: 1.5.0
[cli][debug] Requests(2.18.4), Socks(1.6.5), Websocket(0.44.0)
[cli][info] Found matching plugin btsports for URL https://sport.bt.com/btsportplayer/bt-sportespn-01363810201883
[cli][debug] Plugin specific arguments:
[cli][debug]  --btsports-email=xxxxx@hotmail.co.uk (email)
[cli][debug]  --btsports-password=******** (password)
[plugin.btsports][debug] Logging in as xxxxx@hotmail.co.uk
error: Unable to open URL: https://signin1.bt.com/siteminderagent/forms/login.fcc (('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',)))

REPLACE THIS TEXT WITH THE LOG OUTPUT
```


### Additional comments, screenshots, etc.



[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by mkbloke** [comment] 2020-09-10 13:59
Unfortunately, the btsports plugin seems to have been broken for a while now.  See also: #2946

It's probably only going to get fixed if somebody with an account can make the necessary changes to the plugin code.

**Comment by whittinghamj** [comment] 2020-09-10 17:28
Oh, I was not aware that it was broken.

I might have a poke around and see if I can make some progress myself. Thanks for the reply.

**Comment by mkbloke** [comment] 2020-09-10 17:57
It *might* be worth pinging beardy-pig on that other issue, he could have work in progress as he self assigned the issue, although that was back in early May.

**Comment by bastimeyer** [comment] 2020-09-11 10:03
Closing, as it's a duplicate of #2946

**Closed by bastimeyer** 2020-09-11 10:03 UTC
