### ISSUE TITLE
PSVue plugin?

### ISSUE THREAD

**Issue by jacob1218** [streamlink/streamlink#160] opened 2016-11-12 19:38 UTC
I want to have a PSVue plugin, because right now, it requests a auth from key.totsuko.tv, but instead recives a 401 code.

**Comment by beardypig** [comment] 2016-11-12 20:02
I assume you are talking about the PlayStation Live TV service? I don't have a subscription, but with a bit more information we might be able to tell if it is possible or not. 
Do you have any more information about the request it makes? How did you find out that it makes that request? What are you using to access the service? 
I would assume that the streams would be encrypted and,  at the moment, we might not be able to support decrypting them.

**Comment by jacob1218** [comment] 2016-11-12 20:05
no, i do not have anymore info about the request, how i found it was through livestreamer requesting it, and i use the browser client. yes, they are encrypted

**Comment by beardypig** [comment] 2016-11-12 20:08
I see. How did you invoke livestreamer, which URL did you tell it to open?

**Comment by jacob1218** [comment] 2016-11-12 20:15
I invoked Livestreamer via CLI, and I cant give the link out, however I can tell you that they are HLS streams, for all channels, and all of them run through totsuko.

**Comment by beardypig** [comment] 2016-11-12 20:25
OK. When you watch it in the browser (which browser do you use?), are you able to turn the developer tools on to see the key request that it makes? If so you might be able to grab the cookie header and get `streamlink` to use the cookie to auth and get the key, either with `--http-cookie` or `--http-header`.

**Comment by jacob1218** [comment] 2016-11-12 20:57
I found the cookie, but i get a pyCrypto required message with streamlink. I installed it, but it wont pick it up.

**Comment by jacob1218** [comment] 2016-11-12 21:01
Another reason they require totsuko is EPG services.

**Comment by jacob1218** [comment] 2016-11-12 21:12
OK, so I got pyCrypto installed, but totsuko still returns a 401 code.

**Comment by beardypig** [comment] 2016-11-12 21:20
Well, sounds like it might work. Maybe there are some other headers you need to include, or the cookie header was sent correctly. How did you set it? Paste the command you ran (replace the sensitive stuff with *). I'll have to sign up for an account to write a plugin though.

**Comment by jacob1218** [comment] 2016-11-12 21:22
>streamlink hls://*/PROD01/sony/NBC_NBCSPORTSNETWORK/live/2016/10/25/4942649/4500K/4500_slide.m3u8 best --http-cookie reqPayload="iaodNwtkT225JhvKtpRLb+jpeFpWv4aiQAGGeKu0UO0xAsJdu4leyx6jabp7vz5j0CEp4+I75PywzavUSCKB7FMPWl4iJvbZMsYWMk+YqftPFoteInOwFcMMKUJfq3NVgDw3s7WJBAVYjA7EPdVG+q7kiLi/9t12ERIY9n6vplh+BhlTi6kLqjjraZnny32Rc/1yAMmcvT0rWQ66gpjYefiyi6Lh+sZk8jbEwnINDTvaAGg78AQCMAo39e+sFEAr3C6oRNuDhlW9qQsRTspOeJLGLZfArRt8bomPEzVCDHYrtXd1xWqc62cCrUN4Ydnd5CxBu/qB26P+Mybe4Jy+BjZYZ/FL1A+R4P07R2VMhSEiGNNyvpJMAfCBRfcFCdk61M9piGYlHPEaVS/01Y234Mcn08oxCnPwzFsVqEXuf2W7KDVMoQ7xUZcc1VMwwG4m76edu9mvldNH+eekaAUExpGx+GLx1QDvHO3orsTDwx6EEkqc2HH/GzTfOLywjwCiPQmh00RncTxJ2dC69C6xvAHrqCnl+PD6UQCS6WK68AQ2UixnSrWXk10K0XDTC4C10RwbQMJzvdLFyynemxtLmhVZGkcQNGYxV6EYKC2oJ4ZdYc7W26oGKIETMuzMR0vuSiJkQdsXmE5av9Q6SPik/2TMyuwb+9T61V5bBAiYgUkbsApWrmJnoAdyPllC7+r7/K/dgh8VDfii2DghPAfDveRPxUmMfR/YaV8+ujSFH7w72yVWIrWUYKoBlInSEsIlnJ2FnXwRMm/TtfVzXfPL0nXu6B9r9iz5is3AO10U+4VclqLIZnAof+zs318lXCOAy05z1A0z/9xnEis=";
[cli][info] Found matching plugin stream for URL hls://*/PROD01/sony/NBC_NBCSPORTSNETWORK/live/2016/10/25/4942649/4500K/4500_slide.m3u8
[cli][info] Available streams: live (best, worst)
[cli][info] Opening stream: live (hls)
[stream.hls][error] Failed to create decryptor: Unable to open URL: https://key-service.totsuko.tv/key-service/key/key?contentId=12419675&channelId=25159&kid=21298206 (401 Client Error: Unauthorized for url: https://key-service.totsuko.tv/key-service/key/key?contentId=12419675&channelId=25159&kid=21298206)
[cli][error] No data returned from stream

**Comment by beardypig** [comment] 2016-11-12 21:33
Maybe try putting single quotes (') around the cookie string. Are you using Windows, Linux or macOS?

**Comment by jacob1218** [comment] 2016-11-14 02:01
I put single quotes, and it also doesn't work, I am using windows, and i found something interesting. When played in osmfhls.kutu.ru, it seems to request the same server, but then be successfully authed to play.

**Comment by stevek123** [comment] 2016-11-14 19:39
Part of the URL is definitely missing, but I'm pretty sure that your cookie is not right, and the plugin works fine.

ps: If you send me an email (see my profile), I can help you troubleshoot it

**Comment by jacob1218** [comment] 2016-11-15 18:52
I can give one link out. It is a channel not avail. screen, but it still requires auth. http://sonycobra.vod.sonytv.adaptive.level3.net/media/hls/sony/vue_slates/ch_no_avail/4500K/Vue_Slate_ChNotAvail_4500k.m3u8

**Comment by colt082295** [comment] 2016-11-21 18:49
I'm pretty sure the cookie you're using is wrong. I inserted my cookie into the command, it it worked fine.

**Comment by chovy** [comment] 2017-02-09 18:11
How do I get this cookie?

**Comment by beardypig** [comment] 2017-02-09 18:37
You need to have a PSN account, with a PSVue subscription. Then you can use your browser's' developer tools to find the cookies that it sends when you watch a stream.

**Comment by klack** [comment] 2017-03-04 23:59
I am also getting 

> [stream.hls][error] Failed to create decryptor: Unable to open URL: https://key-service.totsuko.tv/key-service/key/key?contentId=12419675&channelId=25159&kid=21298206 (401 Client Error: Unauthorized for url: https://key-service.totsuko.tv/key-service/key/key?contentId=12419675&channelId=25159&kid=21298206)
> [cli][error] No data returned from stream

The link posted above does works for me (Vue_Slate_ChNotAvail_4500k.m3u8)
but this is not a real video stream.

When using streamlink on a real video, I get this error

**Comment by besweeet** [comment] 2017-03-05 00:22
You have to add --http-header "reqPayload=keyhere" to the command.

**Comment by enigma1400** [comment] 2017-03-10 22:21
I'm able to get it working, but I'm running into an issue where after _exactly_ 3 hours both streamlink and livestreamer throw an error relating to the auth token, and I have to go to the Vue page and get a new one. Obviously the actual Vue client doesn't do this or else everyone would be complaining. I believe the error might be due to the cookie not having an expiration date in it, but not sure. Anyone got an idea?

**Comment by jacob1218** [comment] 2017-03-10 22:35
@enigma, believe this would be the are you still vueing screen on mobile

**Comment by besweeet** [comment] 2017-03-10 22:42
I assume you'd need a script that can refresh the page automatically and strip the new cookie automatically.

**Comment by enigma1400** [comment] 2017-03-10 23:02
@jacob1218 I'm not, only had Vue open in the browser and closed it after I got the cookie.

@besweeet sounds interesting, do you know of any way I could make streamlink do this? I figured out where to grab the cookie when you arrive on the landing page, but am unsure if you can script the cookie into livestreamer like that.

**Comment by besweeet** [comment] 2017-03-11 00:19
@enigma1400 Others may know of an easier way, but I imagine you can use automation software to automatically refresh your browser every hour, grab the cookie / reqPayload value and put it into a streamlink command.

**Comment by enigma1400** [comment] 2017-03-11 01:52
@besweeet Yeah, I figured you could do that too, but how would you put the cookie into streamlink without stopping streamlink, or is that not possible?

**Comment by besweeet** [comment] 2017-03-11 02:16
Ah, doing it all without it stopping could be iffy. One idea might be to use Streamlink's --player-external-http and --player-external-http-port commands. Have VLC play the IP:port, then during the brief downtime, VLC might be able to pick up without having to do anything else with it.

I'll try it with an FSGO feed real quick (start Streamlink, open in VLC via IP:port, stop Streamlink, start Streamlink, see if VLC resumes).

And that didn't work. VLC crashes while Windows Media Player just stops. MPC was taking too long to start initially so I closed it.

**Comment by enigma1400** [comment] 2017-03-11 05:04
Hmm, seems like the issue is related with the cookie/streamlink. I recall hearing people were able to open the streams and have the cookies persist via Kodi, but it seems that it's been patched out by Sony themselves.

**Comment by markeymark** [comment] 2017-04-30 20:23
hello guys, I could be of some help to you guys, the streams are HLS and static, as your aware they just need cookie to release them, ive been working on this and got streams working in browser via chrome with HLS add on, unfortunately im in the UK so cannot sign up for a trial to psvue, ive also had the streams working in kodi, get in touch if u want to explore this more

**Comment by nywiley** [comment] 2017-06-18 11:30
SOLVED:  Add HLS Native Add-On to Chrome on Linux and your can sign in and watch Live TV.

**Comment by eyealaska** [comment] 2017-09-13 03:41
@markeymark How were you able to execute the streams via Chrome? I've been experimenting with this for days (and with several HLS add-ons), and can't seem to solve it. Of true interest is the fact that I've discovered two separate sites that appear to be pulling from various Vue m3u8 streams, and displaying them via a web-based media player. No idea how they're authenticating for the key.

**Comment by markeymark** [comment] 2017-09-15 13:39
they are cookie authenticated, what sites are you pulling from?

**Comment by mosb3rgler** [comment] 2017-11-11 19:12
Hey folks, i have some experience with this system. At the moment what we require beardypig is a login based plugin similar to wwe network or ufc network to accomplish whats needed. They have updated the system recently and it requires too frequent of a reauthentication. while the payload value might not change, the urls are now hash signed which are timed. So this requires the login system to get the required details then to also get the latest url. This is why its required that a plugin is made for the system.

I have a current login that i pay for, and i can provide samples and examples to assist you beardypig. I wont waste your time as i have experience with this methodology.

**Comment by fivehorizons** [comment] 2017-12-30 21:35
I would like to see this looked at again.  Having the cookie or key renewed automatically for long running streams

**Comment by fivehorizons** [comment] 2017-12-30 21:52
@markeymark

**Comment by gravyboat** [comment] 2017-12-31 03:39
@fivehorizons We've had this question/discussion on several other plugins regarding cookie/stream reneawal and it's just not something that Streamlink was designed for. If you want to open a new copy of a stream after it closes via cookie expiration you can just write a little wrapper that calls multiple Streamlink commands in a row.

**Comment by fivehorizons** [comment] 2017-12-31 03:49
@gravyboat thank you for response.  

I have seen the m3u8 links expire rather quickly. do you think inserting the http token would prevent that?

**Comment by gravyboat** [comment] 2017-12-31 05:27
@fivehorizons I don't know, I haven't been keeping much of an eye on how the token system works for PSVue.

**Comment by markeymark** [comment] 2018-04-10 16:28
@enigma1400 have you had any joy with longer lasting cookies?

**Comment by fivehorizons** [comment] 2018-04-10 16:29
No but have not tried again for some time.

**Comment by markeymark** [comment] 2018-04-10 16:41
@fivehorizons drop me an email, might be able to help

mcunni1817@googlemail.com

**Comment by markeymark** [comment] 2018-05-25 09:05
Are ps vue streams not able o go thru streamlink anymore?

**Comment by nanmer** [comment] 2019-04-08 16:00
Anybody have success with this?

**Comment by back-to** [comment] 2019-04-12 16:00
closing, as nobody found a good way for this or just nobody has an account to even look at this.

**Closed by back-to** 2019-04-12 16:00 UTC
Labels: enhancement, plugin request
