### ISSUE TITLE
afreecatv.com to check if it works

### ISSUE THREAD

**Issue by edcba1057344** [streamlink/streamlink#2068] opened 2018-09-16 14:50 UTC
Does the program run normally when downloading live broadcasts? Always, if the live broadcast is lost
The downloaded live mp3 file is broken.
If the live broadcast is lost, the cmd should also be disconnected, but it will not work.

Please check

streamlink http://play.afreecatv.com/****/0 best --hls-segment-threads 10 --retry-streams 1 --retry-max 100 --hls-live-edge 5 --ringbuffer-size 100M --stream-segment-attempts 100 --hls-segment-attempts 100 --stream-segment-timeout 10 --hls-segment-timeout 10 --hls-timeout 600 -o G:\Live\-test.mp4

Or is my command a strange thing?

**Comment by back-to** [comment] 2018-09-21 13:59
Duplicate of https://github.com/streamlink/streamlink/issues/2057

**Closed by back-to** 2018-09-21 13:59 UTC
