### ISSUE TITLE
Youtube livestreams error: "no playable streams"

### ISSUE THREAD

**Issue by dimyself** [streamlink/streamlink#2246] opened 2019-01-12 16:11 UTC
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.

### Description
It seems youtube has updated their site? youtube-dl and streamlink were both broken. After I updated youtube-dl, it is working again...but streamlink is still broken for me on livestreams. I tried the youtube URL as well as the "Share" URL. Here's the output of the error:

streamlink -o "01-12-2019_streamlink_part1.ts" https://www.youtube.com/watch?v=DODXh3UJNgc worst -l debug
[cli][debug] OS:         Linux-4.20.0-arch1-1-ARCH-x86_64-with-arch
[cli][debug] Python:     3.7.2
[cli][debug] Streamlink: 0.14.2
[cli][debug] Requests(2.21.0), Socks(1.6.7), Websocket(0.54.0)
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=DODXh3UJNgc
[plugin.youtube][debug] get_video_info - 1: Found data
[plugin.youtube][debug] This video is live.
error: No playable streams found on this URL: https://www.youtube.com/watch?v=DODXh3UJNgc

Thank you!

**Comment by bastimeyer** [comment] 2019-01-12 16:18
Duplicate of #2237, which got fixed a couple of hours ago.

> [cli][debug] Streamlink: 0.14.2

You are not using the latest Streamlink build.

```
$ streamlink -l debug 'https://www.youtube.com/watch?v=DODXh3UJNgc' best
[cli][debug] OS:         Linux-4.20.0-zen1-1-zen-x86_64-with-arch
[cli][debug] Python:     3.7.2
[cli][debug] Streamlink: 0.14.2+197.g42b8edd
[cli][debug] Requests(2.21.0), Socks(1.6.7), Websocket(0.54.0)
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=DODXh3UJNgc
[plugin.youtube][debug] Video ID from URL
[plugin.youtube][debug] Using video ID: DODXh3UJNgc
[plugin.youtube][debug] get_video_info - 1: Found data
[plugin.youtube][debug] This video is live.
[utils.l10n][debug] Language code: en_US
[cli][info] Available streams: 144p (worst), 240p, 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (hls)
```

**Closed by bastimeyer** 2019-01-12 16:18 UTC
