### ISSUE TITLE
plugins.twitch: streams missing in Twitch video

### ISSUE THREAD

**Issue by superbonaci** [streamlink/streamlink#6145] opened 2024-08-29 18:24 UTC
### Checklist

- [X] This is a [plugin issue](https://streamlink.github.io/plugins.html) and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Collaboration

- [X] [I will provide feedback should a pull request be opened with a fix for the plugin](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#pull-request-feedback)

### Streamlink version

6.9.0

### Description

2 streams are missing: chunked (`1440p60`) and `1080p60`.

### Debug log

```text
$ streamlink --url 'https://www.twitch.tv/videos/2223719525' -l all
[04:20:23.731233][cli][debug] OS:         macOS 14.6.1
[04:20:23.731354][cli][debug] Python:     3.12.5
[04:20:23.731400][cli][debug] OpenSSL:    OpenSSL 3.3.1 4 Jun 2024
[04:20:23.731435][cli][debug] Streamlink: 6.9.0
[04:20:23.731771][cli][debug] Dependencies:
[04:20:23.732660][cli][debug]  certifi: 2024.7.4
[04:20:23.733072][cli][debug]  isodate: 0.6.1
[04:20:23.733409][cli][debug]  lxml: 5.3.0
[04:20:23.733744][cli][debug]  pycountry: 24.6.1
[04:20:23.734091][cli][debug]  pycryptodome: 3.20.0
[04:20:23.734475][cli][debug]  PySocks: 1.7.1
[04:20:23.734830][cli][debug]  requests: 2.32.3
[04:20:23.735213][cli][debug]  trio: 0.26.2
[04:20:23.735587][cli][debug]  trio-websocket: 0.11.1
[04:20:23.735884][cli][debug]  typing-extensions: 4.12.2
[04:20:23.736232][cli][debug]  urllib3: 2.2.2
[04:20:23.736586][cli][debug]  websocket-client: 1.8.0
[04:20:23.736837][cli][debug] Arguments:
[04:20:23.736873][cli][debug]  url=https://www.twitch.tv/videos/2223719525
[04:20:23.736913][cli][debug]  --loglevel=all
[04:20:23.736961][cli][debug]  --url=https://www.twitch.tv/videos/2223719525
[04:20:23.737128][cli][info] Found matching plugin twitch for URL https://www.twitch.tv/videos/2223719525
[04:20:23.737162][plugins.twitch][debug] Getting HLS streams for video ID 2223719525
[04:20:24.065985][utils.l10n][debug] Language code: en_US
[04:20:24.298797][stream.hls.m3u8][all] #EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="720p60",NAME="720p60",AUTOSELECT=YES,DEFAULT=YES
[04:20:24.299068][stream.hls.m3u8][all] #EXT-X-STREAM-INF:BANDWIDTH=3729133,CODECS="avc1.640020,mp4a.40.2",RESOLUTION=1280x720,VIDEO="720p60",FRAME-RATE=60.000
[04:20:24.299320][stream.hls.m3u8][all] https://dgeft87wbj63p.cloudfront.net/09b88c14ef8300ea9fc4_r0dn3y_42737372968_1723598775/720p60/index-dvr.m3u8
[04:20:24.299672][stream.hls.m3u8][all] #EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="480p30",NAME="480p",AUTOSELECT=YES,DEFAULT=YES
[04:20:24.299899][stream.hls.m3u8][all] #EXT-X-STREAM-INF:BANDWIDTH=1205664,CODECS="avc1.64001F,mp4a.40.2",RESOLUTION=854x480,VIDEO="480p30",FRAME-RATE=30.000
[04:20:24.300109][stream.hls.m3u8][all] https://dgeft87wbj63p.cloudfront.net/09b88c14ef8300ea9fc4_r0dn3y_42737372968_1723598775/480p30/index-dvr.m3u8
[04:20:24.300351][stream.hls.m3u8][all] #EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="audio_only",NAME="Audio Only",AUTOSELECT=NO,DEFAULT=NO
[04:20:24.300569][stream.hls.m3u8][all] #EXT-X-STREAM-INF:BANDWIDTH=200835,CODECS="mp4a.40.2",VIDEO="audio_only"
[04:20:24.300794][stream.hls.m3u8][all] https://dgeft87wbj63p.cloudfront.net/09b88c14ef8300ea9fc4_r0dn3y_42737372968_1723598775/audio_only/index-dvr.m3u8
```

**Comment by bastimeyer** [comment] 2024-08-29 22:16
Duplicate of #5768
The missing streams are AV1 (1440p) and HEVC/H265 (1080p), which must be requested explicitly.

PR #5769 adds the `--twitch-supported-codecs` plugin argument, but it's still unmerged.

```
$ streamlink --no-config -l all --twitch-supported-codecs=av1,h265,h264 https://www.twitch.tv/videos/2223719525
[00:14:14.377037][cli][debug] OS:         Linux-6.10.6-1-git-x86_64-with-glibc2.40
[00:14:14.377144][cli][debug] Python:     3.12.4
[00:14:14.377197][cli][debug] OpenSSL:    OpenSSL 3.3.1 4 Jun 2024
[00:14:14.377239][cli][debug] Streamlink: 6.8.2+7.g2e57c4a3
[00:14:14.377681][cli][debug] Dependencies:
[00:14:14.378315][cli][debug]  certifi: 2024.7.4
[00:14:14.378661][cli][debug]  isodate: 0.6.1
[00:14:14.378949][cli][debug]  lxml: 5.3.0
[00:14:14.379364][cli][debug]  pycountry: 24.6.1
[00:14:14.379637][cli][debug]  pycryptodome: 3.20.0
[00:14:14.379977][cli][debug]  PySocks: 1.7.1
[00:14:14.380269][cli][debug]  requests: 2.32.3
[00:14:14.380601][cli][debug]  trio: 0.26.2
[00:14:14.380879][cli][debug]  trio-websocket: 0.11.1
[00:14:14.381130][cli][debug]  typing-extensions: 4.12.2
[00:14:14.381432][cli][debug]  urllib3: 2.2.2
[00:14:14.381741][cli][debug]  websocket-client: 1.8.0
[00:14:14.382002][cli][debug] Arguments:
[00:14:14.382055][cli][debug]  url=https://www.twitch.tv/videos/2223719525
[00:14:14.382103][cli][debug]  --no-config=True
[00:14:14.382144][cli][debug]  --loglevel=all
[00:14:14.382230][cli][debug]  --twitch-supported-codecs=['av1', 'h264', 'h265']
[00:14:14.382645][cli][info] Found matching plugin twitch for URL https://www.twitch.tv/videos/2223719525
[00:14:14.382698][plugins.twitch][debug] Getting HLS streams for video ID 2223719525
[00:14:14.783873][utils.l10n][debug] Language code: en_US
[00:14:15.050675][stream.hls.m3u8][all] #EXT-X-TWITCH-INFO:ORIGIN="s3",B="false",REGION="EU",USER-IP="REDACTED",SERVING-ID="REDACTED",CLUSTER="metro_vod",USER-COUNTRY="DE",MANIFEST-CLUSTER="metro_vod"
[00:14:15.050780][stream.hls.m3u8][all] #EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="chunked",NAME="1440p60",AUTOSELECT=NO,DEFAULT=NO
[00:14:15.050851][stream.hls.m3u8][all] #EXT-X-STREAM-INF:BANDWIDTH=11239847,CODECS="av01.0.12M.08.0.110.01.01.01.0,mp4a.40.2",RESOLUTION=2560x1440,VIDEO="chunked",FRAME-RATE=60.000
[00:14:15.050915][stream.hls.m3u8][all] https://d1ymi26ma8va5x.cloudfront.net/09b88c14ef8300ea9fc4_r0dn3y_42737372968_1723598775/chunked/index-dvr.m3u8
[00:14:15.050987][stream.hls.m3u8][all] #EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="720p60",NAME="720p60",AUTOSELECT=YES,DEFAULT=YES
[00:14:15.051040][stream.hls.m3u8][all] #EXT-X-STREAM-INF:BANDWIDTH=3729133,CODECS="avc1.640020,mp4a.40.2",RESOLUTION=1280x720,VIDEO="720p60",FRAME-RATE=60.000
[00:14:15.051086][stream.hls.m3u8][all] https://d1ymi26ma8va5x.cloudfront.net/09b88c14ef8300ea9fc4_r0dn3y_42737372968_1723598775/720p60/index-dvr.m3u8
[00:14:15.051143][stream.hls.m3u8][all] #EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="480p30",NAME="480p",AUTOSELECT=YES,DEFAULT=YES
[00:14:15.051198][stream.hls.m3u8][all] #EXT-X-STREAM-INF:BANDWIDTH=1205664,CODECS="avc1.64001F,mp4a.40.2",RESOLUTION=854x480,VIDEO="480p30",FRAME-RATE=30.000
[00:14:15.051243][stream.hls.m3u8][all] https://d1ymi26ma8va5x.cloudfront.net/09b88c14ef8300ea9fc4_r0dn3y_42737372968_1723598775/480p30/index-dvr.m3u8
[00:14:15.051296][stream.hls.m3u8][all] #EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="1080p60",NAME="1080p60",AUTOSELECT=YES,DEFAULT=YES
[00:14:15.051346][stream.hls.m3u8][all] #EXT-X-STREAM-INF:BANDWIDTH=6231498,CODECS="hvc1.1.2.L123.90.0.0.0.0.0,mp4a.40.2",RESOLUTION=1920x1080,VIDEO="1080p60",FRAME-RATE=60.000
[00:14:15.051389][stream.hls.m3u8][all] https://d1ymi26ma8va5x.cloudfront.net/09b88c14ef8300ea9fc4_r0dn3y_42737372968_1723598775/1080p60/index-dvr.m3u8
[00:14:15.051444][stream.hls.m3u8][all] #EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="audio_only",NAME="Audio Only",AUTOSELECT=NO,DEFAULT=NO
[00:14:15.051492][stream.hls.m3u8][all] #EXT-X-STREAM-INF:BANDWIDTH=200835,CODECS="mp4a.40.2",VIDEO="audio_only"
[00:14:15.051536][stream.hls.m3u8][all] https://d1ymi26ma8va5x.cloudfront.net/09b88c14ef8300ea9fc4_r0dn3y_42737372968_1723598775/audio_only/index-dvr.m3u8
Available streams: audio, 480p (worst), 720p60, 1080p60, 1440p60 (best)
```

**Closed by bastimeyer** 2024-08-29 22:16 UTC
Labels: plugin issue

**Comment by superbonaci** [comment] 2024-08-30 05:02
Why do they have to be requested explicitly?
