### ISSUE TITLE
Support multiple URLs given at the command line

### ISSUE THREAD

**Issue by mlindner** [streamlink/streamlink#444] opened 2017-01-18 08:24 UTC
Streamlink should be able to support a queue of URLs to parse through that it will go through one after another. Currently it tries to parse a second URL as the stream quality instead.

**Comment by beardypig** [comment] 2017-01-18 08:25
@mlindner what is the use case for this? And what is the expected behaviour? To play the first available stream, to play each one in turn?

**Comment by mlindner** [comment] 2017-01-18 09:13
To play each one in turn. This is useful when there's a playlist of videos and there is a need to queue them back to back. A bad workaround is to simply call streamlink multiple times but that requires a shutdown and restart of player and streamlink for every URL.

**Comment by beardypig** [comment] 2017-01-18 09:17
Do you have a concrete example?

It is not always possible to concatenate multiple videos into a single stream, if the formats, resolution, codecs, etc. are different it is not really possible, or too far out of scope for the project.

**Comment by mlindner** [comment] 2017-01-18 09:19
http://www.crunchyroll.com/ninja-girl-samurai-master for example each video link is only 3 minutes long so is a pain to have to manually set up the player for each one each time.

**Comment by karlo2105** [comment] 2017-01-18 09:40
I think he meant streamlink could support a playlist of videos.

**Comment by beardypig** [comment] 2017-01-18 10:05
I think this is out of scope for Streamlink in general. There is already support for a Playlist of streams, but it is an API available to plugins and not intended to be used to string together arbitrary streams - this would be fraught with issues. 

It is entirely possible to add support for a Playlist of streams on plugin by plugin basis, eg. the crunchyroll plugin could offer some method to specify a list of episodes to play... 

Of course, if you are using Linux with bash (or similar) you can do something like this
```sh
for u in http://www.crunchyroll.com/ninja-girl-samurai-master/episode-1-lets-go-see-nobunaga-sama-721031 http://www.crunchyroll.com/ninja-girl-samurai-master/episode-2-the-oda-clan-and-their-merry-friends-721033; do
    streamlink -O "${u}" best; 
done | vlc -
```

Or put the URLs in a file

**episodes.txt**
```
http://www.crunchyroll.com/ninja-girl-samurai-master/episode-1-lets-go-see-nobunaga-sama-721031
http://www.crunchyroll.com/ninja-girl-samurai-master/episode-2-the-oda-clan-and-their-merry-friends-721033
```

and do 
```sh
for u in $(cat episodes.txt); do
    streamlink -O "${u}" best; 
done | vlc -
```

**Comment by mlindner** [comment] 2017-01-18 10:52
No I don't mean support parsing playlists. I mean support doing:

`streamlink http://www.crunchyroll.com/ninja-girl-samurai-master/episode-1-lets-go-see-nobunaga-sama-721031 http://www.crunchyroll.com/ninja-girl-samurai-master/episode-2-the-oda-clan-and-their-merry-friends-721033 http://www.crunchyroll.com/ninja-girl-samurai-master/episode-3-attack-imagawa-san-next-door-721035 http://www.crunchyroll.com/ninja-girl-samurai-master/episode-4-the-monkey-and-the-tsundere-girl-721037 best`
or
`streamlink --playlist foobar.txt best`

This is possible with any player and fits the mode where streamlink is used as a frontend to mpv or some other video player. It would work great with --player-no-close as well because streamlink could just pass link after link to the player or even parse them all at once and pass them all to the player and the player would take care of going through each stream.

**Comment by mlindner** [comment] 2017-01-18 10:53
Even if you don't implement this soon, you have to admit this is a pretty basic feature that is missing that will eventually and should eventually be added.

**Comment by mlindner** [comment] 2017-01-18 10:56
It's the first thing I tried to do when I started using it after all and I think many others hit the same roadblock. I initially thought it was a bug and considered hacking away at the internals to just repeatedly call the main function and pass in file after file but the code wasn't too clean to do that easily within a few minutes so I abandoned the idea for the time being. Adding it at that level would be pretty simple.

**Comment by beardypig** [comment] 2017-01-18 11:08
@mlindner it may appear basic at first, but it's actually quite complex. Video streams cannot simply be concatenated, they would not be valid. Adding a feature like this would introduce too much scope for errors. However, as I said, it could be added at the plugin level.

**Comment by mlindner** [comment] 2017-01-18 11:24
I'm not talking about concatenating video streams. I'm talking about cycling through them back to back and handing them off to the player.

**Comment by mlindner** [comment] 2017-01-18 11:27
Additionally, a plugin is very much not appropriate for this. Plugins are for adapting to sites, not for adapting to players. We don't have an mpv plugin for example.

**Comment by mlindner** [comment] 2017-01-18 11:30
The hacky way to add this is simply to modify the argparse to support multiple urls in args.url and then modify handle_url such that it wraps all its code in a loop and loops over each element in args.url.

**Comment by beardypig** [comment] 2017-01-18 11:37
Streamlink is designed to handle one video stream at a time, it streams the video content to the player via a pipe (or HTTP). As far as the player is concerned the video that it is playing is a single video stream, ie. if you want to play more than video stream back-to-back they need to be concatenated. Streamlink has no facility to supply multiple separate video streams to a player.

If you hacked `handle_url` it would spawn one instance of the player for each video that you played.

**Comment by mlindner** [comment] 2017-01-18 11:44
@beardypig That's not how I use it. I use `player-passthrough=hls,http,rtmp` so no they would not be concatenated. I'd possibly modify handle_url such that if it sees multiple urls it sets a flag which then simply parses each URL and then passes them in a string blob to mpv.

In my case:
`streamlink http://www.crunchyroll.com/girlish-number/episode-11-wavering-chitose-and-determined-gojo-722465 streamlink http://www.crunchyroll.com/girlish-number/episode-12-karasuma-chitose-and-722467`
would get passed as
`mpv --cache=2048 --cache-secs=60 --screen=1 --no-ytdl https://v.vrv.co/evs/assets/52521c7d9a2bb8d4aec9e86098687b7f_3047117.mp4/index-v1-a1.m3u8?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly92LnZydi5jby9ldnMvYXNzZXRzLzUyNTIxYzdkOWEyYmI4ZDRhZWM5ZTg2MDk4Njg3YjdmXzMwNDcxMTcubXA0LyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE0ODQ4MjYxMjB9fX1dfQ__&Signature=Dy4cB-lii39aPg8FgSIgOrZEZzHjq1uOeYWVylLCiimQ2-d1oMwFvURPGpb8GyciBKiVqUVKEap7FQq8E-cZR9fSangDggF9zW0fSSbAMZTTF6aJtNnYhiadLQudBkPoJ8Xces65BJoysIeYFdoUrv1XHlLwc2fvEJWChfXOTAt7zL9KY1ns0sEN1na9efqa1YGYOVAII9o6S1fXV~I1cKxVATQ3YO8wHEs8SKPSm~Au5LYA2NE8ai37skEsYcmkxdizoohij~RiVyZHB8LpLg28ZkNLpTci37ZOsZU1oeSoExvLK~iq-o39wbLDqzabQa3SWHe4KVE6yP4c-qWErw__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA https://v.vrv.co/evs/assets/73365e3c001cfd8833a76638bed66140_3061271.mp4/index-v1-a1.m3u8?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly92LnZydi5jby9ldnMvYXNzZXRzLzczMzY1ZTNjMDAxY2ZkODgzM2E3NjYzOGJlZDY2MTQwXzMwNjEyNzEubXA0LyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE0ODQ4MjYxNDl9fX1dfQ__&Signature=iTlf982TVrXtvEKmGiOXTKa9ZIiJhat8bcCwLdNGwucO5-oByBYgcDWt1DwTyeiQrL9Yp1thoDsghJ2INW2URJojKKUmUWWPAcOmfM43VoQNxUEACdEgIkwcdLPixnnQoko53w2mQc1z-xcktlO8Laj3lsMKHtLrklNOHaMeXwiQ2NqLZt3zhS9p-wjBmFwG0~RAqC3ub~oxZfbPDDqR~yliO7SRyQ5pS~9AYQNM0MDAZct0PIjzhJw8yv63HHM8relKdxf91cAD~UTa1xOK8xP257QHYjmy77Le23H-U79klYHCUYG1dFhYetDHqqwALHGTsSlyvXi1So54NYpr2A__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA`

**Comment by mlindner** [comment] 2017-01-18 11:46
After quoting the URLs, just tried that and it works, at least until the temporary keys in there die out.

**Comment by mlindner** [comment] 2017-01-18 11:48
streamlink should really default to passthrough unless passthrough fails. When doing through a pipe many players get very broken and don't seek properly.

**Comment by bastimeyer** [comment] 2017-01-18 11:51
> When doing through a pipe many players get very broken and don't seek properly.

You can't seek at all by using pipes...
There's some talk about changing Streamlink's behavior in #134

**Comment by beardypig** [comment] 2017-01-18 11:52
That's in your case, not everyone uses `--player-passthrough`. 
What's to say that by the time you get to the second item in the list the URL is still valid? 

`player-passthrough` is useful, but it doesn't not work for every stream, some require cookies or other verification tokens, others are simply not supported by many (if any) players, eg.

**Comment by mlindner** [comment] 2017-01-18 11:52
I should also mention that when passing the URLs directly to mpv they are handled very well and the delay between videos is zero as the player reuses connections and pre-loads things. When going through @beardypig 's suggestion of using a script there is a 10 second delay or so between player invocations which is untenable for streaming videos back to back.

**Comment by bastimeyer** [comment] 2017-01-18 11:55
> there is a 10 second delay or so between player invocations

Because you're using an additional cache in mpv (plus Streamlink's cache). You can disable this in mpv by setting the `--no-cache` parameter (`-a "--no-cache {filename}"` Streamlink parameter).

**Comment by mlindner** [comment] 2017-01-18 11:56
Using no cache causes other problems (slow seeking, freezes) so I use an extra large cache which eliminated those. We should be able to have both.

**Comment by mlindner** [comment] 2017-01-18 11:58
I just measured and even with --no-cache there is a 7 second delay between video finishing and next video beginning because of all the setup that both streamlink and mpv do.

**Comment by bastimeyer** [comment] 2017-01-18 12:04
> there is a 7 second delay

How would this change if there would be a playlist implementation? Streamlink would still need to request the API/website to retrieve the stream data, which ofc has a slight delay. By using the hls passthrough, Streamlink doesn't know about the current position in the currently playing stream, because the player is fetching the data instead of Streamlink, so it can't do these requests ahead of time.

**Comment by mlindner** [comment] 2017-01-18 12:09
I can think of two ways, neither ideal.
1. Pre-parse all the given URLs and pass them all en-masse to mpv. They may expire before mpv gets to them all but that would still be better than what currently exists. I'm not 100% sure the links even do expire and they certainly last as long as it takes to play them.
2. Leave the player open and use the mpv api to stream additional URLs to it as they finish. There would be a short delay as streamlink determines the URL but the player wouldn't need to set itself up. The crunchyroll plugin could possibly also be modified to be able to query the play length and streamlink could use that to cache the URL that it passes to mpv. (not sure on this last part)

**Comment by beardypig** [comment] 2017-01-18 12:14
@mlindner _1._ would be fine in the case of crunchyroll, but perhaps not other sites. _2._ would mean some specific code for mpv, and any other player that people want to use... as you mentioned before, we don't have plugins for adapting to players. 

Here are a couple of additional scenarios where things might not go as expected: 
- The user requests two streams, one `hls` that can be passed to the player and one `hds` stream that must be piped to the player via http???
- The user requests two streams, both `hds` that both have to be piped to the player in turn. Can they be concatenated? (doubtful) 
- Any combination of streams where `player-passthrough` is not used... the videos must be concatenated. 
- The stream requires specific authorization headers that have to be passed to the player so they can be included in the request. (Generally a problem for `player-passthrough`).

**Comment by mlindner** [comment] 2017-01-18 12:17
I mean this all sounds like it works wherever player-passthrough also works. It's okay to have the option fail when player-passthrough also fails.

**Comment by beardypig** [comment] 2017-01-18 12:35
Except when the URL expires as you need to do all the URL resolution upfront. 

If you are using linux you can do it with a simple bash script.

**streamlink-playlist.sh**
```sh
#!/usr/bin/env bash

playlist=$(mktemp -t)
for url in $*; do
    streamlink --stream-url "${url}" best
done > ${playlist}

mpv --playlist=${playlist}
rm -f ${playlist}
```
and run it by doing 

```sh
bash streamlink-playlist.sh http://www.crunchyroll.com/girlish-number/episode-11-wavering-chitose-and-determined-gojo-722465 http://www.crunchyroll.com/girlish-number/episode-12-karasuma-chitose-and-722467
```

It won't help if the URLs expire though.

**Comment by mlindner** [comment] 2017-01-19 04:59
@gravyboat This should have enhancement label.

@beardypig I'm not sure you're following. I know how to do bash scripting but that's exactly not what I need.

**Comment by mlindner** [comment] 2017-01-19 05:00
I guess I'll need to do a pull request for this myself as there seems to be zero interest in adding what should be a basic required feature.

**Comment by beardypig** [comment] 2017-01-19 06:58
@mlindner as I understand your request that bash script does what you wanted, obviously you'd need to add any extra mpv options. 

I don't this the feature can be implemented in a user friendly enough way to be added as a core feature, and is better implemented with an external script. There are too many edge/failure cases. Tell me what you would expect the behaviour to be if you supplied a playlist with 10 hls streams and 1 hds stream at the end? 

Additionally, Streamlink is mainly aimed at live streaming, which don't really need to be played back to back.

**Comment by gravyboat** [comment] 2017-02-01 05:04
I'm going to close this for now, there are too many chances for edge cases and we don't have enough devs involved right now to deal with that.

**Closed by gravyboat** 2017-02-01 05:04 UTC
Labels: question
