### ISSUE TITLE
tvplayer handshake failure

### ISSUE THREAD

**Issue by maanich** [streamlink/streamlink#1800] opened 2018-06-14 14:33 UTC
streamlink --tvplayer-email=hxxxxx@gmail.com --tvplayer-password=xxxxx33 https://tvplayer.com/watch/drama best
[cli][info] streamlink is running as root! Be careful!
[cli][info] Found matching plugin tvplayer for URL https://tvplayer.com/watch/drama
error: Unable to open URL: https://tvplayer.com/account/login ([Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure)
 while login is ok when i looged to website.

**Comment by beardypig** [comment] 2018-06-14 14:58
Try with `--http-no-ssl-verify`, looks like you might be running on an old OS version with old certs.
It helps if you include a debug log, because we can see which version of Streamlink, what OS, etc. you are running and this helps us to help you.

**Comment by maanich** [comment] 2018-06-14 15:14
thanks i will try i m using ubuntu 14 


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: beardypig <notifications@github.com> Date: 14/06/2018  15:58  (GMT+00:00) To: streamlink/streamlink <streamlink@noreply.github.com> Cc: maanich <manigorgeous@gmail.com>, Author <author@noreply.github.com> Subject: Re: [streamlink/streamlink] tvplayer handshake failure (#1800) 
Try with --http-no-ssl-verify, looks like you might be running on an old OS version with old certs.

It helps if you include a debug log, because we can see which version of Streamlink, what OS, etc. you are running and this helps us to help you.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/streamlink/streamlink/issues/1800#issuecomment-397326434","url":"https://github.com/streamlink/streamlink/issues/1800#issuecomment-397326434","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/streamlink/streamlink","title":"streamlink/streamlink","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/streamlink/streamlink"}},"updates":{"snippets":[{"icon":"PERSON","message":"@beardypig in #1800: Try with `--http-no-ssl-verify`, looks like you might be running on an old OS version with old certs.\r\nIt helps if you include a debug log, because we can see which version of Streamlink, what OS, etc. you are running and this helps us to help you."}],"action":{"name":"View Issue","url":"https://github.com/streamlink/streamlink/issues/1800#issuecomment-397326434"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [streamlink/streamlink] tvplayer handshake failure (#1800)",
"sections": [
{
"text": "",
"activityTitle": "**beardypig**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@beardypig",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"streamlink/streamlink\",\n\"issueId\": 1800,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"streamlink/streamlink\",\n\"issueId\": 1800\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/streamlink/streamlink/issues/1800#issuecomment-397326434"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 346050409\n}"
}
],
"themeColor": "26292E"
}

**Comment by back-to** [comment] 2018-06-14 15:20
you can find a solution at https://github.com/requests/requests/issues/2022

duplicate of https://github.com/streamlink/streamlink/issues/1597

**Comment by beardypig** [comment] 2018-06-14 15:30
Ubuntu 14.04? is pretty old now - you are likely running in to the issue that @back-to has linked to.

**Comment by maanich** [comment] 2018-06-14 16:10
well cant change as running a server alot 9f stuff in it will try once i back from ground


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: beardypig <notifications@github.com> Date: 14/06/2018  16:30  (GMT+00:00) To: streamlink/streamlink <streamlink@noreply.github.com> Cc: maanich <manigorgeous@gmail.com>, Author <author@noreply.github.com> Subject: Re: [streamlink/streamlink] tvplayer handshake failure (#1800) 
Ubuntu 14.04? is pretty old now - you are likely running in to the issue that @back-to has linked to.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/streamlink/streamlink/issues/1800#issuecomment-397337429","url":"https://github.com/streamlink/streamlink/issues/1800#issuecomment-397337429","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/streamlink/streamlink","title":"streamlink/streamlink","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/streamlink/streamlink"}},"updates":{"snippets":[{"icon":"PERSON","message":"@beardypig in #1800: Ubuntu 14.04? is pretty old now - you are likely running in to the issue that @back-to has linked to. "}],"action":{"name":"View Issue","url":"https://github.com/streamlink/streamlink/issues/1800#issuecomment-397337429"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [streamlink/streamlink] tvplayer handshake failure (#1800)",
"sections": [
{
"text": "",
"activityTitle": "**beardypig**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@beardypig",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"streamlink/streamlink\",\n\"issueId\": 1800,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"streamlink/streamlink\",\n\"issueId\": 1800\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/streamlink/streamlink/issues/1800#issuecomment-397337429"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 346050409\n}"
}
],
"themeColor": "26292E"
}

**Comment by maanich** [comment] 2018-06-14 20:34
streamlink -l debug --tvplayer-email hxxx@gmail.com --tvplayer-password xxx3 --http-no-ssl-verify hls://https://tvplayer.com/watch/drama best
[cli][info] streamlink is running as root! Be careful!
[cli][info] Found matching plugin stream for URL hls://https://tvplayer.com/watch/drama
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (hls)
[stream.hls][debug] Reloading playlist
[cli][error] Try 1/1: Could not open stream <HLSStream('https://tvplayer.com/watch/drama')> (Could not open stream: Missing #EXTM3U header)

**Comment by maanich** [comment] 2018-06-14 20:39
streamlink 0.7.0
 ubuntu 14 64 bit

**Comment by maanich** [comment] 2018-06-14 22:35
usinng proxy as its geo restricted    proxy ok with web browser
treamlink --http-proxy "http://xxxx.xxxx.xxxx:8000/" --tvplayer-email xxx@gmail.com --tvplayer-password xxxx--http-no-ssl-verify https://tvplayer.com/watch/drama
[console][info] streamlink is running as root! Be careful!
[console][info] Found matching plugin tvplayer for URL https://tvplayer.com/watch/drama
error: Unable to open URL: https://live.tvplayer.com/stream.m3u8?id=346&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cCo6XC9cL2xpdmUudHZwbGF5ZXIuY29tXC9zdHJlYW0ubTN1OD9pZD0zNDYiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE1MjkwNDQyNDJ9LCJJcEFkZHJlc3MiOnsiQVdTOlNvdXJjZUlwIjoiODYuMTIuMjQ1LjIyXC8zMiJ9fX1dfQ__&Signature=iC7P~klpMomBdU5-7Cz64IKKqKQQFDMPXlfiJcV4IqS02k8JRyHo248rk-L7y7d5dWIN~MTCEoNT7iJOb-siFa7hEIRLJqodx2sZpX-AYYLLISDA-HmVoSSl~ulKkV4nkzc9zugClPLrgxD5KwGuLyQewL~CwS7-5DKtmyTxgnQFsRGLOcdAZ3n2SUXuhvblCLuINCldHss0Ztr9Ck0dRBCnJfvZXLUjavNU86y3Rvgdft5BAuhvnpoi8Z7iuCEdHIn6fTj8JjFT8MtcfCqahddSQrwdx-k9QoVPAuundh03yVthhQ1kcrH2F~XeJ8XcsHZxSMTieqMMrUvlIL9nJQ__&Key-Pair-Id=APKAJGWDVCU5SXAPJELQ (403 Client Error: Forbidden)

**Comment by maanich** [comment] 2018-06-14 22:36
streamlink --http-proxy "http://xxxxxxx2:8000/" --tvplayer-email xxxx@gmail.com --tvplayer-password xxxxhttpstream://https://tvplayer.com/watch/drama best
[console][info] streamlink is running as root! Be careful!
[console][info] Found matching plugin http for URL httpstream://https://tvplayer.com/watch/drama
[console][info] Available streams: live (worst, best)
[console][info] Opening stream: live (http)
[console][info] Starting player: /usr/bin/vlc
[console][info] Stream ended
[console][info] Closing currently open stream...

**Comment by maanich** [comment] 2018-06-14 22:48
streamlink -l debug --tvplayer-email xxxx@gmail.com --tvplayer-password xxxx https://tvplayer.com/watch/dave best
[cli][info] streamlink is running as root! Be careful!
[cli][info] Found matching plugin tvplayer for URL https://tvplayer.com/watch/dave
[plugin.tvplayer][debug] Getting stream information for resource=dave
error: Unable to open URL: http://api.tvplayer.com/api/v2/stream/live (400 Client Error: Bad Request

**Comment by beardypig** [comment] 2018-06-14 22:53
Try with `--https-proxy` set to the same value as `--http-proxy`.

**Comment by maanich** [comment] 2018-06-15 02:02
https://tvplayer.com/watch/natgeowild
but this doesnt owrk and some other from tvplayer not work too
manifest file while debug 
Request URL: https://plus-secondary.tvplayer.com/tiana/natgeowild/bitrate1.isml/Manifest.mpd
Request Method: GET
Status Code: 200  (from disk cache)
Remote Address: 54.230.9.144:443
Referrer Policy: no-referrer-when-downgrade
accept-ranges: bytes
access-control-allow-credentials: true
access-control-allow-headers: origin, range, Date
access-control-allow-methods: GET, HEAD, OPTIONS
access-control-allow-origin: *
access-control-expose-headers: Server,range,Date
cache-control: max-age=6
content-length: 5409
content-type: application/dash+xml
date: Fri, 15 Jun 2018 01:58:41 GMT
etag: "15290279174799294"
expires: Fri, 15 Jun 2018 01:58:47 GMT
last-modified: Fri, 15 Jun 2018 01:58:40 GMT
server: Apache/2.4.7 (Ubuntu)
status: 200
vary: Origin
via: 1.1 2297ae65d06c070d63c49ed7259f5fbb.cloudfront.net (CloudFront)
x-amz-cf-id: XJ6bQju7tty4REN83vRItXyZc2hOs4HPj_lTCm5UOVbhtXsr0cLhQQ==
x-cache: Miss from cloudfront
x-usp: version=1.7.28 (10646)
Provisional headers are shown
DNT: 1
Origin: https://tvplayer.com
Referer: https://tvplayer.com/watch/natgeowild
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36

![tvplayer1](https://user-images.githubusercontent.com/11740761/41446628-90aa755c-7048-11e8-9c0b-aae9d0582bc7.png)


Request URL: https://nqs-nl1-c10.youboranqs01.com/ping?diffTime=5003&bitrate=2500000&throughput=41355430.460611284&droppedFrames=0&playrate=1&timemark=1529027922381&sessionId=U_20000679_4acoz5mg68yceg13&pingTime=5&code=U_20000679_4acoz5mg68yceg13_0
Request Method: GET
Status Code: 200 OK
Remote Address: 81.171.21.52:443
Referrer Policy: no-referrer-when-downgrade
Access-Control-Allow-Origin: *
Content-Length: 0
Content-Type: text/plain
Date: Fri, 15 Jun 2018 01:58:44 GMT
Last-Modified: Fri, 15 Jun 2018 01:58:44 GMT
Server: NiceHttpQualityService/1.0 (Nice264 1.0)
Provisional headers are shown
DNT: 1
Origin: https://tvplayer.com
Referer: https://tvplayer.com/watch/natgeowild
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36
diffTime: 5003
bitrate: 2500000
throughput: 41355430.460611284
droppedFrames: 0
playrate: 1
timemark: 1529027922381
sessionId: U_20000679_4acoz5mg68yceg13
pingTime: 5
code: U_20000679_4acoz5mg68yceg13_0

**Comment by beardypig** [comment] 2018-06-15 10:59
The `tvplayer` plugin does not support DASH, also all the DASH streams from TVPlayer.com are protected by DRM - which is also not supported by Streamlink. These channels (the subscription channels + channel 5) will not work (and will likely never work) with Streamlink.

**Comment by maanich** [comment] 2018-06-15 11:17
tvplayer we can get only free channels?



Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: beardypig <notifications@github.com> Date: 15/06/2018  11:59  (GMT+00:00) To: streamlink/streamlink <streamlink@noreply.github.com> Cc: maanich <manigorgeous@gmail.com>, Author <author@noreply.github.com> Subject: Re: [streamlink/streamlink] tvplayer handshake failure (#1800) 
The tvplayer plugin does not support DASH, also all the DASH streams from TVPlayer.com are protected by DRM - which is also not supported by Streamlink. These channels (the subscription channels + channel 5) will not work (and will likely never work) with Streamlink.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/streamlink/streamlink/issues/1800#issuecomment-397587039","url":"https://github.com/streamlink/streamlink/issues/1800#issuecomment-397587039","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/streamlink/streamlink","title":"streamlink/streamlink","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/streamlink/streamlink"}},"updates":{"snippets":[{"icon":"PERSON","message":"@beardypig in #1800: The `tvplayer` plugin does not support DASH, also all the DASH streams from TVPlayer.com are protected by DRM - which is also not supported by Streamlink. These channels (the subscription channels + channel 5) will not work (and will likely never work) with Streamlink. "}],"action":{"name":"View Issue","url":"https://github.com/streamlink/streamlink/issues/1800#issuecomment-397587039"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [streamlink/streamlink] tvplayer handshake failure (#1800)",
"sections": [
{
"text": "",
"activityTitle": "**beardypig**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@beardypig",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"streamlink/streamlink\",\n\"issueId\": 1800,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"streamlink/streamlink\",\n\"issueId\": 1800\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/streamlink/streamlink/issues/1800#issuecomment-397587039"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 346050409\n}"
}
],
"themeColor": "26292E"
}

**Comment by beardypig** [comment] 2018-06-15 11:20
Correct. The rest are protected by DRM.

**Comment by maanich** [comment] 2018-06-15 11:48
is filmon fully supported with streamlink


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: beardypig <notifications@github.com> Date: 15/06/2018  12:20  (GMT+00:00) To: streamlink/streamlink <streamlink@noreply.github.com> Cc: maanich <manigorgeous@gmail.com>, Author <author@noreply.github.com> Subject: Re: [streamlink/streamlink] tvplayer handshake failure (#1800) 
Correct. The rest are protected by DRM.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/streamlink/streamlink/issues/1800#issuecomment-397591153","url":"https://github.com/streamlink/streamlink/issues/1800#issuecomment-397591153","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/streamlink/streamlink","title":"streamlink/streamlink","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/streamlink/streamlink"}},"updates":{"snippets":[{"icon":"PERSON","message":"@beardypig in #1800: Correct. The rest are protected by DRM. "}],"action":{"name":"View Issue","url":"https://github.com/streamlink/streamlink/issues/1800#issuecomment-397591153"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [streamlink/streamlink] tvplayer handshake failure (#1800)",
"sections": [
{
"text": "",
"activityTitle": "**beardypig**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@beardypig",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"streamlink/streamlink\",\n\"issueId\": 1800,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"streamlink/streamlink\",\n\"issueId\": 1800\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/streamlink/streamlink/issues/1800#issuecomment-397591153"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 346050409\n}"
}
],
"themeColor": "26292E"
}

**Comment by beardypig** [comment] 2018-06-15 15:05
@maanich the `filmon` plugin supports free channels, there is no support for login - you can request support for authentication in a separate issue. 

This issue is going off topic, I believe the original question has been answered and as such I will close this issue.

**Closed by beardypig** 2018-06-15 15:05 UTC
Labels: duplicate

**Comment by maanich** [comment] 2018-07-03 13:39
is drm supported in v14 of streamlink for dash streams .  or no support for tvplayer dash streams.

**Comment by beardypig** [comment] 2018-07-03 13:50
@maanich no support for DRM. It's not likely there ever will be support for DRM.
