### ISSUE TITLE
questions about commands to close streamlink asap after error

### ISSUE THREAD

**Issue by CplSgt82** [streamlink/streamlink#1567] opened 2018-03-22 23:18 UTC
Hello, after I have read through the command-line interface tutorial, I have some questions about some of the commands in streamlink.

Situation: youtube live streams will get a 403 error after streaming for 6hrs, so I tried to write a bat file to automatically launch a new streamlink. I've succeeded in doing that, but it takes 1min 10s for the new streamlink to launch because the old streamlink keeps reloading the playlist.

Question:  if i want the 'old' streamlink to close asap after it encounter the 403 error at 5:59:59, which one of the following should i include in the command line? or is it some other commands ?

--hls-playlist-reload-attempts=0 (can i set to 0,or is 1 smallest?)

--hls-timeout=1 (means 1 sec right?)

sorry if i am asking noob questions, because its my 1st time trying out all this.

**Comment by back-to** [comment] 2018-03-27 21:13
isn't it easier to close streamlink after 5:59:59 and reopen it with a script,
instead of waiting for streamlink to close itself.

**Comment by sbernsteinHBO** [comment] 2018-03-27 21:20
Or even easier -- why not just launch a new streamlink in a different process/batch file at 5:59 before the other one even has a chance to close???

**Comment by johnthecracker** [comment] 2018-03-27 22:13
the issue is this:

I run streamlink, stream ends and streamlink is still trying for 1 minute to access
no longer existing stream.

What switch do I have to use to terminate streamlink when the stream comes to an end,
instead of waiting for streamlink for 1 minute ?

After 1 minute batch file continues running, 1 minute lost.

This is how my batch file looks like:

:start
set url=http://x.x.x.x/website/playlist.m3u8
streamlink.exe --http-header %agent% hlsvariant://%url% best --stdout | ffmpeg.exe -hide_banner -i pipe:0 -c:v copy -c:a aac c:\%stream%_%d%.flv
timeout /t 30
goto start

**Comment by back-to** [comment] 2019-09-14 18:01
#2626

**Closed by back-to** 2019-09-14 18:01 UTC
Labels: question
