### ISSUE TITLE
[plugin request] micujoo.tv

### ISSUE THREAD

**Issue by 097115** [streamlink/streamlink#2077] opened 2018-09-23 09:56 UTC
## Plugin Request

- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description

Would be great to have a plugin for https://micujoo.tv.

From [Wikipedia](https://en.wikipedia.org/wiki/Mycujoo):

> [Mycujoo](https://micujoo.tv) is a streaming platform providing live and on-demand broadcast of football matches and highlights from around the world.

### Example stream URLs

1. https://mycujoo.tv/video/futebolpaulista?id=25865
2. https://mycujoo.tv/video/fc-basel-1893?id=23132
3. More example URLs, live or past, can be found [here](https://mycujoo.tv/calendar).

Thanks :).

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment] 2018-09-23 10:38
Duplicate of #1981

There's also a pending pull request for that plugin request: #1985

**Closed by bastimeyer** 2018-09-23 10:38 UTC
