### ISSUE TITLE
run streamlink this happen

### ISSUE THREAD

**Issue by p1020119** [streamlink/streamlink#976] opened 2017-06-02 12:24 UTC
```
~$ streamlink
Traceback (most recent call last):
  File "/usr/bin/streamlink", line 9, in <module>
    load_entry_point('streamlink==0.6.0', 'console_scripts', 'streamlink')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/share/streamlink/streamlink_cli/main.py", line 3, in <module>
    import requests
  File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 73, in <module>
    ssl.PROTOCOL_SSLv3: OpenSSL.SSL.SSLv3_METHOD,
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'
```

**Comment by beardypig** [comment] 2017-06-02 13:34
Which version of python are you running? `2.7.?` (`python --version`).

**Comment by back-to** [comment] 2017-06-02 13:57
try to update your `requests` version, if you didn't try it already

https://stackoverflow.com/questions/28987891/patch-pyopenssl-for-sslv3-issue?answertab=votes#tab-top

**Comment by horacio9a** [comment] 2017-06-02 15:48
I don't know exactly how important is requests version in this story.
I have Python 2.7.13 and requests 2.16.2 
I see that exist requests 2.6.0
With command:

pip install --upgrade requests

requests 2.16.2 is replaced with requests 2.17.3

I know I could use the command:

pip install requests==2.6.0

But I'm afraid for that ;)

**Comment by beardypig** [comment] 2017-06-02 16:42
@horacio9a are you having the same issue? `2.17.3` is the latest version of `requests`, there shouldn't be any need to revert to `2.6.0`. The `urllib3` version might be important too, but if you update `requests` then it should be up-to-date as well.

**Comment by horacio9a** [comment] 2017-06-02 17:58
Thanks for the explanation. I need to be honest and admit that I thought version 2.17.3 is older than 2.6.0 because number 1 is less than 6 ;)

**Comment by beardypig** [comment] 2017-06-02 18:49
It is slightly confusing because it doesn't follow the same rules as a decimal number, but then again it has 3 parts :)

**Comment by bastimeyer** [comment] 2017-06-28 23:26
There hasn't been a response in almost a month, the issue is caused by an old `requests` version and instructions for upgrading have been provided. Can this be closed now?

@horacio9a
Regarding the versioning scheme, see http://semver.org/ 😃

**Comment by gravyboat** [comment] 2017-06-28 23:47
Yep I'm closing it @bastimeyer.

**Closed** 2017-06-28 23:47 UTC
Labels: dependency issue
