### ISSUE TITLE
Can you consider joining Douyu Live?

### ISSUE THREAD

**Issue by emmIsabella** [streamlink/streamlink#5329] opened 2023-05-05 13:42 UTC
### Checklist

- [X] This is a feature request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Description

https://www.douyu.com

**Comment by mkbloke** [comment] 2023-05-05 13:52
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

**Comment by bastimeyer** [comment] 2023-05-05 16:37
Duplicate of #4511

**Closed by bastimeyer** 2023-05-05 16:37 UTC
Labels: plugin request
