### ISSUE TITLE
afreecatv plugin

### ISSUE THREAD

**Issue by nirgalka** [streamlink/streamlink#2917] opened 2020-04-17 14:52 UTC
## Plugin Issue

- [x ] This is a plugin issue and I have read the contribution guidelines.

### Description

Hi guys,
This is my first post here, so I hope I don't make any mistakes reporting this problem...
Afreecatv plugin stopped working for me about 2 weeks ago. Quality of stream doesn't seem to affect the problem nor the 19+ restricted streams. The streams work fine in a browser (firefox or opera in my case). And I've also tried the update of the plugin I found here. Sorry if it's a trivial problem but my little knowledge stops here...
Here is a log output and thanks for your help :

```
streamlink http://play.afreecatv.com/cbn270/222915074 hd
[cli][info] Found matching plugin afreeca for URL http://play.afreecatv.com/cbn270/222915074
[cli][info] Available streams: sd (worst), hd, original (best)
[cli][info] Opening stream: hd (hls)
[cli][error] Try 1/1: Could not open stream <HLSStream('http://live-hls-local-cf.afreecatv.com/ko-livestream-05/auth_playlist.m3u8?aid=.A32.7bbT56vyHM9fKZk.eU0M8puF9G9qtRHl8HsFqfazglVxdXyuuKxxxFgW5EWZKhXerpP1ZdDkAjgQxkvg80R4IwXmvNAi0nCeEw0JWJTXvQsITKdvLE2v3SJ1k5w')> (Could not open stream: Unable to open URL: http://live-hls-local-cf.afreecatv.com/ko-livestream-05/auth_playlist.m3u8?aid=.A32.7bbT56vyHM9fKZk.eU0M8puF9G9qtRHl8HsFqfazglVxdXyuuKxxxFgW5EWZKhXerpP1ZdDkAjgQxkvg80R4IwXmvNAi0nCeEw0JWJTXvQsITKdvLE2v3SJ1k5w (403 Client Error: Forbidden for url: http://live-hls-local-cf.afreecatv.com/ko-livestream-05/auth_playlist.m3u8?aid=.A32.7bbT56vyHM9fKZk.eU0M8puF9G9qtRHl8HsFqfazglVxdXyuuKxxxFgW5EWZKhXerpP1ZdDkAjgQxkvg80R4IwXmvNAi0nCeEw0JWJTXvQsITKdvLE2v3SJ1k5w&aid=.A32.7bbT56vyHM9fKZk.eU0M8puF9G9qtRHl8HsFqfazglVxdXyuuKxxxFgW5EWZKhXerpP1ZdDkAjgQxkvg80R4IwXmvNAi0nCeEw0JWJTXvQsITKdvLE2v3SJ1k5w))
error: Could not open stream <HLSStream('http://live-hls-local-cf.afreecatv.com/ko-livestream-05/auth_playlist.m3u8?aid=.A32.7bbT56vyHM9fKZk.eU0M8puF9G9qtRHl8HsFqfazglVxdXyuuKxxxFgW5EWZKhXerpP1ZdDkAjgQxkvg80R4IwXmvNAi0nCeEw0JWJTXvQsITKdvLE2v3SJ1k5w')>, tried 1 times, exiting

```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment] 2020-04-17 15:02
Duplicate of #2850 and #2874.

The current stable version of Streamlink doesn't set a `User-Agent` HTTP header by default, which is now apparently required by the site. You either need to set one yourself on the current version by using the [`--http-header`](https://streamlink.github.io/latest/cli.html#cmdoption-http-header) parameter (eg. [Firefox](https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugin/api/useragents.py#L7)), or you can install the latest development build from the master branch, where this problem has been fixed.

https://streamlink.github.io/latest/install.html

```
$ streamlink --loglevel debug 'https://play.afreecatv.com/cbn270/222915074' best
[cli][debug] OS:         Linux-5.6.0-1-git-x86_64-with-glibc2.2.5
[cli][debug] Python:     3.8.2
[cli][debug] Streamlink: 1.3.1+117.g1809c8f
[cli][debug] Requests(2.23.0), Socks(1.7.1), Websocket(0.56.0)
[cli][info] Found matching plugin afreeca for URL https://play.afreecatv.com/cbn270/222915074
[cli][info] Available streams: sd (worst), hd, original (best)
[cli][info] Opening stream: original (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 1; Last Sequence: 3
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 1; End Sequence: None
[stream.hls][debug] Adding segment 1 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Skipping segment 1
[stream.hls][debug] Adding segment 2 to queue
[stream.hls][debug] Adding segment 3 to queue
[stream.hls][debug] Skipping segment 2
[stream.hls][debug] Skipping segment 3
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 4 to queue
[stream.hls][debug] Adding segment 5 to queue
[cli][info] Starting player: mpv
[stream.hls][debug] Download of segment 4 complete
[cli.output][debug] Opening subprocess: mpv --title=https://play.afreecatv.com/cbn270/222915074 --cache=no -
[cli][debug] Writing stream to output
[cli][info] Player closed
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

**Closed by bastimeyer** 2020-04-17 15:02 UTC
