### ISSUE TITLE
Stream ended ,Closing currently open stream...

### ISSUE THREAD

**Issue by brunomoreno71** [streamlink/streamlink#1563] opened 2018-03-19 03:00 UTC
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

He stopped at 20 minutes, this did not happen, record time 50 minutes ago and I stopped him.

### Expected / Actual behavior

...

### Reproduction steps / Explicit stream URLs to test

root@zzzzzzz:~# streamlink --http-ignore-env --hls-segment-attempts 6 --hls-timeout 1200 --retry-streams 1 -l debug "http://disfruta.life:8000/live/Magno7/Magno7/4218.m3u8" best -o xxxxx.mp4
[cli][info] streamlink is running as root! Be careful!
[cli][debug] OS:         Linux-2.6.32-042stab108.8-x86_64-with-Ubuntu-14.04-trusty
[cli][debug] Python:     2.7.6
[cli][debug] Streamlink: 0.10.0
[cli][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.46.0)
[cli][info] Found matching plugin hls for URL http://disfruta.life:8000/live/Magno7/Magno7/4218.m3u8
[plugin.hls][debug] URL=http://disfruta.life:8000/live/Magno7/Magno7/4218.m3u8; params={}
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 20; Last Sequence: 25
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 23; End Sequence: None
[stream.hls][debug] Adding segment 23 to queue

### Logs

https://gist.github.com/brunomoreno71/20e03929aa11bf62c0e81ea7fe80f237
```

**Comment by bastimeyer** [comment] 2018-03-19 03:33
> 403 Client Error: Forbidden

As you can see, the server is returning several [403](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#4xx_Client_errors) codes when reloading the HLS playlist. This might be caused by an expired access token.
This is not a Streamlink issue...

**Comment by CplSgt82** [comment] 2018-03-22 16:08
I am trying to stream and record a YouTube live video for 46hrs non-stop, and I also have encountered the same problem as yours. I've tried it 3 times, and everytime after 5 Hrs+ the video will stop and I got the same error as yours.

For example i found this in my log:
[stream.hls][warning] Failed to reload playlist: Unable to open URL: https://manifest.googlevideo.com/api/manifest/hls_playlist/id/dvpJJ6krCiM.0/itag/96/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/cmbypass/yes/goi/160/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dyes%3Bitag%3D
137/hls_chunk_host/r5---sn-npobuxa-npoe6.googlevideo.com/ei/0XKzWsqxI82WoAON_rKQDw/gcr/sg/playlist_type/LIVE/initcwndbps/11930/mm/32/mn/sn-npobuxa-npoe6/ms/lv/mv/m/pl/17/dover/10/keepalive/yes/mt/1521709694/ip/115.66.218.231/ipbits/0/expire/1521731377/sparams/ip,ipbits,expire,id,itag,source,requiressl,ratebypass,live,cmbypass,goi,sgoap,sgovp,hls_chunk_host,ei,gcr,playlist_type,initcwndbps,mm,mn,ms,mv,pl/signature/2A36DAC1F2DC9D4883F9D58545BE348BD1FE1E07.17FAC759E0DA8736B65B8AC3908595F27CA9998B/key/dg_yt0/playlist/index.m3u8 (403 Client Error: Forbidden for url: https://mani
fest.googlevideo.com/api/manifest/hls_playlist/id/dvpJJ6krCiM.0/itag/96/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/cmbypass/yes/goi/160/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dyes%3Bitag%3D137/hls_chunk_host/r5---sn-npobuxa-npoe6.googlevideo.com/ei/0XKzWsqxI82WoAON_rKQDw/gcr/sg/playlist_type/LIVE/initcwndbps/11930/mm/32/mn/sn-npobuxa-npoe6/ms/lv/mv/m/pl/17/dover/10/keepalive/yes/mt/1521709694/ip/115.66.218.231/ipbits/0/expire/1521731377/sparams/ip,ipbits,expire,id,itag,source,requiressl,ratebypass,live,cmbypass,goi,sgoap,sgovp,hls_chunk_host,ei,gcr,playlist_type,initcwndbps,mm,mn,ms,mv,pl/signature/2A36DAC1F2DC9D4883F9D58545BE348BD1FE1E07.17FAC759E0DA8736B65B8AC3908595F27CA9998B/key/dg_yt0/playlist/index.m3u8)
------------------------------------------------------------------------------------------

Right now I am trying out a bat file to overcome this problem:

@echo off

::set _task=notepad.exe
set _task=streamlink

goto CHECK

:CHECK
REM  Check whether the process is running 
qprocess  >tasklist_tmp.txt

type tasklist_tmp.txt | findstr /i %_task%
  
if %errorlevel% ==0  goto SLEEP

if %errorlevel% ==1  goto RUN


:RUN

set _suffix=.ts
set _command=streamlink  https://www.youtube.com/watch?v=dvpJJ6krCiM  best  -o 
::set _current_time=%date:~0,4%%date:~5,2%%date:~8,2%-%time:~0,2%%time:~3,2%%time:~6,2% 
::set _service=%_command%%_current_time%%_suffix%

rem echo Get current date
for /f "tokens=1,2,3 delims=/- " %%a in ("%date%") do @set D=%%a%%b%%c
rem echo Get current time
for /f "tokens=1,2,3 delims=:." %%a in ("%time%") do @set T=%%a%%b%%c
rem echo if less than 10hr, replace space with 0
set T=%T: =0%
rem echo indicate date and time
echo %D%%T%

set _service=%_command%S:\testing-%D%%T%%_suffix%

echo %_service%
::start c:\windows\system32\notepad.exe
start %_service%
echo The program started at %time%>>deamon.log

:SLEEP
REM  sleep for 10 minutes
echo %time% The Program is Running,sleep for 10s...
echo Wscript.Sleep WScript.Arguments(0) >%tmp%\delay.vbs 
cscript //b //nologo %tmp%\delay.vbs 10000

goto CHECK

----------------------------------------------------------------------------------------------------
Just wanna ask, is there any command in streamlink to refresh the access token for youtube live?

**Comment by gravyboat** [comment] 2018-03-22 16:27
@CplSgt82 No there isn't, people have asked about this before and it isn't something we intend on adding since it's complicated and doesn't really jive with the design. Your best bet is to queue up multiple Streamlink commands so they run as soon as the last one exits then edit them all together. I'm going to close this issue since we're diverging on topics here and the original problem isn't something we can do anything about.

**Closed by gravyboat** 2018-03-22 16:27 UTC
Labels: invalid
