### ISSUE TITLE
 Timeshift for ¿Youtube?

### ISSUE THREAD

**Issue by markosc** [streamlink/streamlink#4674] opened 2022-07-21 22:25 UTC
### Checklist

- [X] This is a feature request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Description

good morning, some youtube channels can go back the "live" streaming and see the content from two or 3 hours ago, is it possible to have that function? I think it's called "Timeshift" since you can go back maybe supported with tvheadend? thanks

**Comment by bastimeyer** [comment] 2022-07-21 22:25
Duplicate of #2936

**Closed by bastimeyer** 2022-07-21 22:25 UTC
Labels: feature request
