### ISSUE TITLE
ITV player uses DASH 

### ISSUE THREAD

**Issue by danpilch** [streamlink/streamlink#1788] opened 2018-06-13 04:39 UTC
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Expected / Actual behavior
running streamlink against itv player does not work for new streams as they use DASH encoding. Is there any way to get dash working with itv player?

```console
> streamlink https://www.itv.com/hub/unforgotten/2a3372a0008
[console][info] Found matching plugin itvplayer for URL https://www.itv.com/hub/unforgotten/2a3372a0008
error: No playable streams found on this URL: https://www.itv.com/hub/unforgotten/2a3372a0008
```

### Logs

_Logs are always required for a bug report, use `-l debug` [(help)](https://streamlink.github.io/cli.html#cmdoption-l)
Make sure to **remove username and password**
You can upload your logs to https://gist.github.com/ or_

```
REPLACE THIS TEXT WITH YOUR LOG
```

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by beardypig** [comment] 2018-06-13 09:34
@danpilch the VOD streams that I have seen that are DASH are protected by ClearKey DRM - at this time, DRM (even ClearKey) is not supported. However, it might be worth adding ClearKey support, as this is similar to the basic encryption supported by HLS streams.

**Comment by Vangelis66** [comment] 2018-06-13 17:41
@beardypig 
Hello 😃 
I urge you to be careful in the way you modify the ITV plugin...
For LIVE ITVHub streams, 
```
https://www.itv.com/hub/itv
https://www.itv.com/hub/itv2
https://www.itv.com/hub/itvbe
https://www.itv.com/hub/itv3
https://www.itv.com/hub/citv
https://www.itv.com/hub/itv4
```
streamlink still uses a legacy playlist API 
```
https://secure-mercury.itv.com/PlaylistService.svc?wsdl 
(=> http://tempuri.org/PlaylistService/GetPlaylist)
``` 
that returns RTMPE streams; 
at this time of posting, it appears that it is only for ITV1+ITV4 that the 
old API returns working streams (for the rest, you get errors of the type: 
```
[cli][error] Try 1/1: Could not open stream <RTMPStream({'rtmp': 'rtmpe://cp2739
90.live.edgefcs.net/live', 'app': 'live', 'playpath': 'itv3livefms_1200@s172816?
auth=eaEbxb5dHdkdlc2c4abcIapaKaOazcUaeaSclbGafaLdPdVaCapbNbxbOdgd9c4anam-bBit7x-
frG-dDLhFDnmw0Ebuavp&aifp=v001&slist=itv3livefms_1200@s172816', 'swfVfy': 'http:
//www.itv.com/mediaplayer/ITVMediaPlayer.swf', 'timeout': 10, 'live': True, 'flv
': '-'}, redirect=False> (No data returned from stream)
error: Could not open stream <RTMPStream({'rtmp': 'rtmpe://cp273990.live.edgefcs
.net/live', 'app': 'live', 'playpath': 'itv3livefms_1200@s172816?auth=eaEbxb5dHd
kdlc2c4abcIapaKaOazcUaeaSclbGafaLdPdVaCapbNbxbOdgd9c4anam-bBit7x-frG-dDLhFDnmw0E
buavp&aifp=v001&slist=itv3livefms_1200@s172816', 'swfVfy': 'http://www.itv.com/m
ediaplayer/ITVMediaPlayer.swf', 'timeout': 10, 'live': True, 'flv': '-'}, redire
ct=False>, tried 1 times, exiting
[cli][info] Closing currently open stream...
```
The advantage of the old live API is it can be accessed from overseas with a simple 
`--http-header "X-Forwarded-For=<UK IP here>"`, while the FMS _does not geo-block_.
The disadvantage is that currently only one quality variant (1200k) is offered, for only two 
(ITV1+ITV4) of the channels... 😞 

Their new **Live channel API** is a total mess, if you ask me... 😠 For starters, it requires 
user authentication, but, to make matters worse, is not consistent across all channels...

Fot ITV1 and ITV4, they employ the following API: 
```
https://mediaplayer.itv.com/flash/playlists/ukonly/itv1.xml
https://mediaplayer.itv.com/flash/playlists/ukonly/itv4.xml
```
which, as expected, geo-blocks, but **can't be tricked with an X-F-F request header** 😢 ;
you need a full blown, whitelisted, UK HTTP(S) proxy to gain access to RTMPE (only) streams which, 
fortunately, are not (yet) geo-blocked but, again, only offer the 1200k variant...
Working cmd for ITV1+ITV4: 
```
rtmpdump -v -r "rtmpe://cp532701.live.edgefcs.net/live" -a "live" -f "WIN 30,0,0,113" -p "https://www.itv.com/hub/itv" -W "http://www.itv.com/mediaplayer/ITVMediaPlayer.swf" -y "itv1static@45475" -o "itv1live_1200k.flv"

rtmpdump -v -r "rtmpe://cp532702.live.edgefcs.net/live" -a "live" -f "WIN 30,0,0,113" -p "https://www.itv.com/hub/itv4" -W "http://www.itv.com/mediaplayer/ITVMediaPlayer.swf" -y "itv4static@45482" -o "itv4live_1200k.flv" 
```
In a random fashion, and for **ITV1 only**, I was served AdobeHDS streams, unencrypted, 
of the following manifest: 
`https://itv1livehds-lh.akamaihd.net/z/itv1livehds_1@321229/manifest.f4m?hdcore=3.11`
That manifest is geo-blocked, but can be tricked with a X_F_F header; advantage over the RTMPE 
stream is it offers 5 variants, higher quality one being 1800k ! 👍 

For the rest of the Live channels, they employ `*magni.itv.com/playlist/itvonline/*` playlist API URL, 
which can be tricked (X-F-F) to divulge live stream data...
On a desktop browser, these are MPEG-DASH streams served from 
```
itv2simadotcom.akamaized.net
itvbesimadotcom.akamaized.net
itv3simadotcom.akamaized.net
citvsimadotcom.akamaized.net
```
hosts which **all geo-block** and, to add insult to injury, **all use Common Encryption** (cenc) 
with Widevine DRM 👎 :angry: ; ITV2 example: 
```json
      "Base" : "https://itv2simadotcom.akamaized.net/",
      "MediaFiles" : [
        {
          "Href" : "playout/itv2/cenc.isml/.mpd?hdnea=st=1522019201~exp=1522040801~acl=/*~data=nohubplus~hmac=df9af29ad634c2e5ee82785ef00da299ea453e6821bb4fbd51af5846ff5e0af2",
          "KeyServiceUrl" : "https://itvpnp.live.ott.irdeto.com/Widevine/getlicense?CrmId=itvpnp&AccountId=itvpnp&ContentId=itv2"
        }
```
I don't know whether streamlink can do anything about these live ITV streams, given the stance 
of the main repo owner with regards to DRM... 
Addendum: Just the other day I was offered, **just for ITV2**, unencrypted AdobeHDS streams, 
of the following manifest: 
`https://itv2livehds-lh.akamaihd.net/z/itv2livehds_1@321228/manifest.f4m?hdcore=3.11`
with the same limitations and features as the ITV1 manifest quoted previously in this comment; 
but it cannot be returned by their API in a reproducible fashion... 

I was unsuccessful in discovering AppleHLS streams for ITVHub Live streams; spoofing a mobile 
browser UA, I was always offered to install their Android/iOS app, so this is left to others to test...

VOD ITVHub streams were previously discussed in https://github.com/streamlink/streamlink/issues/1436; I was of the first to point out they were deprecating RTMPE streams and moving on to encrypted (cenc) DASH on desktop and encrypted AES-128 HLS on mobile platforms...
While I think a "_fix_" for ClearKey would be awesome, for VOD on the ITVhub the quickest approach 
would be to explore existing HLS streams for mobile, a la [youtube-dl](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/itv.py) ...

Closing this, let me stress once again that my original intention is **NOT** piracy 
(as I believe is also the case with 99% of streamlink users...); I have an old laptop, 
with an old CPU, a very old integrated GPU without hardware decoding capabilities 
for the h264 codec, using streamlink is one of the few solutions I have for watching 
in a comfortable manner on-line media content (fetching to disk and watching via a 
dedicated media player, making use of DXVA features...). 
As such, my heartfelt gratitude goes to all devs keeping this project alive!

**Comment by beardypig** [comment] 2018-06-13 20:32
@Vangelis66 quite the essay, as usual ;)

I can leave the rtmp/hds streams intact, it’s quite easy as they have changed it a bit so you don’t need to build the silly SOAP request. In the current PR, only HLS streams are returned - they are on akamai so I imagine they are geoblocked (I didn’t try as I have a proxy configured by config file). 
As for the DASH streams; they use DRM, but ClearKey is an option which should be quite simple to support - I just need to design and implement an API for the Stream class to support DRM... (it’s called DRM, but ClearKey is the same as encrypted HLS streams - technically DRM, just not very good ;))

**Comment by danpilch** [comment] 2018-06-14 07:15
@beardypig thanks for your update. I'll look forward to your implementation 😀

**Comment by beardypig** [comment] 2018-06-14 12:52
@Vangelis66 OK, I added back the legacy Flash streams - I don't like it cos it bloats the plugin up ... If it was anyone else, I would have said "too bad".

**Comment by AshUK** [comment] 2018-06-22 14:21
looks like the legacy playlist API is now fully deprecated

**Comment by beardypig** [comment] 2018-06-22 14:44
@AshUK I get a 503 error now, looks like you are right... 

@Vangelis66 if this message reaches you in the future, can you confirm that the old API is no longer working?

**Closed** 2018-06-25 02:44 UTC
Labels: enhancement, plugin issue
