### ISSUE TITLE
Feature request: Automated Bitrate information

### ISSUE THREAD

**Issue by duramato** [streamlink/streamlink#1048] opened 2017-06-29 15:36 UTC
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description
For: http://tubitv.com/video/290649/bad_seed_a_tale_of_mischief_magic_and_medical_marijuana

It isn't getting the best avaiable quality on tubi

### Expected / Actual behavior

Should get the best quality when using `best`

### Reproduction steps / Explicit stream URLs to test

Run `Streamlink.exe  hlsvariant://http://c13.adrise.tv/v2/sources/content-owners/kinonation/290649/v0806122039-1280x716-HD-,353,821,1175,1500,2690,k.mp4.m3u8?SXz0tIlaDMyatJI2kdw4JLnpLfeBrfQo_C-tudGsMWg3Rcz6gZOdSgKfAxKFIWjx best -o file.ts`  

### Environment details

Operating system and version: Windows 10
Streamlink and Python version: Python 3.5.2, streamlink 0.6.0

### Comments, logs, screenshots, etc.

`Available streams: 716p_alt, 716p_alt2, 716p (worst, best)`

on site: 
![image](https://user-images.githubusercontent.com/10121067/27694376-cfd823ce-5ce3-11e7-8ef1-a1ed51797e77.png)

**Comment by back-to** [comment] 2017-06-29 17:33
you could use  `name_fmt={bitrate}`

```
streamlink "hlsvariant://URL name_fmt={bitrate}" best 
[cli][info] Found matching plugin stream for URL hlsvariant://URL best name_fmt={bitrate}
[cli][info] Available streams: 348k (worst), 816k, 1170k, 1495k, 2684k (best)
[cli][info] Opening stream: 2684k (hls)
[cli][info] Starting player: /usr/bin/vlc
```

**Comment by duramato** [comment] 2017-06-29 20:22
But `streamlink` should show all avaiable sources which are five, right? it only shows 3 of them.

There is a discrepancy between the default mode: 
`Available streams: 716p_alt, 716p_alt2, 716p (worst, best)`
and using the bitrate
`Available streams: 348k (worst), 816k, 1170k, 1495k, 2684k (best)`

**Comment by Quaraxkad** [comment] 2017-06-29 20:26
The main issue here is that the streams listed in the master playlist provided are detected by Streamlink as being mirrors of each-other, and they are not. I can confirm this is not an isolated incident and can provide more example playlists where this occurs if necessary. Ideally, I would like if Streamlink returned available streams like this: 716p@348k (worst), 716p@816k, 716p@1170k, 716p@1495k, 716p@2684k (best). That way there is no ambiguity. Selecting the format "716p" in this instance would default to the highest bitrate available of that resolution.

**Comment by gravyboat** [comment] 2017-06-29 20:52
While the format isn't what you would like to see @Quaraxkad I believe that #731 should resolve this once it's merged as it will sort the streams more accurately. I understand the lack of total clarity, however the sorting will be accurate.

**Comment by Quaraxkad** [comment] 2017-06-29 21:15
Reading the discussions under https://github.com/streamlink/streamlink/pull/731 it's not clear that those changes would actually fix the underlying problem. In this case there are five 716p streams and Streamlink will ignore all but three of them (one main and two alt, see https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugin/plugin.py#L281). Since none of these are "mirrors" but actually totally different bitrate streams that just happen to share a resolution, it's possible that the two highest quality versions are ignored entirely. Sorting the chosen three after-the-fact doesn't fix that.

**Comment by gravyboat** [comment] 2017-06-29 22:22
Hmm you're right. I don't think the new logic is going to impact that. Let's get it merged first and tested out on the nightly for this one, then we can confirm if modifying the number of alts resolves the issue. I imagine originally that made sense because the bitrate versus resolution in cases like this doesn't make much sense but we should definitey support it.

**Comment by enzanki-ars** [comment] 2017-06-29 22:23
As the co-author of #731, I can confirm that @Quaraxkad is correct. #731 only reorders what is shown based only on it's name displayed, nothing else.  The stream in the example is not being parsed correctly before being sorted, and the sorting code throws out all but 3 of the same quality.  In this case, the stream is being reported to the display code as each stream being exactly the same: 5x 720p streams, and not noticing that the streams are any different.  

I wonder if it would be worth removing the 2 alt limit and amending the HLS code to return the names with the bitrates if there are multiple bitrates for the same quality.  I do like the suggestion of returning 

`716p@348k (worst), 716p@816k, 716p@1170k, 716p@1495k, 716p@2684k (best)` 

in this example.

**Comment by gravyboat** [comment] 2017-06-29 22:25
@enzanki-ars Thanks for weighing in. It's something we can definitely look at. I don't know if there's any reliance on the output being in the specific existing format for the gui, so we should talk to @bastimeyer just to confirm. I agree it would be a more transparent change.

**Comment by beardypig** [comment] 2017-06-30 03:55
The name formats are plugin specific and the builtin hls plugin uses resolution only for the name. There is a limit of 2 alts currently, which I think is reasonable as they are meant to represent mirrors (I don't even this they shout be displayed to the user). I also think that the bitrate should be added to the name if there are multiple different streams at the same resolution but have different bitrates - however,  the way it is written now it's not so simple to do that :-) 

I would work on it but I'm busy for the next few weeks, if someone doesn't look at it before I'm back then I'll take a look :-)

**Comment by bastimeyer** [comment] 2017-06-30 07:56
@gravyboat 
Changing the format of the streams/qualities would be a breaking change and would require a major version bump, as it affects the `--default-stream` and `--stream-sorting-excludes` CLI parameters and of course the second positional parameter.

I'm not sure if it's a good idea to use a different format by default for all plugins, as it's usually not expected by the user to see different stream names. For example, why should a youtube stream suddenly be named 720p@3000k?

This change either needs to be applied only for certain plugins or a new parameter for customizing the stream name format needs to be added. But even with a new param I'm not sure if a major version bump would be required, because this param could be added to a user config file which would then break applications relying on the default format if they don't set their own format.

@beardypig 
An implementation that would fix the `--stream-sorting-excludes` param, so that lower/higher bitrate streams can be filtered would be nice:
https://github.com/streamlink/streamlink-twitch-gui/issues/470

**Comment by beardypig** [comment] 2017-06-30 10:34
@bastimeyer that would be nice too.

**Comment by back-to** [comment] 2018-01-04 21:59
it would be nice to remove the **stream_names** from there files

https://github.com/streamlink/streamlink/blob/master/src/streamlink/stream/hls.py#L373-L401
https://github.com/streamlink/streamlink/blob/master/src/streamlink/stream/hds.py#L518-L527

and create them at

https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugin/plugin.py#L312-L337

the stream_name from the hls/hds file should return something like this
```py
[
  {
    "name": "source",
    "bitrate": "3000",
    "resolution": "720",
    "type": "hls",
  },
  {
    "name": "",
    "bitrate": "3500",
    "resolution": "720",
    "type": "hls",
  },
  {
    "name": "",
    "bitrate": "3500",
    "resolution": "",
    "type": "hds",
  },
]
```

with this we could sort the streams and rename them to `720p_3000k` if there are more than one `720p`

it would be only **one place** to create the filenames not 3 or more.

but it's a lot of sorting

**Closed** 2021-05-08 11:31 UTC
Labels: enhancement, feature request, wontfix
