### ISSUE TITLE
Wrong segment calculation for $SegmentNumber template

### ISSUE THREAD

**Issue by magicbic** [streamlink/streamlink#4945] opened 2022-11-10 23:00 UTC
### Checklist

- [X] This is a bug report and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

I've recently stumbled upon Streamlink and this tool is amazing. Hands down to the developers!

So far, every stream I tried worked like a charm except for this sort of template. I can't notice anything different on its mpegdash manifest but I noticed one strange thing on logs. The parsing calculates segments that are different than the ones I can see on my browser. 

I`ve attached two manifests I am having this issue. On the first manifest I can see on my browser network tab it should start on segment **57010**, but on logs, I can see Streamlink tries to fetch the segment **45081**. And on the second manifest, Streamlink tries to fetch segment **369661** but on my browser, I can see it starts fetching the segment **2680149**.

Both segments are close but not enough to keep up with the live stream. I hope I am clear enough with evidence about this issue.

[first_manifest.txt](https://github.com/streamlink/streamlink/files/9985166/first_manifest.txt)
[second_manifest.txt](https://github.com/streamlink/streamlink/files/9985167/second_manifest.txt)

### Debug log

```text
First manifest
➜  streamlink streamlink --loglevel debug --default-stream 576p URL_REDACTED
[cli][debug] OS:         macOS 13.0
[cli][debug] Python:     3.10.8
[cli][debug] Streamlink: 5.0.1
[cli][debug] Dependencies:
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.1
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.15.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.28.1
[cli][debug]  websocket-client: 1.4.1
[cli][debug] Arguments:
[cli][debug]  url=URL_REDACTED
[cli][debug]  --loglevel=debug
[cli][debug]  --default-stream=['576p']
[cli][info] Found matching plugin dash for URL URL_REDACTED
[plugins.dash][debug] URL=URL_REDACTED; params={}
[utils.l10n][debug] Language code: en_US
[stream.dash][debug] Available languages for DASH audio streams: NONE (using: n/a)
[cli][info] Available streams: 180p (worst), 360p, 576p_alt, 576p, 720p (best)
[cli][info] Opening stream: 576p (dash)
[cli][info] Starting player: /Applications/VLC.app/Contents/MacOS/VLC
[stream.dash][debug] Opening DASH reader for: video2 (video/mp4)
[stream.dash][debug] Opening DASH reader for: audio1 (audio/mp4)
[stream.dash_manifest][debug] Generating segment numbers for dynamic playlist (id=None)
[stream.dash_manifest][debug] Generating segment numbers for dynamic playlist (id=None)
[utils.named_pipe][info] Creating pipe streamlinkpipe-14239-1-1132
[utils.named_pipe][info] Creating pipe streamlinkpipe-14239-2-9778
[stream.ffmpegmux][debug] ffmpeg command: /opt/homebrew/bin/ffmpeg -nostats -y -i /var/folders/45/s8s9zpnd687117_kt4rfwt980000gn/T/streamlinkpipe-14239-1-1132 -i /var/folders/45/s8s9zpnd687117_kt4rfwt980000gn/T/streamlinkpipe-14239-2-9778 -c:v copy -c:a copy -copyts -f matroska pipe:1
[stream.ffmpegmux][debug] Starting copy to pipe: /var/folders/45/s8s9zpnd687117_kt4rfwt980000gn/T/streamlinkpipe-14239-1-1132
[stream.ffmpegmux][debug] Starting copy to pipe: /var/folders/45/s8s9zpnd687117_kt4rfwt980000gn/T/streamlinkpipe-14239-2-9778
[cli][debug] Pre-buffering 8192 bytes
[stream.dash][debug] Download of segment: video2-Header.m4s complete
[stream.dash][debug] Download of segment: audio1-Header.m4s complete
[stream.dash][debug] Waiting for segment: video2-45081.m4s (0.1s)
[stream.dash][debug] Download of segment: video2-45080.m4s complete
[stream.dash][debug] Download of segment: audio1-45080.m4s complete
[stream.dash][debug] Download of segment: video2-45081.m4s complete
[stream.dash][debug] Waiting for segment: video2-45082.m4s (1.3s)
[stream.dash][debug] Waiting for segment: audio1-45082.m4s (1.0s)
[stream.dash][debug] Download of segment: audio1-45081.m4s complete
[stream.dash][error] Failed to open segment URL_REDACTED/segment/video2-45082.m4s: Unable to open URL: URL_REDACTED/segment/video2-45082.m4s (502 Server Error: Bad Gateway for url: URL_REDACTED/segment/video2-45082.m4s)
[stream.dash][debug] Waiting for segment: audio1-45083.m4s (1.0s)
[stream.dash][debug] Download of segment: audio1-45082.m4s complete
[stream.dash][debug] Download of segment: video2-45082.m4s complete
[stream.dash][debug] Waiting for segment: video2-45083.m4s (0.5s)
[stream.dash][debug] Waiting for segment: audio1-45084.m4s (1.1s)
[stream.dash][debug] Download of segment: audio1-45083.m4s complete
[stream.dash][debug] Waiting for segment: video2-45084.m4s (1.1s)
[stream.dash][debug] Download of segment: video2-45083.m4s complete
[stream.dash][debug] Waiting for segment: audio1-45085.m4s (1.3s)
[stream.dash][debug] Download of segment: audio1-45084.m4s complete
[stream.dash][debug] Waiting for segment: video2-45085.m4s (1.1s)
[stream.dash][debug] Download of segment: video2-45084.m4s complete
^CInterrupted! Exiting...
[cli][info] Closing currently open stream...
[stream.ffmpegmux][debug] Closing ffmpeg thread
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[stream.segmented][debug] Closing writer thread
[stream.ffmpegmux][debug] Pipe copy complete: /var/folders/45/s8s9zpnd687117_kt4rfwt980000gn/T/streamlinkpipe-14239-1-1132
[stream.ffmpegmux][debug] Closed all the substreams

Second manifest
➜  streamlink streamlink --loglevel debug --default-stream 576p+a96k URL_REDACTED
[cli][debug] OS:         macOS 13.0
[cli][debug] Python:     3.10.8
[cli][debug] Streamlink: 5.0.1
[cli][debug] Dependencies:
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.1
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.15.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.28.1
[cli][debug]  websocket-client: 1.4.1
[cli][debug] Arguments:
[cli][debug]  url=URL_REDACTED
[cli][debug]  --loglevel=debug
[cli][debug]  --default-stream=['576p+a96k']
[cli][info] Found matching plugin dash for URL URL_REDACTED
[plugins.dash][debug] URL=URL_REDACTED; params={}
[utils.l10n][debug] Language code: en_US
[stream.dash][debug] Available languages for DASH audio streams: NONE (using: n/a)
[cli][info] Available streams: 180p+a96k_alt (worst), 180p+a96k, 360p+a96k_alt, 360p+a96k, 576p+a96k_alt3, 576p+a96k_alt2, 576p+a96k_alt, 576p+a96k, 720p+a96k_alt, 720p+a96k (best)
[cli][info] Opening stream: 576p+a96k (dash)
[cli][info] Starting player: /Applications/VLC.app/Contents/MacOS/VLC
[stream.dash][debug] Opening DASH reader for: video2 (video/mp4)
[stream.dash][debug] Opening DASH reader for: audio1 (audio/mp4)
[stream.dash_manifest][debug] Generating segment numbers for dynamic playlist (id=None)
[stream.dash_manifest][debug] Generating segment numbers for dynamic playlist (id=None)
[utils.named_pipe][info] Creating pipe streamlinkpipe-14350-1-1933
[utils.named_pipe][info] Creating pipe streamlinkpipe-14350-2-8850
[stream.ffmpegmux][debug] ffmpeg command: /opt/homebrew/bin/ffmpeg -nostats -y -i /var/folders/45/s8s9zpnd687117_kt4rfwt980000gn/T/streamlinkpipe-14350-1-1933 -i /var/folders/45/s8s9zpnd687117_kt4rfwt980000gn/T/streamlinkpipe-14350-2-8850 -c:v copy -c:a copy -copyts -f matroska pipe:1
[stream.ffmpegmux][debug] Starting copy to pipe: /var/folders/45/s8s9zpnd687117_kt4rfwt980000gn/T/streamlinkpipe-14350-1-1933
[stream.ffmpegmux][debug] Starting copy to pipe: /var/folders/45/s8s9zpnd687117_kt4rfwt980000gn/T/streamlinkpipe-14350-2-8850
[cli][debug] Pre-buffering 8192 bytes
[stream.dash][debug] Download of segment: video2-Header.m4s complete
[stream.dash][debug] Download of segment: audio1-Header.m4s complete
[stream.dash][debug] Download of segment: audio1--369661.m4s complete
[stream.dash][debug] Download of segment: video2--369661.m4s complete
[stream.dash][debug] Download of segment: audio1--369660.m4s complete
[stream.dash][debug] Download of segment: video2--369660.m4s complete
[stream.dash][debug] Download of segment: audio1--369659.m4s complete
[stream.dash][debug] Download of segment: video2--369659.m4s complete
[stream.dash][debug] Waiting for segment: audio1--369657.m4s (0.3s)
[stream.dash][debug] Download of segment: audio1--369658.m4s complete
[stream.dash][debug] Download of segment: video2--369658.m4s complete
[stream.dash][debug] Download of segment: video2--369657.m4s complete
[stream.dash][debug] Waiting for segment: video2--369656.m4s (1.2s)
[stream.dash][debug] Waiting for segment: audio1--369656.m4s (1.0s)
[stream.dash][debug] Download of segment: audio1--369657.m4s complete
[stream.dash][debug] Download of segment: audio1--369656.m4s complete
[stream.dash][debug] Waiting for segment: audio1--369655.m4s (1.2s)
[stream.dash][debug] Waiting for segment: video2--369655.m4s (0.9s)
[stream.dash][debug] Download of segment: video2--369656.m4s complete
[stream.dash][error] Failed to open segment URL_REDACTED/segment/video2--369655.m4s: Unable to open URL: URL_REDACTED/segment/video2--369655.m4s (502 Server Error: Bad Gateway for url: URL_REDACTED/segment/video2--369655.m4s)
[stream.dash][debug] Download of segment: audio1--369655.m4s complete
```

**Comment by bastimeyer** [comment] 2022-11-14 00:18
Duplicate of #4607.

The issue is apparently caused by the `presentationTimeOffset` attribute which results in a wrong offset. Nobody has had the time yet to properly debug and fix this.

**Closed by bastimeyer** 2022-11-14 00:18 UTC
Labels: bug
