### ISSUE TITLE
Picarto.tv doesn't work

### ISSUE THREAD

**Issue by harkint** [streamlink/streamlink#215] opened 2016-11-25 01:32 UTC
Picarto doesn't work, I get the following error type:

streamlink https://picarto.tv/*
[cli][info] Found matching plugin picarto for URL https://picarto.tv/*
error: No streams found on this URL: https://picarto.tv/*

Asterisk is used here just for the example.

**Comment by Vangelis66** [comment] 2016-11-25 04:34
Dupe of #199 :wink:

Friendly advice: Before submitting a new issue, **do a search of (or browse) [open](https://github.com/streamlink/streamlink/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+is%3Aclosed)** ones; 
it might be that your issue has already been reported by a fellow streamlink user 
(and would be already present within the **open** ones) or, better yet, might have 
already been acted upon (hence been moved to the **closed** ones).

**Comment by gravyboat** [comment] 2016-11-25 05:00
Thanks @Vangelis66, I'm going to close this out for now, feel free the follow the instructions in #199 if you want to immediately update your files, or you can wait till we roll the next release (we just released a few days ago so it might be a bit!).

**Closed by gravyboat** 2016-11-25 05:00 UTC
Labels: duplicate
