### ISSUE TITLE
Afreeca TV plugin doesn't work.

### ISSUE THREAD

**Issue by NuMs1** [streamlink/streamlink#1210] opened 2017-09-10 12:30 UTC
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description
Streamlink doesn't work with Afreeca streams.

### Reproduction steps / Explicit stream URLs to test

http://play.afreecatv.com/jaedong23
Tried with many different streams.

If the above isn't currently live you can find one from here:
http://www.teamliquid.net/video/streams/

Streams do work if I open them in browse.

### Environment details

Operating system and version: Windows 10 64bit.
Streamlink and Python version: Streamlink 0.7.0. As for Python, whichever version Streamlink installs?

### Error Log:

```
C:\Users\Me>streamlink.exe http://play.afreecatv.com/jaedong23
[cli][info] Found matching plugin afreeca for URL http://play.afreecatv.com/jaedong23
error: Unable to open URL: http://sessionmanager01.afreeca.tv:6060/broad_stream_assign.html (HTTPConnectionPool(host='sessionmanager01.afreeca.tv', port=6060): Max retries exceeded with url:/broad_stream_assign.html?broad_no=196000998-mobile-hd-rtmp&broad_key=196000998-flash-hd-rtmp&cors_origin_url=m.afreeca.com&use_cors=true&return_type=gs_cdn (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x045F2290>, 'Connection to sessionmanager01.afreeca.tv timed out. (connect timeout=20.0)')))
```

**Comment by gravyboat** [comment] 2017-09-10 18:31
Duplicate of https://github.com/streamlink/streamlink/issues/837.

**Closed by gravyboat** 2017-09-10 18:31 UTC
