### ISSUE TITLE
Playlist (re)loading is not using HTTP Keep-Alive

### ISSUE THREAD

**Issue by PleasantMachine9** [streamlink/streamlink#2963] opened 2020-05-10 17:03 UTC
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.

### Description

While using the twitch plugin, I checked the network traffic generated by Streamlink with Wireshark.
The sockets which fetch the video segments are persistently open, which is working as expected.

**However I noticed that the connection which fetches the playlist keeps being closed and re-opened on the TCP level. This means that every 2-3s when the playlist is reloaded (for twitch), and entirely new TCP+HTTPS connection is created** (which is also not using the session ticket either, but that is the smaller concern). 

This could very well be the cause of some micro-stutters and lag in the video playback, as TCP+TLS connection establishment seems to take around .5s on my machine to the twitch servers.

### Expected / Actual behavior

1. **The playlist fetching logic should use HTTP Keep-Alive so that the connection is preserved.**

Allegedly `requests.Session` and `urllib` guarantees this according to their docs, but it seems that for some reason, it does not actually work in the current version of streamlink.

Is it possible that streamlink discards or overwrites this "Keep-Alive" behavior?

2. *(Minor) In case the socket must be reopened for some reason, the playlist fetching logic should use TLS Session tickets to resume faster, if they are available.*

*Currently every new connection is also a full new TLS handshake, and the session ticket provided by the server is ignored. This is probably the fault of the `requests` lib, as from my testing, their `Session` class does not use the tickets at all either, even though the `SSLContext` supports this.*

### Reproduction steps / Explicit stream URLs to test

Any twitch stream works, possibly and HLS stream as well.
For example `streamlink.exe -l trace twitch.tv/elajjaz 360p`

Observe the traffic in wireshark, see that a brand new TCP+TLS connection is being established every time the playlist is being reloaded, with the full TLS handshake as well.

1. Start wireshark or tcpdump.
2. Start a stream (that uses HLS).
3. Observe the spammy nature of new TCP connections to the same server (in my case `https://video-weaver.fra02.hls.ttvnw.net/v1/playlist/someurl`)

### Log output

```
C:\Users\Admin>streamlink.exe -l trace twitch.tv/elajjaz 360p
[18:50:53,457][cli][debug] OS:         Windows 10
[18:50:53,457][cli][debug] Python:     3.6.6
[18:50:53,457][cli][debug] Streamlink: 1.4.1
[18:50:53,457][cli][debug] Requests(2.23.0), Socks(1.7.1), Websocket(0.57.0)
[18:50:53,457][cli][info] Found matching plugin twitch for URL twitch.tv/elajjaz
[18:50:53,457][cli][debug] Plugin specific arguments:
[18:50:53,457][cli][debug]  --twitch-low-latency=True (low_latency)
[18:50:53,457][plugin.twitch][debug] Getting live HLS streams for elajjaz
[18:50:55,100][utils.l10n][debug] Language code: en_US
[18:50:55,581][cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p, 720p60, 1080p60 (best)
[18:50:55,581][cli][info] Opening stream: 360p (hls)
[18:50:55,581][plugin.twitch][info] Low latency streaming (HLS live edge: 2)
[18:50:55,596][stream.hls][debug] Reloading playlist
[18:50:55,913][stream.hls][debug] First Sequence: 5122; Last Sequence: 5137
[18:50:55,913][stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 5136; End Sequence: None
[18:50:55,913][stream.hls][debug] Adding segment 5136 to queue
[18:50:55,913][cli][debug] Pre-buffering 8192 bytes
[18:50:55,913][stream.hls][debug] Adding segment 5137 to queue
[18:50:56,82][cli][info] Starting player: "C:\Program Files\MPC-HC\mpc-hc64.exe"
[18:50:56,82][cli.output][debug] Opening subprocess: "C:\Program Files\MPC-HC\mpc-hc64.exe" -
[18:50:56,182][stream.hls][debug] Download of segment 5136 complete
[18:50:56,598][cli][debug] Writing stream to output
[18:50:57,914][stream.hls][debug] Reloading playlist
[18:50:57,950][stream.hls][debug] Adding segment 5138 to queue
[18:50:58,106][stream.hls][debug] Download of segment 5137 complete
[18:50:59,950][stream.hls][debug] Reloading playlist
[18:50:59,991][stream.hls][debug] Adding segment 5139 to queue
[18:51:00,120][stream.hls][debug] Download of segment 5138 complete
[18:51:01,992][stream.hls][debug] Reloading playlist
[18:51:02,28][stream.hls][debug] Adding segment 5140 to queue
[18:51:02,127][stream.hls][debug] Download of segment 5139 complete
[18:51:04,29][stream.hls][debug] Reloading playlist
```

Nothing much interesting in the logs. However it can be observed, that every time `Reloading playlist` is logged, a new TCP connection is opened.

### Additional comments, screenshots, etc.

I applied a patch locally to my requests code that fixed the issue, but it's probably not an elegant one. I manually added the `Connection: Keep-Alive` and `Keep-Alive: timeout=8` headers in `streamlink/stream/hls.py`:
![image](https://user-images.githubusercontent.com/65126927/81505519-520a7200-92df-11ea-8fe8-990e661ddc14.png)

It is easy to verify however, that once it is applied, the HTTP connection is kept alive to the playlist server, which improved my latency issues greatly so far.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment] 2020-05-10 19:49
Hm, that's a bit surprising. I haven't verified this issue myself yet, but the `requests` docs say that it should handle this automatically:
https://requests.readthedocs.io/en/latest/user/advanced/#session-objects
https://requests.readthedocs.io/en/latest/user/advanced/#keep-alive

Streamlink subclasses the `Session` and `HTTPAdapter` classes of `requests`, but nothing related to the connection pool gets changed, as you can see here:
https://github.com/streamlink/streamlink/blame/master/src/streamlink/plugin/api/http_session.py

In your diff you're adding custom keep alive headers to the `HLSStreamWorker`. This should actually be the job of the `HTTPAdapter` and if you're saying that your patch works, then this means that the `HTTPAdapter` doesn't add these headers by itself.

I'm rather a novice here unfortunately, so I don't have the insights of requests and urllib3. @beardypig or @back-to?

**Comment by PleasantMachine9** [comment] 2020-05-10 21:54
I cannot reproduce it now for some reason now after I changed my local files, I suppose the change may have gotten cached somewhere.

I agree it's strange, I'm not sure of the cause.

I might try reinstalling to see if I can reproduce it again if needed.

**Comment by back-to** [comment] 2020-05-12 16:07
i can't reproduce this

> print(res.request.headers)

```
{'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0',
'Accept-Encoding': 'gzip,deflate',
'Accept': '*/*',
'Connection': 'keep-alive'}
```

**Comment by gravyboat** [comment] 2020-05-13 02:17
I'm going to close this for now since we can't replicate. Can always open it back up if there are further details.

**Closed by gravyboat** 2020-05-13 02:17 UTC
Labels: bug
