### ISSUE TITLE
Retreiving master HLS playlist/manifest of streams

### ISSUE THREAD

**Issue by ThomasSkinner** [streamlink/streamlink#3098] opened 2020-08-06 22:18 UTC
Is there a way to get master HLS playlist for twitch streams. When i use the options --stream-url and --json, then I'm able to retrieve links for the media playlists. This is different than the master playlist. Where can I find the master playlist?

Or is there a way to convert to the media playlist to the master playlist? I think I would need codec information for that.

**Comment by bastimeyer** [comment] 2020-08-07 08:38
This is currently unsupported by streamlink / streamlink_cli.

The `--stream-url` parameter is only being used on a single stream after resolving and fetching the master playlist / manifest. The `--json` parameter does this as well, but is also involved in some other outputs.

The problem is that by calling `Plugin.streams`, only a dict of resolved and weighted `Stream`s is returned, and the information from where these are coming from is not included. This is a bit tough though, since plugins can yield streams from multiple sources, which means each individual instance of the basic `Stream` class would need to have this metadata on its own, and returning a single master URL with the `--stream-url` parameter would only be possible if all streams share the same source.

It would be better to add another parameter in addition to `--stream-url`, so that only the selected stream could be queried for its master playlist / manifest metadata. But this requires some work on the entire stack of Stream classes and each individual plugin needs to be checked as well.

**Closed** 2020-11-01 09:25 UTC
Labels: feature request
