### ISSUE TITLE
Use ffprobe to weigh streams by resolution, framerate, and other attributes

### ISSUE THREAD

**Issue by calculon7** [streamlink/streamlink#2682] opened 2019-11-07 14:39 UTC
## Feature Request

- [x] This is a feature request and I have read the contribution guidelines.

### Description

Instead of gathering available stream info by parsing the m3u8 file, use the ffmpeg utility [ffprobe](https://ffmpeg.org/ffprobe.html) to determine stream attributes, whether they are provided in the m3u8 file or not. This would enable Streamlink to weigh and name streams more accurately.

### Expected / Actual behavior

**Expected:**  
720p 60fps streams are always marked as 'best' over 720p 30fps streams.

**Actual:**  
According to [this post](https://github.com/streamlink/streamlink/issues/2384#issuecomment-479563173), Streamlink does not take framerate into account when weighing streams, and instead marks them as 720p, 720p_alt, etc. due to lack of available stream information in the m3u8 file. Therefore, using the 'best' option may return the 720p 30fps stream, even if a 720p 60fps stream is available. I assume this is just based on the order of the streams in the m3u8 file.

Using ffprobe, missing stream information could be gathered, including framerate, regardless of what stream tags are included in the m3u8 file.

### Additional comments, screenshots, etc.
The following command can be used to get stream information in json format:
`ffprobe -v quiet -print_format json -show_format -show_programs -show_streams <url>`

Sample video stream output:  
`
"index": 16,
 "codec_name": "h264",
...
"codec_type": "video",
...
 "width": 640,
"height": 360,
...
"avg_frame_rate": "30000/1001".
...
"tags": {
"variant_bitrate": "931842"
 }
`

**Comment by beardypig** [comment] 2019-11-08 10:19
This would slow down the stream listing _a lot_, although it could be enabled with an option and only for duplicate stream labels. 

Do you have an example m3u8 URL to test?

**Comment by calculon-jr** [comment] 2019-11-08 16:11
I do not, the stream I was using is authenticated and changes throughout the day. Here is an example of the situation I am referring to:
`#EXTM3U`  
`#EXT-X-STREAM-INF:RESOLUTION=1280x720,CODECS="mp4a.40.5,avc1.4d0020",AUDIO="aac"`  
`<urlof720@30fps>`  
`#EXT-X-STREAM-INF:RESOLUTION=1280x720,CODECS="mp4a.40.5,avc1.640020",FRAME-RATE=60.000,AUDIO="aac"`  
`<urlof720@60fps>`  

Maybe a more practical solution would be to rank a stream with a framerate tag higher than those of the same resolution without the framerate tag, since it is sometimes only included on the higher framerate stream.

**Comment by beardypig** [comment] 2019-11-08 16:54
We can include the frame rate in the score, for some streams this is already the case.

**Comment by back-to** [comment] 2020-10-24 08:07
> ffprobe

out of scope for streamlink

> include the frame rate in the score

Duplicate of https://github.com/streamlink/streamlink/issues/2384

**Closed by back-to** 2020-10-24 08:07 UTC
Labels: duplicate, out of scope
