### ISSUE TITLE
Failed to create decryptor: ('Unable to decrypt cipher {0}', 'SAMPLE-AES')

### ISSUE THREAD

**Issue by unlocKing** [streamlink/streamlink#354] opened 2017-01-05 03:51 UTC
Anyone able to help with this:

[cli][info] Found matching plugin stream for URL hlsvariant://https://yahoo7p-a.akamaihd.net/2376984108001/201612/1664/2376984108001_5262246578001_5262237941001.m3u8?pubId=2376984108001&videoId=5262237941001
[cli][info] Available streams: 360p (worst), 576p, 720p (best)
[cli][info] Opening stream: 720p (hls)
[stream.hls][error] Failed to create decryptor: ('Unable to decrypt cipher {0}', 'SAMPLE-AES')
[cli][error] No data returned from stream

Thanks!

**Comment by beardypig** [comment] 2017-01-05 07:36
Sorry @unlocKing, @Vangelis66 is right and there's not a lot we can do. Streams using Apple FairPlay, Microsoft PlayReady or Widevine are not currently supported and likely never will be.

**Comment by gravyboat** [comment] 2017-01-05 08:16
I'm really against spending development time breaking stupid DRM software. If they want to lock their streams down then screw 'em. @Vangelis66 I like the suggestion but yeah, no Windows support = no go on these kinds of issues. @beardypig I think we need to add a section to the known issues talking about the fact we're not going to waste time breaking DRM for people, if they want that kind of support they can either pay a dev to add the support, or work on it themselves. It just isn't worth our time or the potential trouble we could run into.

**Comment by beardypig** [comment] 2017-01-05 08:48
@Vangelis66 `SAMPLE-AES` is different encryption scheme where NAL units are optionally encrypted with extra information embedded in to the transport streams, rather than encrypted the entire transport stream (as in the regular AES-128 method). This means that you have to parse the transport stream to work out what to decrypt, which is not trivial. [hlsdl](https://github.com/selsta/hlsdl) uses `libav` to support MPEG-TS, which is probably why it's written in C :) 
`SAMPLE-AES` support isn't impossible, but it's unlikely as it doesn't seem to appear in the wild much unless when used with DRM - probably because platforms such as Wowza and Unified Streaming use it by default, and you only pay for the licence for those if you wanna use DRM :)

@gravyboat agreed.

**Comment by unlocKing** [comment] 2017-01-10 18:12
Thanks for your replies gents.. now that only leaves one question, how much??? ;)

**Comment by gravyboat** [comment] 2017-01-10 18:33
@unlocKing While we might be able to post a bounty on it via bountysource, I'm kind of against doing so. Currently Streamlink operates in a space where we are in good standing with most organizations since we just pull the stream data they are already making available. Purposefully targeting and breaking DRM/encryption puts us into a space where we could potentially face legal repercussions/takedown attempts.

**Comment by beardypig** [comment] 2017-01-10 18:51
SAMPLE-AES is possible. FairPlay DRM, not likely.

**Comment by unlocKing** [comment] 2017-01-11 00:09
@gravyboat Understood, the project should not be seen to be actively hacking DRM. Thanks for your reply.

**Comment by unlocKing** [comment] 2017-01-24 02:35
I might be wildly wrong, but can this help at all?:

https://github.com/google/shaka-packager

**Comment by beardypig** [comment] 2017-01-24 06:57
@unlocKing that's for developers to write software to package video content in to MPEG DASH format with DRM enabled.

**Comment by gravyboat** [comment] 2017-07-12 01:14
I'm going to close this since we aren't going to fix it anyways. Thanks for all the discussion everyone.

**Closed by gravyboat** 2017-07-12 01:14 UTC
Labels: wontfix

**Comment by campones** [comment] 2018-11-05 23:34
the problem is more and more streams from corporate will be drm'ed..  so at the end the script will become nearly useless, especially since you don't support "third party" websites.

**Comment by gravyboat** [comment] 2018-11-06 00:04
This issue is over a year and a half old @campones. The discussion was complete.
