### ISSUE TITLE
stream.hls: ConnectionError / ReadTimeoutError with http.get(stream=True)

### ISSUE THREAD

**Issue by bobvargas** [streamlink/streamlink#3901] opened 2021-08-05 13:42 UTC
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest build from the master branch

### Description

Hi Streamlink team I have a bug on the latest nightly build of streamlink and it has something to do with with the removal of the remove hls-segment-option. During a twitch stream sometimes it may throw an error of Traceback (most recent call last) 
and after that stream ended without warning. When I watched a VOD It now shows a downloading segment### failed and sometimes the player crashes or the stream just crashes itself. The streams were fine before the removal of the hls-segment-option and now removing it forces the hls-segment-option to go true even if it's not low latency streams. can you address that issue for me thanks.

### Debug log

```text
G:\Users\Senpai>streamlink --loglevel debug
[cli][debug] OS:         Windows 7
[cli][debug] Python:     3.8.7
[cli][debug] Streamlink: 2.3.0_2.gccdd84b-win32
[cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(1.1.0)
[cli][debug] Arguments:
[cli][debug]  --loglevel=debug
[cli][debug]  --rtmp-rtmpdump=rtmpdump.exe
[cli][debug]  --rtmpdump=G:\Program Files (x86)\Streamlink\rtmpdump\rtmpdump.exe

[cli][debug]  --ffmpeg-ffmpeg=G:\Program Files (x86)\Streamlink\ffmpeg\ffmpeg.ex
e
usage: streamlink [OPTIONS] <URL> [STREAM]

Use -h/--help to see the available options or read the manual at https://streaml
ink.github.io
```

**Comment by bastimeyer** [comment] 2021-08-05 14:14
> When I watched a VOD It now shows a downloading segment### failed and sometimes the player crashes or the stream just crashes itself.

Post the actual error log, otherwise this is useless. Your description doesn't sound like it's related.

> the removal of the remove hls-segment-option

`--hls-segment-stream-data` has been removed, which set the [`stream=True` parameter for all HTTP requests via `requests`](https://docs.python-requests.org/en/latest/api/#requests.request) in the HLSStreamWriter, which enables data being written to the output buffer while the segments are still being downloaded instead of waiting for them to complete first. This was already enabled when `--twitch-low-latency` was set, so nothing has actually changed.

**Comment by bobvargas** [comment] 2021-08-05 21:27
Well after testing it out with a Vod I got this:

 Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Senpai>streamlink -p C:\Users\Senpai\Downloads\mpv-x86_64-20210711-git-
f049acf\mpv.exe --player-no-close twitch.tv/djaramistv/video/1104875973 --twitch
-disable-ads
[cli][info] Found matching plugin twitch for URL twitch.tv/djaramistv/video/1104
875973
Available streams: audio, 160p (worst), 360p, 480p, 720p60, 900p60 (best)

C:\Users\Senpai>streamlink -p C:\Users\Senpai\Downloads\mpv-x86_64-20210711-git-
f049acf\mpv.exe --player-no-close twitch.tv/djaramistv/video/1104875973 360p --t
witch-disable-ads
[cli][info] Found matching plugin twitch for URL twitch.tv/djaramistv/video/1104
875973
[cli][info] Available streams: audio, 160p (worst), 360p, 480p, 720p60, 900p60 (
best)
[cli][info] Opening stream: 360p (hls)
[plugins.twitch][info] Will skip ad segments
[cli][info] Starting player: C:\Users\Senpai\Downloads\mpv-x86_64-20210711-git-f
049acf\mpv.exe
Exception in thread Thread-TwitchHLSStreamWriter:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Streamlink\pkgs\urllib3\response.py", line 438, i
n _error_catcher
    yield
  File "C:\Program Files (x86)\Streamlink\pkgs\urllib3\response.py", line 519, i
n read
    data = self._fp.read(amt) if not fp_closed else b""
  File "http\client.py", line 458, in read
  File "http\client.py", line 502, in readinto
  File "socket.py", line 669, in readinto
  File "ssl.py", line 1241, in recv_into
  File "ssl.py", line 1099, in read
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Streamlink\pkgs\requests\models.py", line 753, in
 generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "C:\Program Files (x86)\Streamlink\pkgs\urllib3\response.py", line 576, i
n stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Program Files (x86)\Streamlink\pkgs\urllib3\response.py", line 541, i
n read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "contextlib.py", line 131, in __exit__
  File "C:\Program Files (x86)\Streamlink\pkgs\urllib3\response.py", line 443, i
n _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='d1ymi26ma8va5x.cl
oudfront.net', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\stream\segmented.py",
line 200, in run
    self.write(segment, result, *data)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\stream\hls.py", line 1
61, in write
    return self._write(sequence, *args, **kwargs)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\stream\hls.py", line 1
95, in _write
    for chunk in res.iter_content(8192):
  File "C:\Program Files (x86)\Streamlink\pkgs\requests\models.py", line 760, in
 generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='d1ymi26ma8va5x.cl
oudfront.net', port=443): Read timed out.
[cli][info] Stream ended

And this is running on the latest nightly build of streamlink 2.3.0_2

**Comment by bobvargas** [comment] 2021-08-05 21:28
And testing it out on vlc I got this Vod as well:

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Senpai>streamlink -p C:\Users\Senpai\Desktop\SenPaiLANold\VLC\vlc.exe -
-player-no-close twitch.tv/djaramistv/videos/1104875973 360p --twitch-disable-ad
s
[cli][info] Found matching plugin twitch for URL twitch.tv/djaramistv/videos/110
4875973
error: No playable streams found on this URL: twitch.tv/djaramistv/videos/110487
5973

C:\Users\Senpai>streamlink -p C:\Users\Senpai\Desktop\SenPaiLANold\VLC\vlc.exe -
-player-no-close twitch.tv/djaramistv/video/1104875973 360p --twitch-disable-ads

[cli][info] Found matching plugin twitch for URL twitch.tv/djaramistv/video/1104
875973
[cli][info] Available streams: audio, 160p (worst), 360p, 480p, 720p60, 900p60 (
best)
[cli][info] Opening stream: 360p (hls)
[plugins.twitch][info] Will skip ad segments
[cli][info] Starting player: C:\Users\Senpai\Desktop\SenPaiLANold\VLC\vlc.exe
[stream.hls][error] Download of segment 54 failed
[stream.hls][error] Download of segment 153 failed
[stream.hls][error] Download of segment 272 failed
[stream.hls][error] Download of segment 386 failed
[stream.hls][error] Download of segment 519 failed
[stream.hls][error] Download of segment 549 failed
[stream.hls][error] Download of segment 688 failed
[stream.hls][error] Download of segment 751 failed

**Comment by bastimeyer** [comment] 2021-08-06 01:10
> ```
>   File "ssl.py", line 1099, in read
> socket.timeout: The read operation timed out
>
>   File "C:\Program Files (x86)\Streamlink\pkgs\urllib3\response.py", line 443, in _error_catcher
>     raise ReadTimeoutError(self._pool, None, "Read timed out.")
> urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='d1ymi26ma8va5x.cloudfront.net', port=443): Read timed out.
>
>   File "C:\Program Files (x86)\Streamlink\pkgs\requests\models.py", line 760, in generate
>     raise ConnectionError(e)
> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='d1ymi26ma8va5x.cloudfront.net', port=443): Read timed out.
> ```

Your connection has timed out and requests is raising a `ConnectionError` while trying to read/stream the response content:
https://github.com/psf/requests/blob/v2.25.1/requests/models.py#L759-L760

As you can see from the call stack, this error comes from `urllib3` as a `ReadTimeoutError`
https://github.com/urllib3/urllib3/blob/1.26.6/src/urllib3/response.py#L440-L443

and ultimately from Python's native ssl module as a `socket.timeout` with "The read operation timed out" as error message:
https://github.com/python/cpython/blob/v3.8.7/Lib/ssl.py#L1099

This means that the TLS/SSL (HTTPS) connection to "d1ymi26ma8va5x.cloudfront.net" has timed out on your system, which is not a Streamlink issue.

The way this error can occur now is however different due to the `stream=True` change, as one can see in the linked requests source code. Streamlink currently only excepts `ChunkedEncodingError`s while iterating the response's streamed content, but not `ContentDecodingError`s or `ConnectionError`s that can be raised by `requests` as well, which should be changed for better error messages:
- https://github.com/streamlink/streamlink/blob/db73cb2b00efaf54a13d6a6c642f49ea4777c6b2/src/streamlink/stream/hls.py#L194-L199
- https://github.com/psf/requests/blob/v2.25.1/requests/models.py#L755-L760

The timeout value for each segment can be tweaked with [`--stream-segment-timeout`](https://streamlink.github.io/latest/cli.html#cmdoption-stream-segment-timeout), which defaults to 10 seconds, and the number of re-attempts on an error can be set via [`--stream-segment-attempts`](https://streamlink.github.io/latest/cli.html#cmdoption-stream-segment-attempts), which defaults to 3.

Other than that, there's nothing which Streamlink can do to recover from timeouts on your system like this.

----

> tested the same Vod on mpv and VLC I tested the stable release of streamlink (2.3.0) it produce no errors.

It is completelt irrelevant which player you're using when you see download issues that get logged by Streamlink.

**Comment by bobvargas** [comment] 2021-08-06 01:49
So What I can do revert back to the stable build or are you gonna revert and put back hls-segment-option and the 5 other files from the last build? Because everything went fine without issue until now

**Comment by bastimeyer** [comment] 2021-08-06 03:57
If I understand the issue correctly then this is caused by the lack of segment retry attempts when the HTTP response content is being streamed.

Streamlink's `HTTPSession` which subclasses request's `Session` includes the logic for reattempting HTTP requests on any errors, but this does only work when `stream=False` is set, which makes it buffer the whole response content until it has completed. Streamed HTTP responses however skip that retry logic and `HTTPSession` is only able to reattempt those HTTP requests on an invalid server response for example. Timeout errors are being raised in the HLSStreamWriter's write call instead while reading the content that's still being downloaded.

As I've already said, the `stream=True` parameter was already set by Streamlink since several years whenever `--twitch-low-latency` was set by the user, and I haven't seen any issues with TLS timeouts since then. Seeing this now with these strange circumstances makes me believe that this is rather an edge case on your outdated W7 system. I could be wrong though.

I've just submitted a PR (#3902) which has already been merged into master and it now catches the raised timeout exception(s), so that Streamlink can continue with the failed segments missing in the output. This basically restores the behavior of `2.3.0` which logs the "download of segment X failed" error messages, but it doesn't fix your issue.

**Comment by bobvargas** [comment] 2021-08-06 21:06
And I did a test on Win 10 still causing the same thing on the nightly build Streamlink: 2.3.0_2.gccdd84b-win32
I'll give you the error log as soon as I can.

**Comment by back-to** [comment] 2021-08-07 05:39
> And I did a test on Win 10 still causing the same thing on the nightly build Streamlink: 2.3.0_2.gccdd84b-win32

this is the same version as before, you had to wait until the nightly updated
it should be 2.3.0_7, try again.

**Comment by bobvargas** [comment] 2021-08-07 17:37
I did the test again on windows 10 and found this 

Microsoft Windows [Version 10.0.19043.1023]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Senpai>streamlink -p C:\Users\Senpai\Downloads\mpv-x86_64-20210711-git-f049acf\mpv.exe --player-no-close twitch.tv/heavymetal_mike 720p60 
[cli][info] Found matching plugin twitch for URL twitch.tv/heavymetal_mike
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p60_alt, 720p60 (best)
[cli][info] Opening stream: 720p60 (hls)
[cli][info] Starting player: C:\Users\Senpai\Downloads\mpv-x86_64-20210711-git-f049acf\mpv.exe
Exception in thread Thread-TwitchHLSStreamWriter:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Streamlink\pkgs\urllib3\response.py", line 438, in _error_catcher
    yield
  File "C:\Program Files (x86)\Streamlink\pkgs\urllib3\response.py", line 767, in read_chunked
    chunk = self._handle_chunk(amt)
  File "C:\Program Files (x86)\Streamlink\pkgs\urllib3\response.py", line 711, in _handle_chunk
    value = self._fp._safe_read(amt)
  File "http\client.py", line 612, in _safe_read
  File "socket.py", line 669, in readinto
  File "ssl.py", line 1241, in recv_into
  File "ssl.py", line 1099, in read
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Streamlink\pkgs\requests\models.py", line 753, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "C:\Program Files (x86)\Streamlink\pkgs\urllib3\response.py", line 572, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "C:\Program Files (x86)\Streamlink\pkgs\urllib3\response.py", line 793, in read_chunked
    self._original_response.close()
  File "contextlib.py", line 131, in __exit__
  File "C:\Program Files (x86)\Streamlink\pkgs\urllib3\response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='video-edge-6916b4.jfk04.abs.hls.ttvnw.net', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\stream\segmented.py", line 199, in run
    self.write(segment, result, *data)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\stream\hls.py", line 165, in write
    return self._write(sequence, *args, **kwargs)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\stream\hls.py", line 199, in _write
    for chunk in res.iter_content(8192):
  File "C:\Program Files (x86)\Streamlink\pkgs\requests\models.py", line 760, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='video-edge-6916b4.jfk04.abs.hls.ttvnw.net', port=443): Read timed out.
error: Error when reading from stream: Read timeout, exiting
[cli][info] Stream ended
[cli][info] Closing currently open stream...

it was on the streamlink's recent nightly build

**Comment by bastimeyer** [comment] 2021-08-07 17:43
You are not using the latest version and it's exactly the same which you have posted earlier, no difference. Stop posting logs without `--loglevel=debug`.

**Closed** 2021-08-12 15:08 UTC
Labels: stream: HLS
