### ISSUE TITLE
Facebook Live plugin not working

### ISSUE THREAD

**Issue by bebetoalves** [streamlink/streamlink#1203] opened 2017-09-07 11:42 UTC
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*
*Also check the list of known issues before reporting an issue!*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

I just get this error in every live I test...

C:\>streamlink https://www.facebook.com/jairmessias.bolson
aro/videos/910275185788135/
[cli][info] Found matching plugin facebook for URL https://www.facebook.com/jair
messias.bolsonaro/videos/910275185788135/
Available streams: 0p (worst, best)

### Expected / Actual behavior

...

### Reproduction steps / Explicit stream URLs to test

1. ...
2. ...
3. ...

### Environment details

Operating system and version: Windows 7 Ultimate X64
Streamlink and Python version: Streamlink lastest version & Python 2.7

...

### Comments, logs, screenshots, etc.

Screenshot: http://i.imgur.com/NwSikUO.png

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment] 2017-09-07 17:39
Duplicate of https://github.com/streamlink/streamlink/issues/990 Facebook uses DASH streaming which we don't support yet.

**Closed by gravyboat** 2017-09-07 17:39 UTC
