### ISSUE TITLE
Feature: Rewind to a specific time

### ISSUE THREAD

**Issue by D1mon** [streamlink/streamlink#709] opened 2017-03-16 10:26 UTC
- [x] This is a feature request.

The rewind does not work. https://www.twitch.tv/videos/128990173?t=01h03m58s the video starts from the very beginning, and it should start 1 hour 3 minutes and 58 seconds. And also it should work and record with the "-o" parameter (streamlink -o file.mp4 https://www.twitch.tv/videos/128990173?t=01h03m58s best). It should be written from the specified time to the end.

**Comment by bastimeyer** [comment] 2017-03-16 10:38
Duplicate of #134 

You can't seek in Twitch VODs unless you're using the [`--player-passthrough hls`](https://streamlink.github.io/cli.html#cmdoption-player-passthrough) parameter. This lets Streamlink forward the VOD's HLS url to your player. Recording the stream via Streamlink doesn't work when using this method.

See the thread I've linked for an idea about rewriting the passthrough logic.

**Closed** 2017-03-16 20:15 UTC
Labels: duplicate
