### ISSUE TITLE
Twitch plugin read timeout

### ISSUE THREAD

**Issue by bennyhillthebest** [streamlink/streamlink#3178] opened 2020-09-15 20:41 UTC
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

after a certain amount of time that the stream is opened the plugin is not able to download a new segment and the stream freezes

### Reproduction steps / Explicit stream URLs to test

I'm on Debian Buster with Streamlink from backports (1.5.0+dfsg-1~bpo10+1)

1. streamlink -p "mpv --no-cache" --twitch-disable-hosting --twitch-disable-ads --twitch-low-latency --hls-live-edge 1 --loglevel debug twitch.tv/pokelawls best (or twitch.tv/lirik)
2. wait some time
3. the stream freezes

### Log output

```
[stream.hls][debug] Download of segment 523 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 525 to queue
[stream.hls][debug] Download of segment 524 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 526 to queue
[stream.hls][debug] Download of segment 525 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 527 to queue
[stream.hls][debug] Download of segment 526 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 528 to queue
[stream.hls][debug] Download of segment 527 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 529 to queue
[stream.hls][debug] Download of segment 528 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 530 to queue
[stream.hls][debug] Download of segment 529 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Download of segment 530 complete
[stream.hls][debug] Adding segment 531 to queue
[stream.hls][debug] Adding segment 532 to queue
[stream.hls][debug] Download of segment 531 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 533 to queue
[stream.hls][debug] Download of segment 532 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 534 to queue
[stream.hls][debug] Download of segment 533 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 535 to queue
[stream.hls][debug] Download of segment 534 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 536 to queue
[stream.hls][debug] Download of segment 535 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 537 to queue
[stream.hls][debug] Download of segment 536 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 538 to queue
[stream.hls][debug] Download of segment 537 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 539 to queue
[stream.hls][debug] Download of segment 538 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 540 to queue
[stream.hls][debug] Download of segment 539 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 541 to queue
[stream.hls][debug] Download of segment 540 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 542 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 543 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 544 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 545 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 546 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 547 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 548 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 549 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 550 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 551 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 552 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 553 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 554 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 555 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 556 to queue
[stream.hls][debug] Adding segment 557 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 558 to queue
[stream.hls][debug] Adding segment 559 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 560 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 561 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 562 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 563 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 564 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 565 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 566 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 567 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 568 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 569 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 570 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 571 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 572 to queue
error: Error when reading from stream: Read timeout, exiting
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[cli][info] Stream ended
[cli][info] Closing currently open stream...
benny@debian:~$ 
```

### Additional comments

I'm not sure if this problems relates to the ads problem that have come up recently. If it is the case i'm sorry and you can delete this issue.

**Comment by bastimeyer** [comment] 2020-09-15 21:07
See #3165 and please look for already existing issues next time. As you can see, we are getting a ton of duplicate issues because of Twitch right now and yours is one, too.

**Also, if you take a look at the pinned thread (#3120), you will see that there is a workaround for the embedded ads which prevents them completely. This already got merged on the master branch, so please install the latest development version. See the linked thread for more details.**

----

But let me reply here and sum this up once again, because #3165 is a bit messy due to the amount of replies and incorrect title, so please don't do what you've said and delete yours.

> is not able to download a new segment and the stream freezes
> error: Error when reading from stream: Read timeout, exiting

No, when filtering out ads via `--twitch-disable-ads`, segments will still get downloaded. This is done to work around an ads filtering detection by Twitch. The segments will however not get written to the output. But because streamlink_cli only waits for output of the running stream for at most 60 seconds in its default configuration, you're seeing this error message.

As I've already explained in #3165, you'll have to increase the [`--hls-timeout`](https://streamlink.github.io/cli.html#cmdoption-hls-timeout) value until an improvement to the filtering has been implemented.

**Comment by gravyboat** [comment] 2020-09-15 23:35
Closing and locking.

**Comment by bastimeyer** [comment] 2020-09-18 13:13
Let's keep this thread open, even though we have #3120 pinned for the embedded ads situation on Twitch.

The read timeout is a different issue caused by the ads filtering. Even though it is independent of the Twitch plugin, it is related to it, because the Twitch plugin is currently the only one which has implemented logic for filtering out parts of the output stream.

As I've mentioned before somewhere, the read timeout can be solved without increasing the hls-timeout value by disabling the timeout in the ringbuffer while segments get filtered out. The issue here however is that the thread which is reading the ringbuffer will run into the timeout event (lock) earlier than the writer thread which is also controlling the filtering. That means that in the read thread, the event needs to be set (timeout lock released) after it already attempted to read and the timeout exception either needs to be caught or prevented from being raised. streamlink_cli should not be modified for this exception handling, as it needs to work in streamlink alone. Maybe we could override the TwitchHLSStreamReader.read method, as it currently inherits it from SegmentedStreamReader and only returns the ringbuffer's read result.

**Closed** 2020-09-21 21:11 UTC
Labels: duplicate
