### ISSUE TITLE
[YouTube] Support for long livestreams? (DVR)

### ISSUE THREAD

**Issue by spookyahell** [streamlink/streamlink#2776] opened 2020-01-22 04:18 UTC
## Feature request

- [x] This is a feature request and I have read the contribution guidelines.

### Description
The YouTube player supports going 10 hours back.
Somehow it should be possible to replicate that behavior (when the video allows it) with streamlink
Some URL parameters some how probably allow it to happen...
But I don't know the specifics for sure...
so maybe this is not possible
or maybe just not without implementing a whole lot more code...

if nobody has any direct ideas I'd like this to be the discussion about possibilities and options
(even other software can be recommended if you know any capable of doing so, especially if it's open source, might help....)

### Expected / Actual behavior
Expected:
Be able to record YouTube livestream from the start (every bit of if it it has DVR on)

Actual:
Only goes a few hours back into the past at most: Good but not good enough

### Reproduction steps / Explicit stream URLs to test
Pick any livestream that is longer than a few hours (i.e. 10 hours or more) (it applies to livestreams only so IDK how much it helps once it's finished)
1. https://www.youtube.com/watch?v=GFEc3zdo0ws

**Comment by bastimeyer** [comment] 2020-01-22 05:11
Duplicate of #2542

**Closed by bastimeyer** 2020-01-22 05:11 UTC
