### ISSUE TITLE
Error while installing development version of streamlink 0.7.0

### ISSUE THREAD

**Issue by karlo2105** [streamlink/streamlink#1208] opened 2017-09-09 22:19 UTC
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

I just updated streamlink development from source code : 
`pip install --no-cache-dir -U git+https://github.com/streamlink/streamlink.git`

### Expected / Actual behavior

In command prompt I got such error : 

`streamlink
Traceback (most recent call last):
  File "C:\Program Files\Python27\Scripts\streamlink-script.py", line 6, in <mod
ule>
    from pkg_resources import load_entry_point
  File "c:\program files\python27\lib\site-packages\pkg_resources\__init__.py",
line 3017, in <module>
    @_call_aside
  File "c:\program files\python27\lib\site-packages\pkg_resources\__init__.py",
line 3003, in _call_aside
    f(*args, **kwargs)
  File "c:\program files\python27\lib\site-packages\pkg_resources\__init__.py",
line 3030, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "c:\program files\python27\lib\site-packages\pkg_resources\__init__.py",
line 659, in _build_master
    ws.require(__requires__)
  File "c:\program files\python27\lib\site-packages\pkg_resources\__init__.py",
line 967, in require
    needed = self.resolve(parse_requirements(requirements))
  File "c:\program files\python27\lib\site-packages\pkg_resources\__init__.py",
line 853, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'PySocks!=1.5.7,>=1.5.6; extra == "socks
"' distribution was not found and is required by requests`

### Environment details

Operating system and version: W7 Pro
Streamlink and Python version: streamlink development 0.7.0 / Python 2.7.3

### Comments, logs, screenshots, etc.

Any chance for fix ?
Thanks.

**Comment by gravyboat** [comment] 2017-09-09 23:24
Duplicate of https://github.com/streamlink/streamlink/issues/1195. This is a problem with pip, there are some workarounds in the other issue.

**Closed by gravyboat** 2017-09-09 23:24 UTC
