### ISSUE TITLE
plugins.afreeca: Failed to open segment, Unable to open URL & 400 Client Error: Bad Request for url

### ISSUE THREAD

**Issue by crackerbear** [streamlink/streamlink#3738] opened 2021-05-21 12:16 UTC
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.
- [x] I am using the latest development version from the master branch.

### Description

When trying to download a live afreeca stream, after a few seconds or minutes of downloading, streamlink returns `Failed to open segment xxx: Unable to open URL` and `400 Client Error: Bad Request for url`.

It occurs for every stream I've tried and was working fine a few days ago, so I presume Afreeca may have updated their site in some way very recently.

This is a similar issue to [this bug report](https://github.com/streamlink/streamlink/issues/3538) from a few months ago.

### Reproduction steps / Explicit stream URLs to test

Example:

streamlink --loglevel trace --afreeca-username ******** --afreeca-password ******** https://play.afreecatv.com/joey1114/ best -o C:\output.ts

### Log output

```
[plugins.afreeca][debug] Restored cookies: _au, PdboxBbs, PdboxSaveTicket, PdboxTicket, PdboxUser, RDB, isBbs
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.8.7
[cli][debug] Streamlink: 2.1.2
[cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(1.0.0)
[cli][debug] Arguments:
[cli][debug]  url=https://play.afreecatv.com/joey1114/233286167
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --player="C:\Program Files\mpv\mpv.exe" 
[cli][debug]  --output=C:\output.ts
[cli][debug]  --default-stream=['720p', '720p60', '1080p', '1080p60', '480p', 'medium', 'best']
[cli][debug]  --rtmpdump=C:\Program Files (x86)\Streamlink\rtmpdump\rtmpdump.exe
[cli][debug]  --ffmpeg-ffmpeg=C:\Program Files (x86)\Streamlink\ffmpeg\ffmpeg.exe
[cli][debug]  --afreeca-username=********
[cli][debug]  --afreeca-password=********
[cli][info] Found matching plugin afreeca for URL https://play.afreecatv.com/joey1114/233286167
[plugins.afreeca][debug] Attempting to authenticate using cached cookies
[cli][info] Available streams: sd (worst), hd, original (best)
[cli][info] Opening stream: original (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 3568; Last Sequence: 3573
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 3571; End Sequence: None
[stream.hls][debug] Adding segment 3571 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 3572 to queue
[stream.hls][debug] Adding segment 3573 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3574 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3575 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3576 to queue
[stream.hls][debug] Download of segment 3571 complete
[cli][debug] Checking file output
[cli][debug] Writing stream to output
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3577 to queue
[stream.hls][debug] Adding segment 3578 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3579 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3580 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3581 to queue
[stream.hls][debug] Download of segment 3572 complete
[download][..12-59-20.88 joey1114.ts] Written 2.0 MB (10s @ 195.6 KB/s)                                                [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3582 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3583 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3584 to queue
[stream.hls][debug] Adding segment 3585 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3586 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3587 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3588 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Download of segment 3573 complete
[download][..12-59-20.88 joey1114.ts] Written 4.0 MB (24s @ 164.3 KB/s)                                                [stream.hls][debug] Adding segment 3589 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3590 to queue
[stream.hls][error] Failed to open segment 3574: Unable to open URL: http://pc-web.stream.afreecatv.com/live-stm-09/1920x1080/233286167-common-original-hls_3573_0000009300F800E526B9157C7CE96A68.TS (400 Client Error: Bad Request for url: http://pc-web.stream.afreecatv.com/live-stm-09/1920x1080/233286167-common-original-hls_3573_0000009300F800E526B9157C7CE96A68.TS?aid=.A32.7bbT56vyHM9fKZk.qQpxQlTkXbc6sWFCoLYnErUwzm6lKrsWI3_c51O8L58MTp_9PSjeH7DkvYQDVjj_b14Lc5DPCc39ZhGrfour8LukPIMrAnoyKF7n7x5cXpxYBWErbg-x9B14z8DsHd1k)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3591 to queue
[stream.hls][debug] Adding segment 3592 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][error] Failed to open segment 3575: Unable to open URL: http://pc-web.stream.afreecatv.com/live-stm-09/1920x1080/233286167-common-original-hls_3574_00000082001000412591A45AC5E8E586.TS (400 Client Error: Bad Request for url: http://pc-web.stream.afreecatv.com/live-stm-09/1920x1080/233286167-common-original-hls_3574_00000082001000412591A45AC5E8E586.TS?aid=.A32.7bbT56vyHM9fKZk.qQpxQlTkXbc6sWFCoLYnErUwzm6lKrsWI3_c51O8L58MTp_9PSjeH7DkvYQDVjj_b14Lc5DPCc39ZhGrfour8LukPIMrAnoyKF7n7x5cXpxYBWErbg-x9B14z8DsHd1k)
[stream.hls][debug] Adding segment 3593 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3594 to queue
[stream.hls][error] Failed to open segment 3576: Unable to open URL: http://pc-web.stream.afreecatv.com/live-stm-09/1920x1080/233286167-common-original-hls_3575_000000F60064001B5D661905F7FD8606.TS (400 Client Error: Bad Request for url: http://pc-web.stream.afreecatv.com/live-stm-09/1920x1080/233286167-common-original-hls_3575_000000F60064001B5D661905F7FD8606.TS?aid=.A32.7bbT56vyHM9fKZk.qQpxQlTkXbc6sWFCoLYnErUwzm6lKrsWI3_c51O8L58MTp_9PSjeH7DkvYQDVjj_b14Lc5DPCc39ZhGrfour8LukPIMrAnoyKF7n7x5cXpxYBWErbg-x9B14z8DsHd1k)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3595 to queue
[stream.hls][error] Failed to open segment 3577: Unable to open URL: http://pc-web.stream.afreecatv.com/live-stm-09/1920x1080/233286167-common-original-hls_3576_0000007F00420078BC5541DF1A29B907.TS (400 Client Error: Bad Request for url: http://pc-web.stream.afreecatv.com/live-stm-09/1920x1080/233286167-common-original-hls_3576_0000007F00420078BC5541DF1A29B907.TS?aid=.A32.7bbT56vyHM9fKZk.qQpxQlTkXbc6sWFCoLYnErUwzm6lKrsWI3_c51O8L58MTp_9PSjeH7DkvYQDVjj_b14Lc5DPCc39ZhGrfour8LukPIMrAnoyKF7n7x5cXpxYBWErbg-x9B14z8DsHd1k)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3596 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3597 to queue
[stream.hls][error] Failed to open segment 3578: Unable to open URL: http://pc-web.stream.afreecatv.com/live-stm-09/1920x1080/233286167-common-original-hls_3577_00000099008600CC662098DCFA921840.TS (400 Client Error: Bad Request for url: http://pc-web.stream.afreecatv.com/live-stm-09/1920x1080/233286167-common-original-hls_3577_00000099008600CC662098DCFA921840.TS?aid=.A32.7bbT56vyHM9fKZk.qQpxQlTkXbc6sWFCoLYnErUwzm6lKrsWI3_c51O8L58MTp_9PSjeH7DkvYQDVjj_b14Lc5DPCc39ZhGrfour8LukPIMrAnoyKF7n7x5cXpxYBWErbg-x9B14z8DsHd1k)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3598 to queue
[stream.hls][debug] Adding segment 3599 to queue
[stream.hls][error] Failed to open segment 3579: Unable to open URL: http://pc-web.stream.afreecatv.com/live-stm-09/1920x1080/233286167-common-original-hls_3578_00000045006F002DB0E29BB658211A6C.TS (400 Client Error: Bad Request for url: http://pc-web.stream.afreecatv.com/live-stm-09/1920x1080/233286167-common-original-hls_3578_00000045006F002DB0E29BB658211A6C.TS?aid=.A32.7bbT56vyHM9fKZk.qQpxQlTkXbc6sWFCoLYnErUwzm6lKrsWI3_c51O8L58MTp_9PSjeH7DkvYQDVjj_b14Lc5DPCc39ZhGrfour8LukPIMrAnoyKF7n7x5cXpxYBWErbg-x9B14z8DsHd1k)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3600 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3601 to queue
[stream.hls][error] Failed to open segment 3580: Unable to open URL: http://pc-web.stream.afreecatv.com/live-stm-09/1920x1080/233286167-common-original-hls_3579_0000003C006C003A9A144833C975CD7C.TS (400 Client Error: Bad Request for url: http://pc-web.stream.afreecatv.com/live-stm-09/1920x1080/233286167-common-original-hls_3579_0000003C006C003A9A144833C975CD7C.TS?aid=.A32.7bbT56vyHM9fKZk.qQpxQlTkXbc6sWFCoLYnErUwzm6lKrsWI3_c51O8L58MTp_9PSjeH7DkvYQDVjj_b14Lc5DPCc39ZhGrfour8LukPIMrAnoyKF7n7x5cXpxYBWErbg-x9B14z8DsHd1k)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3602 to queue
[stream.hls][error] Failed to open segment 3581: Unable to open URL: http://pc-web.stream.afreecatv.com/live-stm-09/1920x1080/233286167-common-original-hls_3580_0000008F00B900804692694E680934E1.TS (400 Client Error: Bad Request for url: http://pc-web.stream.afreecatv.com/live-stm-09/1920x1080/233286167-common-original-hls_3580_0000008F00B900804692694E680934E1.TS?aid=.A32.7bbT56vyHM9fKZk.qQpxQlTkXbc6sWFCoLYnErUwzm6lKrsWI3_c51O8L58MTp_9PSjeH7DkvYQDVjj_b14Lc5DPCc39ZhGrfour8LukPIMrAnoyKF7n7x5cXpxYBWErbg-x9B14z8DsHd1k)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3603 to queue
[stream.hls][error] Failed to open segment 3582: Unable to open URL: http://pc-web.stream.afreecatv.com/live-stm-09/1920x1080/233286167-common-original-hls_3581_00000088006100F607CCABAD91F109F2.TS (400 Client Error: Bad Request for url: http://pc-web.stream.afreecatv.com/live-stm-09/1920x1080/233286167-common-original-hls_3581_00000088006100F607CCABAD91F109F2.TS?aid=.A32.7bbT56vyHM9fKZk.qQpxQlTkXbc6sWFCoLYnErUwzm6lKrsWI3_c51O8L58MTp_9PSjeH7DkvYQDVjj_b14Lc5DPCc39ZhGrfour8LukPIMrAnoyKF7n7x5cXpxYBWErbg-x9B14z8DsHd1k)
[stream.hls][debug] Adding segment 3604 to queue
[stream.hls][error] Failed to open segment 3583: Unable to open URL: http://pc-web.stream.afreecatv.com/live-stm-09/1920x1080/233286167-common-original-hls_3582_0000000B00A400A5B830029EEF2E4DDD.TS (400 Client Error: Bad Request for url: http://pc-web.stream.afreecatv.com/live-stm-09/1920x1080/233286167-common-original-hls_3582_0000000B00A400A5B830029EEF2E4DDD.TS?aid=.A32.7bbT56vyHM9fKZk.qQpxQlTkXbc6sWFCoLYnErUwzm6lKrsWI3_c51O8L58MTp_9PSjeH7DkvYQDVjj_b14Lc5DPCc39ZhGrfour8LukPIMrAnoyKF7n7x5cXpxYBWErbg-x9B14z8DsHd1k)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3605 to queue
[stream.hls][error] Failed to open segment 3584: Unable to open URL: http://pc-web.stream.afreecatv.com/live-stm-09/1920x1080/233286167-common-original-hls_3583_00000092001F007F1A573CD31057DD16.TS (400 Client Error: Bad Request for url: http://pc-web.stream.afreecatv.com/live-stm-09/1920x1080/233286167-common-original-hls_3583_00000092001F007F1A573CD31057DD16.TS?aid=.A32.7bbT56vyHM9fKZk.qQpxQlTkXbc6sWFCoLYnErUwzm6lKrsWI3_c51O8L58MTp_9PSjeH7DkvYQDVjj_b14Lc5DPCc39ZhGrfour8LukPIMrAnoyKF7n7x5cXpxYBWErbg-x9B14z8DsHd1k)
[stream.hls][debug] Adding segment 3606 to queue
[stream.hls][error] Failed to open segment 3585: Unable to open URL: http://pc-web.stream.afreecatv.com/live-stm-09/1920x1080/233286167-common-original-hls_3584_0000002F005300F97FD4D8F857EDCFBF.TS (400 Client Error: Bad Request for url: http://pc-web.stream.afreecatv.com/live-stm-09/1920x1080/233286167-common-original-hls_3584_0000002F005300F97FD4D8F857EDCFBF.TS?aid=.A32.7bbT56vyHM9fKZk.qQpxQlTkXbc6sWFCoLYnErUwzm6lKrsWI3_c51O8L58MTp_9PSjeH7DkvYQDVjj_b14Lc5DPCc39ZhGrfour8LukPIMrAnoyKF7n7x5cXpxYBWErbg-x9B14z8DsHd1k)
[stream.hls][debug] Adding segment 3607 to queue
[stream.hls][error] Failed to open segment 3586: Unable to open URL: http://pc-web.stream.afreecatv.com/live-stm-09/1920x1080/233286167-common-original-hls_3585_0000004600660013A6CAC7761E582F70.TS (400 Client Error: Bad Request for url: http://pc-web.stream.afreecatv.com/live-stm-09/1920x1080/233286167-common-original-hls_3585_0000004600660013A6CAC7761E582F70.TS?aid=.A32.7bbT56vyHM9fKZk.qQpxQlTkXbc6sWFCoLYnErUwzm6lKrsWI3_c51O8L58MTp_9PSjeH7DkvYQDVjj_b14Lc5DPCc39ZhGrfour8LukPIMrAnoyKF7n7x5cXpxYBWErbg-x9B14z8DsHd1k)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3608 to queue
[stream.hls][error] Failed to open segment 3587: Unable to open URL: http://pc-web.stream.afreecatv.com/live-stm-09/1920x1080/233286167-common-original-hls_3586_000000E100C00083A7811715788D5CD9.TS (400 Client Error: Bad Request for url: http://pc-web.stream.afreecatv.com/live-stm-09/1920x1080/233286167-common-original-hls_3586_000000E100C00083A7811715788D5CD9.TS?aid=.A32.7bbT56vyHM9fKZk.qQpxQlTkXbc6sWFCoLYnErUwzm6lKrsWI3_c51O8L58MTp_9PSjeH7DkvYQDVjj_b14Lc5DPCc39ZhGrfour8LukPIMrAnoyKF7n7x5cXpxYBWErbg-x9B14z8DsHd1k)
[stream.hls][debug] Adding segment 3609 to queue
[stream.hls][error] Failed to open segment 3588: Unable to open URL: http://pc-web.stream.afreecatv.com/live-stm-09/1920x1080/233286167-common-original-hls_3587_0000002A009B001FCB608D24D5AFCD13.TS (400 Client Error: Bad Request for url: http://pc-web.stream.afreecatv.com/live-stm-09/1920x1080/233286167-common-original-hls_3587_0000002A009B001FCB608D24D5AFCD13.TS?aid=.A32.7bbT56vyHM9fKZk.qQpxQlTkXbc6sWFCoLYnErUwzm6lKrsWI3_c51O8L58MTp_9PSjeH7DkvYQDVjj_b14Lc5DPCc39ZhGrfour8LukPIMrAnoyKF7n7x5cXpxYBWErbg-x9B14z8DsHd1k)
[stream.hls][debug] Adding segment 3610 to queue
[stream.hls][error] Failed to open segment 3589: Unable to open URL: http://pc-web.stream.afreecatv.com/live-stm-09/1920x1080/233286167-common-original-hls_3588_000000AF009500592DC89312BCAA693E.TS (400 Client Error: Bad Request for url: http://pc-web.stream.afreecatv.com/live-stm-09/1920x1080/233286167-common-original-hls_3588_000000AF009500592DC89312BCAA693E.TS?aid=.A32.7bbT56vyHM9fKZk.qQpxQlTkXbc6sWFCoLYnErUwzm6lKrsWI3_c51O8L58MTp_9PSjeH7DkvYQDVjj_b14Lc5DPCc39ZhGrfour8LukPIMrAnoyKF7n7x5cXpxYBWErbg-x9B14z8DsHd1k)
[stream.hls][debug] Adding segment 3611 to queue
[stream.hls][error] Failed to open segment 3590: Unable to open URL: http://pc-web.stream.afreecatv.com/live-stm-09/1920x1080/233286167-common-original-hls_3589_0000003600FC0038E4724AF8DFC3B088.TS (400 Client Error: Bad Request for url: http://pc-web.stream.afreecatv.com/live-stm-09/1920x1080/233286167-common-original-hls_3589_0000003600FC0038E4724AF8DFC3B088.TS?aid=.A32.7bbT56vyHM9fKZk.qQpxQlTkXbc6sWFCoLYnErUwzm6lKrsWI3_c51O8L58MTp_9PSjeH7DkvYQDVjj_b14Lc5DPCc39ZhGrfour8LukPIMrAnoyKF7n7x5cXpxYBWErbg-x9B14z8DsHd1k)
[stream.hls][debug] Adding segment 3612 to queue
error: Error when reading from stream: Read timeout, exiting
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[stream.hls][error] Failed to open segment 3591: Unable to open URL: http://pc-web.stream.afreecatv.com/live-stm-09/1920x1080/233286167-common-original-hls_3590_000000270041005F482E14A10CFD97EE.TS (400 Client Error: Bad Request for url: http://pc-web.stream.afreecatv.com/live-stm-09/1920x1080/233286167-common-original-hls_3590_000000270041005F482E14A10CFD97EE.TS?aid=.A32.7bbT56vyHM9fKZk.qQpxQlTkXbc6sWFCoLYnErUwzm6lKrsWI3_c51O8L58MTp_9PSjeH7DkvYQDVjj_b14Lc5DPCc39ZhGrfour8LukPIMrAnoyKF7n7x5cXpxYBWErbg-x9B14z8DsHd1k)
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

**Comment by back-to** [comment] 2021-05-22 15:50
try `--hls-segment-threads 10`

https://streamlink.github.io/cli.html#cmdoption-hls-segment-threads

**Comment by crackerbear** [comment] 2021-06-02 16:59
With `--hls-segment-threads 10`, whilst the download doesn't get cut short, the resulting file contains a lot of corrupted packets which makes those sections unwatchable and unseekable.

I've currently switched to using ffmpeg instead of steamlink. I don't know what it does differently and it's more effort to get it working since it involves diving into the page source code, but I don't get any errors or cut downloads with it.

For those interested the command is:

`ffmpeg -headers "Referer: https://play.afreecatv.com/STREAMERNAME/STREAMID" -headers "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0" -i "https://live-global-cdn-v02.afreecatv.com/live-stm-12/auth_playlist.m3u8?aid=longstring" -c copy "c:\output.ts"`

In Chrome and with an afreeca stream playing, open the Developer Tools with F12 and in the Network tab, search for m3u8. Copy the m3u8 link address and replace it in the command above after the `-i`. Change the `Referer` to the URL of the stream you have open and it should work from those changes.

**Comment by gravyboat** [comment] 2021-07-14 01:28
@bastimeyer Did you mean to open this back up?

**Comment by bastimeyer** [comment] 2021-07-14 14:34
@gravyboat Yes, because this could potentially be worked around by enforcing a higher number of segment retries if it's indeed a server segment response issue and not related to a session token expiring, etc. But that's just a first thought. I don't have the time or motivation to investigate this myself. I've reopened this thread, so that there are no further duplicates. If this can't be worked around, we can close it again.

**Comment by sirbacon1** [comment] 2021-11-09 00:10
I know I've been having this issue with 2.4.0, but the issue doesn't seem to arise as much on 2.3.0 so I've been running with that the past few months.  With or without additional `--hls-segment-threads` still causes the saved stream to be garbled.

However, the suggestion on https://github.com/streamlink/streamlink/issues/4146#issuecomment-961913470 has seemingly resolved my 'Unable to open URL' issues with 2.4.0.   Still testing it further though.

**Comment by dsnvwlmnt** [comment] 2022-06-09 16:38
> Just wondering if anyone managed to get the plugin to work recently.

IIRC you need ffmpeg installed. 3.2.0 still works here, including with your command (I changed the destination to a different drive letter).

Note that putting files straight in your root c:\ is probably inadvisable. Your command wouldn't work for me there, giving a permission error:
_error: Failed to open output: c:\output.ts ([Errno 13] Permission denied: 'c:\\output.ts')_

**Comment by bastimeyer** [comment] 2022-06-13 15:10
https://github.com/streamlink/windows-builds#notes
https://streamlink.github.io/cli.html#cmdoption-ffmpeg-ffmpeg

**Comment by sirbacon1** [comment] 2022-06-13 20:31
By default it should also be bundled with ffmpeg (check "C:\Program Files\Streamlink\ffmpeg" or wherever you have it installed to verify), but I think the root cause of the problem is actually Windows permissions. You'll want to run PowerShell as an Admin.

The bottom window is running as Administrator and working correctly:
![image](https://user-images.githubusercontent.com/16968559/173433785-677a4aba-9925-469e-b404-d3874406aefc.png)

If it is failing when you're running as Admin I'd definitely double check you PATH variable/use [bastimeyer](https://github.com/bastimeyer)'s link to set the ffmpeg path manually.


In addition, I'm running the stable 4.1.0 release and I'm not seeing the parent issue either. I believe the failed segment issue was resolved in version Streamlink 3.0.3.

**Comment by derekchen60** [comment] 2022-06-14 00:03
Interestingly enough, I tested this on another computer and it seems to just work. To explain further; the first time I installed streamlink, I did it through "winget". I then installed streamlink with the installer package instead. I then tried to uninstall the winget version in case it was interfering. 

The other computer I installed streamlink with was just with the installer package and it seems to work fine. Can't seem to get the first computer working though.

**Comment by KnIfER** [comment] 2022-06-30 03:17
In my case ffmpeg will produce laggy video files ( timeline uneven ) when the network is slow.

https://github.com/streamlink/streamlink/blob/8ef3c73480f172f1535d549a1a6c85c7da1c0c1f/src/streamlink/plugin/api/http_session.py#L173-L183

You need to **reset the retries counter** once a new segment is requested without any error.

Helpful to increase the total_retries number and shorten the delay interval. I also write extra wait-retry logic outside of the streamlink command.


As for hls.py, dont catch any Exception:

```
    def fetch(self, sequence: Sequence) -> Optional[Response]:
        return ...

# and shorten playlist_reload_time

```

**Comment by bastimeyer** [comment] 2022-06-30 05:52
> You need to **reset the retries counter** once a new segment is requested without any error.

[This](https://github.com/streamlink/streamlink/blob/4.1.0/src/streamlink/plugin/api/http_session.py#L218-L227) is the retry counter for **independent HTTP requests**. There is no shared retry counter between multiple different HTTP requests, meaning that [HLS segments don't share a retry counter](https://github.com/streamlink/streamlink/blob/4.1.0/src/streamlink/stream/hls.py#L190-L196).

On the CLI, you can modify the number of segment retries via [`--stream-segment-attempts`](https://streamlink.github.io/latest/cli.html#cmdoption-stream-segment-attempts) and the maximum time for a segment request can be limited via [`--stream-segment-timeout`](https://streamlink.github.io/latest/cli.html#cmdoption-stream-segment-timeout). HLS playlist reload attempts can be limited via [`--hls-playlist-reload-attempts`](https://streamlink.github.io/latest/cli.html#cmdoption-hls-playlist-reload-attempts) and the reload time be modified via [`--hls-playlist-reload-time`](https://streamlink.github.io/latest/cli.html#cmdoption-hls-playlist-reload-time).

**Comment by meehl** [comment] 2023-03-07 18:56
I've been having the same issue.

The rate at which i encounter those errors ranges from several seconds to a few minutes and sometimes up to an hour. I tried playing around with different values for retries, timeouts, etc. but to no avail.
Setting `--hls-segment-threads` 10 does indeed reduce the rate of `Failed to open segment` errors but it eventually just fails with a read timeout.

I did a little digging and noticed that the domain `pc-web.stream.afreecatv.com`, on which the m3u8 playlist and stream segments are hosted, resolves to IPs located in Korea.

Now at this point i should mention that i don't have any playback issues at all when i watch the stream directly through the browser. In this case, the stream is actually served from a different domain `live-global-cdn-v02.afreecatv.com`, which resolves to an IP located closer to me.

My guess is that the long geographical distance to the server and high network activity are the main cause of the problem. This would also explain the high variance of the time between error occurrences.

The change which makes streamlink use the `pc-web.stream.afreecatv.com` domain was introduced in #3549. Manually changing `gs_cdn_pc_web` to `gcp_cdn` (which is the value provided by the afreeca API and used when i watch through the browser) **completely resolves the issue for me**. I recorded multiple 6h+ streams without any errors. No additional parameters are needed.

It seems like this value is used to determine which CDN to use for serving the stream. As someone not living in Korea it makes more sense for me to use the global CDN instead of the korean CDN, which is potentially unreliable because of geographical distance.

So doesn't it make more sense to revert that change and use the value provided by the Afreeca API again? I assume Afreeca automatically chooses the right CDN for you. I'm not sure about that though.

Another option would be a new plugin argument that allows manually overwriting that value. Although i prefer the other option.

Would love to get some input on this. I'd be willing to open a MR, if wanted, once we've figured something out.

**Comment by bastimeyer** [comment] 2023-03-08 07:14
> Setting `--hls-segment-threads 10` does indeed reduce the rate of `Failed to open segment` errors but it eventually just fails with a read timeout.

That's because Streamlink can only output a single progressive stream and can't reset the state of the worker thread and jump back to the live-edge once the stream has fallen too far behind due to poor network conditions, which is where 404 segment errors are coming from. Related: #4535 

> Manually changing `gs_cdn_pc_web` to `gcp_cdn` (which is the value provided by the afreeca API and used when i watch through the browser) **completely resolves the issue for me**.
> I assume Afreeca automatically chooses the right CDN for you.

If that is the case, then the API request param should be chosen which results in the best CDN for each user. A plugin argument should only be used as a last resort solution. If you want to submit a PR, go for it, but please do some research first, so that any changes won't break the usability for other users who don't have network issues. The plugin is also not in an optimal shape and could need some updates, but that's not relevant here.

**Comment by meehl** [comment] 2023-03-08 14:39
> please do some research first, so that any changes won't break the usability for other users who don't have network issues

In order to do that, I used a VPN and connected from a bunch of different countries all around the world to see if using the value provided by the API actually leads to the best server being selected.

In all cases the API returns `gcp_cdn` and the playlist is hosted on the `live-global-cdn-v02.afreecatv.com` domain. The problem is that this domain always resolves to a server located in the US. So this could actually negatively affect some users.

I then did some further tests with the current streamlink implementation which uses `gs_cdn_pc_web` and found some very strange behavior.
The `pc-web.stream.afreecatv.com` domain actually resolves to a server close to the user but **not always**. The DNS entry of that domain sometimes contains a korean IP for some reason. This happens in all the countries i tested.

This can also be seen here:
https://dnschecker.org/#A/pc-web.stream.afreecatv.com/183.111
By setting the refresh to 60s and expected value to `RegExp ^183.11`, we see that most of the time the domain correctly resolves to a local server but sometimes resolves to a korean IP that starts with `183.11`.

The DNS entry has a TTL of 60, i.e. the IP is cached for 60s. So it seems like every 60s there is a possibility of caching that korean IP which, due to poor network conditions or geographical distance, can lead to an unreliable connection and eventually errors.
I'm not familiar with how streamlink fetched the video segments, but would this weird DNS phenomenon explain the errors we get with streamlink?

This looks more like a problem with their CDN so I'm not sure making changes to streamlink is the right approach.
What do you think?

**Comment by bastimeyer** [comment] 2023-03-08 22:25
> This looks more like a problem with their CDN so I'm not sure making changes to streamlink is the right approach.

If there's a DNS misconfiguration on their end, then there's nothing that can be done here, and as you said it yourself, the current plugin implementation already does the best it can do by choosing the right API parameter for getting the best possible CDN.

> I'm not familiar with how streamlink fetched the video segments

It's a regular HLS stream, so the playlist gets polled at regular intervals by the worker thread and segments get queued for the writer thread to download them. The segment-queue's max size is 20 and unless full, the worker thread will keep polling and queuing more segments.

If the cached DNS lookup of a segment's URL (or the playlist itself) expires and results in an IP address of a server with a poor connection, then the polling or segment downloading can become too slow, leading to stream buffering once the output buffer was drained. This also results in falling behind from the stream's live-edge until the connection becomes stable again because the queue needs to be emptied in order. Once fallen too far behind, queued segments are not available anymore, hence the 404 responses. As explained, only progressive stream outputs are supported, so clearing the segment queue would result in a stream discontinuity. This could be forced by the plugin's HLS subclasses though, as it already tries to filter out ads (which is also a discontinuity when it's not at the beginning or end of the stream output), but I'm not really convinced that this would be a great solution.

**Comment by meehl** [comment] 2023-03-08 22:57
That makes sense. So looks like nothing can be done here.

On a side note: I just checked the DNS records of the different regions again and they now all point to korean IPs. I have the suspicion that this is some kind load balancing where servers in other regions are only spun up if their korean servers are under heavy load. At the time of writing it is early in the morning in Korea and there is not much traffic on the site.

But anyways thanks for the quick response. I will probably just sideload a modified version of the plugin which always chooses the US server. That seems to work fine at least for me.

**Comment by lloyd18** [comment] 2024-06-07 15:33
> It is easy to be interrupted in recent days, even when using live-global-cdn-v02.afreecatv.com CDN I don’t know if it is related to their launch of a new live streaming platform. Do you have the same problem?

It seems that they changed the CDN of live-global-cdn-v02.afreecatv.com from GCP to AS22822 www.edg.io

**Comment by sqlurp** [comment] 2024-06-08 23:31
Yes, I am also seeing these errors very frequently now.  Has anyone found a work around or custom plugin?

Ex: `[stream.hls][error] Failed to fetch segment 1741: Unable to open URL: https://pc-web.stream.afreecatv.com/live-stmc-38/1920x1080/270435070-common-original-hls_1740_0000009B00D500A819494400711BED64.TS (400 Client Error: Bad Request for url: https://pc-web.stream.afreecatv.com/live-stmc-38/1920x1080/...`

**Comment by rtyui57** [comment] 2024-07-30 11:03
Any workaround with these changes?

**Comment by rtyui57** [comment] 2024-07-30 11:31
Using a VPN connected to SKorea seems to fix the problem to me, I guess the solution would be to manually let choose the user the CDN better for its location

**Comment by bastimeyer** [comment] 2024-10-16 01:17
Going to close this, since the site rebranded with focus on international expansion (according to what I understood after checking #6246).

As explained, this is a CDN issue which is potentially caused by bad DNS lookups. Once the download becomes too slow, Streamlink can't catch up and the HLS segments start to expire once they're removed from the (live) HLS media playlist, hence the 4xx HTTP response.

If this becomes a recurring issue, then please open a new plugin issue.

**Closed by bastimeyer** 2024-10-16 01:17 UTC
Labels: more info required, plugin issue
