### ISSUE TITLE
Ustream plugin throws erros trying to play or record streamings

### ISSUE THREAD

**Issue by marcozambi** [streamlink/streamlink#4251] opened 2021-12-14 11:32 UTC
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

When trying to play or record from a Ustream (non video.ibm.com) channel (e.g. C:\Users\Marco>streamlink https://video.ibm.com/channel/live-iss-stream besthttps://video.ibm.com/channel/live-iss-stream) I get an error from the websocket api.

I tried the same simple command
`streamlink https://video.ibm.com/channel/live-iss-stream best -o test` 
from 3 different OS, all failing.

1. Win64, installed 3.0.3 via pip
```
[cli][info] Found matching plugin ustreamtv for URL https://video.ibm.com/channel/live-iss-stream
[plugin.api.websocket][error] [Errno 2] No such file or directory
``` 
2. Debian on RaspberryPi 4
```
[cli][info] Found matching plugin ustreamtv for URL https://www.ustream.tv/channel/live-iss-stream
[plugin.api.websocket][error] [Errno 0] Error
```
3. Maybe less common, WSL on Win10
```
[cli][info] Found matching plugin ustreamtv for URL https://www.ustream.tv/channel/live-iss-stream
[plugin.api.websocket][error] EOF occurred in violation of protocol (_ssl.c:1131)
```

So something in websocket seems to be the common denominator.

### Debug log

```text
1. Win64 using CMD

C:\Users\Marco>streamlink https://video.ibm.com/channel/live-iss-stream best --loglevel debug
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.8.3
[cli][debug] Streamlink: 3.0.3
[cli][debug] Requests(2.26.0), Socks(1.7.1), Websocket(1.2.3)
[cli][debug] Arguments:
[cli][debug]  url=https://video.ibm.com/channel/live-iss-stream
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][info] Found matching plugin ustreamtv for URL https://video.ibm.com/channel/live-iss-stream
[plugins.ustreamtv][debug] Connecting to UStream API: media_id=9408562, application=channel, referrer=https://video.ibm.com/channel/live-iss-stream, cluster=live
[plugin.api.websocket][debug] Connecting to: wss://r1792256-1-9408562-channel-ws-live.ums.ustream.tv:1935/1/ustream
[plugins.ustreamtv][debug] Waiting for stream data (for at most 15 seconds)...
[plugin.api.websocket][error] [Errno 2] No such file or directory
[plugin.api.websocket][debug] Closed: wss://r1792256-1-9408562-channel-ws-live.ums.ustream.tv:1935/1/ustream
```
2. Debian on Raspi4
```
/usr/local/bin/streamlink "https://www.ustream.tv/channel/live-iss-stream" best  -o /media/isaa02/test --loglevel debug
[cli][debug] OS:         Linux-5.10.63-v7l+-armv7l-with-debian-10.11
[cli][debug] Python:     3.7.3
[cli][debug] Streamlink: 3.0.3
[cli][debug] Requests(2.25.1), Socks(1.7.0), Websocket(1.2.1)
[cli][debug] Arguments:
[cli][debug]  url=https://www.ustream.tv/channel/live-iss-stream
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --output=/media/isaa02/test
[cli][info] Found matching plugin ustreamtv for URL https://www.ustream.tv/channel/live-iss-stream
[plugins.ustreamtv][debug] Connecting to UStream API: media_id=9408562, application=channel, referrer=https://www.ustream.tv/channel/live-iss-stream, cluster=live
[plugin.api.websocket][debug] Connecting to: wss://r2807768-1-9408562-channel-ws-live.ums.ustream.tv:1935/1/ustream
[plugins.ustreamtv][debug] Waiting for stream data (for at most 15 seconds)...
[plugin.api.websocket][error] [Errno 0] Error
[plugin.api.websocket][debug] Closed: wss://r2807768-1-9408562-channel-ws-live.ums.ustream.tv:1935/1/ustream
```

3. WSL
```
$ /usr/local/bin/streamlink "https://www.ustream.tv/channel/live-iss-stream" best --loglevel debug
[cli][debug] OS:         Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.29
[cli][debug] Python:     3.8.10
[cli][debug] Streamlink: 3.0.3
[cli][debug] Requests(2.26.0), Socks(1.7.1), Websocket(1.2.3)
[cli][debug] Arguments:
[cli][debug]  url=https://www.ustream.tv/channel/live-iss-stream
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][info] Found matching plugin ustreamtv for URL https://www.ustream.tv/channel/live-iss-stream
[plugins.ustreamtv][debug] Connecting to UStream API: media_id=9408562, application=channel, referrer=https://www.ustream.tv/channel/live-iss-stream, cluster=live
[plugin.api.websocket][debug] Connecting to: wss://r15601441-1-9408562-channel-ws-live.ums.ustream.tv:1935/1/ustream
[plugins.ustreamtv][debug] Waiting for stream data (for at most 15 seconds)...
[plugin.api.websocket][error] EOF occurred in violation of protocol (_ssl.c:1131)
[plugin.api.websocket][debug] Closed: wss://r15601441-1-9408562-channel-ws-live.ums.ustream.tv:1935/1/ustream
```
```

**Comment by bastimeyer** [comment] 2021-12-14 11:55
Duplicate of #4236
Fixed by #4238
Install the latest commit from the master branch

**Closed by bastimeyer** 2021-12-14 11:55 UTC
Labels: plugin issue
