### ISSUE TITLE
A help for adding plugins

### ISSUE THREAD

**Issue by wilheamdash** [streamlink/streamlink#3452] opened 2020-12-26 15:32 UTC
## Plugin Request

- [ ] This is a plugin request and I have read the contribution guidelines and plugin request requirements.
- [x] I am using the latest development version from the master branch.

### Description
I would like to thank everyone who have used the streamlin very fondly until now and have contributed, but now I want to add plugins myself so that we do not tire you with more plugin requests. I do not know where to start but I know that I am open to all kinds of support. There is no subject area to open it here and I opened it to the wrong place.I also apologize for this. Good work, my goal is to contribute to streamlink work.

### Example stream URLs

1. ...
2. ...
3. ...

### Additional comments, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment] 2020-12-26 15:37
- #117 
- https://github.com/streamlink/streamlink/issues/3195#issuecomment-697262096
- https://github.com/streamlink/streamlink/issues/3195#issuecomment-697529984
- https://streamlink.github.io/developing.html

**Comment by wilheamdash** [comment] 2020-12-26 15:46
First of all, thanks for such a fast response, I will start trials for tv channels and some live chat applications I hope I can succeed.

**Comment by bastimeyer** [comment] 2020-12-26 16:22
Good luck! I'm going to close this thread, as it's a duplicate of the ones linked above.

**Closed by bastimeyer** 2020-12-26 16:22 UTC
Labels: question
