### ISSUE TITLE
InsecureRequestWarning error on connecting to Twitch channels

### ISSUE THREAD

**Issue by v1kn** [streamlink/streamlink#963] opened 2017-05-28 23:23 UTC
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

error on connecting to Twitch channels
(formatted to increase readability):

    <user-pip-folder>/lib/python3.5/site-packages/urllib3/connectionpool.py:852
    InsecureRequestWarning: Unverified HTTPS request is being made.
    Adding certificate verification is strongly advised.
    See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings

### Environment details

Xubuntu 16.04 LTS
Streamlink 0.6.0
Python 3.5.2

### Other notes

My streamlink invocation (which I've been using since livestreamer days):

    streamlink \
    --http-header (Twitch ID) \
    --retry-open 8000 \
    --retry-streams 10 \
    --player-continuous-http \
    --player-passthrough hls \
    --hls-segment-threads 3 \
    --player "mpv" \
    URL

**Comment by beardypig** [comment] 2017-05-29 09:16
That's weird, certificate verification should be enabled on  any https request. Can you try curling the URL and see if it also gives a warning about certificates?

**Comment by v1kn** [comment] 2017-05-29 09:30
Sure, here is the output

    curl https://twitch.tv/<channel-name>

    <html>
    <head><title>302 Found</title></head>
    <body bgcolor="white">
    <center><h1>302 Found</h1></center>
    <hr><center>nginx</center>
    </body>
    </html>

**Comment by globau** [comment] 2017-05-29 11:25
@beardypig the twitch plugin explicitly disables certificate verification:

https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/twitch.py#L207
```
# The certificate used by Twitch cannot be verified on some OpenSSL versions.
res = http.get(url, params=params, verify=False, headers=headers)
```

changing to `verify=True` removes the warnings.

what's interesting is streamlink should be silencing these InsecureRequestWarnings:

https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugin/api/http_session.py#L20
```
# We tell urllib3 to disable warnings about unverified HTTPS requests,
# because in some plugins we have to do unverified requests intentionally.
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
```

so the crux of this issue is that call to disable_warnings is no longer working.  if i remove the `try`/`except` block it works, so it isn't throwing an exception.

i can still suppress the warning by setting the `PYTHONWARNINGS` environmental variable, so it's possible:
```
PYTHONWARNINGS="ignore:Unverified HTTPS request" streamlink https://www.twitch.tv/sovietwomble
```

**Comment by beardypig** [comment] 2017-05-29 12:02
Ah true... I'll try to recreate it, I haven't seen those warnings recently... @globau do you get the warnings? Which python version/OS are you running?

**Comment by globau** [comment] 2017-05-29 12:12
@beardypig yes - Python 2.7.13 (homebrew) on OSX 10.12.5.

**Comment by beardypig** [comment] 2017-05-30 10:05
@globau @v1kn could you let me know which version of `requests` and `urllib3` you are using. You should be able to find the versions by using `pip freeze`.

**Comment by v1kn** [comment] 2017-05-30 10:19
@beardypig 
Up till yesterday I had `2.16.5`. My systemd service for updating pip packages ran yesterday, now requests are `2.17.3`, and the issue is gone. No more errors.

So this was a `requests` thing?

**Comment by globau** [comment] 2017-05-30 10:29
@beardypig `requests 2.16.5` and `urllib3 1.21.1`.

**Comment by beardypig** [comment] 2017-05-30 10:30
With `2.16.x` I do get the warnings, with `2.17.1+` I do not get the warnings, `2.15.x` also does not give the warnings. It appears to be an issue with `requests`.

@globau are you able to update to `requests>=2.17.1`.

**Comment by v1kn** [comment] 2017-05-30 10:34
@beardypig 
good to know. For me the issue is resolved, at least for now.

**Comment by globau** [comment] 2017-05-30 10:45
@beardypig yes, upgrading requests resolves this issue for me too.

**Comment by beardypig** [comment] 2017-05-30 10:48
From testing versions `2.16.0`, `2.16.1`, `2.16.2`, `2.16.3`, `2.16.4`, `2.16.5`, `2.17.1` are all affected.

**Comment by thinkpad4** [comment] 2017-06-03 01:53
Other then editing the twitch.py file and change # The certificate used by Twitch cannot be verified on some OpenSSL versions.
res = http.get(url, params=params, verify=False, headers=headers) to True, is there something I can add to the configuration file to make it bypass the InsecureRequestWarning?

**Comment by beardypig** [comment] 2017-06-03 09:50
You can try the latest nightly, I think it should have thrown fix now...

**Comment by thinkpad4** [comment] 2017-06-03 22:57
Just tested the latest nightly and still
[cli][info] Found matching plugin twitch for URL twitch.tv/crream
[plugin.twitch][info] Attempting to authenticate using OAuth token
d:\Program Files (x86)\Streamlink\pkgs\urllib3\connectionpool.py:852: InsecureRe
questWarning: Unverified HTTPS request is being made. Adding certificate verific
ation is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advance
d-usage.html#ssl-warnings
  InsecureRequestWarning)
[plugin.twitch][info] Successfully logged in as Thinkpad4
d:\Program Files (x86)\Streamlink\pkgs\urllib3\connectionpool.py:852: InsecureRe
questWarning: Unverified HTTPS request is being made. Adding certificate verific
ation is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advance
d-usage.html#ssl-warnings
  InsecureRequestWarning)
d:\Program Files (x86)\Streamlink\pkgs\urllib3\connectionpool.py:852: InsecureRe
questWarning: Unverified HTTPS request is being made. Adding certificate verific
ation is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advance
d-usage.html#ssl-warnings
  InsecureRequestWarning)
[plugin.twitch][info] crream is hosting admiralbahroo
[plugin.twitch][info] hosting was disabled by command line option
d:\Program Files (x86)\Streamlink\pkgs\urllib3\connectionpool.py:852: InsecureRe
questWarning: Unverified HTTPS request is being made. Adding certificate verific
ation is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advance
d-usage.html#ssl-warnings
  InsecureRequestWarning)
error: No playable streams found on this URL: twitch.tv/crream

**Comment by beardypig** [comment] 2017-06-03 23:56
That's strange, I cannot reproduce that warning. Could you re-download the latest nightly, uninstall and reinstall it. I used [streamlink-0.6.0-20170603.exe](https://bintray.com/streamlink/streamlink-nightly/download_file?file_path=streamlink-0.6.0-20170603.exe) (generated 6 hours ago), and I did not get the warning when playing a twitch stream.

**Comment by thinkpad4** [comment] 2017-06-04 00:11
Yep, uninstalling the old version and install that nightly works with no issue

**Comment by thinkpad4** [comment] 2017-06-14 07:12
I haven't encountered this issue since @beardypig suggested I uninstall and reinstall the nightly.

**Comment by gravyboat** [comment] 2017-06-14 16:11
@thinkpad4 Thanks for the update, are we good to close this out then?

**Comment by thinkpad4** [comment] 2017-06-14 22:28
And using the latest Nightly [cli][info] Found matching plugin twitch for URL twitch.tv/crream
[plugin.twitch][info] Attempting to authenticate using OAuth token
d:\Program Files (x86)\Streamlink\pkgs\urllib3\connectionpool.py:852: InsecureRe
questWarning: Unverified HTTPS request is being made. Adding certificate verific
ation is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advance
d-usage.html#ssl-warnings
  InsecureRequestWarning)
[plugin.twitch][info] Successfully logged in as Thinkpad4
d:\Program Files (x86)\Streamlink\pkgs\urllib3\connectionpool.py:852: InsecureRe
questWarning: Unverified HTTPS request is being made. Adding certificate verific
ation is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advance
d-usage.html#ssl-warnings
  InsecureRequestWarning)
d:\Program Files (x86)\Streamlink\pkgs\urllib3\connectionpool.py:852: InsecureRe
questWarning: Unverified HTTPS request is being made. Adding certificate verific
ation is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advance
d-usage.html#ssl-warnings
  InsecureRequestWarning)
d:\Program Files (x86)\Streamlink\pkgs\urllib3\connectionpool.py:852: InsecureRe
questWarning: Unverified HTTPS request is being made. Adding certificate verific
ation is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advance
d-usage.html#ssl-warnings
  InsecureRequestWarning)
error: No playable streams found on this URL: twitch.tv/crream

Getting this again

**Closed** 2017-07-28 04:10 UTC
Labels: dependency issue
