### ISSUE TITLE
Crunchyroll needs pyCrypto

### ISSUE THREAD

**Issue by Connor22** [streamlink/streamlink#162] opened 2016-11-14 04:44 UTC
When trying to play a crunchyroll stream on Windows, I get 
`Could not open stream: Need pyCrypto installed to decrypt this stream`

**Comment by Vangelis66** [comment] 2016-11-14 06:37
Duplicate of #150

**Comment by gravyboat** [comment] 2016-11-15 03:17
I'm going to close this one and we can keep the discussion going over in #150 .

**Closed by gravyboat** 2016-11-15 03:17 UTC
Labels: oversight, question
