### ISSUE TITLE
Can't find "tv3cat" plugin

### ISSUE THREAD

**Issue by q2dg** [streamlink/streamlink#3246] opened 2020-10-12 12:46 UTC
## Plugin Issue

- [ X ] This is a plugin issue and I have read the contribution guidelines.

### Description

A image is worth a thousand words.

![imatge](https://user-images.githubusercontent.com/7274874/95747957-925c8a80-0c99-11eb-95f9-5d37261e0429.png)

### Reproduction steps 

I've just using the "python3-streamlink" package provided by Fedora 32

Thanks!

**Comment by mkbloke** [comment] 2020-10-12 19:15
**Feedback/answer (see ticked items):**

As requested in the plugin issue template:

- [ ] Description and/or reproduction steps are insufficiently detailed
- [ ] Streamlink version in use not specified
- [ ] Full ```--loglevel debug``` log output not provided
- [ ] Research of prior issues/fixes appears to be insufficient [1]

Other feedback:
- [ ] Issue is out of scope and/or should be reported/help sought elsewhere
- [ ] Issue appears to unnecessarily duplicate another issue that is open/closed
- [ ] User appears to be using an outdated Streamlink version/plugin [2] [3]
- [x] Other (see below)

- Other: In the future, can you please provide the log output as text, not an image, thanks.

It looks like the URL matching needs a little tweaking and some other small issues with it fixed.  For the time being, you can get it to work using the ```http://``` scheme and by appending a ```/``` to the end of the URL you are using:
```
streamlink http://www.ccma.cat/tv3/directe/324/
[cli][info] Found matching plugin tv3cat for URL http://www.ccma.cat/tv3/directe/324/
Available streams: 180p_426k (worst), 360p_646k, 360p_1416k (best)
```

~~Please amend/close your issue accordingly and/or undertake the requested prior research before opening an issue in future.~~

[1] [Search all open/closed issues/pull requests](https://github.com/streamlink/streamlink/issues?q=)
[2] [Install the most recent version of Streamlink](https://streamlink.github.io/install.html)
[3] [Check the master branch for plugin updates](https://github.com/streamlink/streamlink/tree/master/src/streamlink/plugins)

**Closed** 2020-10-13 04:30 UTC

**Comment by q2dg** [comment] 2020-10-13 08:19
Wow!! Thanks a lot!!! 
Understood
