### ISSUE TITLE
No audio from Youtube plugin. Scrubbing breaks stream

### ISSUE THREAD

**Issue by sorianov** [streamlink/streamlink#3084] opened 2020-07-20 07:54 UTC
---
name: Packaged Windows streamlinkrc has unquoted paths
about: Unquoted paths for ffmpeg-ffmpeg and rtmpdump parameters
---

## Plugin Issue

- [ ] This is a plugin issue and I have read the contribution guidelines.

### Description

When using a plugin for Youtube, there is no audio. Video displays but scrubbing breaks the stream.

```
OS: Windows 10 1909
Terminal: Windows Terminal 1.0.1811.0
Streamlink: 1.5.0
Player: VLC 3.0.11 x64
```

Here is the streamlinkrc file I used that reproduces the issue: https://gist.github.com/sorianov/b5c16b81934c358b1f9abfdeaf10790b
Here is the streamlinkrc file where I no longer experience the issue: https://gist.github.com/sorianov/fce15dae10d408f914eb86071e97e13c

### Reproduction steps / Explicit stream URLs to test

Tested using https://www.youtube.com/watch?v=InJS9Dhon04

1. Update from an old version of streamlink using streamlink-1.5.0.exe from 1.5.0 release.
2. Open Windows Terminal
3. Enter ``streamlink https://www.youtube.com/watch?v=InJS9Dhon04 best``

### Log output

https://gist.github.com/sorianov/8fc0201b1c21540274cd3d33c7991509

### Additional comments, screenshots, etc.

Wrapping the ffmpeg-ffmpeg and rtmpdump config parameters in quotes fixed this issue for me. See working streamlinkrc gist. I am able to scrub and audio works with my player (VLC) with the working streamlinkrc.

**Comment by gravyboat** [comment] 2020-07-20 19:26
You don't provide the command you're using. With MPV and Streamlink 1.5.0 `streamlink -l debug https://www.youtube.com/watch?v=InJS9Dhon04` works perfectly fine for me. Did you try just using Streamlink without any extra options? What about a different player? Also since when has scrubbing ever worked by default? The video is still streamed directly. If you're doing additional work on top of the basic Streamlink output to allow scrubbing there's nothing we can do about that.

**Comment by sorianov** [comment] 2020-07-20 22:12
Sorry, I have added further detail to the main post. Please note that I have fixed the issue for myself, but I thought I would bring it up here. I am new to using streamlink and was playing around with it the other night and encountered this issue.

**Comment by gravyboat** [comment] 2020-07-21 00:39
The configs help and make the issue clear. This is the expected behavior due to the special characters such as spaces or the colon that you have in your paths. The config parsing doesn't always understand what to do. The example in the docs has an additional note where you can see this behavior just below the main example: https://streamlink.github.io/cli.html#example

I'm going to close this since you were able to figure it out.

**Closed by gravyboat** 2020-07-21 00:39 UTC
Labels: more info required

**Comment by DCTest1** [comment] 2020-07-26 18:39
I just found this thread. I had the same issue. As far as i know ffmpeg & rtmpdump were never changed by me. Normally I use TwitchGUI to utilize streamlink. For youtube links i had to use the CLI. Interestingly the VLC path is in quotes, as is MPC. Just the paths to ffmpeg and rtmpdump not. This seams to be a issue on your side, not the users. Many more users may experience no sound with youtube, they might just not write feedback here. I can guarantee that I never changed the configfile regarding ffmpeg/rtmpdump. Only thing i changed is to give VLC 10 sec buffering.

You might want to consider checking the configfile for unquoted paths in the next update.

**Comment by bastimeyer** [comment] 2020-07-26 19:34
https://github.com/streamlink/streamlink/blob/1.5.0/win32/streamlinkrc#L50
https://github.com/streamlink/streamlink/blob/1.5.0/win32/streamlinkrc#L56
This thread is about those two lines in the config file which gets written by the Streamlink installer for Windows. Other OSes don't have a default config and config files need to be created by the user himself. As you can see though, both of these two lines are actually comments and not real config vars.

This is the regex of how config lines are parsed by the overwritten [`convert_arg_line_to_args`](https://docs.python.org/3/library/argparse.html#argparse.ArgumentParser.convert_arg_line_to_args) argparse method:
[`(?P<name>[A-z-]+)\s*(?P<op>=)?\s*(?P<value>.*)`](https://github.com/streamlink/streamlink/blob/1.5.0/src/streamlink_cli/argparser.py#L18-L46)
This means that values don't need to be quoted.

This is what the [config file syntax documentation](https://streamlink.github.io/cli.html#syntax) says:
> Any quotes used will be part of the value, so only use when the value needs them, e.g. specifying a player with a path containing spaces.

This is meant for values for the `--player` parameter for example, where you can set a quoted absolute player executable path with spaces in between and additional player parameters, as [the entire value will get parsed with shell scripting syntax](https://github.com/streamlink/streamlink/blob/1.5.0/src/streamlink_cli/output.py#L205-L248). This has nothing to do with the config parsing itself.

If you take a look at the command resolver implementation of the [`FFMPEGMuxer` class](https://github.com/streamlink/streamlink/blob/1.5.0/src/streamlink/stream/ffmpegmux.py#L144-L151), everything you put into the `ffmpeg-ffmpeg` config var (without quotes), will be used as a parameter for the [`which`](https://docs.python.org/3/library/shutil.html#shutil.which) shell utility method, which resolves single executable names, or relative/absolute executable paths from the `PATH` environment variable. Quoting the entire value would therefore cause issues here.

Overall, this means that both lines in the default Windows config file are correct by not being quoted, if they were uncommented.
