### ISSUE TITLE
Bug in detecting best quality.

### ISSUE THREAD

**Issue by sacc91** [streamlink/streamlink#786] opened 2017-04-11 19:31 UTC
### Checklist

- [x] This is a bug report.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description

Streamlink says it's playing Source but it's actually not.

I noticed a while ago that playing **"Source"** with Streamlink didn't look as good as it did on Twitch and I finally opened the Terminal and found out what is going on. The CLI mistakes which is the best quality in some streams.

So it says it's playing **Source** but is actually playing the third best option in this case.

<img width="771" alt="screenshot 2017-04-11 14 15 11" src="https://cloud.githubusercontent.com/assets/255272/24926577/ad98aa5a-1ec1-11e7-9959-bef8a7cd7918.png">

### Reproduction steps / Stream URLs to test

1. Open https://www.twitch.tv/shroud or a stream with similar quality options on Streamlink
2. Use the CLI to list the qualities directly 
3. Open the best quality listed (mislabeled) and compare.

### Environment details (operating system, python version, etc.)

macOS 10.12.3

### Comments, logs, screenshots, etc.

In this screenshot you can compare the quality on a stream opened directly calling the highest quality in CLI and what Streamlink says it's source. (Easier to see difference in quality in the webcam portion of the image).

![screenshot 2017-04-11 14 26 44](https://cloud.githubusercontent.com/assets/255272/24927001/18c72ff8-1ec3-11e7-9620-222430ab9cb5.png)

**Comment by bastimeyer** [comment] 2017-04-11 19:42
You are in the wrong repo, @sacc91...
This is a Streamlink **Twitch GUI** related issue. This issue was introduced by Twitch's new stream quality names two weeks ago and is caused by old quality fallback names which are necessary because of the (deprecated) Livestreamer support.
This has been reported a few days ago, a release got published, although still broken in some cases as it turned out. A new future proof quality selection system for the streamlink streaming provider has already been implemented, but hasn't been released yet. If you have any comments, please use this thread and close this one, thanks.
streamlink/streamlink-twitch-gui#434

**Comment by sacc91** [comment] 2017-04-11 19:50
Thank you!

**Closed** 2017-04-11 19:50 UTC
