### ISSUE TITLE
Only one connection allowed to stream from http. IPLAYER/itvhub is not working

### ISSUE THREAD

**Issue by jamiejacksoncumbria** [streamlink/streamlink#2882] opened 2020-04-11 00:12 UTC
When creating a http stream only one device can connect to that stream. Is it possible to have multiple connections to the stream?

I find filmon cuts off after so lond do we have to give it a user id and password some how?

BBC IPLAYER gives this error when try to play streams. User and password is correct.

streamlink https://www.bbc.co.uk/iplayer/live/bbcone --player-external-http --player-external-http-port 23572 --player-continuous-http --bbciplayer-username xxx --bbciplayer-password xxx
[cli][info] Found matching plugin bbciplayer for URL https://www.bbc.co.uk/iplayer/live/bbcone
[plugin.bbciplayer][info] A TV License is required to watch BBC iPlayer streams, see the BBC website for more information: https://www.bbc.co.uk/iplayer/help/tvlicence
[plugin.bbciplayer][error] Could not authenticate, check your username and password
error: No playable streams found on this URL: https://www.bbc.co.uk/iplayer/live/bbcone

Also itv hub gives this error

streamlink https://www.itv.com/hub/itv2 --player-external-http --player-external-http-port 23572 --player-continuous-http
[cli][info] Found matching plugin itvplayer for URL https://www.itv.com/hub/itv2
error: Unable to open URL: http://mercury.itv.com/PlaylistService.svc?wsdl (403 Client Error: Forbidden for url: http://mercury.itv.com/PlaylistService.svc?wsdl)

am I doing something wrong here?

Thanks in advance

**Comment by bastimeyer** [comment] 2020-04-11 00:21
Wrong repo, moved it to streamlink/streamlink...
Also duplicate of streamlink/streamlink#180

**Closed by bastimeyer** 2020-04-11 00:21 UTC
