### ISSUE TITLE
Streamlink plugins question

### ISSUE THREAD

**Issue by johnthecracker** [streamlink/streamlink#1892] opened 2018-07-01 22:47 UTC
## Plugin Issue

- [x ] This is a plugin issue and I have read the contribution guidelines. 

### Description

I have 2 questions to ask here:

How to modify plugin from another github fork to adapt it to work with streamlink?

Is Streamlink checking each and every plugin for being politically correct after starting itself
and only after that running plugin that I actually want to use ?

### Reproduction steps / Explicit stream URLs to test

Here are more details:

I have modified myfreecams.py plugin from another Github fork successfully to run with Streamlink,
and fc2.py successless.

Is there any general rule that can be explained in simple words how to adapt plugins 
from other Github forks to work with Streamlink?

After failing with my fc2.py modification and observing some redundant work 
carried out by Streamlink while running another plugin I simply coppied working livecli plugin 
as it is to Streamlink plugins directory and here is more of the same result:

streamlink.exe https://www.myfreecams.com/#AnnBrooke best

````
Failed to load plugin fc2:
  File "imp.py", line 234, in load_module
  File "imp.py", line 172, in load_source
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\P\STREAMLINK\pkgs\streamlink\plugins\fc2.py", line 11, in <module>
    from livecli.cache import Cache
ImportError: No module named 'livecli'

[cli][info] Found matching plugin myfreecams for URL https://www.myfreecams.com/#AnnBrooke
[plugin.myfreecams][info] Username: AnnBrooke
[plugin.myfreecams][info] User ID:  17413354
[cli][info] Available streams: 240p (worst), 600p (best)
[cli][info] Opening stream: 600p (hls)
[cli][info] Starting player: C:\P\VLC\vlc.exe
````
It looks to me that Streamlink is checking fc2.py plugin even if I don't want to use it, 
just because it happens to be in plugins directory.

If so, does my CPU has to "think" about 196 more plugins just to see if they are politically correct or not?

Does it also mean that you access SSD once for each plugin ( 196 times ) just for the sake of 
checking each plugin, or you use some Pascal-like Blockread procedure for that?

I would be happy to remove plugins from my Streamlink package that I don't use 
if that would reduce any CPU's work and result in fewer readings from SSD,
and I am asking people who write Streamlink who know best.

And I repeat my other question, how to modify fc2.py to work with Streamlink ?

### Logs

```
REPLACE THIS TEXT WITH YOUR LOG
```

### Comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by Erk-** [comment] 2018-07-01 23:19
Could you try and remove the fc2.py file?

**Comment by johnthecracker** [comment] 2018-07-01 23:36
I have a reason to keep it because I want to use it.

Now you give me one good reson why should I remove it.

**Comment by beardypig** [comment] 2018-07-01 23:40
You replace `livecli` with `streamlink`, which should mostly work. I believe @back-to has abandoned that project in favour of `streamlink` and a custom plugins repo - which probably contains compatible versions of the plugins you want. 

Yes, it checks all the plugins - that’s the only way it knows if the url you give it is supported and by which plugin. Not sure what you mean by politically correct, they just have to be correct ;) You can also remove plugins that you do not want. However, the effect will be pretty negligible (unless you are running on some embedded system, which it doesn’t look like). Any file reads for loading plugins is handled by the python implementation that you are using and is not something that is directly part of streamlink.

**Comment by bastimeyer** [comment] 2018-07-01 23:47
> How to modify plugin from another github fork to adapt it to work with streamlink?

Depends on the changes of the fork. You have to ask the maintainer(s) of the fork or fix it yourself. In cases when a project gets forked and something gets changed, it is not up the maintainers of the upstream project (Streamlink in this case) to fix or support any of the changes being made by the fork. Since Streamlink is being licenced under the 'BSD 2-Clause "Simplified" License', you can see and follow all of the changes in the git log.

> Is Streamlink checking each and every plugin for being politically correct after starting itself and only after that running plugin that I actually want to use ?
> If so, does my CPU has to "think" about 196 more plugins just to see if they are politically correct or not?

Yes, the `ethics` module gets loaded first and then it checks each plugin for being politically correct.
On a more serious note, since you actually mean whether each plugin file has to be free of any errors when it gets loaded, yes, this is the case:
https://github.com/streamlink/streamlink/blob/0.14.2/src/streamlink/session.py#L447-L486
As you can see, there is no try/catch block and this is intended behavior.

> Does it also mean that you access SSD once for each plugin ( 196 times ) just for the sake of
checking each plugin

The input URL has to be tested against all supported plugins until one matches. The impact shouldn't be that big though, since each plugin is usually pre-compiled (which means there's no additional parse/compile step) and depending on Python's optimizations of [`pkgutil.iter_modules`](https://docs.python.org/3/library/pkgutil.html#pkgutil.iter_modules) and your OS's file system, there won't be X individual read accesses on the HDD / SSD / etc.

This whole process could be improved though by loading each plugin separately and immediately testing it until one matches. The [`--plugin-dir`](https://streamlink.github.io/cli.html#cmdoption-plugin-dirs) parameter could also be changed to override the default plugins dir constant instead of adding a new dir, but that would be a breaking change:
https://github.com/streamlink/streamlink/blob/0.14.2/src/streamlink_cli/main.py#L732-L736

**Comment by johnthecracker** [comment] 2018-07-01 23:50
Thank you @beardypig and @bastimeyer.

**Comment by gravyboat** [comment] 2018-07-01 23:56
Closing since this seems to have been answered.

**Closed by gravyboat** 2018-07-01 23:56 UTC
Labels: question

**Comment by johnthecracker** [comment] 2018-07-02 01:19
Thanks @beardypig and @back-to if you are reading this,
here I can study where I was wrong with fc2.py modification:

https://github.com/back-to/plugins/blob/master/plugins/fc2.py

**Comment by johnthecracker** [comment] 2018-07-02 08:29
@beardypig,

answer to your quote:

Not sure what you mean by politically correct

I mean doing something for nothing, in simple words open only plugin that I want to use.
There are 190 other plugins sitting there which I will never use. 
Why OPEN each of them for reading every single time I start the program. 

If File.Exists Method (String) then... 

without OPENING other 196 plugins. Streamlink OPENS fc2.py and looks for something there
even if I am not using it.

**Comment by panhartstuff** [comment] 2018-10-10 08:09
@johnthecracker 
Can you upload your fc2.py plugin, please? Would really appreciate it

**Comment by johnthecracker** [comment] 2018-10-10 15:32
https://ufile.io/1on6d

**Comment by panhartstuff** [comment] 2018-10-11 05:10
Thank you

**Comment by walker9** [comment] 2018-11-30 13:43
> https://ufile.io/1on6d

@johnthecracker

Could you please reupload the plugin? On ufile is a premium account required, it tells the free hosting period for the file is expired.
