### ISSUE TITLE
plugins.pandalive: api doesn't work.

### ISSUE THREAD

**Issue by KOONWHITE** [streamlink/streamlink#5577] opened 2023-09-30 06:47 UTC
### Checklist

- [X] This is a [plugin issue](https://streamlink.github.io/plugins.html) and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

streamlink 6.2.0

### Description

Only the same message is output even though a valid live is entered. 
Only the panda plugin does not work. 
Please check it out.

### Debug log

```text
streamlink "https://www.pandalive.co.kr/live/play/ddalon9911" best -o "1.ts"
[cli][info] Found matching plugin pandalive for URL https://www.pandalive.co.kr/live/play/ddalon9911
error: Unable to open URL: https://api.pandalive.co.kr/v1/live/play (400 Client Error: Bad Request for url: https://api.pandalive.co.kr/v1/live/play)
```

**Comment by bastimeyer** [comment] 2023-09-30 09:44
> * [x]  [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22+sort%3Aupdated-desc)
> * [x]  [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

Duplicate of #5568

Install the latest development version from the master branch or wait until the next stable release.
https://streamlink.github.io/install.html

**Closed by bastimeyer** 2023-09-30 09:44 UTC
Labels: duplicate, plugin issue, does not meet requirements
