### ISSUE TITLE
tango.me

### ISSUE THREAD

**Issue by White-Range** [streamlink/streamlink#3874] opened 2021-07-17 08:01 UTC
### Checklist

- [x] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

Tango Live is a live broadcast application similar to Bigo and Scope, it has two parts as free streams and premium broadcasts. many people show their talent in singing, dancing, playing instument and more. I hope you will add the plugin , please do it.
                                                           THANK YOU

### Input URLs

1. https://www.tango.me/
2. https://www.tango.me/stream/mUdNpBeqmB7agUelEI_sdg

**Comment by gravyboat** [comment] 2021-07-17 19:21
Duplicate of https://github.com/streamlink/streamlink/issues/3493, we've already said we're not adding this site [several times](https://github.com/streamlink/streamlink/issues?q=tango). Closing.

**Closed by gravyboat** 2021-07-17 19:21 UTC
Labels: duplicate, plugin request, wontfix
