### ISSUE TITLE
DASHStream: MPD Parsing Error Could not find required attribute MPD@publishTime

### ISSUE THREAD

**Issue by JunioCalu** [streamlink/streamlink#5877] opened 2024-03-04 12:16 UTC
### Checklist

- [X] This is a bug report and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

[cli][info] Your Streamlink version (6.6.2+2.gef25765c) is up to date!

### Description

I'm trying to parse a DASH manifest file using "DASHStream.parse_manifest" but I'm receiving the error detailed below. How can I resolve this? I have attached the script used for the analysis test and the obtained mpd manifest file.
  
  test script: [test_streamlink.py.txt](https://github.com/streamlink/streamlink/files/14481270/test_streamlink.py.txt)

  MPD file: [mpd_file.txt](https://github.com/streamlink/streamlink/files/14481266/mpd_file.txt)

    python test_streamlink.py
    Traceback (most recent call last):
      File "/home/junio/streamlink/venv-ffplayout/lib/python3.10/site-packages/streamlink/stream/dash/dash.py", line 286, in parse_manifest
        mpd = cls.parse_mpd(manifest, mpd_params)
      File "/home/junio/streamlink/venv-ffplayout/lib/python3.10/site-packages/streamlink/stream/dash/dash.py", line 260, in parse_mpd
        return MPD(node, **mpd_params)
      File "/home/junio/streamlink/venv-ffplayout/lib/python3.10/site-packages/streamlink/stream/dash/manifest.py", line 319, in __init__
        self.publishTime = self.attr(
      File "/home/junio/streamlink/venv-ffplayout/lib/python3.10/site-packages/streamlink/stream/dash/manifest.py", line 222, in attr
        raise MPDParsingError(f"Could not find required attribute {self.__tag__}@{key} ")
    streamlink.stream.dash.manifest.MPDParsingError: Could not find required attribute MPD@publishTime 
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/home/junio/streamlink/test_streamlink.py", line 14, in <module>
        streams = DASHStream.parse_manifest(session, manifest_url)
      File "/home/junio/streamlink/venv-ffplayout/lib/python3.10/site-packages/streamlink/stream/dash/dash.py", line 288, in parse_manifest
        raise PluginError(f"Failed to parse MPD manifest: {err}") from err
    streamlink.exceptions.PluginError: Failed to parse MPD manifest: Could not find required attribute MPD@publishTime 

### Debug log

```text
streamlink --no-config --version-check --loglevel=debug                                                                          ✔  3.10.6  
[cli][debug] OS:         Linux-6.5.13-7-MANJARO-x86_64-with-glibc2.39
[cli][debug] Python:     3.10.6
[cli][debug] OpenSSL:    OpenSSL 3.2.1 30 Jan 2024
[cli][debug] Streamlink: 6.6.2+2.gef25765c
[cli][debug] Dependencies:
[cli][debug]  certifi: 2024.2.2
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 5.1.0
[cli][debug]  pycountry: 23.12.11
[cli][debug]  pycryptodome: 3.20.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.31.0
[cli][debug]  trio: 0.24.0
[cli][debug]  trio-websocket: 0.11.1
[cli][debug]  typing-extensions: 4.9.0
[cli][debug]  urllib3: 2.2.1
[cli][debug]  websocket-client: 1.7.0
[cli][debug] Arguments:
[cli][debug]  --no-config=True
[cli][debug]  --loglevel=debug
[cli][debug]  --version-check=True
[cli][info] Your Streamlink version (6.6.2+2.gef25765c) is up to date!
```

**Comment by bastimeyer** [comment] 2024-03-04 15:19
> ```xml
> <MPD
>   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
>   xmlns="urn:mpeg:DASH:schema:MPD:2011"
>   xmlns:yt="http://youtube.com/yt/2012/10/10"
>   xsi:schemaLocation="urn:mpeg:DASH:schema:MPD:2011 DASH-MPD.xsd"
>   minBufferTime="PT1.500S"
>   profiles="urn:mpeg:dash:profile:isoff-main:2011"
>   type="dynamic"
>   availabilityStartTime="2024-03-04T01:36:00"
>   timeShiftBufferDepth="PT7200.000S"
>   minimumUpdatePeriod="PT1.000S"
>   yt:earliestMediaSequence="26829"
>   yt:mpdRequestTime="2024-03-04T11:03:09.988"
>   yt:mpdResponseTime="2024-03-04T11:03:10.021"
> >
> ```

> Could not find required attribute MPD@publishTime

The `MPD@publishTime` attribute is required for `MPD@type="dynamic"` manifests according to ISO/IEC
23009-1.

The manifest you've posted is from a YouTube stream, which is currently not supported.
Duplicate of #2936

**Closed by bastimeyer** 2024-03-04 15:19 UTC
Labels: bug
