### ISSUE TITLE
Error with live.bilibili.com

### ISSUE THREAD

**Issue by IsoaSFlus** [streamlink/streamlink#1331] opened 2017-11-16 13:39 UTC
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description
```
[cli][info] Found matching plugin bilibili for URL http://live.bilibili.com/513
Traceback (most recent call last):
  File "/bin/streamlink", line 11, in <module>
    load_entry_point('streamlink==0.8.1', 'console_scripts', 'streamlink')()
  File "/usr/lib/python3.6/site-packages/streamlink_cli/main.py", line 1047, in main
    handle_url()
  File "/usr/lib/python3.6/site-packages/streamlink_cli/main.py", line 486, in handle_url
    streams = fetch_streams(plugin)
  File "/usr/lib/python3.6/site-packages/streamlink_cli/main.py", line 398, in fetch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "/usr/lib/python3.6/site-packages/streamlink/plugin/plugin.py", line 385, in get_streams
    return self.streams(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/streamlink/plugin/plugin.py", line 294, in streams
    ostreams = list(ostreams)
  File "/usr/lib/python3.6/site-packages/streamlink/plugins/bilibili.py", line 42, in _get_streams
    room_id = _room_re.search(html_page).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

### Expected / Actual behavior

...

### Reproduction steps / Explicit stream URLs to test

1. ...
2. ...
3. ...

### Environment details

Operating system and version: Archlinux
Streamlink and Python version: streamlink 0.8.1 and Python 3.6.3

...

### Comments, logs, screenshots, etc.

...

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by Zamiell** [comment] 2017-11-19 14:57
This seems to happen with any Billibilli link:

I get the same thing when doing a `streamlink https://live.bilibili.com/4644721` on Windows 7 Professional and Python 2.7.12.

**Comment by IsoaSFlus** [comment] 2017-11-19 15:00
@Zamiell Bilibili has updated their website, so the old plugin has expired…Could you inform this plugin's author that need some tweaks?

**Comment by Zamiell** [comment] 2017-11-19 16:05
https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/bilibili.py

@cdrage @beardypig

**Comment by IsoaSFlus** [comment] 2017-11-20 00:29
@Zamiell I think neither of them are the creator of this plugin…

**Comment by gravyboat** [comment] 2017-11-20 07:29
The original maintainer hasn't made a commit since 2015 when this plugin was still part of Livestreamer. Please don't tag on these sorts of plugin issues as it isn't needed and we won't prioritize specific plugins. If someone is interested in fixing it they will comment on the issue.

**Comment by fozzysec** [comment] 2017-11-29 02:22
I worked on a bilibili plugin fix last month, but the code still had some problem caused by the oversea CDN, I am still working on solving this problem.

**Comment by fozzysec** [comment] 2017-11-29 03:38
Have a try on this https://gist.github.com/fozzysec/52a4d3cd90e0f844e71490ce577901ee
It doesn't works on my machine but works on my remote server, it should be a CDN caused problem. The code should works fine in most cases.

**Comment by IsoaSFlus** [comment] 2017-11-29 03:39
@fozzysec  Thank you for your codes, I'll have a try.

**Comment by IsoaSFlus** [comment] 2017-11-29 03:48
@fozzysec It does work on my machine, I'm in the Mainland of China.

**Comment by fozzysec** [comment] 2017-11-29 03:51
@IsoaSFlus Thanks for the feedback, I will open a PR later.

**Comment by gravyboat** [comment] 2017-12-04 06:19
#1345 is now merged, closing.

**Closed by gravyboat** 2017-12-04 06:19 UTC
Labels: plugin issue
