### ISSUE TITLE
Playing same stream with multiple Clients

### ISSUE THREAD

**Issue by armaghanshahzad** [streamlink/streamlink#1306] opened 2017-11-03 11:53 UTC
Hi,

I have gone through documentation a lot of times and can not find any solution  to play more than one player on the same stream. Is it possible to play more than player with the same stream? or the STREAMLINK is not capable of that. I am running on Ubuntu server 14.

Please help.

Regards
Armaghan

**Comment by beardypig** [comment] 2017-11-03 12:02
Do you mean to play the same stream in VLC and in MPV or what? Can you give some more details about what you have tried?

**Comment by armaghanshahzad** [comment] 2017-11-03 12:11
I have installed Streamlink server on ubuntu and configure to play a youtube stream. When I pleay the stream from laptop it plays and while I am playing if I try to open from desktop pc balck screen. If I stop from laptop then stream starts playing on Desktop PC. It seems 1:1 but I need to play it 1:n.

**Comment by beardypig** [comment] 2017-11-03 12:14
Which options are you using, it will be easier to help you if we know the streamlink command you are running. I think I understand, and what you are trying to do is not possible with streamlink only - you can use `VLC` to restream over RTSP (or similar) though.

**Comment by armaghanshahzad** [comment] 2017-11-03 12:17
Here is :
streamlink  --player-external-http --player-external-http-port 1237  https://www.youtube.com/watch?v=XXXXXXX best

**Comment by beardypig** [comment] 2017-11-03 12:44
OK. That only supports one client. You might be able to do it with VLC... https://wiki.videolan.org/Documentation:Streaming_HowTo/Command_Line_Examples/

**Comment by bastimeyer** [comment] 2017-11-03 14:02
Duplicate of #180

**Closed by bastimeyer** 2017-11-03 14:02 UTC

**Comment by beardypig** [comment] 2017-11-03 14:46
@bastimeyer ah, I couldn't find that before :)
