### ISSUE TITLE
mfc doesnt work using hlsvariant

### ISSUE THREAD

**Issue by shadowht** [streamlink/streamlink#387] opened 2017-01-09 02:44 UTC
i can use "hlsvariant://link.m3u8" just fine on livestreamer
but on streamlink i get "error: Unable to open URL: link.m3u8 (No connection adapters were found 'link.m3u8')

**Comment by beardypig** [comment] 2017-01-09 07:59
Which version of streamlink are you using? How did you install it? The full URL might help debug, from the error it sounds like the URL is invalid.

**Comment by shadowht** [comment] 2017-01-09 17:13
I am using the last streamlink version 0.2
Since there isnt any plugin, this is the method i use to get the links https://github.com/chrippa/livestreamer/issues/561#issuecomment-73791874
And again, the links are working just fine on livestreamer.
![feelsbad](http://i.imgur.com/PBT6PqR.png)

**Comment by beardypig** [comment] 2017-01-09 17:46
Can you try `hlsvariant://http://...playlist.m3u8`? That is a strange error to see.

**Comment by beardypig** [comment] 2017-01-09 17:55
Looks like a regression in 707df4f27bf144f4e33dc76ffafbcf2fac2519b8 I'll fix that right up :)

**Comment by gravyboat** [comment] 2017-01-09 18:42
https://github.com/streamlink/streamlink/pull/393 is merged so I'm going to close this.

**Closed by gravyboat** 2017-01-09 18:42 UTC
Labels: question
