### ISSUE TITLE
plugins.openrectv: There is no video file.

### ISSUE THREAD

**Issue by yuusakuri** [streamlink/streamlink#4133] opened 2021-10-31 11:37 UTC
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

Unable to download livestream archives. I can watch it in my browser.

I ran the following code in Windows PowerShell.

```powershell
streamlink.exe --openrectv-email EMAIL --openrectv-password PASSWORD --loglevel debug https://www.openrec.tv/live/e5rkn5dg6rv
```

### Debug log

```text
[cli][info] Loaded config from deprecated path, see CLI docs for how to migrate: C:\Users\kurisan\AppData\Roaming\streamlink\streamlinkrc
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.9.6
[cli][debug] Streamlink: 2.4.0
[cli][debug] Requests(2.26.0), Socks(1.7.1), Websocket(1.2.1)
[cli][debug] Arguments:
[cli][debug]  url=https://www.openrec.tv/live/e5rkn5dg6rv
[cli][debug]  --loglevel=debug
[cli][debug]  --rtmp-rtmpdump=rtmpdump.exe
[cli][debug]  --ffmpeg-ffmpeg=ffmpeg.exe
[cli][debug]  --openrectv-email=MAILADDRESS
[cli][debug]  --openrectv-password=********
[cli][info] Found matching plugin openrectv for URL https://www.openrec.tv/live/e5rkn5dg6rv
[plugins.openrectv][debug] Logged in as NAME
[plugins.openrectv][debug] Got valid detail response
[plugins.openrectv][debug] Found video: VIDEO_NAME (e5rkn5dg6rv)
[plugins.openrectv][error] There is no video file.
error: No playable streams found on this URL: https://www.openrec.tv/live/e5rkn5dg6rv
```

**Comment by bastimeyer** [comment] 2021-10-31 12:05
Duplicate of #4122 

> [cli][debug] Streamlink: 2.4.0

Use the latest version from the master branch, which includes #4130

**Closed by bastimeyer** 2021-10-31 12:05 UTC
Labels: plugin issue
