### ISSUE TITLE
0.9.0 release

### ISSUE THREAD

**Issue by cdrage** [streamlink/streamlink#1291] opened 2017-10-26 19:53 UTC
Any blockers @bastimeyer @gravyboat ?

**Comment by gravyboat** [comment] 2017-10-29 18:27
@cdrage I think we're good unless @bastimeyer or @beardypig have any concerns. We still aren't ready for a 1.0 but there have been a good amount of fixes we need to get in.

**Comment by gravyboat** [comment] 2017-10-29 23:36
You know I did think of one thing, @beardypig what do you think about adding socks as a dependency by default? We are still getting open issues about this.

**Comment by beardypig** [comment] 2017-10-31 10:28
@gravyboat yeah, lets just add `pysocks` as a dependency, it's shouldn't cause any issue with `requests`.

**Comment by amurzeau** [comment] 2017-10-31 22:25
This is what requests does + an extra dependency when on windows, if I understand extra features correctly:
https://github.com/requests/requests/blob/c14bd018adc715db2810c844258b392870fbc6fe/setup.py#L98
```python
extras_require={
    'security': ['pyOpenSSL>=0.14', 'cryptography>=1.3.4', 'idna>=2.0.0'],
    'socks': ['PySocks>=1.5.6, !=1.5.7'],
    'socks:sys_platform == "win32" and (python_version == "2.7" or python_version == "2.6")': ['win_inet_pton'],
}
```

**Comment by gravyboat** [comment] 2017-11-07 23:25
With https://github.com/streamlink/streamlink/pull/1315 and #1317 merged we should be good on this, let's get the latest nightly built so people can confirm that #1315 is working as intended then we can do a release.

**Comment by gravyboat** [comment] 2017-11-08 22:53
I think we're good to go on this release if you want to make it happen @cdrage.

**Comment by cdrage** [comment] 2017-11-09 16:39
@gravyboat Sure! I'll do it sometime today / tomorrow. Write some release notes :+1:

**Comment by gravyboat** [comment] 2017-11-20 07:39
Release is out, closing.

**Closed by gravyboat** 2017-11-20 07:39 UTC
Labels: meta
