### ISSUE TITLE
macos portable binary version

### ISSUE THREAD

**Issue by marcus13345** [streamlink/streamlink#2748] opened 2019-12-18 04:03 UTC
## Feature Request

- [x] This is a feature request and I have read the contribution guidelines.

### Description

I think that having a macos portable version would be nice, to sit alongside the windows version. Im personally using the windows portable version in a project, and the lack of macos portable is preventing cross platform capabilities

### Expected / Actual behavior

Have a macos portable version in the documentation, linking out to a native binary. i expected to find one, and did not.

**Comment by beardypig** [comment] 2019-12-18 14:11
What do you mean portable for macOS in this case? Do you want a Streamlink.app file that you can use without having to install python/pip or use brew?
It might be possible to use `py2app` to make something like that, I'm not sure how well, or if, it would work with Streamlink. `py2app` doesn't look like it's been updated recently either...

**Comment by marcus13345** [comment] 2019-12-18 19:40
@beardypig sortof. Let me be a bit more specific, I definitely would like a situation where the application doesn't need to be installed via anything, but rather as a standalone thing. However, a .app file is a click more than what I'm asking. All I'm looking for is a binary (similar to how a Linux binary looks). I believe a .app could accomplish that, however it's a bit non standard and probably overkill. I'm given to understand .app files are made for gui applications typically, and cli applications are extensionless native files, as opposed to effectively folders (.apps).

**Comment by bastimeyer** [comment] 2019-12-18 23:53
What about this?
https://pyinstaller.readthedocs.io/en/stable/operating-mode.html#bundling-to-one-file

**Comment by marcus13345** [comment] 2019-12-19 04:21
@bastimeyer that looks like it would work, however, im having some trouble getting the thing to run.

I have the repository downloaded, and im running it with `python -m streamlink_cli.main`. However, that yields no output (like the command usage information)

As well, despite having the dependencies downloaded, when i compile with `pyinstaller src/streamlink_cli/main.py` and try to run the output file `dist/main/main`, i get the output

```
Traceback (most recent call last):
  File "streamlink_cli/main.py", line 9, in <module>
ImportError: No module named requests
[35427] Failed to execute script main
```

**Comment by back-to** [comment] 2019-12-21 10:50
> pyinstaller

well it is a duplicate of https://github.com/streamlink/streamlink/issues/669

**Closed by back-to** 2019-12-21 10:50 UTC

**Comment by marcus13345** [comment] 2019-12-21 20:38
sortof, should I include talk of macos binaries with linux? Im not massively familiar with python, so i dont know if thats reasonable.

**Comment by bastimeyer** [comment] 2023-08-07 17:16
Nobody has come forward so far and proposed a proper solution for packaging Streamlink as a monolithic binary on macOS.

I have dedicated my time to package Streamlink as an AppImage on Linux, including a docker container for building the AppImages, and I've also rewritten the Windows installers and portable builds, with custom Python and FFmpeg builds.

I don't own Apple hardward (and never will), so my personal motivation is basically 0. I don't expect anyone from the other maintainers to spend any time on this either. Apart from that, using homebrew is ridiculously simple, and the package gets updated immediately after a release gets published here, so there really is no reason not to use it.

If you want to see additional macOS binaries, maybe as official Streamlink builds, then you'll either have to help out with this or find someone else who's motivated to submit a repo with a proper build setup that can produce stable and deterministic Streamlink builds for macOS, x86_64 and arm64. The main point however is long-term maintenance.
