### ISSUE TITLE
WP.Pilot (https://pilot.wp.pl/tv)

### ISSUE THREAD

**Issue by remek30** [streamlink/streamlink#1572] opened 2018-03-24 22:24 UTC
May I ask that streamlink also supports this page plugin: https://pilot.wp.pl/tv. After logging in, you will have access to the numerous channels that you can add to the channel list thanks to the stream link. So I ask politely, so streamlink synonymous https://pilot.wp.pl/tv supported.

**Comment by gravyboat** [comment] 2018-03-24 23:25
@remek30 Could you please edit your comment and use English if possible (if not Google Translate will suffice)? We're trying to keep everything associated with the project in English when we can.

**Comment by stachu540** [comment] 2018-03-25 00:08
He asked for supporting WP Pilot, which is a TV platform, and hard to saying.... I don't know where is API for this platform. The guy who asking for supporting this platform, he's asking for impossible reproduce this plugin. 

It is hard to reproduce because there is not a public API.

**Comment by remek30** [comment] 2018-03-25 15:04
There is no public API is a fact, you can rely on examples of implementation in this case. IPTV Player is one.
https://gitlab.com/iptvplayer-for-e2...stwebstream.py

Or something from Kodi plugins
https://github.com/mrknow/filmkodi/b...s/videostar.py

These are examples in python so linking to them will allow you to present the API and restore functions.

**Comment by back-to** [comment] 2018-04-08 16:51
your example python links got broken when you copy and paste it

---

**Notice**
 
a polish verification account is required, _might work directly if you are in poland._

```
Oglądaj po darmowej weryfikacji

Aby oglądać w Unii Europejskiej, załóż konto i pozwól zweryfikować, że mieszkasz w Polsce
```
```
Watch after free verification

To watch in the European Union, let me verify that you live in Poland
```

**Comment by regrepl** [comment] 2018-05-23 21:10
Correct links
https://gitlab.com/iptvplayer-for-e2/iptvplayer-for-e2/blob/master/IPTVPlayer/hosts/hostwebstream.py
https://github.com/mrknow/filmkodi/blob/master/plugin.video.mrknowtv/resources/lib/sources/videostar.py

**Comment by back-to** [comment] 2019-03-24 11:15
Adding new plugins where it is **difficult to get an account**,
will make the new plugin impossible to maintain.

so adding it, is useless.

closing

**Closed by back-to** 2019-03-24 11:15 UTC
Labels: account-needed, plugin request, wontfix

**Comment by JoJk0** [comment] 2020-04-13 19:45
In order to verify an account on WP Pilot you can use any random Polish credit card generator so you don't need to actually have Polish credit card. It would be very useful for many Polish people around the world as only Android TVs have native app.
