### ISSUE TITLE
bilibili live json parse error

### ISSUE THREAD

**Issue by z5n0w** [streamlink/streamlink#2141] opened 2018-10-27 09:42 UTC
## Bug Report

- [ ] This is a bug report and I have read the contribution guidelines.

### Reproduction steps / Explicit stream URLs to test

1. ...
2. ...
3. ...

### Log output

```
REPLACE THIS TEXT WITH THE LOG OUTPUT
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

![2018-10-27 5 41 09](https://user-images.githubusercontent.com/10935328/47602301-9725c680-da0f-11e8-8c87-ffc107997c09.png)

**Comment by bastimeyer** [comment] 2018-10-27 10:09
This looks like a duplicate of the issue which was reported 5 days ago in #2126 and which got fixed 4 days ago by #2129.

You didn't provide a proper debug log (the issue template explicitly asks you to do this - as text and not as a screenshot), so I don't know whether you're using the latest Streamlink version or not. Make sure to use the latest version before reporting any issues.

**Closed by bastimeyer** 2018-10-27 10:09 UTC
