### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by mikhoul** [streamlink/streamlink#526] opened 2017-02-03 15:26 UTC
----

### Checklist

- [x] This is a bug report.

### Description

When trying to record a stream Streamlink crash about 1 on 4
...

### Expected / Actual behavior

Recording the stream every time without crashing/stopping
...

### Reproduction steps / Stream URLs to test

Just try to record the stream multiple time with the same setting I use and it will happen 

### Environment details (operating system, python version, etc.)
I'm under Win7/64 and use latest release version of Streamlink

Here's the output of CMD console with the errors:
```
C:\Users\user\Desktop\FFMpegTest>F:\Streamlink\bin\streamlink.exe "hls://http://tva_chaine_uls-lh.akamaihd.net/i/chaine_tva_1@125892/index_700_av-p.m3u8" best -f -o H:\Telechargement\TVA.ts
[cli][info] Found matching plugin stream for URL hls://http://tva_chaine_uls-lh.akamaihd.net/i/chaine_tva_1@125892/index_700_av-p.m3u8
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (hls)
[download][TVA.ts] Written 240.0 KB (3s @ 78.4 KB/s)                                                                                                                                       Exception in thread Thread-1:
Traceback (most recent call last):
  File "F:\Streamlink\pkgs\requests\packages\urllib3\response.py", line 298, in _error_catcher
    yield
  File "F:\Streamlink\pkgs\requests\packages\urllib3\response.py", line 380, in read
    data = self._fp.read(amt)
  File "http\client.py", line 448, in read
  File "http\client.py", line 488, in readinto
  File "socket.py", line 575, in readinto
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Streamlink\pkgs\requests\models.py", line 719, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "F:\Streamlink\pkgs\requests\packages\urllib3\response.py", line 432, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "F:\Streamlink\pkgs\requests\packages\urllib3\response.py", line 397, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "contextlib.py", line 77, in __exit__
  File "F:\Streamlink\pkgs\requests\packages\urllib3\response.py", line 303, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='tva_chaine_uls-lh.akamaihd.net', port=80): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 914, in _bootstrap_inner
  File "F:\Streamlink\pkgs\streamlink\stream\segmented.py", line 160, in run
    self.write(segment, result)
  File "F:\Streamlink\pkgs\streamlink\stream\hls.py", line 116, in write
    for chunk in res.iter_content(chunk_size):
  File "F:\Streamlink\pkgs\requests\models.py", line 726, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='tva_chaine_uls-lh.akamaihd.net', port=80): Read timed out.

[cli][error] Error when reading from stream: Read timeout
[cli][info] Stream ended
[cli][info] Closing currently open stream...

```

I'm new with Stremlink and recording streams, so it can be also something wrong I've done but I doubt it since the error throw seem to be an "exception" in the python code and sadly I know nothing about python.

Regards :octocat:

**Comment by beardypig** [comment] 2017-02-03 16:27
Thanks for your bug report, I believe that this is a duplicate of an already reported issue: #446.

**Comment by gravyboat** [comment] 2017-02-03 17:30
Going to close this since I merged in #522, can you give the nightly a shot?

**Closed by gravyboat** 2017-02-03 17:30 UTC

**Comment by mikhoul** [comment] 2017-02-03 18:03
@gravyboat @beardypig   Everything id fine with the nightly  👍 

_Some observations since I'm a new user:_ When I installed the nightly the installer did not see automatically my old custom location i.e. `F:\streamlink\...` it would be cool if the installer was able to see the location of the previous installation on an upgrade.

I will use it mainly to record live TV-show stream in replacement of FFMPEG which i lot less reliable and I write batch file to use with the "Windows Scheduler" so I'd like to have the possibility to put a "switch" in the command line to specify the time I want the command to run, something like  `-t=hh.mm.ss` would be very useful to have instead of creating another "sheduled task" to kill the process to stop the recording.

One last question: I'd like to know if there is a way to automatically update "stremlink" for the release version ?


Best Regards ! :octocat:

**Comment by RedPenguin2** [comment] 2017-03-16 07:35
I would not mind a feature like mentioned above.

I record a few different things with streamlink and while Vista 32bit's Task Scheduler easily kills the entire bat file running streamlink easily, Win 10 64-bit just leaves the prompt open until I can tend to it.

It looks from various Google results there is a known issue with 64-bit Windows Task Schedulers not able to successfully kill 32bit processes.

When trying "taskkill /F /IM "streamlink,exe"" because I have loop in just in case it's disconnected while recording, this simply kills streamlink and then the loop reactivate it, still leaving the command prompt open.

This isn't a problem usually but if I am not home, it can take what should be a 30min-2hour recording and record a 6+ hour block.

**Comment by gravyboat** [comment] 2017-03-16 07:49
@mikhoul Looks like I missed this message originally you had from the 3rd, sorry about that. For the stable I just double checked and right now we don't support the update path getting noticed. I don't think anyone has looked into such a feature since it's not checking against the system settings (would be kind of sketchy if an installer just started reading things itself). Regarding the time setting (and I think this applies for you as well @RedPenguin2) it's not something we've talked about and we usually just recommend people set a time kill using something similar to this for batch scripts, or write a custom script that automatically does the kill after X amount of time: http://stackoverflow.com/questions/13515254/how-to-set-a-timeout-for-a-process-under-windows-7.  I think that would solve the problem because it gets around the task scheduler entirely right? Otherwise we might need to see if we can build Streamlink as a 64 bit windows executable.

For your final question @mikhoul there's no auto-update feature for Streamlink since it's just a command line app. I would be against such a feature as well since I don't like applications updating without my knowledge. Instead we just notify users when a new version is available if they have the flag set to check for a new version.

**Comment by mikhoul** [comment] 2017-03-16 14:38
Thanks !   :+1:
