### ISSUE TITLE
vaughnlive... not working.

### ISSUE THREAD

**Issue by 100Max** [streamlink/streamlink#2552] opened 2019-07-16 05:59 UTC
## Plugin Issue

- [ ] This is a plugin issue and I have read the contribution guidelines.

### Reproduction steps / Explicit stream URLs to test

1. ...
2. ...
3. ...

### Log output

```
REPLACE THIS TEXT WITH THE LOG OUTPUT
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

 * Server changed.. and is using google recaptcha for response codes.

  otherwise.. load the url into your browser and be gone with bull plop. LOL!

**Comment by gravyboat** [comment] 2019-07-16 06:22
Duplicate of https://github.com/streamlink/streamlink/issues/2178 and lacking all information. Closing and locking. Don't create issues if you're not going to follow the template.

**Closed by gravyboat** 2019-07-16 06:22 UTC
