### ISSUE TITLE
stream.dash: nested BaseURL resolving

### ISSUE THREAD

**Issue by vstavrinov** [streamlink/streamlink#4586] opened 2022-06-11 18:35 UTC
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest build from the master branch

### Description

This specific URL works with mpv, totem and ffplay, but doesn't with vlc and streamlink:

``https://rfe-ingest.akamaized.net/dash/live/2033030/tvmc05/manifest.mpd``

### Debug log

```text
[cli][debug] OS:         Linux-5.10.0-15-amd64-x86_64-with-glibc2.31
[cli][debug] Python:     3.9.2
[cli][debug] Streamlink: 4.1.0+12.g0dd52932
[cli][debug] Dependencies:
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.8.0
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.14.1
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.27.1
[cli][debug]  websocket-client: 1.3.2
[cli][debug] Arguments:
[cli][debug]  url=https://rfe-ingest.akamaized.net/dash/live/2033030/tvmc05/manifest.mpd
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --player=totem
[cli][info] Found matching plugin dash for URL https://rfe-ingest.akamaized.net/dash/live/2033030/tvmc05/manifest.mpd
[plugins.dash][debug] URL=https://rfe-ingest.akamaized.net/dash/live/2033030/tvmc05/manifest.mpd; params={}
[utils.l10n][debug] Language code: en_US
[stream.dash][debug] Available languages for DASH audio streams: eng (using: eng)
[cli][info] Available streams: 240p (worst), 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (dash)
[cli][info] Starting player: totem
[stream.dash][debug] Opening DASH reader for: video_3311kbps (video/mp4)
[stream.dash][debug] Opening DASH reader for: audio_1 (audio/mp4)
[stream.dash_manifest][debug] Generating segment numbers for dynamic playlist (id=0)
[cli][error] Try 1/1: Could not open stream <DASHStream ['dash', 'https://rfe-ingest.akamaized.net/dash/live/2033030/tvmc05/manifest.mpd']> (Could not open stream: cannot use FFMPEG)
[stream.ffmpegmux][debug] Closing ffmpeg thread
error: Could not open stream <DASHStream ['dash', 'https://rfe-ingest.akamaized.net/dash/live/2033030/tvmc05/manifest.mpd']>, tried 1 times, exiting
[stream.dash_manifest][debug] Generating segment numbers for dynamic playlist (id=1)
Exception in thread Thread-DASHStreamWorker:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/dist-packages/streamlink/stream/segmented.py", line 87, in run
    self.writer.put(segment)
  File "/usr/local/lib/python3.9/dist-packages/streamlink/stream/segmented.py", line 143, in put
    future = self.executor.submit(self.fetch, segment, retries=self.retries)
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 163, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown
[stream.dash][error] Failed to open segment https://rfe-ingest.akamaized.net/dash/live/2033030/tvmc05/init_video_3311kbps.m4s: Unable to open URL: https://rfe-ingest.akamaized.net/dash/live/2033030/tvmc05/init_video_3311kbps.m4s (404 Client Error: Not Found for url: https://rfe-ingest.akamaized.net/dash/live/2033030/tvmc05/init_video_3311kbps.m4s)
```

**Comment by bastimeyer** [comment] 2022-06-11 19:24
> `https://rfe-ingest.akamaized.net/dash/live/2033030/tvmc05/init_video_3311kbps.m4s`

Looks like the `Representation`'s `BaseURL` gets ignored. The URL of the initialization should be
`https://rfe-ingest.akamaized.net/dash/live/2033030/tvmc05/RFE-TVMC05_0240/12wxxnb2/init_video_238kbps.m4s`

```xml
...
<BaseURL>https://rfe-ingest.akamaized.net/dash/live/2033030/tvmc05/</BaseURL>
<Period id="0" start="PT0.0S">
    <AdaptationSet id="0" mimeType="video/mp4" maxWidth="1920" maxHeight="1080" par="16:9" frameRate="25" segmentAlignment="true" startWithSAP="1" subsegmentAlignment="true" subsegmentStartsWithSAP="1">
        <SegmentTemplate presentationTimeOffset="0" timescale="90000" duration="540000" startNumber="1" media="media_$RepresentationID$-$Number$.m4s" initialization="init_$RepresentationID$.m4s"/>
        <Representation id="video_238kbps" codecs="avc1.42c015" width="426" height="240" sar="1:1" bandwidth="238000">
            <BaseURL>RFE-TVMC05_0240/12wxxnb2/</BaseURL>
        </Representation>
...
```

**Comment by bastimeyer** [comment] 2023-02-23 12:13
The issue is caused by the DASH parser not resolving nested BaseURLs on the
1. document level
2. MPD level
3. Period level
4. AdaptationSet level
5. Representation level

This either needs to be fixed in `MPDNode.base_url` where it currently only takes the current level's `BaseURL`  into consideration
https://github.com/streamlink/streamlink/blob/07bd742ddff22dd95ef2c90a64bedfdb0a1bd082/src/streamlink/stream/dash_manifest.py#L177-L182
or better, in the `BaseURL(MPDNode)` class, where it only has to resolve it once from its parent/ancestor nodes
https://github.com/streamlink/streamlink/blob/07bd742ddff22dd95ef2c90a64bedfdb0a1bd082/src/streamlink/stream/dash_manifest.py#L270-L293

**Closed** 2023-02-24 00:21 UTC
Labels: bug, stream: DASH
