### ISSUE TITLE
1440p(60) YouTube live streams only show resolutions up to 1080p as available streams

### ISSUE THREAD

**Issue by dotgodly** [streamlink/streamlink#3158] opened 2020-09-09 01:34 UTC
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.

### Description

When a stream on YouTube is **live** and streaming at a resolution greater than 1080p (have only been able to test 1440p60), the available streams only show up to 1080p. This is only for **live in-progress** streams, VODs work as expected.

### Expected / Actual behavior

I expect 1440p to be a select-able stream when streamlink is given a link that is streaming at 1440p. Streamlink only gives me up to 1080p, and marks 1080p as best.

### Reproduction steps / Explicit stream URLs to test

At the time of issue creation, this stream is streaming at 1440p60. However, as this issue only relates to live in-progress streams, it will probably be too late when you come across this issue.
1. https://www.youtube.com/watch?v=xOyg88PWodA

I suggest visiting https://www.youtube.com/live to browse active streams and searching for one streaming at a resolution greater than 1080p. Gaming streams seem to have the greatest frequency of high resolution streams.

### Log output

```
 streamlink https://www.youtube.com/watch?v=xOyg88PWodA best -o "test_1440.ts" --loglevel debug
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.6
[cli][debug] Streamlink: 1.5.0
[cli][debug] Requests(2.24.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=xOyg88PWodA
[plugin.youtube][debug] Video ID from URL
[plugin.youtube][debug] Using video ID: xOyg88PWodA
[plugin.youtube][debug] get_video_info - 1: Found data
[plugin.youtube][debug] This video is live.
[utils.l10n][debug] Language code: en_US
[cli][info] Available streams: 144p (worst), 240p, 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 2824; Last Sequence: 2838
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 2836; End Sequence: None
[stream.hls][debug] Adding segment 2836 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 2837 to queue
[stream.hls][debug] Adding segment 2838 to queue
[stream.hls][debug] Download of segment 2836 complete
[cli][debug] Checking file output
[cli][debug] Writing stream to output
[stream.hls][debug] Download of segment 2837 complete
[stream.hls][debug] Download of segment 2838 complete
[download][test_1440.ts] Written 1.6 MB (0s @ 2.0 MB/s)                                                                [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 2839 to queue
[stream.hls][debug] Download of segment 2839 complete
[download][test_1440.ts] Written 2.6 MB (2s @ 1.3 MB/s)                                                                [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 2840 to queue
[stream.hls][debug] Download of segment 2840 complete
[download][test_1440.ts] Written 3.4 MB (4s @ 862.9 KB/s)                                                              [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 2841 to queue
[stream.hls][debug] Adding segment 2842 to queue
[stream.hls][debug] Download of segment 2841 complete
[download][test_1440.ts] Written 3.9 MB (6s @ 663.5 KB/s)                                                              [stream.hls][debug] Download of segment 2842 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 2843 to queue
[stream.hls][debug] Download of segment 2843 complete
[download][test_1440.ts] Written 5.3 MB (9s @ 586.4 KB/s)                                                              [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 2844 to queue
[stream.hls][debug] Download of segment 2844 complete
[download][test_1440.ts] Written 6.2 MB (11s @ 443.0 KB/s)                                                             [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 2845 to queue
[stream.hls][debug] Download of segment 2845 complete
[download][test_1440.ts] Written 7.2 MB (13s @ 424.3 KB/s)                                                             [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 2846 to queue
[stream.hls][debug] Download of segment 2846 complete
[download][test_1440.ts] Written 8.1 MB (15s @ 426.1 KB/s)                                                             [stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 2847 to queue
[stream.hls][debug] Download of segment 2847 complete
[download][test_1440.ts] Written 8.6 MB (18s @ 385.8 KB/s)                                                             [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 2848 to queue
[stream.hls][debug] Adding segment 2849 to queue
[stream.hls][debug] Download of segment 2848 complete
[download][test_1440.ts] Written 9.0 MB (20s @ 339.8 KB/s)                                                             [stream.hls][debug] Download of segment 2849 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 2850 to queue
[stream.hls][debug] Download of segment 2850 complete
[download][test_1440.ts] Written 9.3 MB (23s @ 262.8 KB/s)                                                             [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 2851 to queue
[stream.hls][debug] Download of segment 2851 complete
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[stream.segmented][debug] Closing writer thread
[cli][info] Stream ended
Interrupted! Exiting...
[cli][info] Closing currently open stream...
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment] 2020-09-09 05:34
It's likely because the 1440p stream is DASH which we don't currently support. I'm going to close this as it's basically a duplicate of https://github.com/streamlink/streamlink/issues/2936 since that's where we've been dumping all of these.

**Closed by gravyboat** 2020-09-09 05:34 UTC
