### ISSUE TITLE
Failed to install on Debian 9 using pip/pip3

### ISSUE THREAD

**Issue by Symbian9** [streamlink/streamlink#1824] opened 2018-06-19 03:54 UTC
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

Can't install `streamlink` on Debian 9.x using `pip`/`pip3`.

### Actual behavior

Install `streamlink` using `pip` or `pip3` failed.

### Reproduction steps / Explicit stream URLs to test

1. Open terminal;
2. Run `$ pip3 install streamlink`
3. Failed to continue with `error: invalid command 'bdist_wheel'`

### Logs

```
me@home:~
$ pip3 install streamlink
Collecting streamlink
  Using cached https://files.pythonhosted.org/packages/06/8d/735ad0e4b5bf3ccf9a39bbd54a4dc6df8b37d1a54a4ca8d803773a9b107d/streamlink-0.13.0.tar.gz
Collecting requests!=2.12.0,!=2.12.1,!=2.16.0,!=2.16.1,!=2.16.2,!=2.16.3,!=2.16.4,!=2.16.5,!=2.17.1,<3.0,>=2.2 (from streamlink)
  Using cached https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl
Collecting pycryptodome<4,>=3.4.3 (from streamlink)
  Using cached https://files.pythonhosted.org/packages/09/23/561648462715145a7a0d0939b56eca66625b96be5070ad93a195f7a0e0c7/pycryptodome-3.6.1-cp35-cp35m-manylinux1_x86_64.whl
Collecting iso-639 (from streamlink)
  Using cached https://files.pythonhosted.org/packages/5a/8d/27969852f4e664525c3d070e44b2b719bc195f4d18c311c52e57bb93614e/iso-639-0.4.5.tar.gz
Collecting iso3166 (from streamlink)
  Using cached https://files.pythonhosted.org/packages/00/b1/e691b0c487144870a240d2b4d96cc0a733d8ede2bbc26371971ad12aa894/iso3166-0.8-py2.py3-none-any.whl
Collecting isodate (from streamlink)
  Using cached https://files.pythonhosted.org/packages/9b/9f/b36f7774ff5ea8e428fdcfc4bb332c39ee5b9362ddd3d40d9516a55221b2/isodate-0.6.0-py2.py3-none-any.whl
Collecting websocket-client (from streamlink)
  Using cached https://files.pythonhosted.org/packages/8a/a1/72ef9aa26cfe1a75cee09fc1957e4723add9de098c15719416a1ee89386b/websocket_client-0.48.0-py2.py3-none-any.whl
Collecting PySocks!=1.5.7,>=1.5.6 (from streamlink)
  Using cached https://files.pythonhosted.org/packages/53/12/6bf1d764f128636cef7408e8156b7235b150ea31650d0260969215bb8e7d/PySocks-1.6.8.tar.gz
Collecting idna<2.8,>=2.5 (from requests!=2.12.0,!=2.12.1,!=2.16.0,!=2.16.1,!=2.16.2,!=2.16.3,!=2.16.4,!=2.16.5,!=2.17.1,<3.0,>=2.2->streamlink)
  Using cached https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl
Collecting urllib3<1.24,>=1.21.1 (from requests!=2.12.0,!=2.12.1,!=2.16.0,!=2.16.1,!=2.16.2,!=2.16.3,!=2.16.4,!=2.16.5,!=2.17.1,<3.0,>=2.2->streamlink)
  Using cached https://files.pythonhosted.org/packages/bd/c9/6fdd990019071a4a32a5e7cb78a1d92c53851ef4f56f62a3486e6a7d8ffb/urllib3-1.23-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests!=2.12.0,!=2.12.1,!=2.16.0,!=2.16.1,!=2.16.2,!=2.16.3,!=2.16.4,!=2.16.5,!=2.17.1,<3.0,>=2.2->streamlink)
  Using cached https://files.pythonhosted.org/packages/7c/e6/92ad559b7192d846975fc916b65f667c7b8c3a32bea7372340bfe9a15fa5/certifi-2018.4.16-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests!=2.12.0,!=2.12.1,!=2.16.0,!=2.16.1,!=2.16.2,!=2.16.3,!=2.16.4,!=2.16.5,!=2.17.1,<3.0,>=2.2->streamlink)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting six (from isodate->streamlink)
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Building wheels for collected packages: streamlink, iso-639, PySocks
  Running setup.py bdist_wheel for streamlink ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/var/tmp/pip-build-newrcahv/streamlink/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpjl06bofkpip-wheel- --python-tag cp35:
  /usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
    warnings.warn(msg)
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for streamlink
  Running setup.py clean for streamlink
  Running setup.py bdist_wheel for iso-639 ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/var/tmp/pip-build-newrcahv/iso-639/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmprijrb_0cpip-wheel- --python-tag cp35:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for iso-639
  Running setup.py clean for iso-639
  Running setup.py bdist_wheel for PySocks ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/var/tmp/pip-build-newrcahv/PySocks/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpvj8t5egvpip-wheel- --python-tag cp35:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for PySocks
  Running setup.py clean for PySocks
Failed to build streamlink iso-639 PySocks
Installing collected packages: idna, urllib3, certifi, chardet, requests, pycryptodome, iso-639, iso3166, six, isodate, websocket-client, PySocks, streamlink
  Running setup.py install for iso-639 ... done
  Running setup.py install for PySocks ... done
  Running setup.py install for streamlink ... done
Successfully installed PySocks-1.6.8 certifi-2018.4.16 chardet-3.0.4 idna-2.7 iso-639-0.4.5 iso3166-0.8 isodate-0.6.0 pycryptodome-3.6.1 requests-2.19.1 six-1.11.0 streamlink-0.13.0 urllib3-1.23 websocket-client-0.48.0
me@home:~
$
```

### Comments, screenshots, etc.

I try both variants: install using `pip` and `pip3` -- result was same.

OS / Platform: *MX Linux MX-17.1* ( aka *Debian 9.x Stretch*) / *x86_64*

**Comment by gravyboat** [comment] 2018-06-19 04:51
This is typically due to old versions of Python2.7. You need to install wheel via `pip install wheel`. You may also wish to upgrade your version of setuptools/pip  via `pip install --upgrade setuptools` and `pip install --upgrade pip`.

**Comment by Symbian9** [comment] 2018-06-19 05:13
> This is typically due to old versions of Python2.7 but Debian 9 is pretty new (or maybe Debian 9 isn't getting this package by default again since it's the current stable? I'm not sure). You need to install wheel via pip install wheel

As you can see in log: `$ pip3 install streamlink` , - it mean that I try install it using `pip3` aka Python3.

> You need to install wheel via `pip install wheel`

OK, I just `pip3 install wheel` and got next:

```
me@home:~
$ pip3 install wheel
Collecting wheel
  Downloading https://files.pythonhosted.org/packages/81/30/e935244ca6165187ae8be876b6316ae201b71485538ffac1d718843025a9/wheel-0.31.1-py2.py3-none-any.whl (41kB)
    100% |████████████████████████████████| 51kB 18kB/s 
Installing collected packages: wheel
Successfully installed wheel-0.31.1
me@home:~
$ pip3 install streamlink
Collecting streamlink
  Using cached https://files.pythonhosted.org/packages/06/8d/735ad0e4b5bf3ccf9a39bbd54a4dc6df8b37d1a54a4ca8d803773a9b107d/streamlink-0.13.0.tar.gz
Collecting requests!=2.12.0,!=2.12.1,!=2.16.0,!=2.16.1,!=2.16.2,!=2.16.3,!=2.16.4,!=2.16.5,!=2.17.1,<3.0,>=2.2 (from streamlink)
  Using cached https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl
Collecting pycryptodome<4,>=3.4.3 (from streamlink)
  Using cached https://files.pythonhosted.org/packages/09/23/561648462715145a7a0d0939b56eca66625b96be5070ad93a195f7a0e0c7/pycryptodome-3.6.1-cp35-cp35m-manylinux1_x86_64.whl
Collecting iso-639 (from streamlink)
  Using cached https://files.pythonhosted.org/packages/5a/8d/27969852f4e664525c3d070e44b2b719bc195f4d18c311c52e57bb93614e/iso-639-0.4.5.tar.gz
Collecting iso3166 (from streamlink)
  Using cached https://files.pythonhosted.org/packages/00/b1/e691b0c487144870a240d2b4d96cc0a733d8ede2bbc26371971ad12aa894/iso3166-0.8-py2.py3-none-any.whl
Collecting isodate (from streamlink)
  Using cached https://files.pythonhosted.org/packages/9b/9f/b36f7774ff5ea8e428fdcfc4bb332c39ee5b9362ddd3d40d9516a55221b2/isodate-0.6.0-py2.py3-none-any.whl
Collecting websocket-client (from streamlink)
  Using cached https://files.pythonhosted.org/packages/8a/a1/72ef9aa26cfe1a75cee09fc1957e4723add9de098c15719416a1ee89386b/websocket_client-0.48.0-py2.py3-none-any.whl
Collecting PySocks!=1.5.7,>=1.5.6 (from streamlink)
  Using cached https://files.pythonhosted.org/packages/53/12/6bf1d764f128636cef7408e8156b7235b150ea31650d0260969215bb8e7d/PySocks-1.6.8.tar.gz
Collecting certifi>=2017.4.17 (from requests!=2.12.0,!=2.12.1,!=2.16.0,!=2.16.1,!=2.16.2,!=2.16.3,!=2.16.4,!=2.16.5,!=2.17.1,<3.0,>=2.2->streamlink)
  Using cached https://files.pythonhosted.org/packages/7c/e6/92ad559b7192d846975fc916b65f667c7b8c3a32bea7372340bfe9a15fa5/certifi-2018.4.16-py2.py3-none-any.whl
Collecting idna<2.8,>=2.5 (from requests!=2.12.0,!=2.12.1,!=2.16.0,!=2.16.1,!=2.16.2,!=2.16.3,!=2.16.4,!=2.16.5,!=2.17.1,<3.0,>=2.2->streamlink)
  Using cached https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl
Collecting urllib3<1.24,>=1.21.1 (from requests!=2.12.0,!=2.12.1,!=2.16.0,!=2.16.1,!=2.16.2,!=2.16.3,!=2.16.4,!=2.16.5,!=2.17.1,<3.0,>=2.2->streamlink)
  Using cached https://files.pythonhosted.org/packages/bd/c9/6fdd990019071a4a32a5e7cb78a1d92c53851ef4f56f62a3486e6a7d8ffb/urllib3-1.23-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests!=2.12.0,!=2.12.1,!=2.16.0,!=2.16.1,!=2.16.2,!=2.16.3,!=2.16.4,!=2.16.5,!=2.17.1,<3.0,>=2.2->streamlink)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting six (from isodate->streamlink)
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Building wheels for collected packages: streamlink, iso-639, PySocks
  Running setup.py bdist_wheel for streamlink ... done
  Stored in directory: /home/me/.cache/pip/wheels/37/f7/d9/d1a900f43bc7e00c8d64f4ca285e029b6ff8a4ac34155a5b58
  Running setup.py bdist_wheel for iso-639 ... done
  Stored in directory: /home/me/.cache/pip/wheels/52/60/07/73aed7d23ae9b5729970632922ed5e45b535bcd4b8df77ebe9
  Running setup.py bdist_wheel for PySocks ... done
  Stored in directory: /home/me/.cache/pip/wheels/22/5c/b5/12e0dfdfa85bea67b23628b6425fae715c687e947a45ee3df9
Successfully built streamlink iso-639 PySocks
Installing collected packages: certifi, idna, urllib3, chardet, requests, pycryptodome, iso-639, iso3166, six, isodate, websocket-client, PySocks, streamlink
Successfully installed PySocks-1.6.8 certifi-2018.4.16 chardet-3.0.4 idna-2.7 iso-639-0.4.5 iso3166-0.8 isodate-0.6.0 pycryptodome-3.6.1 requests-2.19.1 six-1.11.0 streamlink-0.13.0 urllib3-1.23 websocket-client-0.48.0
me@home:~
```

**Comment by beardypig** [comment] 2018-06-19 10:22
```
/usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
```
This indicates an old version of `setuptools` - did you upgrade `setuptools` for Python 3 too?

**Comment by Symbian9** [comment] 2018-06-19 11:18
> did you upgrade setuptools for Python 3 too?
Yes, but I update all above, including `pip3`, BUT now `pip3` failed on start too:
```
$ pip3 install --upgrade setuptools
Traceback (most recent call last):
  File "/usr/bin/pip3", line 9, in <module>
    from pip import main
ImportError: cannot import name 'main
$ 
```

**Comment by beardypig** [comment] 2018-06-19 11:33
You could try a couple of things

- see if `python3 -m pip` works
- if not, do `hash -d pip` then try again
- and as a last resort `curl https://bootstrap.pypa.io/get-pip.py | python3`

**Comment by back-to** [comment] 2018-06-19 12:01
because you are not using `sudo` to update pip, you are having this pip issue with pip10

https://github.com/pypa/pip/issues/5221
https://github.com/pypa/pip/issues/5221

you can uninstall **your local** pip version with
`python3 -m pip uninstall pip`

and this will restore the system pip version

**if you want** an updated system pip use, **which is not required**

`sudo python3 -m pip install -U pip`

---

> Successfully installed PySocks-1.6.8 certifi-2018.4.16
chardet-3.0.4 idna-2.7 iso-639-0.4.5 iso3166-0.8 isodate-0.6.0
pycryptodome-3.6.1 requests-2.19.1 six-1.11.0
streamlink-0.13.0 urllib3-1.23 websocket-client-0.48.0

it's maybe already install just the bin file is not in your PATH

also run this commands

```
python3 -c "import streamlink;print(streamlink.__version__)"
python3 -c "import pip;print(pip.__version__)"
python3 -c "import setuptools;print(setuptools.__version__)"
python3 -m pip -V
```

you will probably run into **permission erros** at some point if you don't use `sudo` or `pip install --user`

> bash: streamlink: command not found

the bin might not be created or is not set into PATH,
you might need to update your $PATH in the **.bashrc** file

```
PATH="$HOME/.local/bin:$PATH"
```

`$HOME/.local/bin` you can check there it it was created

if not,
install streamlink with the `--user` flag it will create a bin file in `$HOME/.local/bin` ,

**Comment by Symbian9** [comment] 2018-06-19 12:57
> `python3 -m pip uninstall pip`

Done. Not solve issue yet.

>  ```
> python3 -c "import streamlink;print(streamlink.__version__)"
> python3 -c "import pip;print(pip.__version__)"
> python3 -c "import setuptools;print(setuptools.__version__)"
> python3 -m pip -V
> ```

Done. Here is output:

```
$ python3 -c "import streamlink;print(streamlink.__version__)"
0.13.0
$ python3 -c "import pip;print(pip.__version__)"
9.0.1
$ python3 -c "import setuptools;print(setuptools.__version__)"
39.2.0
$ python3 -m pip -V
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.5)
```

**Comment by back-to** [comment] 2018-06-19 13:18
streamlink is installed but there might be no bin file or the PATH is not set

```
/usr/bin/streamlink
/usr/local/bin/streamlink
$HOME/.local/bin/streamlink
/bin/streamlink
```

could you try if one of this bin file for streamlink is installed on your system

---

if yes, make sure the `$PATH` is set  _like I explained it above._

---

if not you can install streamlink again with the `--user` flag

`python3 -m pip install --user -U streamlink` _like I explained it above._

---

you can also use `pip3 show streamlink` to get the Location where it was installed.

**Comment by Symbian9** [comment] 2018-06-19 18:38
Found `streamlink` in `$HOME/.local/bin/streamlink`.

Then update it path as you said:
```
$ PATH="$HOME/.local/bin:$PATH"
```

Now I **got it**

```
$ streamlink
usage: streamlink [OPTIONS] <URL> [STREAM]

Use -h/--help to see the available options or read the manual at https://streamlink.github.io
```

P.S.: So, why it not installed from first try?

**Comment by back-to** [comment] 2018-06-19 21:31
> P.S.: So, why it not installed from first try?

here is a list of your issues

---

**1.** `error: invalid command 'bdist_wheel'`

some old version / package missing

**2.**

```
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
ImportError: cannot import name main
```

known **pip10** issue

**3.** `bash: streamlink: command not found`

you did an [User Install](https://pip.pypa.io/en/stable/user_guide/#user-installs) which installs it somewhere in `$HOME` instead of globally _(sudo as root user)_

some OS will have `$HOME/.local/bin` already set in `PATH`,
but for your example **Debian** does not do it by default.

---

closing as the issue is solved.

**Closed by back-to** 2018-06-19 21:31 UTC
Labels: more info required

**Comment by nurupo** [comment] 2018-09-29 08:10
This should suffice.

```bash
sudo apt-get update
sudo apt-get install python3 python3-venv ffmpeg
python3 -m venv ~/.local/test-python-env
~/.local/test-python-env/bin/pip3 install --upgrade --upgrade-strategy only-if-needed pip
~/.local/test-python-env/bin/pip3 install --upgrade --upgrade-strategy only-if-needed setuptools
~/.local/test-python-env/bin/pip3 install --upgrade --upgrade-strategy only-if-needed streamlink
~/.local/test-python-env/bin/streamlink --help
```
