### ISSUE TITLE
Crunchyroll failing again

### ISSUE THREAD

**Issue by KBD20** [streamlink/streamlink#3153] opened 2020-09-06 01:39 UTC
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

Any Crunchyroll stream returns `error: Unable to validate API response: Unable to validate key 'auth': Type of None should be 'str' but is 'NoneType'
`
And exits

### Reproduction steps / Explicit stream URLs to test

1. Use `streamlink --crunchyroll-username=xxxx --crunchyroll-password=xxxx --player-no-close  --crunchyroll-purge-credentials --ringbuffer-size 32M [video link] best`
2. See the error returned

### Log output

```
[cli][debug] OS:         Linux-5.4.0-45-generic-x86_64-with-glibc2.29
[cli][debug] Python:     3.8.2
[cli][debug] Streamlink: 1.5.0
[cli][debug] Requests(2.22.0), Socks(1.6.7), Websocket(0.53.0)
[cli][info] Found matching plugin crunchyroll for URL https://www.crunchyroll.com/xxxx
[cli][debug] Plugin specific arguments:
[cli][debug]  --crunchyroll-username=***** (username)
[cli][debug]  --crunchyroll-password=******** (password)
[cli][debug]  --crunchyroll-purge-credentials=True (purge_credentials)
[utils.l10n][debug] Language code: en_NZ
[plugin.crunchyroll][debug] Creating session with locale: en_NZ
[plugin.crunchyroll][debug] Session created with ID: ddf53dcf03308995d488779a00cd9024
[plugin.crunchyroll][debug] Attempting to login using username and password
error: Unable to validate API response: Unable to validate key 'auth': Type of None should be 'str' but is 'NoneType'

```

### Additional comments, screenshots, etc.
The same issue happens with and without purge credentials.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment] 2020-09-06 01:54
Duplicate of https://github.com/streamlink/streamlink/issues/3148, this has already been fixed but it isn't in the stable release yet.

**Closed by gravyboat** 2020-09-06 01:54 UTC
