### ISSUE TITLE
--retry-streams command switches to hosted user. Is that intended?

### ISSUE THREAD

**Issue by NeoFahrenheit** [streamlink/streamlink#1485] opened 2018-02-16 19:05 UTC
Hi guys.

I want to download her streams, but if she is hosting someone, the plugin switches to the host.
If there a fix or this is intended?

https://i.imgur.com/dw6ES3O.jpg

If is intended, can I request this feature?

Thanks very much! :)

**Comment by gravyboat** [comment] 2018-02-16 19:24
This is the intended functionality, and this issues is a duplicate of this: https://github.com/streamlink/streamlink/issues/1017, use the `--twitch-disable-hosting param: https://streamlink.github.io/cli.html#cmdoption-twitch-disable-hosting.

**Closed by gravyboat** 2018-02-16 19:24 UTC
Labels: duplicate
