### ISSUE TITLE
plugins.bigo: not working

### ISSUE THREAD

**Issue by shiro789** [streamlink/streamlink#3626] opened 2021-03-16 17:58 UTC
## Plugin Issue

- [ ] This is a plugin issue and I have read the contribution guidelines.
- [ ] I am using the latest development version from the master branch.

### Reproduction steps / Explicit stream URLs to test

1. https://www.bigo.tv/swxytx
2. https://bigo.tv/20566029

### Log output

```
[cli][info] Found matching plugin bigo for URL https://www.bigo.tv/swxytx
error: No playable streams found on this URL: https://www.bigo.tv/swxytx
```

### Additional comments, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment] 2021-03-16 18:12
Neither of these two channels is online and it also seems that the plugin does only support input URLs with the "bigo ID", and not profile names, which means you'll have to find the right URL for the stream. The other streams on this site are working fine.

**Comment by mkbloke** [comment] 2021-03-17 23:24
@shiro789, how/from where are you getting a username?  I do not see anything other than IDs used on the website (while not logged in, as I do not have an account).

**Comment by unnutricious** [comment] 2021-03-18 05:35
I can confirm I saw this problem as well, but it appears to be on the bigo.tv side.  You can replicate this issue by going to https://bigo.tv/show and clicking on streamers randomly. Some will work and some won't, showing offline. The site seems to still be in transition from flash to html5, so that might be related. If you try sending a query to the API url  `https://www.bigo.tv/OInterface/getVideoParam?bigoId={0}`, the data section is empty, no wsUrl. It seems random, not tied to particular broadcasters, just each live stream it may or may not work.

The apps still work correctly, but they do not use HLS, they use the proprietary bigo protocol, which is beyond my comprehension to reverse-engineer. This plugin used to support it, and I removed it after it stopped working correctly a few years ago. I don't know if it's still the same or not.

**Comment by back-to** [comment] 2021-03-20 09:16
closing `https://bigo.tv/<ID>` works normally

**Closed by back-to** 2021-03-20 09:16 UTC
Labels: does not meet requirements, plugin issue, unconfirmed

**Comment by unnutricious** [comment] 2021-03-20 17:45
This is not the issue of id vs profile name, the site is still broken when viewing in a browser as of today. There's nothing that can be done on the streamlink side to fix it though, other than changing it to support the streaming protocol used in-app.

**Comment by shiro789** [comment] 2021-03-27 19:17
is there any way to fix manually?

**Comment by trodiz** [comment] 2021-03-29 13:49
> Neither of these two channels is online and it also seems that the plugin does only support input URLs with the "bigo ID", and not profile names, which means you'll have to find the right URL for the stream. The other streams on this site are working fine.

I just wanted to add that both these URLs are valid `bigoId`s. Now they've renamed it to `siteId`. Infact both formats are equivalent from their perspective. Which makes sense since they probably don't want to break their old API. Most bigo rooms used to be promoted using these URLs.

Here's an example: both siteId=82693649 and siteId=angel9 will land you on the same page. Try it `https://bigo.tv/{siteId}`.

**Comment by unnutricious** [comment] 2021-04-01 04:00
> is there any way to fix manually?

Nope. I suggest trying to provide feedback to Bigo that their website is broken. I couldn't actually find an easy way to provide feedback. Besides streamlink not always working, if you share a stream from the app, it will send the user a link to bigo.tv, but it will say the user is offline (when this is not true) most of the time. This is either because they don't care about the website or maybe they are intentionally trying to prevent recording.

**Comment by shiro789** [comment] 2021-06-22 14:01
there's a bug that if the host just started streaming we can use streamlink, if it's already few minutes usually cannot use it.
but if you already using streamlink at the beginning of the live you can still use it until the end of the show.
hope someone understand, sorry for my bad english.
