### ISSUE TITLE
Using both "Allow the player to get closed" and "Set custom title" options on macOS result in a fail with VLC

### ISSUE THREAD

**Issue by Porkepix** [streamlink/streamlink#1322] opened 2017-11-08 08:09 UTC
### Checklist

- [x] This is a bug report.
- [x] I have read the contribution guidelines.

### Description

When both "Allow the player to get closed" and "Set custom title" options are enabled on macOS with VLC player selected, stream is instantly closed when opened with an error printed by VLC (sadly, this is too quick to be able to report the kind of error here).

The problem does not reproduce if only one of those options is checked, whichever one is it.

### Expected / Actual behavior

Player should just run the stream with the title and close when ended.

### Reproduction steps / Explicit stream URLs to test

1. Pick VLC as the player to use
2. Enable "Allow the player to get closed" and "Set custom title"
3. Launch any stream

### Environment details

Operating system and version: macOS 10.9 with an up-to-date VLC
Streamlink and Python version: streamlink 0.8.1, probably running through system or homebrew's python (streamlink installed with homebrew).

**Comment by beardypig** [comment] 2017-11-08 09:04
Are you using the GUI? Do you know the `streamlink` command that is being run, with the options?

**Comment by bastimeyer** [comment] 2017-11-08 14:24
@Porkepix 
Wrog repo and a duplicate of streamlink/streamlink-twitch-gui#464
See this comment here: https://github.com/streamlink/streamlink-twitch-gui/issues/464#issuecomment-305063831

**Comment by Porkepix** [comment] 2017-11-08 14:47
Well, I noticed the issue using Twitch GUI, but managed to reproduce it with just the CLI tool:
`
streamlink -p vlc -a '--play-and-exit --input-title-format "{name} - {game} - {status}"' https://twitch.tv/foobar best
[cli][info] Found matching plugin twitch for URL https://twitch.tv/foobar
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (hls)
[cli][info] Starting player: vlc
[cli][info] Closing currently open stream...
Traceback (most recent call last):
  File "/usr/local/Cellar/streamlink/0.8.1/libexec/bin/streamlink", line 11, in <module>
    load_entry_point('streamlink==0.8.1', 'console_scripts', 'streamlink')()
  File "/usr/local/Cellar/streamlink/0.8.1/libexec/lib/python2.7/site-packages/streamlink_cli/main.py", line 1045, in main
    handle_url()
  File "/usr/local/Cellar/streamlink/0.8.1/libexec/lib/python2.7/site-packages/streamlink_cli/main.py", line 502, in handle_url
    handle_stream(plugin, streams, stream_name)
  File "/usr/local/Cellar/streamlink/0.8.1/libexec/lib/python2.7/site-packages/streamlink_cli/main.py", line 384, in handle_stream
    success = output_stream(stream)
  File "/usr/local/Cellar/streamlink/0.8.1/libexec/lib/python2.7/site-packages/streamlink_cli/main.py", line 262, in output_stream
    output.open()
  File "/usr/local/Cellar/streamlink/0.8.1/libexec/lib/python2.7/site-packages/streamlink_cli/output.py", line 23, in open
    self._open()
  File "/usr/local/Cellar/streamlink/0.8.1/libexec/lib/python2.7/site-packages/streamlink_cli/output.py", line 124, in _open
    self._open_subprocess()
  File "/usr/local/Cellar/streamlink/0.8.1/libexec/lib/python2.7/site-packages/streamlink_cli/output.py", line 139, in _open_subprocess
    self.player = subprocess.Popen(self._create_arguments(),
  File "/usr/local/Cellar/streamlink/0.8.1/libexec/lib/python2.7/site-packages/streamlink_cli/output.py", line 112, in _create_arguments
    args = self.args.format(filename=filename)
KeyError: 'name'
`

**Comment by bastimeyer** [comment] 2017-11-08 15:00
> Maybe not the same issue though?

No, because you're using a different (invalid) command that includes the title **template**. This issue is just showing unresolvable variables in the `-a` paramater.

This is the correct line which will let VLC fail:
`streamlink -p vlc -a '--play-and-exit --input-title-format "foo"' twitch.tv/foobar best`

**Comment by Porkepix** [comment] 2017-11-08 15:05
This is the template format I copied from the GUI though:
![capture d ecran 2017-11-08 a 16 02 23](https://user-images.githubusercontent.com/709500/32556004-8090c29e-c49e-11e7-9a4d-b85026522b50.png)
Why is the GUI showing template that you tell is invalid?

And if the VLC issue can be reproduced from the CLI tool, then I guess this is finally the correct repository?

**Comment by bastimeyer** [comment] 2017-11-08 15:15
> Why is the GUI showing template that you tell is invalid?

It is using its own variable substitution, because this feature doesn't exist in Streamlink (and its Twitch.tv plugin).
https://github.com/streamlink/streamlink-twitch-gui/wiki/Player-configuration#custom-player-parameters

There was an attempt to bing a similar feature to Streamlink, but the implementation had a few flaws and was not as flexible with the available variables:
#623

**Closed** 2018-02-04 14:08 UTC
Labels: player issue
