### ISSUE TITLE
arconai plugin not working

### ISSUE THREAD

**Issue by kark445** [streamlink/streamlink#1243] opened 2017-09-24 22:44 UTC
arconai change ther sourc code and plugin not working..
new source code on page shows like below..ty

```
<video id="stream_player" class="stream-player video-js vjs-default-skin vjs-16-9 vjs-big-play-centered" controls preload="auto" width="640" height="264" data-setup="{}">
  <source id="stream_player_src" src="" type="application/x-mpegURL">
    <p class="vjs-no-js">
      To view this video please enable JavaScript, and consider upgrading to a web browser that <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
    </p>
  </video>
<script>
  document.getElementsByTagName('video')[0].volume = 1.0;
  eval(function(p,a,c,k,e,d){e=function(c){return c.toString(36)};if(!''.replace(/^/,String)){while(c--){d[c.toString(a)]=k[c]||c.toString(a)}k=[function(e){return d[e]}];e=function(){return'\\w+'};c=1};while(c--){if(k[c]){p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c])}}return p}('4 0=5.3(\'2\');0.1(\'6\',\'7://c.d/b/a/8/9.e\');',15,15,'source|setAttribute|stream_player_src|getElementById|var|document|src|https|1506303514|d8320fedb4a90fb06c9f7bff96a7e619|v93UqwBUrRbCaqDeiwKc2A|live|videoserver2|org|m3u8'.split('|'),0,{}));
</script>
```

**Comment by JourneyOver** [comment] 2017-09-25 21:43
yep, sadly this isn't a simple change in url to get it working like the last couple times this plugin broke, there's more that needs to be fixed this time around.

**Comment by sdfwv** [comment] 2017-09-26 15:26
Here is a fix https://github.com/sdfwv/streamlink/commit/806732dc46d4a13d8afbb549927d4561117b2734

not sure if streamlink wants an unpacker.

**Comment by bastimeyer** [comment] 2017-09-26 15:43
Thanks for providing a fix for this plugin. Could you please open a PR once you think that your fixes are complete?

> not sure if streamlink wants an unpacker.

I think it would make more sense using the [jsbeautifier](https://pypi.python.org/pypi/jsbeautifier) package as a dependency and using its unpacker module instead of copying it into Streamlink. Even if packing JS is a very bad practice and you probably won't see this on other websites again because it's so rare fortunately, adding a new dependency should be worth it, so that this code doesn't have to be included and tested here.

**Comment by cirrusUK** [comment] 2017-10-07 20:32
@sdfwv 

+1  :+1:

**Comment by kark445** [comment] 2017-11-09 14:38
arconai plugin not working agian.

**Comment by cirrusUK** [comment] 2017-11-09 16:23
I can confirm the arconai plugin no longer works, as a temp workaround you can hit F12 on the browser page where desired stream is playiing, hit the newtwork tab and filter .m3u8 to get the source URL which can then be played in VLC/MPV, the URL's are subject to change so will have to do the F12 workaround each visit.
regards

**Comment by rollykaunang** [comment] 2017-11-16 13:58
Yes it is not working, Please fix it, hope someone could fix it.. Thank You so much!

**Comment by sdfwv** [comment] 2017-11-19 10:33
they change there domain / code way to often

not really worth it to maintain this

maybe deleting it would make more sense

**Comment by techmouse** [comment] 2017-11-27 04:31
> they change there domain / code way to often
>
> not really worth it to maintain this
>
> maybe deleting it would make more sense

Nice try, @sdfwv or should I say... Arconai! We all know it's you and your ruse won't work!

But in all seriousness, I think it is worth it to at least not give up. Arconai.tv is another site that melts processors and there are a lot of people with weak machines that can't watch the content there. Streamlink is the solution they need. After all, what other solutions do they have?

**Comment by issues420** [comment] 2017-12-28 02:02
Here is a working [plug-in](https://github.com/a-posadas/plugin.video.arconaitv/blob/master/main.py) for Kodi from a-posadas that pulls streams currently from the Arconai site.   Not much of a coder otherwise I could pull out the useful code.   It would be helpful if these codes were commented out so we could change things on our own on the fly.  Hope this helps as I used streamlink mainly with Arconai.

**Comment by a-posadas** [comment] 2018-01-09 05:39
issues420, nah, they just changed the code again. My plugin is kaput.

**Comment by issues420** [comment] 2018-01-30 18:00
I see that your kodi stuff works again.  how would i go about adapting this to streamlink?  I know that we only need the part of the code where we define the def play_video(selection).  and also to import your lib.aadecode import aadecode in the start.  I just don't know what is what.

**Comment by a-posadas** [comment] 2018-01-30 19:24
Well, that is basically the gist of it. I guess the only thing you really need to know besides that is that everything between the script tags of the html from where the obfuscated code is is what you input into aadecode.

You also have to make sure it is in plain unicode format. So you might have to do a decode on your string. 

If you look at the aadecode.py file, it corresponds pretty closely to the link to stackoverflow. After line 16 it gets pretty messy since it is a mixture of adding, subtracting and string concatenation. 

Aside from that, without knowing what specifically you have tried and what errors you are getting I'm not sure how I can help. I haven't really looked at the streamlink code but I could if you would like me to.

**Comment by issues420** [comment] 2018-01-31 18:13
I have been trying to work on this but know nothing about the code from streamlink.  I think that I have most of the code sorted out but am having trouble with getting a stream url output at the end of the code.    The yield 'live' line is getting me.  I have posted the start of my code on my git under test [https://github.com/issues420/test/blob/master/arconai.py](url)  any help would be great!  Thanks

**Comment by issues420** [comment] 2018-01-31 20:12
Ok I was able to get this working.  Have no idea how but after a couple of days and no previous knowledge of python I was able to rework this plug in.  not sure what is needed in the includes but it is working on my system.  If you want to check this out I will be updating my git.  I did have to install bs4 as well as jsbeautifier on my system not sure if it is needed but this does work.  A big Thanks to A-Posada for the original code and guidance.

**Comment by dubl1n** [comment] 2018-02-10 17:39
I'm getting the following error:

```
Failed to load plugin arconai:
  File "imp.py", line 234, in load_module
  File "imp.py", line 172, in load_source
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\arconai.py", line 38
    code = aadecode(code)
                        ^
TabError: inconsistent use of tabs and spaces in indentation
```

**Comment by mmetak** [comment] 2018-03-01 21:12
@issues420's modified plug-in doesn't work and I get the same error as @dubl1n .

**Comment by issues420** [comment] 2018-03-01 22:28
This modified plug-in does work as I am using it now.  You have to make sure you copy the code correctly with consistent use of tabs and or spaces for ALL indentation.  you could copy the code and redo all of the spacing.  That is what I did initially to get everything in check.

**Comment by techmouse** [comment] 2018-03-01 23:22
I can confirm the problem is both tabs and spaces exist in the raw file. Copy-pasting _and_ saving the file to the hard drive doesn't seem to preserve the whitespace.

You can fix it by opening a text editor and then using the find and replace feature to replace all tabs with 4 spaces.

I am however getting an entirely different error:
```
Failed to load plugin arconai:
  File "/usr/lib/python3.4/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.4/imp.py", line 169, in load_source
    module = methods.exec(sys.modules[name])
  File "<frozen importlib._bootstrap>", line 1153, in exec
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/mouse/.livestreamlinkgui/plugins/arconai.py", line 9, in <module>
    from bs4 import BeautifulSoup
  File "/usr/lib/python3/dist-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/usr/lib/python3/dist-packages/bs4/builder/__init__.py", line 306, in <module>
    from . import _html5lib
  File "/usr/lib/python3/dist-packages/bs4/builder/_html5lib.py", line 57, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'
```

I don't use python (because of the mandatory whitespace issue) so I can only guess at what this error means. Is it an outdated library?

**Comment by a-posadas** [comment] 2018-03-06 04:43
Yes, arconaitv has changed their obfuscation once again. Luckily it is an easy fix as it unpacks directly with jsbeautifier. I think the overall lesson here is that if you want to have a working plugin for arconaitv, whether it be kodi, streamlink or whatever else, you're going to need to update it regularly as they change their obfuscation method pretty regularly every few months.

**Comment by techmouse** [comment] 2018-03-13 18:18
I would seriously update it myself if I knew enough about python or the method.

**Comment by josefson** [comment] 2018-04-09 05:35
There is this solution i have been using, that depends on [chome|chromium] webdriver.
Where i make an http request to the main page and extract all the shows/movies and its ids.
And given an user input/selection it:
1- opens a headless browser with a --log-net-log argument
2- go to the show/movie url
3- regex the log file for the stream-url
4- put the command i need to run in my terminal in my clipboard
Now, i know there are a lot of dependencies: chrome/webdriver, and it has some overhead openning a headless browser in order to get the  network data. But it works consistently. The only changable things here are:
1- Regex pattern for finding the streamlink
2- Arconai base address and show sufix link
And both are really a no brainer to do.
Here is an example:
![arconai](https://s17.postimg.org/vkhsdxuq7/out.gif)

**Closed** 2018-08-26 00:15 UTC
Labels: plugin issue, wontfix
