### ISSUE TITLE
Add option to force progress display

### ISSUE THREAD

**Issue by tonycpsu** [streamlink/streamlink#2353] opened 2019-03-11 21:53 UTC
## Feature Request

- [x] This is a feature request and I have read the contribution guidelines.

### Description

Per #1770, `streamlink` will currently only output progress messages if stdout is a tty:

https://github.com/streamlink/streamlink/blob/71d550fedf7048288435b564c4c1b49373911f6c/src/streamlink_cli/main.py#L341

This is normally what a user wants, but I'm developing an application that runs `streamlink` as a subprocess, and I'd like to capture the progress messages to display the transfer rate in the app.  However, isatty() fails on pipes.  I can work around this by using `pty.openpty()`, but this causes the subprocesses to terminate when the app exits, which isn't what I want.

My proposed solution would be to add an option, e.g. `force-progress`, which would skip the isatty check if the option is supplied.  This way there is no change for users who count on the current behavior, but those who would like to monitor the progress on a pipe can do so.

I will submit a PR for this change if so desired.

### Expected / Actual behavior

Progress display can be forced even when stdout is not a TTY.

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by Quaraxkad** [comment] 2019-03-12 19:28
I second this request.

**Comment by beardypig** [comment] 2019-03-12 22:06
@tonycpsu can you give an example of how you are invoking streamlink so that we can test it?

**Comment by tonycpsu** [comment] 2019-03-12 22:34
@beardypig, sure:

```python
import io
import asyncio

async def get_progress(proc):
    while True:
        line = await proc.stdout.readline()
        if line == b'':
            break

        print(line)

async def run(with_pty=False):

    proc = await asyncio.create_subprocess_exec(
        "streamlink", "https://www.youtube.com/watch?v=__dFiuEpW6c",
        "720p",
        "-o", "foo.mp4",
        stdout=asyncio.subprocess.PIPE
    )
    import os
    await asyncio.gather(get_progress(proc))


loop = asyncio.get_event_loop()
loop.run_until_complete(run())
```

**Comment by back-to** [comment] 2019-08-25 07:22
closing, it seems like it's too specific and not worth it.

**Comment by rseanhall** [comment] 2019-09-13 23:15
I don't understand why you think it's too specific. I think it's fairly common to write an application that spawns apps like streamlink as a subprocess. Is there some other way for those wrapper applications to get download progress when saving to a file?

**Comment by fatalis** [comment] 2020-02-18 23:40
> I don't understand why you think it's too specific. I think it's fairly common to write an application that spawns apps like streamlink as a subprocess. Is there some other way for those wrapper applications to get download progress when saving to a file?

Agreed. @back-to Please reconsider this issue.

**Comment by jamesrc** [comment] 2020-02-23 22:10
I would also like to request @back-to reconsider this.  It does not seem like an esoteric use case.

**Comment by back-to** [comment] 2020-02-24 17:20
https://github.com/streamlink/streamlink/pull/2438 was open for 4 months and **nobody wanted to test it or had a need for it.**

and now **6 months later** someone wants it again,
this is just not worth it.

**Comment by tonycpsu** [comment] 2020-02-24 17:32
...or maybe people have been employing workarounds as mentioned above, and lost track of the status?  It wasn't made clear that further testing was required, so I figured this would just get merged eventually.  If your expectations of the community were different, you could have said so.

**Comment by rseanhall** [comment] 2020-02-24 22:10
I posted my comment in September hoping to begin a conversation on why your perfectly good pull request was abandoned. While waiting for you to respond, I applied your pull request to the latest release in my custom fork and it has been working for me all this time. I don't understand what else I should have done.

**Comment by jamesrc** [comment] 2020-02-25 00:28
I needed it a while back, applied the change locally and moved on with my life.

I came back to it recently to apply it on another machine and noticed it had been closed without being merged.

If I'd known feedback was needed then I would have posted some.  It seemed like an obviously useful feature, to me.

**Closed** 2020-03-07 20:22 UTC
Labels: feature request

**Comment by TooLoose** [comment] 2020-08-07 09:26
Updated  today and my app is broke. Taken hours to find out what the issue is. Please put the switch in. It would be very helpful. thanks.
