### ISSUE TITLE
Streamlink + Twitch Turbo (to block ads)

### ISSUE THREAD

**Issue by farzaa** [streamlink/streamlink#2370] opened 2019-03-21 18:55 UTC
Hey there!

Twitch recently began inserting server side ads and patching a lot of the solutions I've been discovering to block ads. I know Streamlink currently blocks ads, but it's unknown for how long this will work. 

I wanted to know if it was possible to just use a Twitch Turbo subscription (which stops ads completely) subscription alongside the Streamlink to view content ad-free on my own player.

**Comment by bastimeyer** [comment] 2019-03-21 19:38
You can try authenticating your Twitch account and see whether they respect the OAuth-token in their HLS advertisement system.
https://streamlink.github.io/cli.html#cmdoption-twitch-oauth-authenticate

Other than that, it's a duplicate of #2368

**Closed by bastimeyer** 2019-03-21 19:38 UTC
