### ISSUE TITLE
python.exe left running after streamlink.exe exit (ctrl-c)

### ISSUE THREAD

**Issue by SnowLeopard71** [streamlink/streamlink#1287] opened 2017-10-25 07:11 UTC
- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description
When using ctrl-C to exit from a recording to file (-o), streamlink.exe exits but python.exe is still running and continues to output update info ("[download][file.mpeg] Written 1.88 GB (1h40m0s @ 259.0 KB/s)")

### Expected / Actual behavior
python.exe should also be shutdown.
...

### Reproduction steps / Explicit stream URLs to test
Using cygwin bash, "streamlink -o savefile.mpg URL best"

### Environment details
Operating system and version: Windows 7
Streamlink and Python version:  0.8.1 windows installer

**Comment by gravyboat** [comment] 2017-10-25 16:32
This is a duplicate of https://github.com/streamlink/streamlink/issues/521 so I'm going to close this one out. Thanks for the report.

**Closed by gravyboat** 2017-10-25 16:32 UTC
