### ISSUE TITLE
The Picarto arms race continues - HTML5 HLS is now a thing for (some ?) streams.

### ISSUE THREAD

**Issue by mjevans** [streamlink/streamlink#364] opened 2017-01-06 00:49 UTC
The Picarto arms race continues - HTML5 HLS is now a thing for (some ?) streams.

**Comment by gravyboat** [comment] 2017-01-06 02:39
Again?! This is getting ridiculous, if they want to keep us from handling their apps is it even worth doing? Jeez what a pain...

**Comment by mjevans** [comment] 2017-01-06 02:48
They've actually changed from an integer to text for the stream type.

Oddly the place stream option has a /different/ value in the popout for the page than in this snip.

Flash is now literally 'flash'.  In the popout the value returned is 'hls'.


This method needs one line changed to fix for the current interface change.

@staticmethod
    def _get_stream_arguments(page):
...
        player_id, product, offline_image, online, is_flash = \
            map(lambda a: bool(int(a)), [player_id, product, offline_image, online, True if is_flash == "flash" else False])







                <div class="flexPlayerOuter">

                        <div class="centerFixed playerBackdrop flexPlayerInnerFull">
                                <div class="posRel">
                                        <video playsinline id="playerHolder1" class="video-js vjs-default-skin vjs-big-play-centered vjs-16-9 overflowHidden"></video>
                                        
                    <div class="colBGWW pd10 roundCorners ontop maininfoFeatureMenu boxShadow zI1 text-left fontSize1 techMenu-XXX" style="display: none;">
                        <div class="cutLine0 dark pdbot5 bot5 fontSize1-2">Playback options</div>
                        <div class="pdtop5">
                            <div class="displayBlock btnBase btn-sm topbot5 techBtn tech_switch" data-channel="XXX" data-playerid="1" data-token="public" data-tech="flash">
                                FLASH
                            </div>
                                                        <div class="displayBlock btnBase btn-sm topbot5 techBtn tech_switch" data-channel="XXX" data-playerid="1" data-token="public" data-tech="hls">
                                HTML5 (HLS)
                            </div>
                        </div>
                    </div>

                                        <div class="colBGWW pd10 roundCorners ontop maininfoFeatureMenu boxShadow zI1 text-left fontSize1 stnMenu-XXX" style="display: none;">
                                                <div class="cutLine0 dark pdbot5 bot5 fontSize1-2">Player Options</div>
                                                <div class="pdtopbot5">
                                                        <div class="bot5 fontSize0-8">Please give us Feedback.</div>
                                                        <div class="bot5 displayBlock btnBase btn-sm Green settingsBtn"
                                                                 onclick="window.open('https://www.surveymonkey.de/r/picartohtml5player','_blank');" data-channel="XXX"><i
                                                                        class="fa fa-pencil-square iconContainer"></i> HTML5 Feedback
                                                        </div>
                                                </div>
                                                <div class="pdtopbot5">
                                                        <div class="bot5 fontSize0-8">You don't like what you see?</div>
                                                        <div class="bot5 displayBlock btnBase btn-sm Red settingsBtn reportStream" data-channel="XXX" value="Report"><i
                                                                        class="fa fa-flag iconContainer"></i> Report
                                                        </div>
                                                </div>
                                                <div class="pdtop10">
                                                        
                                                                                                                        <div class="bot5 displayBlock btnBase btn-sm settingsBtn popoutStream" data-playerid="1" data-channel="XXX" data-token="public"><i class="fa fa-external-link iconContainer"></i> Popout
                                                                </div>
                                                                                                                
                                                        
                                                                                                                
                                                </div>
                                        </div>
                                        
                                </div>
                        </div>
                        
                        
                        <script> placeStream("XXX",1,0, 0, 1, "public", "flash" ); </script>
                                                                </div>
                                                        <div class="streamer_infos colBG2">

**Comment by bluesaphiresky** [comment] 2017-01-06 05:33
Ah yes I just noticed my streamlink not working for picarto, I'm sorry because I am computer illiterate but how do I take what mjevans changed into my picarto plugin script?

**Comment by Keisonne** [comment] 2017-01-06 05:49
my streamlink also has stopped functioning for picarto, we must band together brothers and defeat this new evil.

**Comment by Hotwire75** [comment] 2017-01-06 06:06
It took me a few to figure out, but in picarto.py, you will want to change the one section to read

```    @staticmethod
    def _get_stream_arguments(page):
        match = _channel_casing_re.search(page.text)
        if not match:
            raise ValueError

        # transform the arguments
        channel, player_id, product, offline_image, online, token, is_flash = \
            map(lambda a: a.strip("' \""), match.group(1).split(","))
        player_id, product, offline_image, online, is_flash = \
 			map(lambda a: bool(int(a)), [player_id, product, offline_image, online, True if is_flash == "flash" else False])

        return channel, online, token, is_flash
```

**Comment by bluesaphiresky** [comment] 2017-01-06 07:58
Hmmm i copy pasted what you gave me I can't seem to get it to work but thanks anyways hotwire :)

**Comment by mjevans** [comment] 2017-01-06 09:07
You really only need to change the last part of the array you're passing in to the map function to be eaten by the lambda.  The change is pre-digesting the value of is_flash based on a string comparison (which makes the result already boolean) using an in-line-if statement equivalent know as a ternary conditional operator.

I think that ultimately, however, recognizing the existence of the divs with classes :: techBtn tech_switch :: are the way forward.  They present a reliable method for enumerating the /options/ of a given stream and selecting whichever one has a benefit in a technical sense.

**Comment by beardypig** [comment] 2017-01-06 12:15
@Hotwire75, looks like you're using an old version of the plugin which is why it probably didn't work for @bluesaphiresky. 

The simplest fix would be to change line 37 from
```py
online, is_flash = bool(int(online)), bool(int(is_flash))
```
to
```py
online, is_flash = bool(int(online)), is_flash == "flash"
```

However, I have created a more sophisticated fix in #365

@gravyboat, I don't think this change was designed to intentionally break support for picarto, they just changed their player code slightly :)

**Comment by gravyboat** [comment] 2017-01-06 17:32
Sounds good, I'm closing this out since it's been addressed.

**Closed by gravyboat** 2017-01-06 17:32 UTC
Labels: bug

**Comment by Hotwire75** [comment] 2017-01-06 19:25
@beardypig, I'd copypasta'ed from here straight into fresh from git and added a missing '/', which is right at my limit on things python, lol.

I'm now using your current fix, and it's working well.

Thanks for all y'alls work on this program, it means I can lounge back and lurk a while with high quality video on an ancient laptop that otherwise has problems with even 360p flash/html5. (early 32 bit Intel Atom) :D

**Comment by mjevans** [comment] 2017-01-07 01:43
Thanks, the latest git works for both live_hls and the flash style options, and they are discovered as /options/ now.
