### ISSUE TITLE
Twitch video lags behind 2 seconds in OSX El Capitan

### ISSUE THREAD

**Issue by pakoito** [streamlink/streamlink#2104] opened 2018-10-07 23:33 UTC
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.

### Description

In OSX, El Capitan, pip3 installed streamlinks lags behind exactly 2 second on the video track for hls twitch streams.

### Expected / Actual behavior

- Audio and video are synced

- Instead, audio is 2 seconds ahead of the video

### Reproduction steps / Explicit stream URLs to test

1. open `streamlink https://www.twitch.tv/dragonballfighterz best`
2. use Track Sync to put +2 seconds of delay in the audio
3. see that the tracks are synchronized now

### Log output

TBD

**Comment by bastimeyer** [comment] 2018-10-08 00:29
Since Streamlink doesn't do any (re-)muxing here and simply concatenates MPEGTS segments, I'm pretty sure that it's a player or player-config related issue on @pakoito's system.

**Comment by pakoito** [comment] 2018-10-08 00:39
That may be the case. I'm using `VLC Version 3.0.4 Vetinari (Intel 64bit)` and `streamlink 0.14.2`.

Logs: https://pastebin.com/4AVSrvx3

**Comment by gravyboat** [comment] 2018-10-08 02:40
@pakoito We've had a couple people report issues with that version of VLC (https://github.com/streamlink/streamlink/issues/2060 is the main issue that was discussed and where I noted another person having the same problem). Someone had an Arch Linux workaround, but that won't help much in your case since it was Pacman related. If you can try another video player, or downgrade to post 3.x.x of VLC and see if that addresses it. There's also a ticket open with VLC over here: https://github.com/streamlink/streamlink/issues/2060

**Comment by Jolmberg** [comment] 2018-12-12 11:37
@gravyboat I think I can confirm that for you. I have a similar setup with El Capitan and VLC 3.0.4 and I also get exactly 2 seconds of video delay. The problem goes away when I use mpv instead.

**Comment by belthesar** [comment] 2019-01-15 02:32
VLC often by default introduces 2 seconds of delay for network sources as an internal buffer pool. You can adjust the settings to shorten/remove this. YMMV for playback stability.

**Comment by back-to** [comment] 2019-02-07 16:10
closing as this is more of a player/system issue

**Closed by back-to** 2019-02-07 16:10 UTC
Labels: more info required, unconfirmed
