### ISSUE TITLE
stream.dash (or stream.segmented): takes long time to finish dash manifest

### ISSUE THREAD

**Issue by thisisgk** [streamlink/streamlink#4311] opened 2022-01-25 16:15 UTC
### Checklist

- [X] This is a bug report and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

When streamlink processes DASH manifest and makes an output, it takes a very long time in finishing. It took about 5 seconds in my test every time.

I generated and tested the input files as follows.
```
$ mkdir /tmp/test
$ ffmpeg -f lavfi -i testsrc \
-use_template 0 \
-init_seg_name 'init$RepresentationID$.$ext$' \
-media_seg_name 'seg$RepresentationID$-$Number%02d$.$ext$' \
-dash_segment_type mp4 \
-hls_playlist 1 -hls_master_name master.m3u8 \
-f dash -t 30 /tmp/test/manifest.mpd
```
Then ran streamlink.
```
$ streamlink -l trace dash://file:///tmp/test/manifest.mpd best -o /dev/null
$ streamlink -l trace hls://file:///tmp/test/master.m3u8 best -o /dev/null
```
In the following log, please notice these lines for DASH manifest. For HLS playlist, streamlink finishes soon.
```
[00:59:47.924248][stream.dash][debug] Download of segment: file:///tmp/test/seg0-03.m4s complete
[00:59:52.922646][stream.segmented][debug] Closing worker thread
```

### Debug log

```text
# log for DASH manifest
[00:59:47.815443][cli][debug] OS:         macOS 10.12.6
[00:59:47.815670][cli][debug] Python:     3.9.10
[00:59:47.815745][cli][debug] Streamlink: 3.1.0
[00:59:47.815865][cli][debug] Requests(2.27.1), Socks(1.7.1), Websocket(1.2.3)
[00:59:47.816320][cli][debug] Arguments:
[00:59:47.816447][cli][debug]  url=dash://file:///tmp/test/manifest.mpd
[00:59:47.816647][cli][debug]  stream=['best']
[00:59:47.816800][cli][debug]  --loglevel=trace
[00:59:47.816950][cli][debug]  --output=/dev/null
[00:59:47.817352][cli][info] Found matching plugin dash for URL dash://file:///tmp/test/manifest.mpd
[00:59:47.817557][plugins.dash][debug] Parsing MPD URL: file:///tmp/test/manifest.mpd
[00:59:47.915656][utils.l10n][debug] Language code: en_US
[00:59:47.915826][stream.dash][debug] Available languages for DASH audio streams: NONE (using: n/a)
[00:59:47.917304][cli][info] Available streams: 240p (worst, best)
[00:59:47.917486][cli][info] Opening stream: 240p (dash)
[00:59:47.917880][cli][debug] Checking file output
[00:59:47.918306][stream.dash][debug] Opening DASH reader for: 0 (video/mp4)
[00:59:47.919071][cli][debug] Pre-buffering 8192 bytes
[00:59:47.920896][stream.dash][debug] Download of segment: file:///tmp/test/init0.m4s complete
[00:59:47.921416][cli][debug] Writing stream to output
[00:59:47.922346][stream.dash][debug] Download of segment: file:///tmp/test/seg0-01.m4s complete
[00:59:47.923426][stream.dash][debug] Download of segment: file:///tmp/test/seg0-02.m4s complete
[00:59:47.924248][stream.dash][debug] Download of segment: file:///tmp/test/seg0-03.m4s complete
[00:59:52.922646][stream.segmented][debug] Closing worker thread
[00:59:52.923078][stream.segmented][debug] Closing writer thread

[00:59:52.923513][cli][info] Stream ended
[00:59:52.923871][cli][info] Closing currently open stream...

# log for HLS playlist for comparison
[01:00:01.271367][cli][debug] OS:         macOS 10.12.6
[01:00:01.271601][cli][debug] Python:     3.9.10
[01:00:01.271713][cli][debug] Streamlink: 3.1.0
[01:00:01.271866][cli][debug] Requests(2.27.1), Socks(1.7.1), Websocket(1.2.3)
[01:00:01.272300][cli][debug] Arguments:
[01:00:01.272396][cli][debug]  url=hls://file:///tmp/test/master.m3u8
[01:00:01.272525][cli][debug]  stream=['best']
[01:00:01.272673][cli][debug]  --loglevel=trace
[01:00:01.272824][cli][debug]  --output=/dev/null
[01:00:01.273216][cli][info] Found matching plugin hls for URL hls://file:///tmp/test/master.m3u8
[01:00:01.273371][plugins.hls][debug] URL=file:///tmp/test/master.m3u8; params={}
[01:00:01.359532][utils.l10n][debug] Language code: en_US
[01:00:01.365674][cli][info] Available streams: 240p (worst, best)
[01:00:01.365858][cli][info] Opening stream: 240p (hls)
[01:00:01.366116][cli][debug] Checking file output
[01:00:01.367035][stream.hls][debug] Reloading playlist
[01:00:01.367991][cli][debug] Pre-buffering 8192 bytes
[01:00:01.380139][stream.hls][debug] First Sequence: 1; Last Sequence: 3
[01:00:01.380287][stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 1; End Sequence: 3
[01:00:01.380366][stream.hls][debug] Adding segment 1 to queue
[01:00:01.381053][stream.hls][debug] Adding segment 2 to queue
[01:00:01.381717][stream.hls][debug] Adding segment 3 to queue
[01:00:01.381872][stream.segmented][debug] Closing worker thread
[01:00:01.382355][stream.hls][debug] Segment initialization 1 complete
[01:00:01.383110][cli][debug] Writing stream to output
[01:00:01.384028][stream.hls][debug] Segment 1 complete
[01:00:01.384196][stream.hls][debug] Segment initialization 2 complete
[01:00:01.385400][stream.hls][debug] Segment 2 complete
[01:00:01.385591][stream.hls][debug] Segment initialization 3 complete
[01:00:01.386479][stream.hls][debug] Segment 3 complete
[01:00:01.386975][stream.segmented][debug] Closing writer thread

[01:00:01.387420][cli][info] Stream ended
[01:00:01.387602][cli][info] Closing currently open stream...
```

**Comment by bastimeyer** [comment] 2022-01-25 18:40
Duplicate of #3137

**Comment by thisisgk** [comment] 2022-01-26 02:24
This doesn't seem to be a duplicate of that issue. I'm not using Windows and this report is not related to stream.ffmpegmux nor utils.named_pipe.

I ran streamlink with options similar to that issue and had no delay in finishing. But changed stream 480p to worst (because of YouTube throttling) and vlc to mpv. (From the output of `youtube-dl -F`, both v 135 for 480p and v 160 for worst are mp4_dash containers so using worst shouldn't make any difference.)
```
$ streamlink -l trace https://www.youtube.com/watch?v=ET9HeSFYlEs worst --stream-type muxed-stream -p mpv -v --player-no-close
```
### Debug log
There is a gap in the time shown in the log, but when the playback is finished and mpv window is closed, streamlink also finishes immediately. '10:49:47' (start writing stream to output) plus '00:04:13' (duration of the stream) gets '10:54:00'.
And, if I quit mpv with 'q' during playback, streamlink will finish immediately as expected.
```
[10:49:45.823986][cli][debug] OS:         macOS 10.12.6
[10:49:45.824211][cli][debug] Python:     3.9.10
[10:49:45.824286][cli][debug] Streamlink: 3.1.0
[10:49:45.824424][cli][debug] Requests(2.27.1), Socks(1.7.1), Websocket(1.2.3)
[10:49:45.824811][cli][debug] Arguments:
[10:49:45.824898][cli][debug]  url=https://www.youtube.com/watch?v=ET9HeSFYlEs
[10:49:45.825062][cli][debug]  stream=['worst']
[10:49:45.825215][cli][debug]  --loglevel=trace
[10:49:45.825351][cli][debug]  --player=mpv
[10:49:45.825487][cli][debug]  --verbose-player=True
[10:49:45.825620][cli][debug]  --player-no-close=True
[10:49:45.825761][cli][debug]  --stream-types=['muxed-stream']
[10:49:45.826159][cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=ET9HeSFYlEs
[10:49:46.309300][plugins.youtube][trace] videoDetails = ('ET9HeSFYlEs', 'Jump Cuts', 'Comedy', 'Ajith fans vs vijay fans - a conclusion', None)
[10:49:46.309481][plugins.youtube][debug] Using video ID: ET9HeSFYlEs
[10:49:46.313456][plugins.youtube][debug] MuxedStream: v 137 a 251 = 1080p
[10:49:46.313610][plugins.youtube][debug] MuxedStream: v 135 a 251 = 480p
[10:49:46.313710][plugins.youtube][debug] MuxedStream: v 133 a 251 = 240p
[10:49:46.313872][plugins.youtube][debug] MuxedStream: v 160 a 251 = 144p
[10:49:46.315920][cli][info] Available streams: 144p (worst), 240p, 480p, 1080p (best)
[10:49:46.316080][cli][info] Opening stream: 144p (muxed-stream)
[10:49:46.316220][cli][info] Starting player: mpv
[10:49:46.316471][stream.ffmpegmux][debug] Opening http substream
[10:49:46.351239][stream.ffmpegmux][debug] Opening http substream
[10:49:46.401414][utils.named_pipe][info] Creating pipe streamlinkpipe-4405-1-3045
[10:49:46.403148][utils.named_pipe][info] Creating pipe streamlinkpipe-4405-2-3335
[10:49:46.403735][stream.ffmpegmux][debug] ffmpeg command: ffmpeg -nostats -y -i /tmp/streamlinkpipe-4405-1-3045 -i /tmp/streamlinkpipe-4405-2-3335 -c:v copy -c:a copy -map 0 -map 1 -f matroska pipe:1
[10:49:46.404102][stream.ffmpegmux][debug] Starting copy to pipe: /tmp/streamlinkpipe-4405-1-3045
[10:49:46.404495][stream.ffmpegmux][debug] Starting copy to pipe: /tmp/streamlinkpipe-4405-2-3335
[10:49:46.412891][cli][debug] Pre-buffering 8192 bytes
[10:49:46.609740][cli.output][debug] Opening subprocess: mpv --force-media-title=https://www.youtube.com/watch?v=ET9HeSFYlEs -
[file] Reading from stdin...
[10:49:47.119582][cli][debug] Writing stream to output
 (+) Video --vid=1 (*) (h264 256x144 23.976fps)
 (+) Audio --aid=1 --alang=eng (*) (opus 2ch 48000Hz)
[vo/gpu] opengl cocoa backend is deprecated, use vo=libmpv instead
AO: [coreaudio] 48000Hz stereo 2ch floatp
VO: [gpu] 256x144 yuv420p
[10:53:44.688544][stream.ffmpegmux][debug] Pipe copy complete: /tmp/streamlinkpipe-4405-1-3045
[10:53:47.487416][stream.ffmpegmux][debug] Pipe copy complete: /tmp/streamlinkpipe-4405-2-3335
[10:53:54.922372][stream.ffmpegmux][debug] Closing ffmpeg thread
[10:53:54.922803][stream.ffmpegmux][debug] Closed all the substreams
[10:53:54.922967][cli][info] Stream ended
AV: 00:04:13 / 00:04:13 (100%) A-V:  0.000

Exiting... (End of file)
[10:54:00.553670][cli][info] Closing currently open stream...
```

**Comment by bastimeyer** [comment] 2022-01-26 02:37
Let me see...

It's possible (or rather likely) that this is caused by the `sleep_until` method call in the `DASHStreamWriter` thread.
- https://github.com/streamlink/streamlink/blame/3.1.1/src/streamlink/stream/dash_manifest.py#L70-L74
- https://github.com/streamlink/streamlink/blame/3.1.1/src/streamlink/stream/dash.py#L36

I haven't been involved with Streamlink's DASH implementation, but I recently rewrote the UStream plugin which was previously using this same method and its own writer thread was stalling because of that.

The writer thread shouldn't call `time.sleep` and should instead wait for a thread-lock to time out which other threads (main thread or worker thread) can set to "cancel" the writer thread. That would solve the issue.

**Comment by bastimeyer** [comment] 2022-01-26 02:43
The `DASHStreamWorker` thread has the same issue, which is probably the main reason here, because there are no "Waiting for segment" log messages in your log output. The worker basically does the same, but with the `sleeper` method.

- https://github.com/streamlink/streamlink/blame/3.1.1/src/streamlink/stream/dash_manifest.py#L61-L67
- https://github.com/streamlink/streamlink/blame/3.1.1/src/streamlink/stream/dash.py#L91

**Closed** 2022-07-02 06:23 UTC
Labels: bug, stream: DASH
