### ISSUE TITLE
cli.utils.progress: relative paths on Windows don't get truncated correctly

### ISSUE THREAD

**Issue by DCxDESIGN** [streamlink/streamlink#4829] opened 2022-09-17 04:54 UTC
### Checklist

- [X] This is a bug report and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

Hello again, I'm the submitter of #4752 and thank you so much for improving it as #4764 said.

But after I updated it to 5.0.0, I found that it doesn't behave as your screen record https://github.com/streamlink/streamlink/pull/4764#issuecomment-1223952285 showed. I recorded some clips in debug / default loglevel in PowerShell / CMD. Here are the clips:

https://user-images.githubusercontent.com/48208459/190840790-f2053d51-9f83-4866-9f24-719364f88352.mp4

https://user-images.githubusercontent.com/48208459/190840793-f376856c-c3d1-4dc4-8399-09e55251035b.mp4

https://user-images.githubusercontent.com/48208459/190840796-1130d9d9-2bc9-4baf-ab16-ada8a905cfcd.mp4

https://user-images.githubusercontent.com/48208459/190840799-b7fb2fca-13ed-45d8-a620-ea5b2fb19e03.mp4

You can see that in Windows it shows either "..." or the full filename and can't show the last strings to fill the row as your record did. And when showing "..." it shows several times a second even in default loglevel.

### Debug log

```text
Please refer to the screen records above.
```

**Comment by bastimeyer** [comment] 2022-09-17 10:43
This is a bug in regards to relative paths on Windows, because Streamlink tries to retain the `drive` part of Python's `WindowsPath` implementation in its progress output. Apparently, the `drive` attribute exists as part of the `parts` property, even if it's unset/empty. I wasn't aware of this, so when a path is relative, it unnecessarily cuts off the first part, which is the file name.

- https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.parts
- https://github.com/streamlink/streamlink/blob/5.0.0/src/streamlink_cli/utils/progress.py#L202-L206

----

Btw, there are new nightly builds available each day, for people on Windows to test and give early feedback before a new release gets published, so they don't have to install a separate Python environment with Streamlink installed from the master branch. I'm saying this because you've opened issues multiple times now after a new release has been published. While this is of course my mistake to not catch this issue while implementing this and closing your previous bug report, early feedback when issues get closed, especially when it involved a bit of effort implementing stuff, would be greatly appreciated, so we can avoid issues like this in new releases.
https://streamlink.github.io/install.html#windows-nightly-builds

**Comment by DCxDESIGN** [comment] 2022-09-17 11:23
> Btw, there are new nightly builds available each day, for people on Windows to test and give early feedback before a new release gets published, so they don't have to install a separate Python environment with Streamlink installed from the master branch. I'm saying this because you've opened issues multiple times now after a new release has been published. While this is of course my mistake to not catch this issue while implementing this and closing your previous bug report, early feedback when issues get closed, especially when it involved a bit of effort implementing stuff, would be greatly appreciated, so we can avoid issues like this in new releases. https://streamlink.github.io/install.html#windows-nightly-builds

I did check for nightly builds in earlier versions, but at that time, only installers can be generated while I used a portable version. So I stopped and only waited for new stable releases. Thank you for your kind reminder and I'm glad that nightly builds now have both installers and portable ones. 

I feel sorry for that and next time I will use nightly builds before submitting new things.

**Closed** 2022-09-17 18:49 UTC
Labels: bug, os: Windows, CLI

**Comment by DCxDESIGN** [comment] 2022-09-18 04:46
> And when showing "..." it shows several times a second even in default loglevel.

I tried the latest nightly build, and it seems that this problem is still existed. I recorded a clip as the following:

https://user-images.githubusercontent.com/48208459/190886072-c4e24bee-181b-4cb9-999c-4696d51f4db3.mp4

As you can see in the clip, when the filename is fully shown, or completely cut off, it behaves normally just like your previous screen record showed. But when the filename is truncated, the output info is being shown at the speed of several lines a second. And this obviously behaves diffrently compared to yours.

By the way, the clip above is recorded at the default log level. I also tried the debug mode and it behaves similarly.

**Comment by bastimeyer** [comment] 2022-09-18 11:52
This is because of your terrible terminal emulator (and operating system), which doesn't clear the output of the last line on resize when the last line contains a carriage-return character (`\r`). Terminal emulators with proper text reflow support (eg. Konsole, Gnome-Terminal, XTerm, etc) don't have this issue.

Usually, ANSI escape codes (VT100 codes) can be used by CLI/TUI applications if the used terminal application supports those codes. This enables being able to clear lines, show colored output and much more. However, support for these codes varies and it's an utter mess, especially on Windows. The previous implementation also didn't support this, and it's not worth spending much time on that. This is nothing that I care about, as it's a totally unimportant edge case. If this is important to someone, then they can open a pull request.

- https://en.wikipedia.org/wiki/List_of_terminal_emulators
- https://en.wikipedia.org/wiki/ANSI_escape_code

**Comment by DCxDESIGN** [comment] 2022-09-18 13:58
I know what you mean and have already realized how terribly Windows and its CLI behaves. So I understand that it might take a lot of work to fully make it act like UNIX-based OS. I will accept it and thank you for your explanation.

I always appreciate what you and your teammates have done and did my best to speak politely (as my foreign language) during the conversation. I also fully understand that Streamlink is a project maintained by a group of warm-hearted volunteers and we the users should never take it for granted. Based on this, could you kindly reduce the frequency of insultation to some certain softwares or tools as people who use them usually have no other choices. Those who made them worth insulted cannot see what you said, while we who saw it can do nothing except feeling sorry and embarrased just because we were foolish to use them and made you feel troubled.

And again, please forgive me if my words were aburpt. Hope you have a nice day.

**Comment by crackerbear** [comment] 2022-09-25 19:42
I've tried with the latest stable 5.0.1 and the latest nightly streamlink-5.0.1-2-gfacf193-py310-x86_64, but I'm still getting a truncated path problem when downloading via streamlink it outputs on a new line instead of the existing one if the console window doesn't fit the full line.

For example:

![cmd](https://user-images.githubusercontent.com/1721661/192162145-3c9c4dd2-28df-4eb6-bbca-9b6b9e690874.PNG)

**Comment by bastimeyer** [comment] 2022-09-25 20:19
> it outputs on a new line instead of the existing one if the console window doesn't fit the full line

I can't reproduce this at all. Post the **exact command you're running**, as well as the **exact environment** (including the terminal width).

The output is working correctly in my W10 VM using

- "Windows Terminal" app using cmd
- "Windows Terminal" app using pwsh
- "Windows Terminal" app using pwsh7
- "Windows Terminal" app using bash
- cmd
- pwsh
- pwsh7
- msys2 terminal using bash (git-for-windows)

The progress output queries the available space via the `shutil` module of Python's stdlib, and the calculation for the string width should be correct ([and is fully tested](https://github.com/streamlink/streamlink/blob/5.0.1/tests/cli/utils/test_progress.py)). The only difference on Windows is that the available space needs to be [reduced by one character](https://github.com/streamlink/streamlink/blob/5.0.1/src/streamlink_cli/utils/progress.py#L85-L90).

**Comment by crackerbear** [comment] 2022-09-25 21:19
The command I used above is:
`streamlink.exe --hls-live-restart --twitch-disable-ads -o D:\longnametruncatedtestlongnametruncatedtestlongnametruncatedtestlongnametruncatedtestlongnametruncatedtest.mkv https://www.twitch.tv/puppyrescuestream best`

```
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.10.7
[cli][debug] Streamlink: 5.0.1+2.gfacf193
[cli][debug] Dependencies:
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.1
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.15.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.28.1
[cli][debug]  websocket-client: 1.4.1
```

![cmdproperties](https://user-images.githubusercontent.com/1721661/192165751-9dae65e6-e004-4bd0-96d7-e25fa99e67c1.png)

On further testing it appears to be a font issue. Of the fonts that I can choose, the repeating new line output occurs with MS Gothic and NSimSun, but not with Consolas, Courier New and Lucida Console.

I switched to NSimSun as the default font Consolas and other available fonts don't support Asian characters in the console.

It's strange this behaviour didn't occur to streamlink versions prior to v5.

**Comment by bastimeyer** [comment] 2022-09-25 21:53
> It's strange this behaviour didn't occur to streamlink versions prior to v5.

4.3.0 introduced a completely new progress output implementation that's running in a secondary thread, for better continuous outputs that don't depend on the stream iterator's output (which doesn't work in fixed time intervals and can stall the output by a lot if there's no download activity for example). The old implementation also had a static output format with a fixed length for the output path that was not useful. Since the resolved output path was added as a log message in 3.2.0, I decided to remove the output path in the new implementation.

The decision of removing the output path however got a complaint for usecases when monitoring multiple running download processes, which kind of made sense, so I decided to re-implement the output format again and made it so that the output path's max length gets calculated dynamically on each output tick. This means that the output path will always try to take as much space as possible, to show as much information as possible.

In regards to the "print-inplace" logic via the carriage-return character, or the calculation of CJK character widths, nothing has changed between all these re-implementations. The output lengths are caluclated correctly, even with the special case on Windows where the available space has to be reduced by one character.

> On further testing it appears to be a font issue.

The issue however is that your [old, outdated and deprecated](https://devblogs.microsoft.com/commandline/windows-terminal-as-your-default-command-line-experience/) terminal emulator is calculating incorrect character widths, and this breaks Streamlink's implementation, which is based on characters and not on rendered text output. The carriage-return character at the beginning of the line gets ignored because the line "overflows" in these old terminal emulators, even though you can't see it because of that last character at the end of the line, and that's why every tick of the output prints a new line.

The "new" "Windows Terminal" app doesn't have this problem when choosing cmd as the shell and setting MS Gothic as font (why would you even choose this when there are at least 1000 better fonts with full CJK support?).

**So all I can tell you is to use a modern terminal emulator.**

This bug can't be fixed, because there's no way for Streamlink to detect the font in the `cmd` or `pwsh` terminal emulator (there's no distinction on Windows between a command line shell and a terminal emulator). And having an implementation with special exceptions based on specific fonts on specific OSes while using specific terminal emulators doesn't make any sense anyway.

**Comment by crackerbear** [comment] 2022-09-25 22:10
I am by no means a programmer of any sort, so I won't claim to understand the logistics and how the calculations are made, but would making it on Windows to where the available space is always reduced by 2 characters fix the issue?

Although I understand this goes against your initial philosophy of displaying as much information as possible.

And yes MS Gothic is an awful font, which is why I never use it, but thankfully NSimSun is actually readable.

**Comment by bastimeyer** [comment] 2022-09-25 22:24
> would making it on Windows to where the available space is always reduced by 2 characters fix the issue?

Maybe, at least it does when having simple paths in the progress output. But there's a reason why there's a different width calculation, and that is because of the characters being displayed by the terminal emulator. If the path contains certain characters which are also displayed incorrectly, then more than 2 characters would need to be removed from the overall available width. At least that's what I'm thinking.

You can experiment with this if you want and change the `gap` class attribute value in the `streamlink_cli/utils/progress.py` file:
https://github.com/streamlink/streamlink/blob/5.0.1/src/streamlink_cli/utils/progress.py#L85-L90

If you can convince me that a gap of 2 is working reliably, then we can change it, as a compromise.

**Comment by crackerbear** [comment] 2022-09-25 22:33
I have no clue how to compile things from source so unfortunately I'll have to pass on your offer, or at least until either hopefully someone else steps in to test or I learn how to compile myself, which may take a while.

Thanks for taking the time to look into this either way.

**Comment by bastimeyer** [comment] 2022-09-25 22:37
Python is an interpreted language. You just need to change the file's contents. Any bytecode that was compiled for the old file contents (this is just an accelerator thing) will get replaced, since the file's hash and filesystem modification time have changed.

**Comment by gravyboat** [comment] 2022-09-26 01:27
> If you can convince me that a gap of 2 is working reliably, then we can change it, as a compromise.

@bastimeyer I don't want us to make this concession. The new terminal (or powershell) app has been around for at least.. 2 years I think? There's no reason for us to support something that should have been updated along with other operating system patches.
