### ISSUE TITLE
Schoolism Plugin Error with newer streams

### ISSUE THREAD

**Issue by dinorahcorella** [streamlink/streamlink#2950] opened 2020-05-06 00:00 UTC
## Plugin Issue

- [ X] This is a plugin issue and I have read the contribution guidelines.

### Description
The plugin is working with older streams but not working with newer streams like "Deconstructed: Drawing People"

Description

Schoolism plugin doesnt work with the following

Deconstructed: Drawing People

I'm using streamlink 1.4.1 latest installation

### Reproduction steps / Explicit stream URLs to test

1. ... Using Username and password the plugin logs in correctly
2. ... Accessing the path of the course either to stream or to output doesn't work https://www.schoolism.com/watchLesson.php?type=st&id=596
3. ... It throws the following error "Unable to parse JSON" (see log)

### Log output

```
Using the log i get the following:

C:\Users\PC>streamlink -l debug "https://www.schoolism.com/watchLesson.php?type=
st&id=596" --schoolism-email --schoolism-password --schoolism-part 1
[cli][debug] OS: Windows 7
[cli][debug] Python: 3.6.6
[cli][debug] Streamlink: 1.4.1
[cli][debug] Requests(2.23.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin schoolism for URL https://www.schoolism.com/wa
tchLesson.php?type=st&id=596
[cli][debug] Plugin specific arguments:
[cli][debug] --schoolism-email= (email)
[cli][debug] --schoolism-password= (password)
[cli][debug] --schoolism-part=1 (part)
[plugin.schoolism][debug] Logged in to Schoolism as
error: Unable to parse JSON: Expecting ',' delimiter: line 1 column 1053 (char 1
052) ('[{"sources":[{"type":"application/ ...)
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by iamVab** [comment] 2020-05-20 13:45
I can confirm that this is happening on my end as well. I've tested old and new courses URLs and it only happens to this course: "Deconstructed: Drawing People with Viktor Kalvachev"

### Log output
```
> C:\Users\Test\Lesson 1 - Crosshatching\Lesson>streamlink --schoolism-email email --schoolism-password password --schoolism-part 1 -o "1.mp4" "https://www.schoolism.com/watchLesson.php?type=st&id=593" best
> [cli][info] Found matching plugin schoolism for URL https://www.schoolism.com/watchLesson.php?type=st&id=593
> error: Unable to parse JSON: Expecting ',' delimiter: line 1 column 1053 (char 1052) ('[{"sources":[{"type":"application/ ...)
```

Do let me know if I'm not supposed to post here, just wanted to highlight the issue.

**Comment by mkbloke** [comment] 2020-09-28 17:54
I'd like to try and fix this, but I don't have an account.  I presume it would also be necessary to have a subscription to see this content.  It's possible it could be fixed with help from one or both of you though.

Initially, if you could visit a working video page, right click, select view source, then copy and paste the HTML here (formatted nicely with the GH markup, please), then repeat that on the non-working URL you have identified, then I can perhaps use that to make a fix.

I note that the plugin uses a User-Agent string for Safari 8, so it's hard to know if the output will differ enough in other browsers that it matters, but hopefully not.  Cheers.

**Comment by back-to** [comment] 2020-12-03 16:58
basically https://github.com/streamlink/streamlink/issues/1683#issuecomment-397264747

**Comment by tianwang95** [comment] 2020-12-16 03:45
I had the same problem so I looked into this issue and found the bug on line 18 in the [schoolism plugin](https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/schoolism.py)

Line 18:
```js_to_json = partial(re.compile(r'(?!<")(\w+):(?!/)').sub, r'"\1":')```

Basically a regex sub is used to transform a raw javascript object into python parsable JSON. This breaks for this video because the javascript object in question looks like
```{title: "Deconstructed: Drawing People"}```
which then gets transformed into
```{"title": ""Deconstructed": Drawing People"}```
since the colon inside the string is tripping up the pattern.

Regex patterns can't be created to fix this since the underlying data is nesting. So you need a slightly beefier implementation like [hjson](https://github.com/hjson/hjson) to do this correctly.

Personally I don't know much about the streamlink codebase so maybe this is an issue that's been fixed before in a different plugin?

**Comment by mkbloke** [comment] 2020-12-16 14:43
@tianwang95, many thanks for finding that.  Here's a band-aid fix for it:

https://raw.githubusercontent.com/mkbloke/streamlink/schoolism/src/streamlink/plugins/schoolism.py

If you could test that against the problem course and just verify the plugin is working as usual for other courses, it would be much appreciated, thank you.

**Comment by tianwang95** [comment] 2020-12-17 22:25
@mkbloke Thanks for writing up that up! I tested it but it had a tiny bug (caused by me not providing the most accurate js object in my previous post)

If you update the line with the new regex pattern `fix_colon_in_title` to:
`fix_colon_in_title = partial(re.compile(r'"title":""(.*?)":(.*?)"').sub, r'"title":"\1:\2"')`
then it should work. All I did was fix a spacing issue and make sure the quantifiers were lazy as opposed to greedy.

For refrence the full (buggy) json object looks like:
[buggy_json.txt](https://github.com/streamlink/streamlink/files/5712454/buggy_json.txt)

**Comment by bastimeyer** [comment] 2020-12-18 13:10
> Regex patterns can't be created to fix this since the underlying data is nesting.

The only proper fix would be adding a JS parser and walking the generated AST. The regexes are just simple workarounds. Streamlink will add a JS parser dependency eventually, but for now, regexes have to do the dirty job here.

@tianwang95 
Could you please post the full input string and not the incorrect JSON output, so I can have a look?

> `.*?`

A greedy regex quantifier would capture too much, as there are multiple similar title properties.

**Comment by mkbloke** [comment] 2020-12-18 13:36
I've made a second attempt at fixing this based on @tianwang95's feedback and the data provided:

https://raw.githubusercontent.com/mkbloke/streamlink/schoolism/src/streamlink/plugins/schoolism.py

Thanks.

**Comment by bastimeyer** [comment] 2020-12-18 13:49
Please open a PR with your changes, @mkbloke, this looks fine. .

```py
input = '[{"title":""foo":bar"},{"title":""FOO":BAR"},{"title":""f00":b4r"}]'

re.compile(r'"title":""(.*)":(.*)"').sub(r'"title":"\1:\2"', input)
'[{"title":"foo":bar"},{"title":""FOO":BAR"},{"title":""f00:b4r"}]'

re.compile(r'"title":""(.*?)":(.*?)"').sub(r'"title":"\1:\2"', input)
'[{"title":"foo:bar"},{"title":"FOO:BAR"},{"title":"f00:b4r"}]'
```

**Closed** 2020-12-18 14:50 UTC
Labels: plugin issue, restriction: account needed

**Comment by tianwang95** [comment] 2020-12-18 18:13
@bastimeyer Here's the raw JS:

[js_output.txt](https://github.com/streamlink/streamlink/files/5717379/js_output.txt)
