### ISSUE TITLE
[youtube] error 429 Client Error: Unable to open URL

### ISSUE THREAD

**Issue by jjsly11** [streamlink/streamlink#2979] opened 2020-05-15 22:34 UTC
Thanks for reading this , one of my pc is report error 429 ,and another pc is ok, please help me !
log:
streamlink https://www.youtube.com/watch?v=MJDrNi6fJbw best                            
[cli][info] streamlink is running as root! Be careful!
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=MJDrNi6fJbw
error: Unable to open URL: https://youtube.com/get_video_info (429 Client Error: unknown for url: https://youtube.com/get_video_info?video_id=MJDrNi6fJbw&el=detailpage)

I used another pc is ok
streamlink https://www.youtube.com/watch?v=MJDrNi6fJbw best
[cli][info] streamlink is running as root! Be careful!
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=MJDrNi6fJbw
[cli][info] Available streams: 144p (worst), 240p, 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (hls)

**Comment by mkbloke** [comment] 2020-05-15 23:02
You should post logs with '-l debug' output.  As back-to mentioned in the previously closed issue (#2978), this is not reproducible.  The link you are using also works fine for me too.

**Comment by gravyboat** [comment] 2020-05-15 23:36
This is just a duplicate of https://github.com/streamlink/streamlink/issues/2978, @jjsly11 this is your one and only warning, I'm closing this and locking it. If I see you post the same thing again trying to bypass what you were already told (that your IP is banned by Youtube) or see you commenting in another issue with this, I'm banning you from being able to view the Streamlink project at all. We can't do anything about this, stop abusing Youtube's servers.

**Closed by gravyboat** 2020-05-15 23:36 UTC
Labels: duplicate
