### ISSUE TITLE
Vaughnlive plugin not working

### ISSUE THREAD

**Issue by bebetoalves** [streamlink/streamlink#1204] opened 2017-09-07 11:46 UTC
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*
*Also check the list of known issues before reporting an issue!*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

I can't watch any stream, all present the same error:

C:\>streamlink https://vaughnlive.tv/sherming99
[cli][info] Found matching plugin vaughnlive for URL https://vaughnlive.tv/sherming99
error: Unable to open URL: https://vaughnlive.tv/sherming99 (405 Client Error: Not Allowed for url: https://vaughnlive.tv/sherming99)

### Expected / Actual behavior

...

### Reproduction steps / Explicit stream URLs to test

1. https://vaughnlive.tv/sherming99
2. https://vaughnlive.tv/sherming3
3. ...

### Environment details

Operating system and version: Windows 7 Ultimate X64
Streamlink and Python version: Lastest streamlink version & Python 2.7

### Comments, logs, screenshots, etc.

Screenshot: http://i.imgur.com/Bspeyfg.png

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment] 2017-09-07 17:41
Duplicate of https://github.com/streamlink/streamlink/issues/1187

**Closed by gravyboat** 2017-09-07 17:41 UTC
