### ISSUE TITLE
twitch: No Author Detection

### ISSUE THREAD

**Issue by drag0n141** [streamlink/streamlink#5179] opened 2023-02-18 07:45 UTC
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

It happens sometimes, that streamlink does not detect the output attributes. I name my files like that.

{author}/{author} - {time:%Y%m%d_%H-%M} - {id} - {title}.mkv

But the output is then "- 20230217_16-13 -  -.mkv"

### Debug log

```text
Dont have Debug log at the moment because the Problem is not persistent.
```

**Comment by bastimeyer** [comment] 2023-02-18 09:06
Duplicate of #4783 and #4411
It's a Twitch issue, and we won't implement a workaround for that. Check and wait until metadata becomes available via `--json`.

**Closed by bastimeyer** 2023-02-18 09:06 UTC
Labels: plugin issue
