### ISSUE TITLE
nownews: random dropout after a period of time 

### ISSUE THREAD

**Issue by fhoshino** [streamlink/streamlink#2830] opened 2020-03-16 06:34 UTC
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

Random dropout after streaming for a period of time (not fixed)

### Log output
streamlink https://news.now.com/home/live best
[cli][info] Found matching plugin nownews for URL https://news.now.com/home/live
[cli][info] Available streams: 270p (worst), 360p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (hls-multi)
[cli][info] Starting player: "C:\TOOLS\mpv\mpv.exe" --cache 8192
Exception in thread Thread-HLSStreamWriter:
Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\stream\segmented.py", line 167, in run
    self.write(segment, result)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\stream\hls.py", line 140, in write
    self.reader.buffer.write(pkcs7_decode(decrypted_chunk))
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\stream\hls.py", line 31, in pkcs7_decode
    raise StreamError("Input is not padded or padding is corrupt, got padding size of {0}".format(val))
streamlink.exceptions.StreamError: Input is not padded or padding is corrupt, got padding size of 112
 
[stream.ffmpegmux][error] Pipe copy aborted: \\.\pipe\ffmpeg-3300-573

**Comment by back-to** [comment] 2020-03-16 16:51
> Random dropout after streaming for a period of time (not fixed)

hours or days?

**Comment by fhoshino** [comment] 2020-03-16 17:19
> > Random dropout after streaming for a period of time (not fixed)
> 
> hours or days?

shortest half an hour, longest 4 to 5 hours

**Comment by back-to** [comment] 2020-04-04 11:31
> Input is not padded or padding is corrupt, got padding size of

to difficult to reproduce

Duplicate of https://github.com/streamlink/streamlink/issues/2365

**Closed by back-to** 2020-04-04 11:31 UTC
Labels: duplicate
