### ISSUE TITLE
[Plugin Request] MTV.com 

### ISSUE THREAD

**Issue by MediaJunkie1** [streamlink/streamlink#1779] opened 2018-06-12 02:39 UTC
### Checklist

- [] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

I believe it would be a quality addition to add a plugin for MTV (http://www.mtv.com/live-tv) so users would be able to quickly and easily dvr their live shows.  Not only from MTV, but many other services.  (There's 16+ I can think of that use the same url structuring.)

Currently there is compatibility via the hlsvariant:// protocol, however the user needs to get the stream url manually and you cannot record to a dvr automatically on a schedule. 

### Expected / Actual behavior

Pass provider + username/password, or cookie, to generic authentication service to generate and play/download m3u8 from mtv.com/live-tv (and many other services).

Thank you for your consideration.

**Comment by bastimeyer** [comment] 2018-06-12 04:30
Duplicate of #336.

**Comment by gravyboat** [comment] 2018-06-12 05:32
I'm going to close this one out since it's a duplicate. @MediaJunkie1 We've discussed this a bit here: https://github.com/streamlink/streamlink/issues/1656#issuecomment-389319380 and why we aren't supporting it. Thanks for making a thorough issue!

**Closed by gravyboat** 2018-06-12 05:32 UTC
Labels: duplicate

**Comment by MediaJunkie1** [comment] 2018-06-13 13:47
Hi Gravy Boat.  Thank's for addressing.

I understand this is off-topic for streamlink, however perhaps you could provide some guidance on how I may begin to fix this issue.

Youtube-dl work around seems to not support live stream on these websites , only VOD.   When attempting to use the live stream url (ex. mtv.com/live-tv), the script just dumps the entire page html in to a file. 

I've watched how the VOD retrevial works with youtube-dl and it seems pretty similar to how one would fetch a LIVE video url, however the script has no mention of the live-tv url, only url structure for vods.    Should I be able to just add in the mtv.com/live-tv as a test url?

**Comment by MediaJunkie1** [comment] 2018-06-16 01:08
Thanks Gravyboat.   :)
