### ISSUE TITLE
Using Streamlink for Twitch live with time offset

### ISSUE THREAD

**Issue by GordonH133** [streamlink/streamlink#1604] opened 2018-04-14 11:24 UTC
- [ ] This is a bug report.
- [x] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

In Command-Line Interface introduction https://streamlink.github.io/cli.html 
It have option: --hls-start-offset HH:MM:SS
Amount of time to skip from the beginning of the stream. For live streams, this is a negative offset from the end of the stream.
I try to use this feature for Twitch live, with offset negative for make HLS start from live begining
But It always show the current live timestamp.

### Reproduction steps / Explicit stream URLs to test

1.
use command
streamlink.exe https://www.twitch.tv/lck1 worst --hls-start-offset="-01:01:01"
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/lck1
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p (best)
[cli][info] Starting player: "C:\Program Files (x86)\VideoLAN\VLC\vlc.exe" --fil
e-caching=5000
[cli][info] Got HTTP request from VLC/3.0.0 LibVLC/3.0.0

Or is there any way for watch Twitch live from the begining?

**Comment by bastimeyer** [comment] 2018-04-14 11:31
Duplicate of #1580
See https://github.com/streamlink/streamlink/issues/1580#issuecomment-376674943

> Or is there any way for watch Twitch live from the begining?

No, you have to use the VOD URL

**Closed by bastimeyer** 2018-04-14 11:31 UTC
