### ISSUE TITLE
BFMTV

### ISSUE THREAD

**Issue by campones** [streamlink/streamlink#2461] opened 2019-05-07 21:51 UTC
Hello, this doesn't seems to be working.

## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

streamlink --loglevel debug https://www.bfmtv.com/mediaplayer/live-video/
[cli][info] streamlink is running as root! Be careful!
[cli][debug] OS:         Linux-3.13.0-168-generic-x86_64-with-Ubuntu-14.04-trusty
[cli][debug] Python:     2.7.6
[cli][debug] Streamlink: 1.0.0+34.ge96c725
[cli][debug] Requests(2.21.0), Socks(1.6.7), Websocket(0.44.0)
[cli][info] Found matching plugin bfmtv for URL https://www.bfmtv.com/mediaplayer/live-video/
error: No playable streams found on this URL: https://www.bfmtv.com/mediaplayer/live-video/

**Comment by campones** [comment] 2019-05-07 22:42
it's weird because it works for https://rmcdecouverte.bfmtv.com/mediaplayer-direct/

**Comment by back-to** [comment] 2019-05-11 07:25
works for me
```
$ streamlink https://www.bfmtv.com/mediaplayer/live-video/
[cli][debug] OS:         Linux-5.0.0-13-generic-x86_64-with-Ubuntu-19.04-disco
[cli][debug] Python:     3.7.3
[cli][debug] Streamlink: 1.1.1+20.gc8ed1da
[cli][debug] Requests(2.21.0), Socks(1.6.7), Websocket(0.56.0)
[cli][info] Found matching plugin bfmtv for URL https://www.bfmtv.com/mediaplayer/live-video/
[plugins.brightcove][debug] Creating player for account 876450610001 (player_id=default_default)
[plugins.brightcove][debug] Finding streams for video: 5615950982001
[plugins.brightcove][debug] Found policy key: XXX
[utils.l10n][debug] Language code: de_DE
[cli][info] Available streams: 180p (worst), 480p, 720p (best)
[cli][info] Opening stream: 720p (hls)
```

**Comment by uNouss** [comment] 2019-05-11 07:51
@back-to @campones I encounter the same issue
```bash
$ streamlink --loglevel debug https://www.bfmtv.com/mediaplayer/live-video/
[cli][debug] OS:         Linux-5.0.0-13-generic-x86_64-with-Ubuntu-19.04-disco
[cli][debug] Python:     3.7.3
[cli][debug] Streamlink: 1.1.1
[cli][debug] Requests(2.21.0), Socks(1.6.7), Websocket(0.56.0)
[cli][info] Found matching plugin bfmtv for URL https://www.bfmtv.com/mediaplayer/live-video/
error: No playable streams found on this URL: https://www.bfmtv.com/mediaplayer/live-video/
```

**Comment by back-to** [comment] 2019-05-11 07:58
the issue is already fixed in https://github.com/streamlink/streamlink/pull/2394

you will need to use the **dev version of Streamlink** or wait for a new version.

**Closed by back-to** 2019-05-11 07:58 UTC
Labels: plugin issue, solved

**Comment by campones** [comment] 2019-05-13 11:37
Thank you.
