### ISSUE TITLE
afreeca.py was broken ,help!([cli][error] Try 1/1: Could not open stream <HLSStream(')

### ISSUE THREAD

**Issue by jjsly11** [streamlink/streamlink#2951] opened 2020-05-06 12:26 UTC
## Issue

- [ ] This is not a bug report, feature request, or plugin issue/request.
- [ ] I have read the contribution guidelines.

### Reproduction steps / Explicit stream URLs to test

1. ...
2. ...
3. ...

### Logs

```
REPLACE THIS TEXT WITH THE LOG OUTPUT
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by jjsly11** [comment] 2020-05-06 12:57
Description
when i use streamlink http://play.afreecatv.com/rlaxordyd/223466791 best
report error:
Could not open stream <HLSStream(

Expected / Actual behavior
Reproduction steps / Explicit stream URLs to test

Logs:

root@iZt4nbvvjcih5qdol5bvwlZ:/tools# streamlink http://play.afreecatv.com/rlaxordyd/223466791 best 
Failed to load plugin dlive:
  File "/usr/lib/python3.5/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/streamlink/plugins/dlive.py", line 5, in <module>
    from streamlink.compat import unquote_plus, is_py3
ImportError: cannot import name 'unquote_plus'

Failed to load plugin facebook:
  File "/usr/lib/python3.5/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/streamlink/plugins/facebook.py", line 4, in <module>
    from streamlink.compat import bytes, is_py3, unquote_plus, urlencode
ImportError: cannot import name 'unquote_plus'

Failed to load plugin nicolive:
  File "/usr/lib/python3.5/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/streamlink/plugins/nicolive.py", line 11, in <module>
    from streamlink.compat import urlparse, unquote_plus
ImportError: cannot import name 'unquote_plus'

Failed to load plugin twitcasting:
  File "/usr/lib/python3.5/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/streamlink/plugins/twitcasting.py", line 7, in <module>
    from streamlink.compat import urlparse, unquote_plus
ImportError: cannot import name 'unquote_plus'

Failed to load plugin ustreamtv:
  File "/usr/lib/python3.5/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/streamlink/plugins/ustreamtv.py", line 14, in <module>
    from streamlink.compat import range, urljoin, urlunparse, urlparse, unquote_plus
ImportError: cannot import name 'unquote_plus'

Failed to load plugin ustvnow:
  File "/usr/lib/python3.5/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/streamlink/plugins/ustvnow.py", line 12, in <module>
    from Crypto.Util.Padding import pad, unpad
ImportError: No module named 'Crypto.Util.Padding'

Failed to load plugin wwenetwork:
  File "/usr/lib/python3.5/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/streamlink/plugins/wwenetwork.py", line 13, in <module>
    from streamlink.utils.times import seconds_to_hhmmss
ImportError: cannot import name 'seconds_to_hhmmss'

[cli][info] streamlink is running as root! Be careful!
[cli][info] Found matching plugin afreeca for URL http://play.afreecatv.com/rlaxordyd/223466791
[cli][info] Available streams: sd (worst), hd, original (best)
[cli][info] Opening stream: original (hls)
[cli][error] Try 1/1: Could not open stream <HLSStream('http://live-hls-local-cf.afreecatv.com/ko-livestream-13/auth_playlist.m3u8?aid=.A32.7bbT56vyHM9fKZk.PnZKyHdxbKZxQwPeVSz2mn_NYZQ-D2dqhFjs88JRqIkzLA77O7GtXdPfbkH_4_BsicOmfOqqe1UR8STDIjKG6fzWqepx7KGvKO57eQqkmeM')> (Could not open stream: Unable to open URL: http://live-hls-local-cf.afreecatv.com/ko-livestream-13/auth_playlist.m3u8?aid=.A32.7bbT56vyHM9fKZk.PnZKyHdxbKZxQwPeVSz2mn_NYZQ-D2dqhFjs88JRqIkzLA77O7GtXdPfbkH_4_BsicOmfOqqe1UR8STDIjKG6fzWqepx7KGvKO57eQqkmeM (403 Client Error: Forbidden for url: http://live-hls-local-cf.afreecatv.com/ko-livestream-13/auth_playlist.m3u8?aid=.A32.7bbT56vyHM9fKZk.PnZKyHdxbKZxQwPeVSz2mn_NYZQ-D2dqhFjs88JRqIkzLA77O7GtXdPfbkH_4_BsicOmfOqqe1UR8STDIjKG6fzWqepx7KGvKO57eQqkmeM&aid=.A32.7bbT56vyHM9fKZk.PnZKyHdxbKZxQwPeVSz2mn_NYZQ-D2dqhFjs88JRqIkzLA77O7GtXdPfbkH_4_BsicOmfOqqe1UR8STDIjKG6fzWqepx7KGvKO57eQqkmeM))
error: Could not open stream <HLSStream('http://live-hls-local-cf.afreecatv.com/ko-livestream-13/auth_playlist.m3u8?aid=.A32.7bbT56vyHM9fKZk.PnZKyHdxbKZxQwPeVSz2mn_NYZQ-D2dqhFjs88JRqIkzLA77O7GtXdPfbkH_4_BsicOmfOqqe1UR8STDIjKG6fzWqepx7KGvKO57eQqkmeM')>, tried 1 times, exiting

**Comment by bastimeyer** [comment] 2020-05-06 13:02
> 403 Client Error: Forbidden for url

Duplicate of #2850, #2874 and #2917.

Use the **latest** version of Streamlink, which is currently `1.4.1`.
https://streamlink.github.io/install.html

**Closed by bastimeyer** 2020-05-06 13:02 UTC
