### ISSUE TITLE
Bug when using batch file with variable in the name of output file.

### ISSUE THREAD

**Issue by mikhoul** [streamlink/streamlink#712] opened 2017-03-17 18:23 UTC
----

### Checklist

- [x] This is a bug report.

### Description

I use a .bat file to start recording and when Streamlink try to open the output file it throw an error: "

` ([Errno 2] No such file or directory: 'TVA_TopModeles_17/03/2017_13.59.42.ts')`

Here's the script I use: 

```
wget -q http://racacaxtv.ga/tva.php?token=ece27dec6af929f4aa52f2347056434d7de0f729 -O  tva.txt

set url=
for /F "delims=" %%i in (tva.txt) do set url=%%i

del tva.txt

streamlink.exe "hlsvariant://%url%" best -f -o TVA_TopModeles_%date%_%time:~0,2%.%time:~3,2%.%time:~6,2%.ts 
```

If I change the name of the output file to a name without variable like "**miketest**" it work fine:

```
wget -q http://racacaxtv.ga/tva.php?token=ece27dec6af929f4aa52f2347056434d7de0f729 -O  tva.txt it work fine.

set url=
for /F "delims=" %%i in (tva.txt) do set url=%%i

echo %url%

del tva.txt

streamlink.exe "hlsvariant://%url%" best -f -o testMike.ts 
```

The error `([Errno 2] No such file or directory` come from the Python script.

Here's the full output of my CMD console with that failed result and the next that work:

```
H:\Telechargement>miketest

H:\Telechargement>wget -q http://racacaxtv.ga/tva.php?token=ece27dec6af929f4aa52f2347056434d7de0f729 -O  tva.txt

H:\Telechargement>set url=

H:\Telechargement>for /F "delims=" %i in (tva.txt) do set url=%i

H:\Telechargement>set url=http://chaine_tva_uls-lh.akamaihd.net/i/tvago_1@410563/master.m3u8?hdnea=st=1489773585~exp=1489773675~acl=/i/tvago_1@410563/*~hmac=76997854c44efb786af71e89b32c6fe36943effbea42b61f3300b76c33d64052

H:\Telechargement>echo http://chaine_tva_uls-lh.akamaihd.net/i/tvago_1@410563/master.m3u8?hdnea=st=1489773585~exp=1489773675~acl=/i/tvago_1@410563/*~hmac=76997854c44efb786af71e89b32c6fe36943effbea42b61f3300b76c33d64052
http://chaine_tva_uls-lh.akamaihd.net/i/tvago_1@410563/master.m3u8?hdnea=st=1489773585~exp=1489773675~acl=/i/tvago_1@410563/*~hmac=76997854c44efb786af71e89b32c6fe36943effbea42b61f3300b76c33d64052

H:\Telechargement>del tva.txt

H:\Telechargement>REM pause

H:\Telechargement>streamlink.exe "hlsvariant://http://chaine_tva_uls-lh.akamaihd.net/i/tvago_1@410563/master.m3u8?hdnea=st=1489773585~exp=1489773675~acl=/i/tvago_1@410563/*~hmac=76997854c44efb786af71e89b32c6fe36943effbea42b61f3300b76c33d64052" best -f -o TVA_TopModeles_17/03/2017_13.59.42.ts
[cli][info] Found matching plugin stream for URL hlsvariant://http://chaine_tva_uls-lh.akamaihd.net/i/tvago_1@410563/master.m3u8?hdnea=st=1489773585~exp=1489773675~acl=/i/tvago_1@410563/*~hmac=76997854c44efb786af71e89b32c6fe36943effbea42b61f3300b76c33d64052
[cli][info] Available streams: 180p_alt, 360p_alt, 64k_alt, 64k (worst), 180p, 360p, 720p (best)
[cli][info] Opening stream: 720p (hls)
error: Failed to open output: TVA_TopModeles_17/03/2017_13.59.42.ts ([Errno 2] No such file or directory: 'TVA_TopModeles_17/03/2017_13.59.42.ts')
[cli][info] Closing currently open stream...

H:\Telechargement>miketest

H:\Telechargement>wget -q http://racacaxtv.ga/tva.php?token=ece27dec6af929f4aa52f2347056434d7de0f729 -O  tva.txt

H:\Telechargement>set url=

H:\Telechargement>for /F "delims=" %i in (tva.txt) do set url=%i

H:\Telechargement>set url=http://chaine_tva_uls-lh.akamaihd.net/i/tvago_1@410563/master.m3u8?hdnea=st=1489773621~exp=1489773711~acl=/i/tvago_1@410563/*~hmac=0b03203a6816288c230629353f83ab01a11e26dcc3018efad7025014b08b3e0b

H:\Telechargement>echo http://chaine_tva_uls-lh.akamaihd.net/i/tvago_1@410563/master.m3u8?hdnea=st=1489773621~exp=1489773711~acl=/i/tvago_1@410563/*~hmac=0b03203a6816288c230629353f83ab01a11e26dcc3018efad7025014b08b3e0b
http://chaine_tva_uls-lh.akamaihd.net/i/tvago_1@410563/master.m3u8?hdnea=st=1489773621~exp=1489773711~acl=/i/tvago_1@410563/*~hmac=0b03203a6816288c230629353f83ab01a11e26dcc3018efad7025014b08b3e0b

H:\Telechargement>del tva.txt

H:\Telechargement>REM pause

H:\Telechargement>streamlink.exe "hlsvariant://http://chaine_tva_uls-lh.akamaihd.net/i/tvago_1@410563/master.m3u8?hdnea=st=1489773621~exp=1489773711~acl=/i/tvago_1@410563/*~hmac=0b03203a6816288c230629353f83ab01a11e26dcc3018efad7025014b08b3e0b" best -f -o testMike.ts
[cli][info] Found matching plugin stream for URL hlsvariant://http://chaine_tva_uls-lh.akamaihd.net/i/tvago_1@410563/master.m3u8?hdnea=st=1489773621~exp=1489773711~acl=/i/tvago_1@410563/*~hmac=0b03203a6816288c230629353f83ab01a11e26dcc3018efad7025014b08b3e0b
[cli][info] Available streams: 360p_alt, 180p_alt, 64k_alt, 64k (worst), 180p, 360p, 720p (best)
[cli][info] Opening stream: 720p (hls)
[download][testMike.ts] Written 3.0 MB (19s @ 156.6 KB/s)
H:\Telechargement>
```
### Expected / Actual behavior

Just open the file and write the stream without error.

### Environment details (operating system, python version, etc.)
Streamlink 0.4.0 under Windows 7/64

Regards :octocat: 

**N.B.:** If you are not in Canada use the `--http-header "X-Forwarded-For=207.179.146.70"` with **Streamlink** to bypass the geo location protection mechanism.

**Comment by gravyboat** [comment] 2017-03-17 18:35
Seems like it could be an issue with the `/` interpretation, what happens if you wrap the output file in quotes?

**Comment by bastimeyer** [comment] 2017-03-17 18:35
I haven't tested any of the parameters you've posted, but from a quick glimpse it looks like the error is caused by the date format you're using. Forward slashes are being interpreted as directory separators. Try using the ISO8601 format.

**Comment by mikhoul** [comment] 2017-03-17 20:02
@gravyboat @bastimeyer  Thanks !

You were right, I was pretty sure to have changed it but I overlooked it when I pasted my code :smile_cat: 


Regards :octocat:

**Comment by gravyboat** [comment] 2017-03-17 20:11
Good stuff! I'm going to close this one out.

**Closed by gravyboat** 2017-03-17 20:11 UTC
