### ISSUE TITLE
Download Livestreams encrypted even if protected with DRM

### ISSUE THREAD

**Issue by VfxCristi4no** [streamlink/streamlink#5315] opened 2023-04-29 00:10 UTC
### Checklist

- [X] This is a feature request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Description

Hello, 
please add a feature as an argument that does download mpd's as well even if proctected with DRM
I don't know the program well so please let me know if anyone knows an argument that lets you directly download when you using key.

Thanks.

**Comment by bastimeyer** [comment] 2023-04-29 02:02
Duplicate of #2184

**Closed by bastimeyer** 2023-04-29 02:02 UTC
Labels: feature request
