### ISSUE TITLE
Plugin for SHOWROOM can't work

### ISSUE THREAD

**Issue by DCxDESIGN** [streamlink/streamlink#2982] opened 2020-05-18 07:51 UTC
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

Streamlink can't read the stream of on-live SHOWROOM room when given the live room URL (eg. https://www.showroom-live.com/[USER_ID] )

### Reproduction steps / Explicit stream URLs to test

1. visit https://www.showroom-live.com/
2. find and copy any on-live SHOWROOM room URL
3. run streamlink given the parameter of the URL above

### Log output

```
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.6
[cli][debug] Streamlink: 1.4.1
[cli][debug] Requests(2.23.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin showroom for URL https://www.showroom-live.com/LOVE_MAIKA_SASAKI
[plugin.showroom][debug] Failed to find room_id for LOVE_MAIKA_SASAKI using primary regex
[utils.l10n][debug] Language code: zh_CN
[utils.l10n][debug] Language code: zh_CN
error: No playable streams found on this URL: https://www.showroom-live.com/LOVE_MAIKA_SASAKI
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bandicootdancing** [comment] 2020-05-20 15:42
I had to install the development release from the install instructions to get showroom to work. It looks like the fix hasn't been pushed to a stable release yet, at least from what I can tell.

**Comment by bastimeyer** [comment] 2020-05-20 16:13
> Streamlink: 1.4.1

Duplicate of #2918

As @bandicootdancing said, use the **latest development** version from the master branch, not the latest stable version.
https://streamlink.github.io/latest/install.html

**Closed by bastimeyer** 2020-05-20 16:13 UTC

**Comment by DCxDESIGN** [comment] 2020-05-21 05:00
> > Streamlink: 1.4.1
> 
> Duplicate of #2918
> 
> As @bandicootdancing said, use the **latest development** version from the master branch, not the latest stable version.
> https://streamlink.github.io/latest/install.html

Thank you for your reply. I saw the bug report #2918 but didn't realize that the bug fixes haven't been merged to stable channel yet.

**Comment by DCxDESIGN** [comment] 2020-05-21 05:01
> I had to install the development release from the install instructions to get showroom to work. It looks like the fix hasn't been pushed to a stable release yet, at least from what I can tell.

Thank you so much. :)
