### ISSUE TITLE
error: No playable streams found on this URL

### ISSUE THREAD

**Issue by Kagunda10** [streamlink/streamlink#2250] opened 2019-01-14 14:55 UTC
## Bug Report

- [x ] This is a bug report and I have read the contribution guidelines.

### Description
I have been using streamlink to download Youtube live streams for about 7 days now using the command streamlink --hls-live-restart --hls-segment-threads 5 -o "filename" URL best but now i get an error: No playable streams found on this URL

### Expected / Actual behavior

I expect a CLI output after the plugin has been found 
```
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p_alt, 720p (best)
```
but this is what i get
```
error: No playable streams found on this URL:
```
### Reproduction steps / Explicit stream URLs to test

1. ... streamlink --hls-live-restart --hls-segment-threads 5 -o "16,52,00.ts" https://www.youtube.com/watch?v=4BetS4GqxHE best --loglevel debug

### Log output

```
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.7.1
[cli][debug] Streamlink: 0.14.2
[cli][debug] Requests(2.21.0), Socks(1.6.7), Websocket(0.54.0)
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=4BetS4GqxHE
[plugin.youtube][debug] get_video_info - 1: Found data
[plugin.youtube][debug] This video is live.
error: No playable streams found on this URL: https://www.youtube.com/watch?v=4BetS4GqxHE
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by Skysurfer31** [comment] 2019-01-15 01:01
I was getting same error in Linux for live streams (non live streams were working fine). I re-cloned the github repository on my machine and re-installed streamlink. I'm no longer getting the error message and live streams play normally in VLC now. There have been some updates to the plugins, so perhaps refreshing those by re-installing did the trick barring anything odd going on with Youtube's API.

I also tested with the URL you gave above, and it's working for me as well.

**Comment by bastimeyer** [comment] 2019-01-15 01:04
Another duplicate of #2237.

> [cli][debug] Streamlink: 0.14.2

You are not using the latest Streamlink build.

**Closed by bastimeyer** 2019-01-15 01:04 UTC

**Comment by mmehrle** [comment] 2019-04-20 11:56
I am getting the same error and I just installed streamlink.

**Comment by bastimeyer** [comment] 2019-04-20 13:43
@mmehrle You are commenting on a closed thread regarding the Youtube plugin which is something totally different. If you are having issues with another plugin, please open a new "plugin issue" thread and fill in the necessary details.
https://github.com/streamlink/streamlink/issues/new?template=plugin_issue.md
