### ISSUE TITLE
[Youtube] URL has an invalid label

### ISSUE THREAD

**Issue by StarWolf3000** [streamlink/streamlink#169] opened 2016-11-16 08:10 UTC
With a lot of Youtube URLs I only get
`[cli][error] Could not open stream: Unable to open URL: http://r4---sn-4g5e6n7k.googlevideo.com/videoplayback?id=o-AMx00u_Hy1utcNFZMyq4fLygBtKL09bG6RGnc83-F8Af&dur=14472.394&signature=977F6BDF0E09E5C488AA419336106DF2EBAEDF84.326F564D004C949EC33D69C1AB82A47553651372&mm=31&mn=sn-4g5e6n7k&upn=dyJorCtyKNU&initcwndbps=697500&ip=<IP address>&key=yt6&lmt=1477844257912727&mime=video%2Fmp4&ms=au&source=youtube&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Cratebypass%2Csource%2Cupn%2Cexpire&mv=m&ratebypass=yes&pl=17&ipbits=0&mt=1479283246&itag=22&expire=1479304889&nh=IgpwZjAxLmZyYTE1Kg04Ny4xMjguMjM2LjUz (URL has an invalid label.)`

For example, this one works: https://www.youtube.com/watch?v=n6gI_RszUgY
while this one does not: https://www.youtube.com/watch?v=iVogxITG97k

Also why are the URLs HTTP and not HTTPS when fetching? With a fetch script I use in my browser, the URLs are always HTTPS.

**Comment by beardypig** [comment] 2016-11-16 08:56
I could not recreate this on Windows 10... It is possibly a bug in requests, did you use the `streamlink` installer? If you did, could you run the following commands in a command prompt and tell me what it prints? 

```bat
cd "C:\Program Files\Streamlink\pkgs"
"..\Python\python.exe" -c "import requests; print(requests.__version__)"
```

**Comment by StarWolf3000** [comment] 2016-11-17 08:19
The output is: 2.11.1
Thats the version that is installed with the 0.0.2 Windows setup.

Strangely it seems to work now and then, I will investigate this further on my system, so its maybe a bug on my side, because I do have other Python versions installed on my system, but they are not in the paths, and streamlink was installed on my second HDD with letter E.

**Comment by Joseph65** [comment] 2016-11-18 17:27
im also having the same error but in Linux
when i watch this live stream https://www.youtube.com/watch?v=HZR0E8TzCsM
with streamlink https://www.youtube.com/watch?v=HZR0E8TzCsM 720p
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=HZR0E8TzCsM
[cli][info] Available streams: 144p (worst), 240p, 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 720p (hls)
[stream.hls][error] Failed to open segment 440565: Unable to open URL: http://r7---sn-h0auphxqpvn-huts.googlevideo.com/videoplayback/id/HZR0E8TzCsM.0/itag/95/source/yt_live_broadcast/sq/440565/file/seg.ts?ratebypass=yes&cmbypass=yes&goi=160&sgoap=gir=yes;itag=140&sgovp=gir=yes;itag=136&hls_chunk_host=r7---sn-h0auphxqpvn-huts.googlevideo.com&playlist_type=DVR&gcr=mx&upn=5Prn-ypUcDE&mm=32&mn=sn-h0auphxqpvn-huts&ms=lv&mt=1479489751&mv=m&pl=20&ip=187.161.94.169&ipbits=0&expire=1479511376&sparams=ip,ipbits,expire,id,itag,source,ratebypass,live,cmbypass,goi,sgoap,sgovp,hls_chunk_host,playlist_type,gcr&signature=98415D27803637282E6ECAEEE8FD3E0AE86AB0F7.723C5688C0CF3D3544822EB32623431A7E2A88C8&key=dg_yt0&playlist=index.m3u8&live=1&goap=clen=32797;lmt=1479489770434768&govp=clen=193402;lmt=1479489770883196&dur=2.000 (URL has an invalid label.)

**Comment by beardypig** [comment] 2016-11-18 17:42
@Joseph65 which versions of `streamlink`, `python` and `requests` do you have?

**Comment by Joseph65** [comment] 2016-11-18 19:53
the version of streamlink is 0.0.2
how do i check versions for requests and python
i installed streamlink with pip

**Comment by beardypig** [comment] 2016-11-18 20:05
@Joseph65 OK. To test the version of `python` you can just type
```sh
python --version
``` 
on the terminal and it will print something like 
```
Python 2.7.11
```
To test the version of requests you can type 
```sh
python -c 'import requests; print(requests.__version__)'
```
which will print something like 
```
2.11.1
```

**Comment by Joseph65** [comment] 2016-11-18 22:49
~$ python --version
Python 2.7.12

~$ python -c 'import requests; print(requests.__version__)'
2.12.1

**Comment by beardypig** [comment] 2016-11-19 20:37
@Joseph65 I can confirm that I get the same issue as you when using `requests>=2.12.0`. Could you try downgrading to `requests==2.11.1`? I did not have a problem with that stream using `2.11.1` You can downgrade by doing
```sh
pip install -U requests==2.11.1
```

@StarWolf3000 I haven't had chance to find out what might be causing it in Windows yet...

**Comment by mmetak** [comment] 2016-11-20 18:42
https://github.com/kennethreitz/requests/issues/3683

**Comment by beardypig** [comment] 2016-11-21 10:38
@mmetak, it's not exactly that, but it is related. Requests 2.12 added IDNA2008 validation which is more strict that the previous IDNA2003 spec, however, some sites use invalid IDNA2008 URIs. In particular YouTube... I think the fix for this is to pin the version of requests to `<2.12.0` until either YouTube sorts out their URIs or `requests` relaxes the validation.

**Comment by StarWolf3000** [comment] 2016-11-21 10:54
Are the domain names used by Youtube URIs used for IDNA? I only know IDNA domains that use "xn".

**Comment by beardypig** [comment] 2016-11-21 11:08
If I understand it correctly, IDNA was extended to reverse `xx--`. [UTS-46](http://www.unicode.org/reports/tr46/#Validity_Criteria) defines the criteria for valid IDNA encoded unicode characters. 

> The first 5 criteria are from [IDNA2008]. Criterion #2 in particular is meant to allow for future label extensions beyond just xn--, such as for future versions of IDNA. Some implementations appear to consider such extentions unlikely, and allow labels such as "r3---sn-apo3qvuoxuxbt-j5pe".

**Comment by mmetak** [comment] 2016-11-21 15:36
@beardypig How long do you think it will take for this to resolve upstream? Youtube or requests. I'm asking since I maintain streamlink for archlinux in AUR and 'python-requests-2.12.1' was uploaded to testing repo three days ago and will reach extra repo shortly and cause problems for youtube streams. Seems like the fix in the progress? https://github.com/kennethreitz/requests/pull/3695

I've tried it myself and youtube plays. ;-)

**Comment by beardypig** [comment] 2016-11-21 16:47
Ah cool, nice to know someone is looking after the arch package. That PR does look like it will fix the issue :-) I can't say which version they'll release it in though. I will keep an eye out.

**Comment by gravyboat** [comment] 2016-11-22 01:06
@beardypig Are we good to close this?

**Comment by beardypig** [comment] 2016-11-22 11:22
Weed to open another issue to upgrade requests when they release a less strict IDNA version. 

Should confirm that it works as expected on Windows too, and make sure the new installer installs the correct version of requests.

**Comment by beardypig** [comment] 2016-11-24 07:49
@StarWolf3000 are you able to test if the latest streamlink version fixes this issue for you? I'd recommended uninstalling the current version and installing the new one :-)

**Comment by StarWolf3000** [comment] 2016-11-26 06:43
Again, gives 2.11.1 as requests version.

I will do some testing if I encounter some problems with IDNA urls.

**Comment by beardypig** [comment] 2016-11-26 10:47
@StarWolf3000 thanks, that would be useful. Did you do an uninstall first before installing the latest version just incase?

**Comment by StarWolf3000** [comment] 2016-11-26 10:54
Yes, I did uninstall the previous one before.

**Comment by beardypig** [comment] 2016-11-26 11:09
Excellent! Let us know if you have any issues and we'll try and get it fixed as soon as possible :-)

**Comment by beardypig** [comment] 2016-11-28 14:07
@StarWolf3000 did have any issues playing youtube videos?

**Comment by StarWolf3000** [comment] 2016-11-28 14:12
Not as of yet, but maybe just because I didn't encounter any problematic IDNA URLs since then.

**Comment by beardypig** [comment] 2016-11-28 14:18
OK cool, I'm going to close this issue. If you do encounter a url that does not work please re-open this issue :)

**Closed by beardypig** 2016-11-28 14:18 UTC
Labels: bug

**Comment by mmetak** [comment] 2016-12-01 08:08
Hey @beardypig, just so you know this has been fixed now upstream in the latest version of requests v2.12.2. No need to pin requests<2.12.0 any more? ;-)

**Comment by beardypig** [comment] 2016-12-01 08:53
Yep, can update it. But should exclude the versions that don't work. How long until that version is in AUR? :-)

**Comment by mmetak** [comment] 2016-12-01 09:06
It's already in the testing repo https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/python-requests&id=b410bff6c3a393125c5d13c6d1560437f84db3ff and it should move to extra quickly since its a minor release.

**Comment by beardypig** [comment] 2016-12-01 09:30
Nice. If no one else does it before me, I will open a PR on Monday to update the version of requests.

**Comment by gravyboat** [comment] 2016-12-01 17:49
I've taken care of it @beardypig, it's over here: https://github.com/streamlink/streamlink/pull/239
