### ISSUE TITLE
Development version error

### ISSUE THREAD

**Issue by Damianonymous** [streamlink/streamlink#1195] opened 2017-09-01 08:10 UTC
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*
*Also check the list of known issues before reporting an issue!*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

Development version (pip) error (The stable version 0.7.0 and the portable 0.7.0 version work well)

### Expected / Actual behavior

...

### Reproduction steps / Explicit stream URLs to test

1. https://chaturbate.com/Model
2. https://www.myfreecams.com/#Model
3. https://www.cam4.com/Model

### Environment details

Operating system and version: Windows 7 Professional
Streamlink and Python version: Development version (pip), Python 2.7.13

..

### Comments, logs, screenshots, etc.

https://s26.postimg.org/k7a426brd/Streamlink_error.jpg

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment] 2017-09-01 16:28
Did you try installing socks like mentioned in the error and still encounter this?

**Comment by Damianonymous** [comment] 2017-09-01 22:45
Installation of PySocks 1.6.7 is not enough, it needs extra win-inet-pton-1.0.1. I wrote, because since I use Streamlink, I did not need to install additional modules :)

**Comment by gravyboat** [comment] 2017-09-01 23:36
Socks was recently added so maybe deps weren't set up properly, @beardypig did you have any deps issues?

**Comment by beardypig** [comment] 2017-09-02 22:03
Could be a Windows specific thing... I'll test it out in the next couple of days :-)

**Comment by sdfwv** [comment] 2017-09-05 16:55
this is a `pip` issue

pypa/pip#4391 | pypa/pip#4653

---

you can find the same issue for PySocks here

https://github.com/docker/compose/pull/4990#issuecomment-313310059

**Comment by gravyboat** [comment] 2017-09-09 02:31
I'm going to close this since it's not our problem.

**Closed by gravyboat** 2017-09-09 02:31 UTC
Labels: out of scope, wontfix

**Comment by ficofabrid** [comment] 2017-09-09 12:15
Had the same issue, solved by installing PySocks.

**Comment by karlo2105** [comment] 2017-09-10 00:11
I installed PySocks too by 
`pip install PySocks` and it gave me same error.

`pkg_resources.DistributionNotFound: The 'PySocks!=1.5.7,>=1.5.6; extra == "socks "' distribution was not found and is required by requests`

I hope there would be some workaround before next stable version of streamlink is released.
So far I installed streamlink from latest stable release.

**Comment by gravyboat** [comment] 2017-09-10 18:36
Did you install the package noted here: https://github.com/streamlink/streamlink/issues/1195#issuecomment-326699104 ?

**Comment by karlo2105** [comment] 2017-09-12 13:27
@ficofabrid 
How did you solve it by installing Pysocks ? Could you please write step by step ?

@gravyboat 
I didn't figure out how to install package there, There isn't any simple explanation how to.
Is there any chance to omit installation of pysocks while installing streamlink from pip ?

**Comment by beardypig** [comment] 2017-09-12 13:56
@karlo2105 did you try updating `pip` (`pip install -U pip`) and then installing streamlink again?

**Comment by karlo2105** [comment] 2017-09-12 17:50
@beardypig 
Yes I did and it didn't change anything. 

```
pip install -U pip
Requirement already up-to-date: pip in c:\program files\python27\lib\site-packages
```

It would be interesting before pip is fixed to be able to update streamlink without pysocks installation. 
I can't take a risk now to try update again as stable Streamlink release has been updated with pysocks, so I won't be able anymore to use it anymore.

**Comment by gravyboat** [comment] 2017-09-12 17:53
@karlo2105 I'll double check the stable release tonight after work but I think it will be okay. You can always uninstall and reinstall 0.7.0 if you need to.

**Comment by karlo2105** [comment] 2017-09-12 18:47
OK I took a risk to update to streamlink 0.8.1 with latest pip and it was a mistake. 
Afterwhile I uninstalled streamlink development and did 
`easy_install -U streamlink` and it worked.

**Comment by gravyboat** [comment] 2017-09-12 18:55
I don't use pip for my Windows install, I always use the executable so I will test that tonight. So you're on 0.8.1 with easy_install?

**Comment by gravyboat** [comment] 2017-09-13 03:44
I've confirmed the stable Windows executable is looking good on Windows 10, no errors or install issues.

**Comment by karlo2105** [comment] 2017-09-13 09:46
@gravyboat 
Yes I managed to run streamlink 0.8.1 from source after installation with easy_install instead of pip. ;)

**Comment by Damianonymous** [comment] 2017-09-13 20:30
In stable version 0.8.1 also needed an additional installation:

pip install PySocks

and

pip install win-inet-pton

**Comment by beardypig** [comment] 2017-09-14 10:17
`win-inet-pton` only appears to be required for Python 2 so it won't affect the Windows installer versions. It seems like an issue with `PySocks` that `win-inet-pton` is not install when required. I will create a PR, but I don't don't if it will get merged, if not then we can handle it in the streamlink setup.py until it's fixed properly.

**Comment by gravyboat** [comment] 2017-09-23 22:24
@beardypig Looks like that PR was merged in. Depending on when the pysocks team builds a new package we might just want to fix it ourselves and do a small release.
