### ISSUE TITLE
Improve Streamlink performance

### ISSUE THREAD

**Issue by 12932** [streamlink/streamlink#4388] opened 2022-03-08 16:20 UTC
### Checklist

- [X] This is a feature request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Description

Streamlink seems to download chunks of videos much slower than my browser (latest Chrome stable)/curl (latest stable) can, for example downloading Twitch VoD segments, on a single thread.

**What is it?**
Make Streamlink faster at downloading video chunks (the limitation is on Streamlink, not my internet connection, as my browser and Curl can both download segments faster than Streamlink on a single thread)

**How would you expect it to work?**
It would work just like normal Streamlink, nothing user-facing would need to change

**What value does it bring to Streamlink?**
I would expect this feature to make Streamlink download chunks faster

**Does it fit into the scope and aims of the project?**
I believe so

**Comment by bastimeyer** [comment] 2022-03-08 16:52
What you've posted is not a feature request. There's nothing magical that Streamlink does while downloading segments in comparison to your web browser and whatever stream implementation the website you're on is using.

Streamlink uses a thread pool of individual segment downloads which are done via python-requests. The results of these segment downloads get queued and written to Streamlink's ringbuffer, which is then read by Streamlink-CLI's main thread for the output that gets read by the player, or it gets written to the filesystem, depending on the options being used.

The only bottleneck you can see is if the number of parallel segment downloads is too low or too high. This can be controlled via the `--stream-segment-threads` CLI argument, but it also depends on the available segments, which depends on lots of other factors.

If you want any help/support/guidance, then **post the entire `--loglevel=trace` output**, otherwise this is just a useless thread without any information at all.

**Comment by 12932** [comment] 2022-03-08 17:21
I'm sorry you think this isn't a feature request, should I post it as a bug instead?

>otherwise this is just a useless thread without any information at all.

Why is it useless? I don't like how Streamlink downloads segments much slower than my browser or other programs like curl

**Comment by gravyboat** [comment] 2022-03-08 17:24
> should I post it as a bug instead?

No because it's not a bug, it's how Streamlink works.

> Why is it useless? I don't like how Streamlink downloads segments much slower than my browser or other programs like curl

You have not provided us with anything actionable. You have not provided any troubleshooting or even logs, you have not pointed out WHERE the problem is, or HOW we might improve it.

If you believe this is easy to implement or obvious in how it should be fixed we will happily review a PR showing data and metrics that your implemented code is faster.

**Comment by 12932** [comment] 2022-03-08 17:52
>You have not provided any troubleshooting or even logs
Because it's not a bug, I can't provide logs

>WHERE the problem is
The Python interpreter is likely the reason why Streamlink can't download chunks in a single thread as fast as a browser

>HOW we might improve it.
Implement Streamlink in a programming language that is faster, maybe something compiled

>If you believe this is easy to implement or obvious in how it should be fixed we will happily review a PR showing data and metrics that your implemented code is faster.
A PR that implements Streamlink in a faster language? That's a mammoth of a task, I think that should be a whole new project, not a PR

**Comment by gravyboat** [comment] 2022-03-08 17:54
> A PR that implements Streamlink in a faster language? That's a mammoth of a task, I think that should be a whole new project, not a PR

So what exactly are you asking for in this issue then? You're asking that we rewrite Streamlink?

**Comment by bastimeyer** [comment] 2022-03-08 18:38
> The Python interpreter is likely the reason why Streamlink can't download chunks in a single thread as fast as a browser

No, it's not, and you still haven't posted any debug/trace log output or anything other useful.

Closing the thread.

**Closed by bastimeyer** 2022-03-08 18:38 UTC
Labels: question

**Comment by 12932** [comment] 2022-03-08 20:10
> > The Python interpreter is likely the reason why Streamlink can't download chunks in a single thread as fast as a browser
> 
> No, it's not, and you still haven't posted any debug/trace log output or anything other useful.
> 
> Closing the thread.

Try it yourself.

**Comment by 12932** [comment] 2022-03-08 20:10
Also, what do you want be to post a debug/trace log of?? It downloading a chunk?

**Comment by 12932** [comment] 2022-04-01 07:55
See #4413 for debug logs of chunk download
