### ISSUE TITLE
Twitch not playing

### ISSUE THREAD

**Issue by RenaKunisaki** [streamlink/streamlink#2072] opened 2018-09-19 18:32 UTC
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

twitch.tv streams no longer play correctly. VLC shows random colours and makes loud noises, or doesn't play at all.

### Reproduction steps / Explicit stream URLs to test

1. `streamlink twitch.tv/360chrism` or any other channel

### Log output

```
~> streamlink --loglevel debug twitch.tv/360chrism
[cli][debug] OS:         Linux-4.14.70-1-lts-x86_64-with-arch
[cli][debug] Python:     3.7.0
[cli][debug] Streamlink: 0.14.2
[cli][debug] Requests(2.19.1), Socks(1.6.7), Websocket(0.53.0)
[cli][info] Found matching plugin twitch for URL twitch.tv/360chrism
[cli][debug] Plugin specific arguments:
[cli][debug]  --twitch-oauth-token=******** (oauth_token)
[plugin.twitch][debug] Getting live HLS streams for 360chrism
[plugin.twitch][info] Attempting to authenticate using OAuth token
[plugin.twitch][info] Successfully logged in as RenaKunisaki
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p60_alt, 720p60 (best)
[cli][info] Starting player: /usr/bin/vlc
VLC media player 3.0.4 Vetinari (revision 3.0.4-0-gf615db6332)
[000055a562dc9570] main libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
[cli][info] Got HTTP request from VLC/3.0.4 LibVLC/3.0.4
[cli][info] Opening stream: 720p60 (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 716; Last Sequence: 729
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 727; End Sequence: None
[stream.hls][debug] Adding segment 727 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 728 to queue
[stream.hls][debug] Adding segment 729 to queue
[cli][debug] Writing stream to player
[stream.hls][debug] Download of segment 727 complete
[stream.hls][debug] Download of segment 728 complete
[00007f096c081a00] avcodec decoder: Using NVIDIA VDPAU Driver Shared Library  396.54  Tue Aug 14 23:07:45 PDT 2018 for hardware decoding
[00007f096c081a00] main decoder error: buffer deadlock prevented
[00007f096c0e2c80] main decoder error: buffer deadlock prevented
[stream.hls][debug] Download of segment 729 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 730 to queue
[stream.hls][debug] Adding segment 731 to queue
[stream.hls][debug] Adding segment 732 to queue
[stream.hls][debug] Download of segment 730 complete
[stream.hls][debug] Download of segment 731 complete
[stream.hls][debug] Download of segment 732 complete
QObject::~QObject: Timers cannot be stopped from another thread
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 733 to queue
[stream.hls][debug] Adding segment 734 to queue
[stream.hls][debug] Adding segment 735 to queue
[stream.hls][debug] Download of segment 733 complete
[cli][info] HTTP connection closed
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[cli][info] Stream ended
[stream.hls][debug] Download of segment 734 complete
[cli][info] Closing currently open stream...
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by RenaKunisaki** [comment] 2018-09-19 18:32
![screenshot 180919 142955 vlc media player](https://user-images.githubusercontent.com/1185585/45773657-d561e600-bc18-11e8-90a8-d1fa2a2dcf60.png)

**Comment by gravyboat** [comment] 2018-09-19 18:55
I can't duplicate this with VLC 3.0.0 or MPV. Seems to me like a duplicate of https://github.com/streamlink/streamlink/issues/2060 which was related to the latest VLC update. What version of VLC are you using?

**Comment by migrome** [comment] 2018-09-19 19:28
> What version of VLC are you using?

```
[cli][info] Starting player: /usr/bin/vlc
VLC media player 3.0.4 Vetinari (revision 3.0.4-0-gf615db6332)
```
https://forum.videolan.org/viewtopic.php?f=13&t=146322
https://bbs.archlinux.org/viewtopic.php?id=240469
`pacman -S aribb24` should solve the issue on Archlinux.

**Comment by gravyboat** [comment] 2018-09-19 19:57
Comment related to this is here: https://github.com/streamlink/streamlink/issues/2060#issuecomment-422923506, closing as a duplicate.

**Closed by gravyboat** 2018-09-19 19:57 UTC
