### ISSUE TITLE
Proxy not working?

### ISSUE THREAD

**Issue by UnrealApp** [streamlink/streamlink#1299] opened 2017-10-30 21:56 UTC
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description
I don't see the proxies working. I thought I was doing everything right and following all the instructions and adding the --http-proxy and --https-proxy options but it wasn't loading it through the proxy. In my VLC player, it was still showing my IP and if I gave an incorrect proxy (like I accidentally typed too many numbers) it would still load. That means that it isn't even looking at the proxy I am giving it. Not sure if I am doing something wrong or what.

### Reproduction steps / Explicit stream URLs to test

1. streamlink --http-proxy "http://proxy:port" --https-proxy "socks5://proxy:port" twitch.tv/summit1g best

### Environment details

Operating system and version: Windows 8.1
Streamlink and Python version: 0.8.1 | Python 2.7.13

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment] 2017-10-31 18:35
Not sure exactly what you mean here...
The socks5 option of the `--https-proxy` parameter and the twitch plugin are working fine. Btw, since the twitch plugin doesn't make any regular http requests, you can omit the `--http-proxy` parameter.

Just a very simple bash script to see that Streamlink is actually using the socks5 proxy server for all of its requests:

```bash
streamlink --https-proxy "socks5://address:port" URL STREAM &
PID=$!
netstat -tp | grep "$PID/python"
```

> In my VLC player, it was still showing my IP

It'll only "show your IP address in your player" if you're using the `--player-passthrough` parameter with a value of `http` or `rtmp`, which tells Streamlink to run a **local proxy server** to which the player will connect to instead of reading the stream data from `stdin` when not using this parameter. If you're using `--player-passthrough=hls` (which you should not when using a proxy server), Streamlink will launch the player with the URL of Twitch's HLS playlist as the first parameter, so that it has to download the stream by itself instead of reading from Streamlink's (passthrough) proxy server.

Can you post the whole command (without explicit proxy server addresses)? Please also make sure that your config file doesn't contain anything special that may interfere here...

**Comment by ryanjgillies** [comment] 2017-11-05 04:37
@bastimeyer sorry if this is a not so appropriate side query but your above answer made me question why I was using http proxy servers for my connection settings - is socks5 more beneficial in anyway?

**Comment by bastimeyer** [comment] 2017-11-06 16:51
@ryanbraganza 
A SOCKS proxy is just something different.
https://en.wikipedia.org/wiki/SOCKS#Comparison_to_HTTP_proxying

I'm going to close this thread, since the original question has been answered...

**Closed by bastimeyer** 2017-11-06 16:51 UTC
Labels: question

**Comment by liword** [comment] 2018-02-06 22:12
Same issue here, and very confusing.
I think streamlink do not support any type of proxy by now.
Lot of people here include me are tested and confirmed Both http and socks5 are not working for streamlink.
