### ISSUE TITLE
plugins.youtube: Error when using a specific link

### ISSUE THREAD

**Issue by TaeDDin** [streamlink/streamlink#4257] opened 2021-12-18 17:11 UTC
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

I am using both exe and api of streamlink using Python. In version 2.4.0, errors began to occur as the link that did well came to the latest version. I'm using a link like this to download only live broadcasts. ex) https://www.youtube.com/channel/OOOOOOO/live
Any channel was the same, and there was no error in the 2.4.0 version. Please resolve the error. 

When you run with bat to write debug logs, it says "[stream.hls][debug] Reloading playlist". But it does download. So I'll write down the Python error log.

### Debug log

```text
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.9.8
[cli][debug] Streamlink: 3.0.3
[cli][debug] Requests(2.26.0), Socks(1.7.1), Websocket(1.2.1)



error:root:Traceback (most recent call last):
  File "C:\Users\[User Name]\AppData\Local\Programs\Python\Python39\lib\site-packages\streamlink\plugin\api\validate.py", line 420, in validate_dict
    new[key] = validate(subschema, value[key])
  File "C:\Users\[User Name]\AppData\Local\Programs\Python\Python39\lib\functools.py", line 877, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "C:\Users\[User Name]\AppData\Local\Programs\Python\Python39\lib\site-packages\streamlink\plugin\api\validate.py", line 417, in validate_dict
    raise ValueError("Key '{0}' not found in {1!r}".format(key, value))
ValueError: Key 'playerMicroformatRenderer' not found in {'microformatDataRenderer': {'urlCanonical': 'https://www.youtube.com/channel/OOOOOOO/live'~~~~~~



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\[User Name]\AppData\Local\Programs\Python\Python39\lib\site-packages\streamlink\plugin\api\validate.py", line 537, in validate
    return validate(self.schema, value)
  File "C:\Users\[User Name]\AppData\Local\Programs\Python\Python39\lib\functools.py", line 877, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "C:\Users\[User Name]\AppData\Local\Programs\Python\Python39\lib\site-packages\streamlink\plugin\api\validate.py", line 380, in validate_all
    value = validate(schema, value)
  File "C:\Users\[User Name]\AppData\Local\Programs\Python\Python39\lib\functools.py", line 877, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "C:\Users\[User Name]\AppData\Local\Programs\Python\Python39\lib\site-packages\streamlink\plugin\api\validate.py", line 422, in validate_dict
    raise ValueError("Unable to validate key '{0}': {1}".format(key, err))
ValueError: Unable to validate key 'microformat': Key 'playerMicroformatRenderer' not found in {'microformatDataRenderer': {'urlCanonical': 'https://www.youtube.com/channel/OOOOOOO/live' ~~~~~~



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\[User Name]\AppData\Local\Programs\Python\Python39\lib\site-packages\streamlink\plugin\plugin.py", line 336, in streams
    ostreams = self._get_streams()
  File "C:\Users\[User Name]\AppData\Local\Programs\Python\Python39\lib\site-packages\streamlink\plugins\youtube.py", line 332, in _get_streams
    self.id, self.author, self.category, self.title, is_live = self._schema_videodetails(data)
  File "C:\Users\[User Name]\AppData\Local\Programs\Python\Python39\lib\site-packages\streamlink\plugins\youtube.py", line 163, in _schema_videodetails
    videoDetails = validate.validate(schema, data)
  File "C:\Users\[User Name]\AppData\Local\Programs\Python\Python39\lib\functools.py", line 877, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "C:\Users\[User Name]\AppData\Local\Programs\Python\Python39\lib\site-packages\streamlink\plugin\api\validate.py", line 544, in validate_schema
    return schema.validate(value, exception=ValueError)
  File "C:\Users\[User Name]\AppData\Local\Programs\Python\Python39\lib\site-packages\streamlink\plugin\api\validate.py", line 539, in validate
    raise exception("Unable to validate {0}: {1}".format(name, err))
ValueError: Unable to validate result: Unable to validate key 'microformat': Key 'playerMicroformatRenderer' not found in {'microformatDataRenderer': {'urlCanonical': 'https://www.youtube.com/channel/OOOOOOO/live', ~~~~~~~~~~~~




During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[py storage path]", line 52, in download
    session.streams("https://www.youtube.com/channel/" + self.channelId + "/live")
  File "C:\Users\[User Name]\AppData\Local\Programs\Python\Python39\lib\site-packages\streamlink\session.py", line 397, in streams
    return plugin.streams(**params)
  File "C:\Users\[User Name]\AppData\Local\Programs\Python\Python39\lib\site-packages\streamlink\plugin\plugin.py", line 346, in streams
    raise PluginError(err)
streamlink.exceptions.PluginError: Unable to validate result: Unable to validate key 'microformat': Key 'playerMicroformatRenderer' not found in {'microformatDataRenderer': {'urlCanonical': 'https://www.youtube.com/channel/OOOOOOO/live', ~~~~~~~~~~~~~~~
```

**Comment by bastimeyer** [comment] 2021-12-18 17:17
Duplicate of #4221

**Closed by bastimeyer** 2021-12-18 17:17 UTC
Labels: plugin issue
