### ISSUE TITLE
output filename controls request

### ISSUE THREAD

**Issue by firestar9114** [streamlink/streamlink#2052] opened 2018-09-05 02:11 UTC
## Feature Request

- [x] This is a feature request and I have read the contribution guidelines.

### Description

I would like the developers to add a little more control over how files can be named by default when generated using the --output option.  For instance, using %Video_title%, %extension% and %Channel_Name%, or something similar in the output string name that will then be replaced by the information from the stream automatically.  For instance, 
```--output "C:\WorkingDevelopment\Videos\%Title%.%Extension%"```
could become:
```--output "C:\WorkingDevelopment\Videos\Critical Role | Campaign 2 Episode 5.mp4"```
or something.

**Comment by back-to** [comment] 2018-09-16 10:17
Duplicate of #791

**Closed by back-to** 2018-09-16 10:17 UTC
