### ISSUE TITLE
vaughnlive plugin not see stream...

### ISSUE THREAD

**Issue by Vinizavr** [streamlink/streamlink#1202] opened 2017-09-07 10:14 UTC
Hello. Need help with this problem:
![ng8citx](https://user-images.githubusercontent.com/20253710/30158450-90b15114-93ef-11e7-8602-7471b2491abc.png)
vaughnlive.tv/sherming3 working but streamlink not see him. How fix this problem?

P.S: Sorry for my bad english.

**Comment by gravyboat** [comment] 2017-09-07 17:42
Duplicate of https://github.com/streamlink/streamlink/issues/1187.

**Closed by gravyboat** 2017-09-07 17:42 UTC
