### ISSUE TITLE
plugins.pluzz: Recent dound desynchronization bug

### ISSUE THREAD

**Issue by jeepcook** [streamlink/streamlink#5447] opened 2023-07-17 12:57 UTC
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest build from the master branch

### Description

Next streamlink updates cause sound desynchronization on france.tv channels. Sometimes in the beginning of the stream, sometimes during the stream.

The following version have this bug: 628e8ab, 07d627f, d89c796.

So back to 33781b7 commit and the bug is not there anymore.

### Debug log

```text
no log because it's a random issue, sometimes in the beginning, sometimes during the stream.
```

**Comment by bastimeyer** [comment] 2023-07-17 14:16
The commits you've posted are 100% irrelevant.

This is a duplicate of #3438

See #4721

**Closed by bastimeyer** 2023-07-17 14:16 UTC
Labels: plugin issue
