### ISSUE TITLE
pls add an extra argument like --dont-mux

### ISSUE THREAD

**Issue by ghoshben** [streamlink/streamlink#2546] opened 2019-07-12 21:30 UTC
## Feature Request

- [x] This is a feature request and I have read the contribution guidelines.

### Description

pls add an extra argument like --dont-mux

when we are using streamlink with -o it autometically calls ffmpeg and mux audio and video stream. add a extra argument so that we can stop it from muxing .

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment] 2019-07-13 01:05
Can you provide a use case for this? In what scenario would you want to do this?

**Comment by beardypig** [comment] 2019-07-13 07:17
Do you mean to disable the option of using `ffmpeg` so that the streams that require `ffmpeg` would not be listed?

**Comment by ghoshben** [comment] 2019-07-13 07:36
for example I am downloading a mpd . the video is downloaded separately & audio is downloaded separately. then it is mux using ffmpeg{probably} , I want to skip the muxing part

**Comment by ghoshben** [comment] 2019-07-13 07:47
@gravyboat

for drm encrypted mpd the audio and video is encrypted using different keys , u can understand the rest I think

**Comment by back-to** [comment] 2019-07-13 08:52
this is a Duplicate of https://github.com/streamlink/streamlink/issues/2184 and seems out of scope for streamlink purposes

**Comment by beardypig** [comment] 2019-07-13 08:52
Streamlink only supports outputting a single stream, we won’t add the functionality to output two streams - it’s not something that is useful to 99% of users, nor is it what streamlink is intended for. DRMed DASH streams are not supported either, so you’d need to modify streamlink yourself to make it output the encrypted streams, at which point you could make the modifications needed to save individual streams yourself.

**Comment by ghoshben** [comment] 2019-07-13 09:00
After modifications if I update streamlink then Again I have to remodify thats why I am saying

**Comment by gravyboat** [comment] 2019-07-13 19:07
I'm going to close this out since our stance is pretty clear that this is out of scope for what we want to do.

**Closed by gravyboat** 2019-07-13 19:07 UTC
Labels: more info required
