### ISSUE TITLE
urllib3 (1.25.1) or chardet (3.0.4) doesn't match a supported version

### ISSUE THREAD

**Issue by Photatoke** [streamlink/streamlink#2448] opened 2019-04-25 16:26 UTC
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.

### Description

Not sure if it should be a Bug report or what sorry if it isn't. Im new to ubuntu/linux stuff so bear with me. I installed python and pip and then streamlink and twitchgui. I noticed i can't start streams, it says "Unexpected Version check output" i thought the problem was twitch gui but i couldn't start streams from the terminal neither . Whenever i type streamlink it outputs:

```
/usr/local/lib/python2.7/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.1) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "/usr/local/bin/streamlink", line 6, in <module>
    from streamlink_cli.main import main
  File "/usr/local/lib/python2.7/dist-packages/streamlink_cli/main.py", line 22, in <module>
    from streamlink import __version__ as streamlink_version
  File "/usr/local/lib/python2.7/dist-packages/streamlink/__init__.py", line 73, in <module>
    from .api import streams
  File "/usr/local/lib/python2.7/dist-packages/streamlink/api.py", line 1, in <module>
    from .session import Streamlink
  File "/usr/local/lib/python2.7/dist-packages/streamlink/session.py", line 11, in <module>
    from streamlink.logger import StreamlinkLogger, Logger
  File "/usr/local/lib/python2.7/dist-packages/streamlink/logger.py", line 7, in <module>
    from streamlink.compat import is_py2
  File "/usr/local/lib/python2.7/dist-packages/streamlink/compat.py", line 48, in <module>
    from backports.shutil_which import which
ImportError: No module named shutil_which
```

I checked both urllib3 and chardet they are updated to the newest versions.

### Expected / Actual behavior

The stream should start?

### Log output

```
REPLACE THIS TEXT WITH THE LOG OUTPUT
```

**Comment by skulblakka** [comment] 2019-04-25 17:04
Seems like a bunch of people are having issues with running streamlink using python2 on ubuntu based systems.

While it is not a fix per se, it seems to be working fine when using python3 as described [here](https://github.com/streamlink/streamlink-twitch-gui/issues/636#issuecomment-486317912).

**Comment by Photatoke** [comment] 2019-04-25 17:26
Uninstalled python2 and installed python3 now it works thanks.

**Comment by bastimeyer** [comment] 2019-04-25 18:48
Related / same issue as #2446
Let me re-open this one here, though...

**Comment by robnardo** [comment] 2019-04-26 15:56
I too am also getting this error.  I have a Wagtail site running.  I am using a docker alpine image pulling from python:3.6-alpine - so there is no python 2.  My requirements.txt file (from a freeze) is below.  One thing to note is the error i am getting is:

```
/usr/local/lib/python3.6/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25) or chardet (3.0.4) doesn't match a supported version!
```
which seems to involve the requests pip module

requirements.txt
```
beautifulsoup4==4.6.0
certifi==2019.3.9
chardet==3.0.4
cssutils==1.0.2
Django==2.1.8
django-appconf==1.0.3
django-cogwheels==0.2
django-colorful==1.3
django-compressor==2.2
django-csp==3.5
django-el-pagination==3.2.4
django-libsass==0.7
django-modelcluster==4.4
django-multiselectfield==0.1.8
django-redis==4.10.0
django-social-share==1.3.2
django-taggit==0.23.0
django-treebeard==4.3
djangorestframework==3.9.2
draftjs-exporter==2.1.5
elasticsearch==5.5.3
html5lib==1.0.1
idna==2.8
libsass==0.18.0
lxml==4.2.6
mysqlclient==1.3.13
Pillow==5.4.1
puput==1.0.3
python-dateutil==2.7.5
pytz==2019.1
rcssmin==1.0.6
redis==3.2.1
requests==2.21.0
rjsmin==1.0.12
six==1.12.0
Unidecode==1.0.23
untangle==1.1.1
urllib3==1.25
uWSGI==2.0.17
wagtail==2.4
wagtailmenus==2.13
webencodings==0.5.1
Willow==1.1
```

**Comment by DJ4ddi** [comment] 2019-04-26 23:32
Hello there.
I received this warning on Elementary OS 0.4.1 (based on Ubuntu 16.04.2) after installing streamlink 1.1.1 with pip (as the ppa isn't updated yet). It caused no issues for streams, but prevented Streamlink Twitch GUI from launching with the infamous unexpected version output error that was already referenced here.

I fixed the issue by manually updating the requests package using pip:
`sudo pip install --upgrade requests`
The chardet package is now on version 3.0.4 and urllib3 is on 1.24.2.

Regards,
Addi

**Comment by saperpsh** [comment] 2019-05-02 03:14
I do have the same question. I just have python3 only.
everytime it run, the warning jumps out first.

**Comment by robnardo** [comment] 2019-05-02 19:26
Just to follow up with my findings.. if i restrict urllib3 to the following (see below) in my requirements.txt file I do not get the RequestDependencyWarning

```
urllib3<1.25,>=1.21.1
```

**Comment by sheoak** [comment] 2019-05-06 04:08
I downgraded urllib3 for now and it works, following @robnardo suggestion:

`pip install --upgrade --user urllib3==1.24.3`

**Comment by mirmirik** [comment] 2019-05-09 18:02
Seems odd but, I've updated "requests" lib and issue is solved. My requirements file was like that:

```
requests==2.21.0
twitter==1.18.0
urllib3>1.24.1
colorama>=0.4.1
```

During the update of requests lib, the message given was:

```
Collecting urllib3<1.25,>=1.21.1 (from requests)
...
Installing collected packages: urllib3
  Found existing installation: urllib3 1.25.2
    Uninstalling urllib3-1.25.2:
      Successfully uninstalled urllib3-1.25.2
Successfully installed urllib3-1.24.3
```

It has **downgraded urllib3 to 1.24.3 from 1.25.2**. I don't know if that'll cause any trouble but it seems OK for now.

**Comment by Vrakfall** [comment] 2019-05-12 03:22
> I fixed the issue by manually updating the requests package using pip:
> `sudo pip install --upgrade requests`

That's going fight with most package managers!

**Comment by retorquere** [comment] 2019-05-12 05:40
My python is installed by brew or virtualenv, so no package manager involved - I'd love to get rid of the message. It seems to work as is - I don't really understand why the message is being emitted at all?

**Comment by ezhu5121** [comment] 2019-05-12 16:18
This is why I don't like something like conan which is written in python but can't manage the dependencies very well, it always complains some packages are too old or some packages are too advanced. it's really annoying because it requires your system to downgrade or upgrade some specific packages there that may not be compatible with or mess up the distro.

**Comment by pujianto** [comment] 2019-05-13 21:01
I have the same issue but it was on docker-compose, but I think it has similar problem. The python `requests` module needs latest urllib3 version ([1.24.3](https://github.com/urllib3/urllib3/releases)).
For me, I reinstall urllib3 with 1.24.3 version solves the problem.
Try, `sudo pip install -Iv urllib3==1.24.3`

**Comment by Achoso** [comment] 2019-05-14 06:59
> I have the same issue but it was on docker-compose, but I think it has similar problem. The python `requests` module needs latest urllib3 version ([1.24.3](https://github.com/urllib3/urllib3/releases)).
> For me, I reinstall urllib3 with 1.24.3 version solves the problem.
> Try, `sudo pip install -Iv urllib3==1.24.3`

I had the same problem using Arch and docker-compose. This fixt it for me too. Thanks

**Comment by Vrakfall** [comment] 2019-05-14 22:35
> My python is installed by brew or virtualenv, so no package manager involved - I'd love to get rid of the message. It seems to work as is - I don't really understand why the message is being emitted at all?

Maybe it's your case but for most people it is not and that command often implies writing on the system's python environment. On top of that, it is sudo'ed and as it would run as root, it might even use another environment's pip than the one linked to your normal user scope!

**Comment by DJ4ddi** [comment] 2019-05-15 21:16
> 
> 
> > My python is installed by brew or virtualenv, so no package manager involved - I'd love to get rid of the message. It seems to work as is - I don't really understand why the message is being emitted at all?
> 
> Maybe it's your case but for most people it is not and that command often implies writing on the system's python environment. On top of that, it is sudo'ed and as it would run as root, it might even use another environment's pip than the one linked to your normal user scope!

You are correct. Since my comment attracted a lot of positive reactions (and is therefore likely to be seen by people looking for solutions) I added a note regarding the problem.

Regards,
Addi

**Comment by Vrakfall** [comment] 2019-05-16 13:03
Good idea, thank you!

**Comment by gun1x** [comment] 2019-05-17 14:41
On ArchLinux just do `pacman -Syu` and don't go through pip, or you will cause chaos.

**Comment by bastimeyer** [comment] 2019-05-17 15:59
`requests` `2.22.0` has been released two days ago and now depends on `urllib3` `1.25.2`. If your distro has upgraded its `requests` package (and `urllib3` package, which was the cause of this issue), then streamlink should be working again without needing to use pip and downgrading `urllib3`.

I'm closing this thread now. In case of any new issues caused by the bump of `requests`, please open a new thread.

Btw, python 3.4 support was dropped by `requests`, as it's reached its EOL a few weeks ago, so it's probably time to remove it from streamlink as well.

----

> don't go through pip, or you will cause chaos

You will only cause chaos if you're installing pip packages system-wide via sudo. If you're using the `--user` parameter, you will be fine, as it'll use `${XDG_DATA_HOME:${HOME}/.local}` instead, which isn't touched by any system package manager.

**Closed by bastimeyer** 2019-05-17 15:59 UTC
Labels: dependency issue, packages

**Comment by burnquist** [comment] 2019-10-22 04:18
/usr/lib/python2.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.24.3) or chardet (2.2.1) doesn't match a supported version!
  RequestsDependencyWarning)

no solve on my centos 7

**Comment by gravyboat** [comment] 2019-10-22 18:23
@burnquist This thread is very old and I'm not sure what you expect from us here since it seems like you didn't even try to update? You need to either move to Python 3 or make sure all the dependencies are up to date. There's nothing we can do about CentOS not having more recent packages by default. You may have to go through some sort of update chain to get all the dependencies figured out.

I'm going to lock this I guess since Bastimeyer already provided solutions, reasoning, and notes regarding not commenting further on this issue.
