### ISSUE TITLE
Plugin request: 6play (M6, W9, 6ter) -> http://www.6play.fr/

### ISSUE THREAD

**Issue by uNouss** [streamlink/streamlink#888] opened 2017-05-06 08:09 UTC
- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

Hello all, 
I was wondering if it was possible to add a plugin for the following tv channel from this website:
http://www.6play.fr/

Thank you for the consideration :)

**Comment by karlo2105** [comment] 2017-05-06 09:50
I don't think any positive outcome shall emerge out of this request as 6play.fr uses Adobe Faxs DRM.

```
streamlink "hlsvariant://http://akm.live.m6web.fr/out/u/m6_ott_p.m3u8" best
[cli][info] Found matching plugin stream for URL hlsvariant://http://akm.live.m6web.fr/out/u/m6_ott_p.m3u8
[cli][info] Available streams: 224p (worst), 360p, 406p (best)
[cli][info] Opening stream: 406p (hls)
[stream.hls][error] Failed to create decryptor: Unable to open URL: faxs://faxs.
adobe.com (No connection adapters were found for 'faxs://faxs.adobe.com')
[cli][error] Try 1/1: Could not open stream <HLSStream('http://akm.live.m6web.fr
/out/u/m6_ott_p_3.m3u8')> (No data returned from stream)
error: Could not open stream <HLSStream('http://akm.live.m6web.fr/out/u/m6_ott_p
_3.m3u8')>, tried 1 times, exiting
[cli][info] Closing currently open stream...
```

**Comment by ukoz** [comment] 2017-05-06 10:45
you have to post link to webpage you get address `hlsvariant://http://akm.live.m6web.fr/out/u/m6_ott_p.m3u8` from. there should be key/token.
this is link to (HLS) stream itself.

**Comment by gravyboat** [comment] 2017-05-06 19:27
Yeah I'm not really a fan of trying to support sites that use Adobe because they change things so often it could be problematic to maintain (not to mention their anti-consumer tactics) but we'll see if someone feels like tackling it.

**Comment by beardypig** [comment] 2017-05-06 20:21
If there are only Adobe Primetime protected streams then we aren't able to support it anyway...

**Comment by gravyboat** [comment] 2017-05-06 21:35
@beardypig Yeah I haven't explored the site at all so I don't know if it's 100% DRM or not, but even the fact some streams are makes it pretty  mediocre to me.

**Comment by melmorabity** [comment] 2017-05-27 13:42
All live streams are DRM-protected on 6play. Only a few VOD streams are DRM-free (I found some in the youth section). Doesn't worth to provide support for this website :(.

**Comment by gravyboat** [comment] 2017-05-27 19:35
@melmorabity Thanks for investigating. I'm going to close this out @uNouss, if they decide to stop using DRM we can revisit this, but for the time being it doesn't seem worth the dev time.

**Closed by gravyboat** 2017-05-27 19:35 UTC
Labels: plugin request

**Comment by MaximeCheramy** [comment] 2019-02-20 23:20
I don't know if that could help but the project Catch Up TV and More supports 6play: https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/blob/master/resources/lib/channels/fr/6play.py

**Comment by annetube** [comment] 2019-05-09 06:44
+ 1 Yes it seems possible and it would be great, i asked also on youtube-dl github but  nobody seems interested for now

**Comment by SylvainCecchetto** [comment] 2020-06-05 07:10
I am part of the Catch Up TV & More Kodi add-on project and I can confirm that 6play live Tv streams use DRM:

* MPD
or
* HLS SAMPLE-AES

**Comment by novazur972** [comment] 2023-07-06 20:16
> I am part of the Catch Up TV & More Kodi add-on project and I can confirm that 6play live Tv streams use DRM:
> 
>     * MPD
>       or
> 
>     * HLS SAMPLE-AES

Always true ?
