### ISSUE TITLE
404 client error on youtube

### ISSUE THREAD

**Issue by jpancake** [streamlink/streamlink#3734] opened 2021-05-20 01:10 UTC
## Issue

- [ ] This is not a bug report, feature request, or plugin issue/request.
- [ ] I have read the contribution guidelines.
- [ ] I am using the latest development version from the master branch.

### Description

When attempting using streamlink on a youtube live stream I get a 404 client error now.

### Expected / Actual behavior

Stream to open on VLC. instead I get an error.
I used to be able to keep trying and eventually it works but every time I get 404 client error now.

### Reproduction steps / Explicit stream URLs to test

1. OPEN CMD
2. streamlink {youtube link here}
3. 404 client error

### Log output
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=xxxxxxxxxx
error: Unable to open URL: https://youtube.com/get_video_info (404 Client Error: Not Found for url: https://www.youtube.com/get_video_info?video_id=xxxxxxxxxx&el=detailpage)

### further comments
Twitch works just as fine using the TWITCH-GUI

**Comment by fruvous** [comment] 2021-05-20 02:18
I'm experiencing this as well.

My verbose output:
C:\Program Files (x86)\Streamlink\bin>streamlink youtube.com/XXX/live 720p --loglevel debug -O
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.8.7
[cli][debug] Streamlink: 2.1.1
[cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(0.58.0)
[cli][debug] Arguments:
[cli][debug]  url=youtube.com/XXX/live
[cli][debug]  stream=['720p']
[cli][debug]  --loglevel=debug
[cli][debug]  --player="C:\Program Files\mpv\mpv.exe"
[cli][debug]  --player-http=True
[cli][debug]  --player-passthrough=['hls']
[cli][debug]  --stdout=True
[cli][debug]  --rtmpdump=C:\Program Files (x86)\Streamlink\rtmpdump\rtmpdump.exe
[cli][debug]  --ffmpeg-ffmpeg=C:\Program Files (x86)\Streamlink\ffmpeg\ffmpeg.exe
[cli][info] Found matching plugin youtube for URL youtube.com/XXX/live
[plugins.youtube][debug] Video ID from currentVideoEndpoint
[plugins.youtube][debug] Using video ID: aEq77MzxnAQ
error: Unable to open URL: https://youtube.com/get_video_info (404 Client Error: Not Found for url: https://www.youtube.com/get_video_info?video_id=aEq77MzxnAQ&el=detailpage)

**Comment by bastimeyer** [comment] 2021-05-20 02:20
Duplicate of #3724, which was fixed yesterday.
You are not using the **latest development version**.

**Closed by bastimeyer** 2021-05-20 02:20 UTC
