### ISSUE TITLE
Add support for Vimeo password protected videos

### ISSUE THREAD

**Issue by Steinar-akh** [streamlink/streamlink#3582] opened 2021-02-23 13:47 UTC
## Feature Request

- [x] This is a feature request and I have read the contribution guidelines.
- [ ] I am using the latest development version from the master branch.

### Description

Add support of Vimeo passowrd protected videos. 
Will give more posibilitys of use. 

### Additional comments, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment] 2021-02-23 19:09
Duplicate of https://github.com/streamlink/streamlink/issues/2508 which was closed as `wontfix`. We don't have any interest in supporting VODs which require log ins and I haven't seen very many people using Vimeo for paywalled live streams. If they have been I'd like to see some examples.

**Closed by gravyboat** 2021-02-23 19:09 UTC
Labels: duplicate, feature request

**Comment by nitram509** [comment] 2025-04-18 09:15
@Steinar-akh as a workaround, you can copy the cookie values and provide them to streamlink.
E.g. load the video in your browser and enter the password.
Once you see the video, use developer tools and copy each cookie `key=value` pair and craft your command similar like this:
`streamlink https://vimeo.com/12345678 -o video.mp4 --http-cookie '__xy_ab=k1Pncsq.lM' --http-cookie 'player=\"\"' ...`
Of course, the URL for the video and keys/values for the cookies must match your use case.
