### ISSUE TITLE
plugins.huya: some channels no playable streams found on this URL

### ISSUE THREAD

**Issue by v2wy** [streamlink/streamlink#4722] opened 2022-08-09 17:14 UTC
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

Some channel is living, but streamlink can not get streams. The error is following:
`error: No playable streams found on this URL: https://www.huya.com/397545`
If the channel name is a number, it's not working. But if the channel name is a nickname, it's working.

root@nuc:~# streamlink https://www.huya.com/shege
[cli][info] streamlink is running as root! Be careful!
[cli][info] Found matching plugin huya for URL https://www.huya.com/shege
Available streams: source_tx (worst), source_ws, source_al, source_hw (best)

### Debug log

```text
root@nuc:~# streamlink https://www.huya.com/397545 best --loglevel debug
[cli][info] streamlink is running as root! Be careful!
[cli][debug] OS:         Linux-5.4.0-122-generic-x86_64-with-glibc2.29
[cli][debug] Python:     3.8.10
[cli][debug] Streamlink: 4.2.0
[cli][debug] Dependencies:
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.1
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.15.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.28.1
[cli][debug]  websocket-client: 1.3.3
[cli][debug]  importlib-metadata: 1.5.0
[cli][debug] Arguments:
[cli][debug]  url=https://www.huya.com/397545
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][info] Found matching plugin huya for URL https://www.huya.com/397545
error: No playable streams found on this URL: https://www.huya.com/397545
```

**Comment by bastimeyer** [comment] 2022-08-09 19:05
> Streamlink: 4.2.0

Install the latest version from the master branch. The plugin got fixed in #4685, but hasn't been published in a new release yet.
https://streamlink.github.io/install.html

Duplicate of #4684

**Closed by bastimeyer** 2022-08-09 19:05 UTC
Labels: plugin issue
