### ISSUE TITLE
VLC Audio studder fix.

### ISSUE THREAD

**Issue by dusty-dusty** [streamlink/streamlink#3303] opened 2020-10-29 02:51 UTC
VLC Audio would studder or VLC Audio would cut out and in while the video was not buffering. Might want to put this in issues on the doc Common issues to help others or link people to this. I dont think im the only one that had this issue and took me 30min of reasearch and messing around to get it working. 

1: open VLC and hit ctrl+p to bring up the preferences interface.
2: 
![1](https://user-images.githubusercontent.com/12129838/97519981-d9b46d80-195f-11eb-9bb8-3adb2f17d090.png)

3: 

![2](https://user-images.githubusercontent.com/12129838/97520000-e638c600-195f-11eb-90f6-572148439ef5.png)

4: 

![3](https://user-images.githubusercontent.com/12129838/97520017-edf86a80-195f-11eb-94b4-56ef6a2bce31.png)

5: restart VLC and it should be fixed

**Comment by bastimeyer** [comment] 2020-10-29 06:33
> Might want to put this in issues on the doc Common issues to help others or link people to this.

Thanks, but screenshots are not suited for this, especially since they are tied to a specific OS with a specific sound configuration. VLC also has CLI parameters for every option/setting, which means screenshots are not the right way to document solutions for assumed "common problems" when using Streamlink and VLC, if your issue is indeed a "common problem", which I don't know.

If it is and you want to contribute to the documentation, then please submit a pull request with a proper description of the reproducible problem and a generic and neutral solution that works for every user.

Closing the thread (it'll still be available here).
Thanks for the efforts of trying to help though.

**Closed by bastimeyer** 2020-10-29 06:33 UTC

**Comment by Snowy001** [comment] 2020-11-04 06:16
I'm having this identical problem with vlc but those setting changes didn't fix my problem. Anyone able to help me?

**Comment by gravyboat** [comment] 2020-11-04 06:31
@Snowy001 No, this issue was out of scope to begin with because it's a player problem, not a Streamlink problem. You can check out VLC's issue tracker: https://trac.videolan.org/vlc/ to see if it's already documented there or fixed in some sort of newer release, but outside of that all we can suggest is you try a different player. I'm going to lock this up now to avoid further confusion.
