### ISSUE TITLE
plugins.mitele: Live streams not working.

### ISSUE THREAD

**Issue by heroku-miraheze** [streamlink/streamlink#4756] opened 2022-08-20 14:11 UTC
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

As for today, Mitele is not working.

### Debug log

```text
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.10.6
[cli][debug] Streamlink: 4.3.0
[cli][debug] Dependencies:
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.1
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.15.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.28.1
[cli][debug]  websocket-client: 1.3.3
[cli][debug] Arguments:
[cli][debug]  url=https://www.mitele.es/directo/telecinco
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --ffmpeg-ffmpeg=C:\Program Files\Streamlink\ffmpeg\ffmpeg.exe
[cli][info] Found matching plugin mitele for URL https://www.mitele.es/directo/telecinco
[plugins.mitele][debug] Stream: https://directos.mitele.es/orilinear01/live/linear01/main/main.isml/web.m3u8 (hls)
[plugins.mitele][debug] Stream: https://directos.mitele.es/orilinear17/live/linear17/playlist/playlist.isml/ctv.m3u8 (hls)
[plugins.mitele][debug] Stream: https://livek.mediaset.es/orilinear01/live/linear01/main/main.isml/web.m3u8 (hls)
[plugins.mitele][debug] Stream: https://livek.mediaset.es/orilinear17/live/linear17/playlist/playlist.isml/ctv.m3u8 (hls)
[plugins.mitele][debug] Stream: https://directos.mitele.es/orilinear01/live/linear01/main/main.isml/mob.m3u8 (hls)
[utils.l10n][debug] Language code: es_ES
[utils.l10n][debug] Language code: es_ES
[utils.l10n][debug] Language code: es_ES
[utils.l10n][debug] Language code: es_ES
error: Unable to open URL: https://livek.mediaset.es/orilinear17/live/linear17/playlist/playlist.isml/ctv.m3u8?hdnts=st%3D1661004667~exp%3D1661091066~acl%3D%2F%2A~hmac%3Da7123c3b4607bce45d304f3849ca57156888cda7617c448777fedf6841adf4ba (403 Client Error: Forbidden token format for url: https://livek.mediaset.es/orilinear17/live/linear17/playlist/playlist.isml/ctv.m3u8?hdnts=st%3D1661004667~exp%3D1661091066~acl%3D%2F%2A~hmac%3Da7123c3b4607bce45d304f3849ca57156888cda7617c448777fedf6841adf4ba)
```

**Comment by bastimeyer** [comment] 2022-08-20 15:37
Duplicate of #4726

**Closed by bastimeyer** 2022-08-20 15:37 UTC
Labels: plugin issue
