### ISSUE TITLE
afreecatv issue

### ISSUE THREAD

**Issue by chance473** [streamlink/streamlink#3546] opened 2021-02-08 04:44 UTC
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.
- [x] I am using the latest development version from the master branch.

### Description

When trying to record a live broadcast, I get error Failed To Open Segment: Unable To Open URL many times. The stream is still live on the website but streamlink says Stream Ended and stops.

This happens most often when recording 2-3 broadcasts at once, but also happens with only 1 broadcast sometimes.

I thought was an issue with my internet or computer speed, but both are good. I can watch 3 streams no lag with my browser.

### Log output

```
streamlink http://play.afreecatv.com/now90709 best -o now.ts --loglevel debug
[plugin.afreeca][debug] Restored cookies: AbroadChk, AbroadVod, PdboxBbs, PdboxSaveTicket, PdboxTicket, PdboxUser, RDB, _au, isBbs
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.6
[cli][debug] Streamlink: 1.4.1
[cli][debug] Requests(2.23.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin afreeca for URL http://play.afreecatv.com/now90709
[cli][info] Available streams: sd (worst), hd, original (best)
[cli][info] Opening stream: original (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 1518; Last Sequence: 1523
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 1521; End Sequence: None
[stream.hls][debug] Adding segment 1521 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 1522 to queue
[stream.hls][debug] Adding segment 1523 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1524 to queue
[stream.hls][debug] Adding segment 1525 to queue
[cli][debug] Checking file output
[stream.hls][debug] Download of segment 1521 complete
[cli][debug] Writing stream to output
[stream.hls][debug] Download of segment 1522 complete
[stream.hls][debug] Download of segment 1523 complete
[download][now.ts] Written 4.0 MB (1s @ 2.9 MB/s)                                                                      [stream.hls][debug] Download of segment 1524 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1526 to queue
[stream.hls][debug] Download of segment 1525 complete
[download][now.ts] Written 8.1 MB (2s @ 2.9 MB/s)                                                                      [stream.hls][debug] Download of segment 1526 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1527 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1528 to queue
[stream.hls][debug] Download of segment 1527 complete
[download][now.ts] Written 12.1 MB (6s @ 1.9 MB/s)                                                                     [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1529 to queue
[stream.hls][debug] Download of segment 1528 complete
[download][now.ts] Written 14.1 MB (8s @ 1.6 MB/s)                                                                     [stream.hls][debug] Download of segment 1529 complete
[download][now.ts] Written 16.1 MB (10s @ 1.6 MB/s)                                                                    [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1530 to queue
[stream.hls][debug] Download of segment 1530 complete
[download][now.ts] Written 18.1 MB (12s @ 1.2 MB/s)                                                                    [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1531 to queue
[stream.hls][debug] Download of segment 1531 complete
[download][now.ts] Written 20.1 MB (14s @ 1.0 MB/s)                                                                    [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1532 to queue
[stream.hls][debug] Adding segment 1533 to queue
[stream.hls][debug] Download of segment 1532 complete
[download][now.ts] Written 22.2 MB (17s @ 892.6 KB/s)                                                                  [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1534 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Download of segment 1533 complete
[download][now.ts] Written 24.2 MB (21s @ 820.8 KB/s)                                                                  [stream.hls][debug] Adding segment 1535 to queue
[stream.hls][debug] Adding segment 1536 to queue
[stream.hls][debug] Download of segment 1534 complete
[download][now.ts] Written 26.2 MB (22s @ 834.7 KB/s)                                                                  [stream.hls][debug] Reloading playlist
[stream.hls][debug] Download of segment 1535 complete
[download][now.ts] Written 28.2 MB (23s @ 936.1 KB/s)                                                                  [stream.hls][debug] Adding segment 1537 to queue
[stream.hls][debug] Download of segment 1536 complete
[download][now.ts] Written 30.2 MB (25s @ 1004.3 KB/s)                                                                 [stream.hls][debug] Reloading playlist
[stream.hls][debug] Download of segment 1537 complete
[download][now.ts] Written 32.2 MB (26s @ 1.2 MB/s)                                                                    [stream.hls][debug] Adding segment 1538 to queue
[stream.hls][debug] Download of segment 1538 complete
[download][now.ts] Written 34.3 MB (28s @ 1.4 MB/s)                                                                    [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1539 to queue
[stream.hls][debug] Adding segment 1540 to queue
[stream.hls][debug] Download of segment 1539 complete
[download][now.ts] Written 36.3 MB (30s @ 1.2 MB/s)                                                                    [stream.hls][debug] Download of segment 1540 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1541 to queue
[stream.hls][debug] Download of segment 1541 complete
[download][now.ts] Written 40.3 MB (32s @ 1.4 MB/s)                                                                    [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1542 to queue
[stream.hls][debug] Download of segment 1542 complete
[download][now.ts] Written 42.3 MB (34s @ 1.2 MB/s)                                                                    [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1543 to queue
[stream.hls][debug] Download of segment 1543 complete
[download][now.ts] Written 44.3 MB (37s @ 1.1 MB/s)                                                                    [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1544 to queue
[stream.hls][debug] Download of segment 1544 complete
[download][now.ts] Written 46.3 MB (39s @ 1.1 MB/s)                                                                    [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1545 to queue
[stream.hls][debug] Adding segment 1546 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1547 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1548 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1549 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1550 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Download of segment 1545 complete
[download][now.ts] Written 48.3 MB (55s @ 491.7 KB/s)                                                                  [stream.hls][debug] Adding segment 1551 to queue
[stream.hls][debug] Adding segment 1552 to queue
[stream.hls][debug] Adding segment 1553 to queue
[stream.hls][debug] Adding segment 1554 to queue
[stream.hls][debug] Adding segment 1555 to queue
[stream.hls][debug] Adding segment 1556 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1557 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1558 to queue
[stream.hls][debug] Adding segment 1559 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1560 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1561 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][error] Failed to open segment 1546: Unable to open URL: http://pc-web.stream.afreecatv.com/live-stm-05/1920x1080/230855542-flash-original-hls_1545_000000A600500063296D249D5C9FB19F.TS (400 Client Error: Bad Request for url: http://pc-web.stream.afreecatv.com/live-stm-05/1920x1080/230855542-flash-original-hls_1545_000000A600500063296D249D5C9FB19F.TS?aid=.A32.7bbT56vyHM9fKZk.rURQyPz8yUyigNkx_2zHm5zi9iXDc1a1piB1XFuOpJAE2k3x7u7cgeLaVuo0R_wKO-rB5WMdW8z7-5fYEpm9fLJQ6fU-pp4oacneVBTDOFk)
[stream.hls][debug] Adding segment 1562 to queue
[stream.hls][debug] Adding segment 1563 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1564 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][error] Failed to open segment 1547: Unable to open URL: http://pc-web.stream.afreecatv.com/live-stm-05/1920x1080/230855542-flash-original-hls_1546_0000004A00DC002FBEB1506670D5F725.TS (400 Client Error: Bad Request for url: http://pc-web.stream.afreecatv.com/live-stm-05/1920x1080/230855542-flash-original-hls_1546_0000004A00DC002FBEB1506670D5F725.TS?aid=.A32.7bbT56vyHM9fKZk.rURQyPz8yUyigNkx_2zHm5zi9iXDc1a1piB1XFuOpJAE2k3x7u7cgeLaVuo0R_wKO-rB5WMdW8z7-5fYEpm9fLJQ6fU-pp4oacneVBTDOFk)
[stream.hls][debug] Adding segment 1565 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1566 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1567 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1568 to queue
[stream.hls][debug] Adding segment 1569 to queue
[stream.hls][error] Failed to open segment 1548: Unable to open URL: http://pc-web.stream.afreecatv.com/live-stm-05/1920x1080/230855542-flash-original-hls_1547_0000008700B600B49F6D5E69C0A28DBF.TS (HTTPConnectionPool(host='pc-web.stream.afreecatv.com', port=80): Read timed out. (read timeout=10.0))
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1572 to queue
[stream.hls][error] Failed to open segment 1549: Unable to open URL: http://pc-web.stream.afreecatv.com/live-stm-05/1920x1080/230855542-flash-original-hls_1548_000000BA0005000217756015B22F5BDA.TS (400 Client Error: Bad Request for url: http://pc-web.stream.afreecatv.com/live-stm-05/1920x1080/230855542-flash-original-hls_1548_000000BA0005000217756015B22F5BDA.TS?aid=.A32.7bbT56vyHM9fKZk.rURQyPz8yUyigNkx_2zHm5zi9iXDc1a1piB1XFuOpJAE2k3x7u7cgeLaVuo0R_wKO-rB5WMdW8z7-5fYEpm9fLJQ6fU-pp4oacneVBTDOFk)
[stream.hls][debug] Adding segment 1573 to queue
[stream.hls][error] Failed to open segment 1550: Unable to open URL: http://pc-web.stream.afreecatv.com/live-stm-05/1920x1080/230855542-flash-original-hls_1549_00000076002200B8C5F65C869CBB88F7.TS (400 Client Error: Bad Request for url: http://pc-web.stream.afreecatv.com/live-stm-05/1920x1080/230855542-flash-original-hls_1549_00000076002200B8C5F65C869CBB88F7.TS?aid=.A32.7bbT56vyHM9fKZk.rURQyPz8yUyigNkx_2zHm5zi9iXDc1a1piB1XFuOpJAE2k3x7u7cgeLaVuo0R_wKO-rB5WMdW8z7-5fYEpm9fLJQ6fU-pp4oacneVBTDOFk)
[stream.hls][debug] Adding segment 1574 to queue
error: Error when reading from stream: Read timeout, exiting
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

### Additional comments, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment] 2021-02-08 05:03
Duplicate of https://github.com/streamlink/streamlink/issues/3538 so I'm closing this. There are some manual workarounds people are discussing in that issue.

**Closed by gravyboat** 2021-02-08 05:03 UTC
