### ISSUE TITLE
Picarto.tv broken?

### ISSUE THREAD

**Issue by dahjin** [streamlink/streamlink#1601] opened 2018-04-12 18:04 UTC
----

### Checklist

- [x] This is a bug report.

### Description
execute streamlink picarto.tv/blah -o blah.mp4

### Expected / Actual behavior
Download vod/stream

### Reproduction steps / Explicit stream URLs to test

1. execute streamlink picarto.tv/blah -o blah.mp4
2. nothing work
3. :(((((

### Logs
streamlink-script.py https://picarto.tv/videopopout/drawingbutts_2018.04.12.14.31.13.flv -l debug
[cli][info] Found matching plugin picarto for URL https://picarto.tv/videopopout/drawingbutts_2018.04.12.14.31.13.flv
[plugin.picarto][debug] Possible VOD stream...
[plugin.picarto][error] The channel drawingbutts_2018.04.12.14.31.13.flv is currently offline
error: No playable streams found on this URL: https://picarto.tv/videopopout/drawingbutts_2018.04.12.14.31.13.flv

streamlink-script.py https://picarto.tv/drawingbutts -l debug
[cli][info] Found matching plugin picarto for URL https://picarto.tv/drawingbutts
[plugin.picarto][error] The channel drawingbutts is currently offline
error: No playable streams found on this URL: https://picarto.tv/drawingbutts

**Comment by skulblakka** [comment] 2018-04-13 17:24
Can not reproduce. Both of your links work fine for me. Make sure you are using the current version.

Logs:
```
>streamlink https://picarto.tv/drawingbutts live_hls
[cli][info] Found matching plugin picarto for URL https://picarto.tv/drawingbutts
[cli][info] Available streams: live_hls, live (worst, best)
[cli][info] Opening stream: live_hls (hls)
[cli][info] Starting player: "mpv\build\mpv.exe"
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...

>streamlink https://picarto.tv/videopopout/drawingbutts_2018.04.12.14.31.13.flv best
[cli][info] Found matching plugin picarto for URL https://picarto.tv/videopopout/drawingbutts_2018.04.12.14.31.13.
[cli][info] Available streams: 1223k (worst, best)
[cli][info] Opening stream: 1223k (hls)
[cli][info] Starting player: "mpv\build\mpv.exe"
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...

>streamlink -l debug
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.2
[cli][debug] Streamlink: 0.11.0
[cli][debug] Requests(2.18.2), Socks(1.6.7), Websocket(0.44.0)
usage: streamlink [OPTIONS] <URL> [STREAM]

Use -h/--help to see the available options or read the manual at https://streamlink.github.io
```

**Comment by dahjin** [comment] 2018-04-13 23:55
Just uninstalled and reinstalled 0.11.0

**Comment by skulblakka** [comment] 2018-04-14 00:51
Just tested it again with a random stream (see log below). Worked with current commit 2f994ac and with release 0.11.0. Looking at the API calls used by the plugin also seems like nothing changed since the last change half a year ago.

Could you please paste the output of running with ```-l debug``` just to make sure the version you are using is the right one?

---

Log:
```
PS> streamlink -l debug https://picarto.tv/BittersweetCandyShow live_hls
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.2
[cli][debug] Streamlink: 0.11.0
[cli][debug] Requests(2.18.2), Socks(1.6.7), Websocket(0.44.0)
[cli][info] Found matching plugin picarto for URL https://picarto.tv/BittersweetCandyShow
[plugin.picarto][debug] Using load balancing server us-east1 : edge1-eu-west.picarto.tv for channel BittersweetCandyShow
[cli][info] Available streams: live_hls, live (worst, best)
[cli][info] Opening stream: live_hls (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 506; Last Sequence: 510
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 508; End Sequence: None
[stream.hls][debug] Adding segment 508 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 509 to queue
[stream.hls][debug] Adding segment 510 to queue
[stream.hls][debug] Download of segment 508 complete
[cli][info] Starting player: "mpv\build\mpv.exe"
[stream.hls][debug] Download of segment 509 complete
[stream.hls][debug] Download of segment 510 complete
[cli][debug] Writing stream to output
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 511 to queue
[stream.hls][debug] Adding segment 512 to queue
[stream.hls][debug] Download of segment 511 complete
[stream.hls][debug] Download of segment 512 complete
[cli][info] Player closed
[stream.hls][debug] Closing worker thread
[stream.hls][debug] Closing writer thread
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

**Comment by back-to** [comment] 2018-04-15 11:08
your `-l debug` doesn't print any versions, so you are below version `0.10.0`

use the last version

https://github.com/streamlink/streamlink/releases/latest

---

@dahjin 

typ
`streamlink --version` and you will see your version

if you are using version `0.9.0`
you might need to uninstall it first.

there was a bug in this version with a different install location

Here is a guide on how you can **uninstall** it

https://github.com/streamlink/streamlink/issues/1391#issuecomment-354275115

---

closing

**Closed by back-to** 2018-04-15 11:08 UTC
Labels: unconfirmed
