### ISSUE TITLE
flextv.co.kr

### ISSUE THREAD

**Issue by TaeDDin** [streamlink/streamlink#4476] opened 2022-04-19 14:50 UTC
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

a livestream site similar to Twitch or afreecaTV, mainly for "just chatting" streams. Some streams require a log in due to minor protection laws (drinking, smoking etc.).

### Input URLs

https://www.flextv.co.kr/
https://www.flextv.co.kr/channels/123456/live

**Comment by gravyboat** [comment] 2022-04-19 16:56
Duplicate of https://github.com/streamlink/streamlink/issues/4135, closing as wontfix.

**Closed by gravyboat** 2022-04-19 16:56 UTC
Labels: plugin request
