### ISSUE TITLE
Twitch streams showing Commercial Break In Progress video

### ISSUE THREAD

**Issue by sfkpmr** [streamlink/streamlink#2894] opened 2020-04-14 21:25 UTC
- [x] This is a bug report and I have read the contribution guidelines.

### Description

When launching a Twitch stream you're shown a Commercial Break video before the actual stream starts playing. This behavior started tonight.

### Expected / Actual behavior

The commercial video is expected to be ignored.

### Reproduction steps / Explicit stream URLs to test

Launch a Twitch stream.

### Log output

```
C:\Users\User>streamlink https://www.twitch.tv/esl_csgo best --loglevel debug
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.6
[cli][debug] Streamlink: 1.3.1
[cli][debug] Requests(2.22.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/esl_csgo
[plugin.twitch][debug] Getting live HLS streams for esl_csgo
[utils.l10n][debug] Language code: sv_SE
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p, 720p60, 1080p60 (best)
[cli][info] Opening stream: 1080p60 (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 0; Last Sequence: 2
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 0; End Sequence: None
[stream.hls][debug] Adding segment 0 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 1 to queue
[stream.hls][debug] Adding segment 2 to queue
[stream.hls][debug] Download of segment 0 complete
[cli][info] Starting player: "C:\Program Files\VideoLAN\VLC\vlc.exe"
[cli.output][debug] Opening subprocess: "C:\Program Files\VideoLAN\VLC\vlc.exe" --input-title-format https://www.twitch.tv/esl_csgo -
[stream.hls][debug] Download of segment 1 complete
[stream.hls][debug] Download of segment 2 complete
[cli][debug] Writing stream to output
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3 to queue
[stream.hls][debug] Download of segment 3 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 4 to queue
[stream.hls][debug] Adding segment 5 to queue
[stream.hls][debug] Adding segment 6 to queue
[stream.hls][debug] Download of segment 4 complete
[stream.hls][debug] Download of segment 5 complete
[stream.hls][debug] Download of segment 6 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 7 to queue
[stream.hls][debug] Adding segment 8 to queue
[stream.hls][debug] Download of segment 7 complete
[stream.hls][debug] Download of segment 8 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 9 to queue
[stream.hls][debug] Adding segment 10 to queue
[stream.hls][debug] Adding segment 11 to queue
[stream.hls][debug] Download of segment 9 complete
[stream.hls][debug] Download of segment 10 complete
[stream.hls][debug] Download of segment 11 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 12 to queue
[stream.hls][debug] Adding segment 13 to queue
[stream.hls][debug] Download of segment 12 complete
[stream.hls][debug] Download of segment 13 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 14 to queue
[stream.hls][debug] Adding segment 15 to queue
[stream.hls][debug] Adding segment 16 to queue
[stream.hls][debug] Download of segment 14 complete
[stream.hls][debug] Download of segment 15 complete
[stream.hls][debug] Download of segment 16 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 17 to queue
[stream.hls][debug] Adding segment 18 to queue
[stream.hls][debug] Download of segment 17 complete
[stream.hls][debug] Download of segment 18 complete
[cli][info] Player closed
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[stream.segmented][debug] Closing writer thread
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

[Screenshot](https://i.imgur.com/BbljzTw.png)

**Comment by DanielHouston** [comment] 2020-04-14 21:34
I'm experiencing this and also finding that once the stream loads, the audio is slightly pitched up?

**Comment by bastimeyer** [comment] 2020-04-14 21:34
Looks like Twitch has implemented a new embedded ads system again.

In #2372, we've added an HLS segment filter that could detect ad segments between certain HLS tags, so these ads could be ignored in the output stream. These tags however don't seem to exist anymore in the HLS playlist.

**Example HLS playlist**

```
$ curl -s $(streamlink --stream-url twitch.tv/CHANNEL_WITH_PREROLL_ADS best)
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:5
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-TWITCH-ELAPSED-SECS:12435.691
#EXT-X-TWITCH-TOTAL-SECS:12441.697
#EXT-X-START:TIME-OFFSET=0.000
#EXT-X-DATERANGE:ID="stitched-ad-1586899127-30197999985",CLASS="twitch-stitched-ad",START-DATE="2020-04-14T21:18:47.355Z",DURATION=30.198,X-TV-TWITCH-AD-AD-FORMAT="standard_video_ad",X-TV-TWITCH-AD-LINE-ITEM-ID="1985958650101",X-TV-TWITCH-AD-ORDER-ID="6733488350001",X-TV-TWITCH-AD-ADVERIFICATIONS="eyJ4bWxuczp4c2kiOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIsIlZlcmlmaWNhdGlvbiI6W3sidmVuZG9yIjoibW9hdC5jb20tb21zZGt0d2l0Y2hob3N0ZWRhbWF6b252aWRlbzk2MzM3MTgzODUyOCIsIkphdmFTY3JpcHRSZXNvdXJjZSI6W3siYXBpRnJhbWV3b3JrIjoib21pZCIsImJyb3dzZXJPcHRpb25hbCI6dHJ1ZSwiVVJJIjoiaHR0cHM6Ly96Lm1vYXRhZHMuY29tL29tc2RrdHdpdGNoaG9zdGVkYW1hem9udmlkZW85NjMzNzE4Mzg1MjgvbW9hdHZpZGVvLmpzIn1dLCJWZXJpZmljYXRpb25QYXJhbWV0ZXJzIjoie1wibW9hdENsaWVudExldmVsMVwiOlwiQWR2ZXJ0aXNlcklkXCIsXCJtb2F0Q2xpZW50TGV2ZWwyXCI6XCJPcmRlcklkXCIsXCJtb2F0Q2xpZW50TGV2ZWwzXCI6XCIxOTg1OTU4NjUwMTAxXCIsXCJtb2F0Q2xpZW50TGV2ZWw0XCI6XCI5MzY2MzYwMzczNzJcIn0ifV19",X-TV-TWITCH-AD-POD-LENGTH="1",X-TV-TWITCH-AD-POD-POSITION="0",X-TV-TWITCH-AD-URL="https://example.com",X-TV-TWITCH-AD-ADVERTISER-ID="5122870240601",X-TV-TWITCH-AD-CREATIVE-ID="936636037372",X-TV-TWITCH-AD-ROLL-TYPE="PREROLL",X-TV-TWITCH-AD-LOUDNESS="-52.25",X-TV-TWITCH-AD-CLICK-TRACKING-URL="https://example.com"
#EXT-X-DATERANGE:ID="source-1586899127",CLASS="twitch-stream-source",START-DATE="2020-04-14T21:18:47.355Z",END-ON-NEXT=YES,X-TV-TWITCH-STREAM-SOURCE="Amazon|936636037372"
#EXT-X-DATERANGE:ID="trigger-1586899127",CLASS="twitch-trigger",START-DATE="2020-04-14T21:18:47.355Z",END-ON-NEXT=YES,X-TV-TWITCH-TRIGGER-URL="https://video-weaver.fra06.hls.ttvnw.net/trigger/CoYDN_6IqMMq3EzZ_PnQOxmwPJCAEYO9hUiLdQxb3ry4B_I2ysyYMy3w3YU8vtxg_fvglNcFeiIClmisA-wvu-NocKe8qvVgHsE_wK8-LPA9GXgT2JTC7K8igFFcG7LhIujhNJRMIvIlzLreUFycDTMWwXKKkaDTKvAroAQOnkmzuG2NU5WIElokIoffAvYnt2PP5HJnY-u3hbykV3m6OKyoWm3tv7Xkjperl6VF2SnLZr3luTGw5SRT0eGEhh9xN-37JfLDBgkH7UPVKKtu0d-mnEMew4w5pmOeXdkHxpj5XdZ6ieg1sjV4SYAVpVLM3cl8ak_TcMKtK-Vs-OokBynS3Det9xcOwNfpuHCbcDy9uJTVQ2q2pBgMNvpxCgq-_NqbzAqeIGi8IsWQ9tWMEEaMUisFvqLDtMCLsKVo4KRGpnvFUDYCW6gPe-T78KQc5DjZu6KQ1sg7ibookcusaaVcucUjYmnfyiz1HOo1Ttydx2Lbc9YXn5l6xlYp2ar8-mIdCCmxxGqSEhCBwq1uaVKAx4YDjwt8z8pXGgw2d4n8IFNtbwqPNl4"
#EXT-X-DATERANGE:ID="quartile-1586899127-0",CLASS="twitch-ad-quartile",START-DATE="2020-04-14T21:18:47.355Z",DURATION=2.002,X-TV-TWITCH-AD-QUARTILE="0"
#EXT-X-DISCONTINUITY
#EXT-X-PROGRAM-DATE-TIME:2020-04-14T21:18:47.355Z
#EXTINF:2.002,Amazon|936636037372
https://video-edge-c2ac3c.fra02.abs.hls.ttvnw.net/v1/segment/CsYE2BpUXchZlaHgViGrudxI2Hk4jZ8Ocd7V73x0DJkF6RNF6oIHCbwXaNpft8-UwsZhxFsSHssiThTsi7zSTIxxCyfN2SWYw4WTYVkw9QpYWMXDhH8ikn6hGlIq3nV_UId-L1m9t4KYpA3-qIdCOCD21Mo_XAISGrzUR6oxnU9esS_87pzD-5mBg-_zTqkqEX35Xd81h7OpCUAXE1jmOqaoSkFod4ukLSsOuRDEEVl54dp6igosdgHLehx_L_7b_6jXBWCR7w3YxLn5cAxgFl8wp4aQFcPtiJjtXY-8s-cKAH3CjIbs7JOMsdtHdU24hUp87MdreJ2OEVlzP-yicyP5AgrtJX-KNEmHw-5SoMpvfObwIARJO4bSs91aCZLNgE_aLM-z_LBlypU2um7SGgjCpbzlP37rhy51wSXkCZFGa8_udLjR_YIEKoRYOOtH2QPxfYgPfYwC1DUafBWnaHS34LYAoYsDjQm7y2Zs0FIlTdJb1mgIfbNMYixQagMnh0xGRyJhFkvU-YhSMsN2OrAOytJ0bty_dARDYXePtZXOnTsh-pbGKtnWbSHJ1v8Xgl7YujW3-6dn2QXd5ZbTWKhhh5n0e81FHqeVNDzNuJAIjPKX4SSggMc9fCnoYE82AM4aKJ1miPfJfp7tDa54oSIy9B1lGwQOBUpiAHV1Ts3ZGpXrIBssyYl0ML85vf9zdwb0z874XGIhr9XVXzpWYJVSKOKVaHsmosxxQ7zncUCxLOKIz3_KQBTIzjAWxOnVUT5fh-7U0D-QEhDPebV1GnPnGRdgtXP66QL2Ggyl9-qKt5naNADMvzI.ts
#EXT-X-PROGRAM-DATE-TIME:2020-04-14T21:18:49.356Z
#EXTINF:2.002,Amazon|936636037372
https://video-edge-c2ac3c.fra02.abs.hls.ttvnw.net/v1/segment/CrsDKfGgfAI3X3UdcNvtkqtXIrkZc8jyEiYTmy8VIsFEabq1fqncpfr5L4ETPREoASsONtCK4N7mVM8rIjMQkE06oelq7G2AuOBwmRWn8jniZJf8y1g1kxfTIsE4oYDWi_3-4NxCE9QMmGXLhyqIfZoXmHoqA_hg3ndBohDXF17KauJaQJmugyDuMDyXvNV_NpTsjzACG93oJ3L0DAeT251hNHxD6ljVIe80UvZviV3_6NKqV89fAznDjYLoFTGQJML9MdVxtEVc3uEh4qVwU7-GjuhLL0Rpnu_Sb0a8lNAEysc9N_DaheYv7jz9sOKAS9exIBW3AAIJbfnqT1NxAv7J-Omw-1ZrbO3xqMLYWSDNXsu_rALdR839OVlgChe-CHJljZIaKHuKOLNEKKCCKVgrxAHRuMAsl3jCFPX107dkAdY4kpCBmcydZ4QaP7_cydpENlrFCzuzoNIgtsohQjXRwQIkavZh5WyTfToCwfoOlZqC2cyxQjWtSWw4HB7350hnB3tBL3XJYfKykvHuShuz1jJTJ2nXjK-bR5IO5VsEIvTqh8oKakuI71L6KDIp1Zz5PH4jHmwY1gtzcegSEE_Xvg6i3IuooX6qEsGVoZYaDIZipqY8rYGeWdQslA.ts
#EXT-X-PROGRAM-DATE-TIME:2020-04-14T21:18:51.358Z
#EXTINF:2.002,Amazon|936636037372
https://video-edge-c2ac3c.fra02.abs.hls.ttvnw.net/v1/segment/CrsDgCt3TVmLthbAPpSmkD6uMWeq-T33VEmFJjfxsnS_Au7ZsYbSOyFzxulBYER80OxzCuqs2DXCH7fPExu4Q4yQYLdS_BJjNJFzm7MS3aVV2twwLd8IJTK2q5JseQ1_Z7r5_68hOdh3C0twR22AM9WiySzZyvRHc1Dc_A6VmgDUUR4JF8dF-v_0cUnBo8LaFLc55r2X41xODYt6qIst9LuQEjB69Ey8IeUSBYhYhzztaUKT00x9YffNFUEb3AQuL5Yc2tySq6Px4ZgJUACDlsgRk7cOW3o-hUFyRXfY40W-SnDOAsYW8LbcF_fxHQxr834M0rdNA7Ojzf4udhTDrhCzDoS1H_wDGjZbmTlnW0NNWyD-LGQIHhDpdwoIVnmwOv91R9qayJT2PCGA3aacOKu2zULUAh4UVD81maewSsi_Cs-28UekG2pYxXQz7pgU89vp6FANnXU9qGa7nYN8KBZ2db-kvjFyI4lMIjofDUUml1eZkylprtdpx21UuM9ePgd4PZKpaAnNoI1T7g0BhUZnzxdhKR1d4DHeUdVPp4wOfEAj3KiM0gN7xdMqVIGW78B0NB3my1IFuj9QryYSEBEnZkzyqjGwl9FK8yM5bHcaDOFe3NE2T_KDw4g8sw.ts
```

The "Commerical Break In Progress" video-loop segments are all annotated like this:
`#EXTINF:2.002,Amazon|936636037372`

**Comment by sfkpmr** [comment] 2020-04-14 21:34
> the audio is slightly pitched up?

I noticed this as well.

**Comment by bastimeyer** [comment] 2020-04-14 21:37
> the audio is slightly pitched up

Which player are you using? VLC? VLC doesn't handle stream discontinuities well. Use a different player if you're using VLC.

**Comment by sfkpmr** [comment] 2020-04-14 21:41
Got it! Works fine in MPC.

**Comment by dCosminn** [comment] 2020-04-14 21:44
> 
> 
> > the audio is slightly pitched up
> 
> Which player are you using? VLC? VLC doesn't handle stream discontinuities well. Use a different player if you're using VLC.

I have the same issue with MPC-HC

**Comment by FractalHippy** [comment] 2020-04-14 22:03
It's happening on all players for me, can't watch any stream as all show "Commercial Break In Progress".

**Comment by bastimeyer** [comment] 2020-04-14 22:18
@dCosminn Use MPV. There also can't be any buffering issues, because this new ad system is completely transparent to Streamlink and it's continuing regularly when the real stream data is made available by Twitch. There is a stream discontinuity though, so it's possible that your player is buffering because of the invalid timestamps.

@FractalHippy This has nothing to do with the player you're using, Twitch is simply serving this video data instead of the real stream content. There is nothing that can be done on the client side, just like watching regular TV. All that can be done is ignoring these HLS segments in the stream output or finding a way of making Twitch serve the actual stream data, which is unlikely, as they are in control with the stream access tokens needed for getting the stream data.

What surprises me though is that the Twitch website is showing HLS playlists with normal data. Unfortunately, I don't see anything special in the request data.

**Comment by 4dams** [comment] 2020-04-14 22:21
Same thing happening here, too. Here's what I'm running:

```
streamlink --twitch-oauth-token <TOKEN> --twitch-disable-ads  twitch.tv/parnstarzilean audio_only
```

I even tried and logged in with an account and purchased Turbo for it which supposedly won't show ads, which didn't work either.

**Comment by JambiBum** [comment] 2020-04-14 22:25
I figured out how to fix the pitch issue with the audio once the stream loads from the ad break in VLC. You need to disable the audio track under the audio menu and then enable it again. For whatever reason the audio issue only happens on some streams but the ad part happens on all of them.

**Comment by bluewww** [comment] 2020-04-14 22:25
@dCosminn You can use vlc with the HLS passtrough option. This seems to work fine

**Comment by arrowgent** [comment] 2020-04-14 22:26
way to go twitch.  prime, turbo, and subscriptions still get ads...

**Comment by bastimeyer** [comment] 2020-04-14 22:34
Please **don't** post "+1", "same", "me too" or other unrelated stuff. It's **not** useful and just spams the thread.

----

@4dams Authentication is **not** supported anymore since Streamlink's `1.3.0` release and using the parameters doesn't have any effect anymore, as you can read here:
https://github.com/streamlink/streamlink/issues/2680#issuecomment-557605851
Also #2846

----

I'm currently working on a patch that blocks the "Commerical Break In Progress" segments. It's already working but not yet finished. Problem is that it delays the stream launch until the real stream is available, which can take up to half a minute. Should fix any player issues caused by the stream discontinuity though.

**Comment by DanielHouston** [comment] 2020-04-14 22:36
> @dCosminn You can use vlc with the HLS passtrough option. This seems to work fine.

FYI Letting VLC handle the stream using `--player-passthrough hls` resolves both the "lagging"/"buffering" and the audio pitching for me. Everything working as before after an initial 30 seconds or so of "Commercial Break in Progress"

**Comment by 4dams** [comment] 2020-04-14 22:41
@bastimeyer Thanks a lot for your fast help and for working on this project at this hour! :)

> @4dams Authentication is **not** supported anymore since Streamlink's `1.3.0` release and using the parameters doesn't have any effect anymore, as you can read here:
> [#2680 (comment)](https://github.com/streamlink/streamlink/issues/2680#issuecomment-557605851)
> Also #2846

I just scrolled through the docs and found these options, I thought they were still working.

As for your patch: Is there any way to work around the delay and get to the main video directly? I'm sorry if that's too much to ask yet, I'm not very familiar with all this. 😟

Thanks again!

**Comment by D3lt4y** [comment] 2020-04-15 00:14
Not sure if this is helpful but I went back to the old 1.2.0 version of streamlink with the workaround described here https://github.com/streamlink/streamlink/issues/2680#issuecomment-552024753 and its working without any issues or breaks (also no delay on launching a stream)

**Comment by 4AM-Campfire** [comment] 2020-04-15 04:32
The ads (well, the purple screen) seem to have stopped for me, both the pre- and mid-steam ones. The channels where I consistently saw them earlier no longer show them.

I've changed nothing on my end.

**Comment by Digitalone1** [comment] 2020-04-15 10:06
I'm having this issue by yesterday and, as someone have already states, the commercial break was also showing in the middle of the stream.

> I'm currently working on a patch that blocks the "Commerical Break In Progress" segments. It's already working but not yet finished. Problem is that it delays the stream launch until the real stream is available, which can take up to half a minute. Should fix any player issues caused by the stream discontinuity though.

But skipping these segments means that, when the break is in the middle, the stream is temporarily stopped until the break is finished?

**Comment by bastimeyer** [comment] 2020-04-15 13:04
Pull request with the new ad filter logic is here, btw: #2895 

@4AM-Campfire Just like last year when they first implemented embedded ads, they tested it in several waves, so it's just a matter of time when it'll start again.

@Digitalone1 As mentioned earlier, there is no other way, as Twitch simply doesn't provide the regular stream data while the ads are playing, like on regular TV. The filtering is just there for players which otherwise break while decoding a stream discontinuity (switch from ad to regular stream without additional metadata). Authentication for prime users, etc. in order to potentially prevent seeing ads is unfortunately off the table due to #2680 / #2846. You can try setting a custom HTTP header with an OAuth token (one from a login on their website) which will be included in the stream access token request, but I'm not sure if this will work. Regular auth methods won't (or rather can't) be supported.

**Comment by S0und** [comment] 2020-04-15 15:16
I'm circumvented it by changing the hls url to this: 

"https://api.twitch.tv/api/channels/" + streamerName + "/access_token?**platform=_**";

**Comment by Digitalone1** [comment] 2020-04-15 15:25
I'm running the latest stable version on Arch Linux, did some tests and seems that the commercial breaks are not inserted, at least for now.

Maybe it was only a temporary change by Twitch, but we will find in the next days.

**Comment by bastimeyer** [comment] 2020-04-15 15:35
@S0und we tried that already last year and Twitch quickly patched it:
https://github.com/streamlink/streamlink/issues/2357#issuecomment-474044718
You're probably not seeing any ads right now, because they currently don't embed ads.

**Comment by S0und** [comment] 2020-04-15 15:51
@bastimeyer 
Keep in mind i'm developing my own twitch app  i don't use streamlink.

That's weird because i patched it yesterday while this "Commercial Break In Progress" was live supplying the Twitch's own Client-ID, and worked, switching back and forth with my "old" url and the "new" one.

**Closed** 2020-04-21 00:11 UTC
Labels: plugin issue

**Comment by 4dams** [comment] 2020-09-14 05:19
It seems like this is happening again :(

**Comment by gravyboat** [comment] 2020-09-14 05:58
Locking, please see the pinned issue: https://github.com/streamlink/streamlink/issues/3120
