### ISSUE TITLE
Twitch streams fail to open randomly

### ISSUE THREAD

**Issue by CarlosCB1986** [streamlink/streamlink#780] opened 2017-04-09 21:15 UTC
----

### Checklist

- [x] This is a bug report.
- [ ] This is a plugin request.
- [ ] This is a feature request.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description

Streams fail to open randomly.

### Expected / Actual behavior

When trying to launch a stream I often get the error shown in the log section below.

### Reproduction steps / Stream URLs to test

I haven't found a pattern as it happens randomly, but if I try to launch the stream again right after I get the error, it always works fine. It does not happen with one stream in particular, I have tried several ones and it occurs randomly with all of them.

Basically, it doesn't always happen, and when it does, it works fine if I launch it again.

### Environment details (operating system, python version, etc.)

Win7 SP1 x64, VLC 2.2.4, Streamlink 0.5.0

### Comments, logs, screenshots, etc.
This is the command executed:
C:\Program Files (x86)\Streamlink\bin\streamlink.exe --twitch-oauth-token ***** --loglevel=debug --player="C:\Program Files (x86)\VideoLAN\VLC\vlc.exe --demux=avformat --file-caching=5000 --network-caching=5000 --meta-title=pokerstaples" twitch.tv/pokerstaples best,source,1080p60,1080p,high,720p60,720p30,720p,540p30,medium,480p30,360p30,low,240p30,mobile,144p30,worst

This is the result I often get:
[cli][info] Found matching plugin twitch for URL twitch.tv/tonkaaaap
[plugin.twitch][debug] Getting live HLS streams for tonkaaaap
[plugin.twitch][info] Attempting to authenticate using OAuth token
[plugin.twitch][info] Successfully logged in as [StreamPlayer]
error: Unable to open URL: https://usher.ttvnw.net/api/channel/hls/tonkaaaap.m3u8?allow_audio_only=true&p=877950&type=any&sig=90d75d155a8e3558b3e984c9b5c0f591a6940b28&allow_source=true&player=twitchweb&allow_spectre=false&token=%7B%22adblock%22%3Afalse%2C%22player_type%22%3Anull%2C%22platform%22%3Anull%2C%22user_id%22%3A141637440%2C%22channel%22%3A%22tonkaaaap%22%2C%22channel_id%22%3A110298250%2C%22expires%22%3A1491772282%2C%22chansub%22%3A%7B%22view_until%22%3A1924905600%2C%22restricted_bitrates%22%3A%5B%5D%7D%2C%22private%22%3A%7B%22allowed_to_view%22%3Atrue%7D%2C%22privileged%22%3Anull%2C%22source_restricted%22%3Afalse%2C%22https_required%22%3Afalse%2C%22show_ads%22%3Atrue%2C%22device_id%22%3Anull%2C%22prerolls_disabled%22%3Afalse%2C%22postrolls_disabled%22%3Afalse%2C%22turbo%22%3Afalse%2C%22subscriber%22%3Afalse%2C%22hide_ads%22%3Afalse%7D (('Connection aborted.', ConnectionResetError(10054, 'Se ha forzado la interrupci�n de una conexi�n existente por el host remoto', None, 10054, None)))

**Comment by gravyboat** [comment] 2017-04-15 01:52
Looking at that error with my limited Spanish knowledge and Google Translate this looks like the edge server you're connecting to is the problem and not something Streamlink is doing.

**Comment by CarlosCB1986** [comment] 2017-04-27 08:28
Well, the only spanish present in the error message ("'Se ha forzado la interrupci�n de una conexi�n existente por el host remoto'") is easily translated into the following generic error: "An existing connection has been interrupted by the remote host".

I'm not sure what you mean by edge server, but I don't think I can choose which server I connect to. If you are referring to the specific stream I am trying to watch, it doesn't really matter, as it happens randomly with any stream I try.

The problem is that I am getting this error randomly even using the most basic Streamlink command to launch a twitch stream, so I don't think this error is caused by anything that I am doing wrong.

The question is, if there is nothing that Streamlink is doing wrong and I don't seem to be doing anything wrong, is this just a problem with Twitch servers? and in that case, is there anyone else encountering this same issue?

**Comment by bastimeyer** [comment] 2017-05-26 16:00
> I am getting this error randomly

This sounds like an issue within the Twitch network in your region. Since Twitch streams are working everywhere else, I doubt this is an issue related to Streamlink.

I'm closing the thread for now. If this issue persists and if you think that it's definitely caused by Streamlink's code, please feel free to reopen.

**Closed by bastimeyer** 2017-05-26 16:00 UTC
