### ISSUE TITLE
segmentation error with LANG=fr_FR.iso885915@euro

### ISSUE THREAD

**Issue by novazur972** [streamlink/streamlink#4562] opened 2022-05-31 17:07 UTC
### Checklist

- [X] This is a bug report and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

Segmentation fault with my locale for several plugins (pluz, tf1)

$ locale
LANG=fr_FR.iso885915@euro
LC_CTYPE="fr_FR.iso885915@euro"
LC_NUMERIC="fr_FR.iso885915@euro"
LC_TIME="fr_FR.iso885915@euro"
LC_COLLATE=C
LC_MONETARY="fr_FR.iso885915@euro"
LC_MESSAGES="fr_FR.iso885915@euro"
LC_PAPER="fr_FR.iso885915@euro"
LC_NAME="fr_FR.iso885915@euro"
LC_ADDRESS="fr_FR.iso885915@euro"
LC_TELEPHONE="fr_FR.iso885915@euro"
LC_MEASUREMENT="fr_FR.iso885915@euro"
LC_IDENTIFICATION="fr_FR.iso885915@euro"
LC_ALL=

BUT works fine with LANG=C

$ LANG=C streamlink --loglevel debug http://www.france.tv/france-2/direct.html
[cli][debug] OS:         Linux-5.15.41-gentoo-x86_64-Intel-R-_Core-TM-_i5-9600K_CPU_@_3.70GHz-with-glibc2.34
[cli][debug] Python:     3.9.12
[cli][debug] Streamlink: 4.1.0
[cli][debug] Requests(2.27.1), Socks(1.7.1), Websocket(1.3.2)
[cli][debug] Arguments:
[cli][debug]  url=http://www.france.tv/france-2/direct.html
[cli][debug]  --loglevel=debug
[cli][debug]  --player=mpv
[cli][info] Found matching plugin pluzz for URL http://www.france.tv/france-2/direct.html
[plugins.pluzz][debug] Country: MQ
[plugins.pluzz][debug] Video ID: 006194ea-117d-4bcf-94a9-153d999c59ae
[utils.l10n][debug] Language code: en_US
[stream.hls][debug] Using external audio tracks for stream 144p (language=fra, name=1 Francais)
[stream.hls][debug] Using external audio tracks for stream 216p (language=fra, name=1 Francais)
[stream.hls][debug] Using external audio tracks for stream 360p (language=fra, name=1 Francais)
[stream.hls][debug] Using external audio tracks for stream 540p (language=fra, name=1 Francais)
[stream.hls][debug] Using external audio tracks for stream 720p (language=fra, name=1 Francais)
Available streams: 144p (worst), 216p, 360p, 540p, 720p (best)

### Debug log

```text
$ streamlink --loglevel debug http://www.france.tv/france-2/direct.html
[cli][debug] OS:         Linux-5.15.41-gentoo-x86_64-Intel-R-_Core-TM-_i5-9600K_CPU_@_3.70GHz-with-glibc2.34
[cli][debug] Python:     3.9.12
[cli][debug] Streamlink: 4.1.0
[cli][debug] Requests(2.27.1), Socks(1.7.1), Websocket(1.3.2)
[cli][debug] Arguments:
[cli][debug]  url=http://www.france.tv/france-2/direct.html
[cli][debug]  --loglevel=debug
[cli][debug]  --player=mpv
[cli][info] Found matching plugin pluzz for URL http://www.france.tv/france-2/direct.html
[plugins.pluzz][debug] Country: MQ
Erreur de segmentation

$ streamlink --loglevel debug https://www.tf1.fr/tf1/direct
[cli][debug] OS:         Linux-5.15.41-gentoo-x86_64-Intel-R-_Core-TM-_i5-9600K_CPU_@_3.70GHz-with-glibc2.34
[cli][debug] Python:     3.9.12
[cli][debug] Streamlink: 4.1.0
[cli][debug] Requests(2.27.1), Socks(1.7.1), Websocket(1.3.2)
[cli][debug] Arguments:
[cli][debug]  url=https://www.tf1.fr/tf1/direct
[cli][debug]  --loglevel=debug
[cli][debug]  --player=mpv
[cli][info] Found matching plugin tf1 for URL https://www.tf1.fr/tf1/direct
[plugins.tf1][debug] Found channel tf1
[plugins.tf1][debug] Got dash stream https://tf1-das-live-ssl.tf1.fr/video/O7QyCqQsLB04KV5BvQ263w/1654030789/out/v1/192e289f861a43739091437725f9c2b1/index.mpd
Erreur de segmentation
```

**Comment by bastimeyer** [comment] 2022-05-31 17:18
Not a bug in streamlink, but in lxml, its dependency for parsing XML and HTML.

For example, the [`tests/utils/test_parse.py::TestUtilsParse::test_parse_xml_entities_fail`](https://github.com/streamlink/streamlink/blob/ea7a243a11b33b6bbe4ae5163e94a8dffd4efd63/tests/utils/test_parse.py#L60) test fails with a SIGSEGV in `lxml._elementpath` and `lxml.etree`

```
$ LANG=fr_FR.iso885915@euro pytest tests/utils/test_parse.py::TestUtilsParse::test_parse_xml_entities_fail
============================================================= test session starts ==============================================================
platform linux -- Python 3.10.4, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/basti/repos/streamlink
plugins: requests-mock-1.9.3, cov-3.0.0
collected 1 item                                                                                                                               

tests/utils/test_parse.py Fatal Python error: Segmentation fault

Current thread 0x00007f8dc962b740 (most recent call first):
  File "/home/basti/repos/streamlink/src/streamlink/utils/parse.py", line 12 in _parse
  File "/home/basti/repos/streamlink/src/streamlink/utils/parse.py", line 83 in parse_xml
  File "/usr/lib/python3.10/unittest/case.py", line 201 in handle
  File "/usr/lib/python3.10/unittest/case.py", line 738 in assertRaises
  File "/home/basti/repos/streamlink/tests/utils/test_parse.py", line 60 in test_parse_xml_entities_fail
  File "/usr/lib/python3.10/unittest/case.py", line 549 in _callTestMethod
  File "/usr/lib/python3.10/unittest/case.py", line 591 in run
  File "/usr/lib/python3.10/unittest/case.py", line 650 in __call__
  File "/home/basti/venv/streamlink-310/lib/python3.10/site-packages/_pytest/unittest.py", line 327 in runtest
  File "/home/basti/venv/streamlink-310/lib/python3.10/site-packages/_pytest/runner.py", line 166 in pytest_runtest_call
  File "/home/basti/venv/streamlink-310/lib/python3.10/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/home/basti/venv/streamlink-310/lib/python3.10/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/home/basti/venv/streamlink-310/lib/python3.10/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/home/basti/venv/streamlink-310/lib/python3.10/site-packages/_pytest/runner.py", line 259 in <lambda>
  File "/home/basti/venv/streamlink-310/lib/python3.10/site-packages/_pytest/runner.py", line 338 in from_call
  File "/home/basti/venv/streamlink-310/lib/python3.10/site-packages/_pytest/runner.py", line 258 in call_runtest_hook
  File "/home/basti/venv/streamlink-310/lib/python3.10/site-packages/_pytest/runner.py", line 219 in call_and_report
  File "/home/basti/venv/streamlink-310/lib/python3.10/site-packages/_pytest/runner.py", line 130 in runtestprotocol
  File "/home/basti/venv/streamlink-310/lib/python3.10/site-packages/_pytest/runner.py", line 111 in pytest_runtest_protocol
  File "/home/basti/venv/streamlink-310/lib/python3.10/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/home/basti/venv/streamlink-310/lib/python3.10/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/home/basti/venv/streamlink-310/lib/python3.10/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/home/basti/venv/streamlink-310/lib/python3.10/site-packages/_pytest/main.py", line 347 in pytest_runtestloop
  File "/home/basti/venv/streamlink-310/lib/python3.10/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/home/basti/venv/streamlink-310/lib/python3.10/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/home/basti/venv/streamlink-310/lib/python3.10/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/home/basti/venv/streamlink-310/lib/python3.10/site-packages/_pytest/main.py", line 322 in _main
  File "/home/basti/venv/streamlink-310/lib/python3.10/site-packages/_pytest/main.py", line 268 in wrap_session
  File "/home/basti/venv/streamlink-310/lib/python3.10/site-packages/_pytest/main.py", line 315 in pytest_cmdline_main
  File "/home/basti/venv/streamlink-310/lib/python3.10/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/home/basti/venv/streamlink-310/lib/python3.10/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/home/basti/venv/streamlink-310/lib/python3.10/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/home/basti/venv/streamlink-310/lib/python3.10/site-packages/_pytest/config/__init__.py", line 164 in main
  File "/home/basti/venv/streamlink-310/lib/python3.10/site-packages/_pytest/config/__init__.py", line 187 in console_main
  File "/home/basti/venv/streamlink-310/bin/pytest", line 8 in <module>

Extension modules: lxml._elementpath, lxml.etree (total: 2)
fish: Job 1, 'LANG=fr_FR.iso885915@euro pytes…' terminated by signal SIGSEGV (Address boundary error)
```

You'll have to report this on the lxml bug tracker:
- https://lxml.de/
- https://github.com/lxml/lxml
- https://bugs.launchpad.net/lxml

**Comment by bastimeyer** [comment] 2022-05-31 18:46
Building lxml from the master branch with an updated cython install should fix the issue. The next lxml version 4.9.0 hasn't been released yet, which will include the bugfixes.

```
$ pip install -U --upgrade-strategy=eager cython
$ pip install -U --upgrade-strategy=eager --no-binary=:all: git+https://github.com/lxml/lxml.git#branch=master
```

```
$ LANG=fr_FR.iso885915@euro python -c 'from lxml.etree import XML; XML("<foo bar=&>")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "src/lxml/etree.pyx", line 3233, in lxml.etree.XML
  File "src/lxml/parser.pxi", line 1913, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1793, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1082, in lxml.etree._BaseParser._parseUnicodeDoc
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: AttValue: " or ' expected, line 1, column 10
```

Alternatively, wheel build artifacts are available here:
https://github.com/lxml/lxml/actions/runs/2413435651

Since this affects the current appimages and windows installers as they don't include self-built wheels of streamlink's dependencies, I will keep the thread open until lxml 4.9.0 has been released, so they can be bumped.

**Comment by novazur972** [comment] 2022-05-31 18:49
Thank you very much for the consideration and the explanations. I do not extend more considering my level of English.

**Comment by bastimeyer** [comment] 2022-05-31 23:25
lxml 4.9.0 has been released with the bugfixes. Please upgrade your streamlink install and its dependencies in order to fix the issue.

4.1.0-2 AppImage and Windows installer builds have been published with the upgraded lxml version.

**Closed by bastimeyer** 2022-05-31 23:25 UTC
Labels: bug, dependencies
