### ISSUE TITLE
Stucks when it comes to 'Available streams: replay (worst, best)'

### ISSUE THREAD

**Issue by strwyn** [streamlink/streamlink#1139] opened 2017-08-03 17:02 UTC
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*
*Also check the list of known issues before reporting an issue!*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

I input the following command to download a video stream:
streamlink https://www.pscp.tv/[usernamehidden]/1OyKArqmgVbGb?autoplay&t=0 best -o file.ts

### Expected / Actual behavior

It worked for the last two months, in Win vista.
And worked a week ago on Mac OSX 10.9.5

and today the terminal output came as:

mav1s-air:~ mav2$ streamlink https://www.pscp.tv/[usernamehidden]/1OyKArqmgVbGb?autoplay&t=0 best -o 802.ts
[1] 634
-bash: best: command not found
mav1s-air:~ mav2$ [cli][info] Found matching plugin periscope for URL https://www.pscp.tv/[usernamehidden]/1OyKArqmgVbGb?autoplay
[plugin.periscope][info] Live Stream ended, using replay instead
Available streams: replay (worst, best)

...and stucked here forever.

### Reproduction steps / Explicit stream URLs to test

streamlink https://www.pscp.tv/[usernamehidden]/1OyKArqmgVbGb?autoplay&t=0 best -o file.ts

### Environment details

Operating system and version: Mac OSX 10.9.5
Streamlink and Python version: Streamlink 0.7.0, Python 2.7

...

### Comments, logs, screenshots, etc.

...

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment] 2017-08-03 17:03
Try quoting the URL.

**Comment by strwyn** [comment] 2017-08-03 17:06
Alright I got the solution when I was writing this thread. LMAO

Just delete '?autoplay' and following characters in the URL.

May the owner retain this thread in case other users encounter this very same issue.

Many thanks.

**Comment by gravyboat** [comment] 2017-08-03 17:10
This is actually a duplicate that we've seen quite a few times so it will remain, but I'm going to close it out.

**Closed by gravyboat** 2017-08-03 17:10 UTC
Labels: question

**Comment by strwyn** [comment] 2017-08-03 17:18
Would you please provide the original thread of this duplicate?
And will streamlink detect and dodge this bug in the future.
Thank you. @gravyboat

**Comment by gravyboat** [comment] 2017-08-03 17:22
I don't have time to look for the other instances of this right now unfortunately (it should be somewhere in the closed issues, it's a question that has come up a few times). From what I remember on the discussion before it isn't something that we're going to address since the problem is how `&` can be used. I'll try to remember to look later, you can probably find it as well in the closed issues if you have time.

**Comment by bastimeyer** [comment] 2017-08-03 17:24
This is not a bug, that's a feature of the command line shell you're using...

https://github.com/streamlink/streamlink/issues?q=shell
https://github.com/streamlink/streamlink/issues?q=escape
https://github.com/streamlink/streamlink/issues?q=ampersand
https://github.com/streamlink/streamlink/issues/1125#issuecomment-318652143

**Comment by gravyboat** [comment] 2017-08-03 17:35
@bastimeyer We should probably add a note in the docs somewhere to further emphasize this as it comes up a lot.

**Comment by strwyn** [comment] 2017-08-03 17:40
@bastimeyer believe you are right. Quote the URL and it works well. Was using the default Terminal (ver 2.4), Mac OSX 10.9.5. What's weird is that I don't need to quote the URL if I am on Windows...
@gravyboat Just what I was thinking.
Still, help much appreciated from you guys.
