### ISSUE TITLE
small documentation fix

### ISSUE THREAD

**Issue by ukoz** [streamlink/streamlink#882] opened 2017-05-04 15:22 UTC
- [ ] This is a bug report.
- [x] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

Hello.
Please, change documentation
https://streamlink.github.io/cli.html
there example for `stream-sorting-excludes`
`stream-sorting-excludes=">720p,>high"` not works
correct syntax in streamlinkrc file (Windows 7) will be
`stream-sorting-excludes=720p60,1080p30,1080p60`
`stream-sorting-excludes=>720p`   --- this is actually correct syntax but not change "[cli][info] Available streams" list. don't know how it should work this way. example http://www.twitch.tv/cohhcarnage

also for `default-stream`
please, note it support multiple parameters, like
`default-stream=720p30,720p_alt,high,720p,480p,480p30,best,source`

It actually kind of important, because when you trying to make some resolution/bitrate priority on default it never said you can make it via `default-stream`. Making some `stream-sorting-excludes` lists don't to job because you still want to allow higher resolutions when no 720p30 avail.

**Comment by bastimeyer** [comment] 2017-05-04 15:40
No, the documentation is correct. 

> Fine tune best/worst synonyms by excluding unwanted streams.

`--stream-sorting-excludes` doesn't filter the available qualities, but instead is being used for filtering the `best` and `worst` quality aliases. If you're using this parameter, you need to use the `best` or `worst` quality selector to get the matched streams.

And since Twitch is using different quality formats (by resolution, by resolution+framerate and by name), you need to always specify the framerate in the explicit formats and also select the old quality names in addition to that.

See here:
https://github.com/streamlink/streamlink/issues/828#issuecomment-297419286

The `--default-stream` parameter behaves exactly the same the the normal quality selection after the stream URL. It's just there for being able to define default quality selections in the config file.

**Comment by bastimeyer** [comment] 2017-05-04 15:48
And depending on your shell, `--stream-sorting-excludes=">720p,>high"` will be interpreted as two parameters `--stream-sorting-excludes=` and `>720p,>high`.

```
# single quoted parameter with an equal sign splitting parameter name and value
"--stream-sorting-excludes=>720p,>high"
'--stream-sorting-excludes=>720p,>high'

# two (quoted) parameters with the first one expecting a second one containing the values
--stream-sorting-excludes ">720p,>high"
--stream-sorting-excludes '>720p,>high'
"--stream-sorting-excludes" ">720p,>high"
'--stream-sorting-excludes' '>720p,>high'

# on unquoted parameters, ">" needs to be escaped if the shell interprets ">" as a pipe-to-file symbol
--stream-sorting-excludes=\>720p,\>high
```

**Comment by ukoz** [comment] 2017-05-04 18:10
> The --default-stream parameter behaves exactly the same the the normal quality selection after the stream URL. It's just there for being able to define default quality selections in the config file.

you can
`default-stream=720p30,720p_alt,high,720p,480p,480p30,best,source`
in _config file_ , while it not allowed to
`Streamlink.exe http://www.twitch.tv/cohhcarnage 720p30,720p_alt,high,720p,480p,480p30,best,source`

also in streamlinkrc you don't have to quote param text

my initial post was related to config rc file...
why would you --extra_param every launch instead

**Comment by bastimeyer** [comment] 2017-05-09 18:46
> while it not allowed to

I don't understand what you're trying to say. The parameter works as intended:

```
$ streamlink twitch.tv/monstercat does-not-exist,another-fake-quality,best
[cli][info] Found matching plugin twitch for URL twitch.tv/monstercat
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (hls)
```

```
$ streamlink --default-stream does-not-exist,another-fake-quality,best twitch.tv/monstercat
[cli][info] Found matching plugin twitch for URL twitch.tv/monstercat
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (hls)
```

Since I've answered your question a couple of days ago on how to correctly filter streams (see the linked comment), can this issue be closed now?

**Closed** 2017-05-10 01:02 UTC
Labels: question
