### ISSUE TITLE
  .

### ISSUE THREAD

**Issue by zmho12** [streamlink/streamlink#1098] opened 2017-07-15 06:48 UTC

**Comment by gravyboat** [comment] 2017-07-15 07:20
I honestly have no idea what you're asking or what this issue is relating to. If you're noting an issue with the plugin please clearly state what the problem is. It seems like you're asking us to provide another IP address for afreeca? If that's the case we can't provide that sort of support as it's far out of scope.

**Closed** 2017-07-22 11:04 UTC
Labels: more info required
