### ISSUE TITLE
Connection drops on when network has higher loads when using recent streamlink versions

### ISSUE THREAD

**Issue by chorong761** [streamlink/streamlink#3865] opened 2021-07-13 22:34 UTC
### Checklist

- [X] This is a bug report and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

When I first started using streamlink, i used 2.0.0 without any issues. Due to the youtube issues recently, I had to upgrade to never versions like 2.1.2 or 2.2.0. Ever since updating to the newer versions, streaming something like afreecaTV would drop when the network is on a high load (upload used).

I have done some tests with the same link, 10 copies of the same link/stream (1920x1080, 8000K) with streamlink 2.2.0. Below are the log for one of the instance of the 10 copies I've tested when i started "disconnecting". This issue started happening before 2.2.0 but after 2.0.0 (I've only used 2.1.2 and 2.2.0 after 2.0.0) and both 2.1.2 and 2.2.0 would have the same issue. 

I've tried reverting to streamlink 2.0.0 and it would not disconnect like this even during "high network loads". During the disconnect, my internet connection did not drop and other programs like youtube-dl still runs fine without disconnects. What I have noticed is the @xx KB/s is much higher with 2.0.0 around 1.0MB/s vs 2.2.0 3xx KB/s as shown in the log at the end. The test has been ran multiple times on different computers at multiple times of the day, and the results would still be 2.0.0 stable, 2.2.0 disconnect/timeout.

Tested on 3 different computers (Windows Server 2019 and Win 10 21H1) on a gigabit fibre connection. I don't have the skills to compile my own build so I could not test that. I could include the log for 2.0.0 if needed.

### Debug log

```text
Windows PowerShell
Copyright (C) Microsoft Corporation. 著作權所有，並保留一切權利。

請嘗試新的跨平台 PowerShell https://aka.ms/pscore6

PS C:\Users\Jian> streamlink https://play.afreecatv.com/poopoo01 best -o C:\Users\Jian\Desktop\poopoo01-$(get-date -f yyyy-MM-dd-HH-mm-ss).ts --loglevel debug
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.8.7
[cli][debug] Streamlink: 2.2.0
[cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(1.1.0)
[cli][debug] Arguments:
[cli][debug]  url=https://play.afreecatv.com/poopoo01
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --output=C:\Users\Jian\Desktop\poopoo01-2021-07-13-18-11-49.ts
[cli][debug]  --rtmp-rtmpdump=rtmpdump.exe
[cli][debug]  --rtmpdump=C:\Program Files (x86)\Streamlink\rtmpdump\rtmpdump.exe
[cli][debug]  --ffmpeg-ffmpeg=C:\Program Files (x86)\Streamlink\ffmpeg\ffmpeg.exe
[cli][info] Found matching plugin afreeca for URL https://play.afreecatv.com/poopoo01
[cli][info] Available streams: sd (worst), hd, original (best)
[cli][info] Opening stream: original (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 3774; Last Sequence: 3779
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 3777; End Sequence: None
[stream.hls][debug] Adding segment 3777 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 3778 to queue
[stream.hls][debug] Adding segment 3779 to queue
[stream.hls][debug] Download of segment 3777 complete
[cli][debug] Checking file output
[cli][debug] Writing stream to output
[stream.hls][debug] Download of segment 3778 complete
[download][..-2021-07-13-18-11-49.ts] Written 395.2 KB (0s @ 619.5 KB/s)                                               [stream.hls][debug] Download of segment 3779 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3780 to queue
[stream.hls][debug] Download of segment 3780 complete
[download][..-2021-07-13-18-11-49.ts] Written 1.4 MB (1s @ 991.1 KB/s)                                                 [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3781 to queue
[stream.hls][debug] Download of segment 3781 complete
[download][..-2021-07-13-18-11-49.ts] Written 1.8 MB (4s @ 440.0 KB/s)                                                 [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3782 to queue
[stream.hls][debug] Download of segment 3782 complete
[download][..-2021-07-13-18-11-49.ts] Written 2.3 MB (6s @ 360.5 KB/s)                                                 [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3783 to queue
[stream.hls][debug] Adding segment 3784 to queue
[stream.hls][debug] Download of segment 3783 complete
[download][..-2021-07-13-18-11-49.ts] Written 2.8 MB (9s @ 307.8 KB/s)                                                 [stream.hls][debug] Download of segment 3784 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3785 to queue
[stream.hls][debug] Download of segment 3785 complete
[download][..-2021-07-13-18-11-49.ts] Written 8.1 MB (10s @ 777.4 KB/s)                                                [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3786 to queue
[stream.hls][debug] Download of segment 3786 complete
[download][..-2021-07-13-18-11-49.ts] Written 10.4 MB (12s @ 795.0 KB/s)                                               [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3787 to queue
[stream.hls][debug] Download of segment 3787 complete
[download][..-2021-07-13-18-11-49.ts] Written 12.6 MB (15s @ 985.3 KB/s)                                               [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3788 to queue
[stream.hls][debug] Adding segment 3789 to queue
[stream.hls][debug] Download of segment 3788 complete
[download][..-2021-07-13-18-11-49.ts] Written 14.9 MB (19s @ 961.4 KB/s)                                               [stream.hls][debug] Reloading playlist
[stream.hls][debug] Download of segment 3789 complete
[download][..-2021-07-13-18-11-49.ts] Written 17.3 MB (20s @ 1.3 MB/s)                                                 [stream.hls][debug] Adding segment 3790 to queue
[stream.hls][debug] Download of segment 3790 complete
[download][..-2021-07-13-18-11-49.ts] Written 19.5 MB (22s @ 1.0 MB/s)                                                 [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3791 to queue
[stream.hls][debug] Download of segment 3791 complete
[download][..-2021-07-13-18-11-49.ts] Written 21.6 MB (23s @ 1.1 MB/s)                                                 [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3792 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3793 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3794 to queue
[stream.hls][debug] Adding segment 3795 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3796 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Download of segment 3792 complete
[download][..-2021-07-13-18-11-49.ts] Written 23.7 MB (34s @ 613.3 KB/s)                                               [stream.hls][debug] Adding segment 3797 to queue
[stream.hls][debug] Download of segment 3793 complete
[download][..-2021-07-13-18-11-49.ts] Written 26.1 MB (35s @ 746.1 KB/s)                                               [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3798 to queue
[stream.hls][debug] Download of segment 3794 complete
[download][..-2021-07-13-18-11-49.ts] Written 26.5 MB (36s @ 582.2 KB/s)                                               [stream.hls][debug] Download of segment 3795 complete
[download][..-2021-07-13-18-11-49.ts] Written 27.0 MB (37s @ 492.8 KB/s)                                               [stream.hls][debug] Reloading playlist
[stream.hls][debug] Download of segment 3796 complete
[download][..-2021-07-13-18-11-49.ts] Written 27.4 MB (38s @ 385.9 KB/s)                                               [stream.hls][debug] Adding segment 3799 to queue
[stream.hls][debug] Download of segment 3797 complete
[download][..-2021-07-13-18-11-49.ts] Written 27.9 MB (39s @ 820.4 KB/s)                                               [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3800 to queue
[stream.hls][debug] Download of segment 3798 complete
[download][..-2021-07-13-18-11-49.ts] Written 28.3 MB (41s @ 368.7 KB/s)                                               [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3801 to queue
[stream.hls][debug] Download of segment 3799 complete
[download][..-2021-07-13-18-11-49.ts] Written 29.9 MB (43s @ 471.6 KB/s)                                               [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3802 to queue
[stream.hls][debug] Download of segment 3800 complete
[download][..-2021-07-13-18-11-49.ts] Written 32.1 MB (45s @ 638.5 KB/s)                                               [stream.hls][debug] Download of segment 3801 complete
[download][..-2021-07-13-18-11-49.ts] Written 34.3 MB (47s @ 803.2 KB/s)                                               [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3803 to queue
[stream.hls][debug] Adding segment 3804 to queue
[stream.hls][debug] Download of segment 3802 complete
[download][..-2021-07-13-18-11-49.ts] Written 36.6 MB (49s @ 910.1 KB/s)                                               [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3805 to queue
[stream.hls][debug] Download of segment 3803 complete
[download][..-2021-07-13-18-11-49.ts] Written 38.9 MB (50s @ 1.2 MB/s)                                                 [stream.hls][debug] Download of segment 3804 complete
[download][..-2021-07-13-18-11-49.ts] Written 41.0 MB (51s @ 1.5 MB/s)                                                 [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3806 to queue
[stream.hls][debug] Download of segment 3805 complete
[download][..-2021-07-13-18-11-49.ts] Written 43.1 MB (52s @ 1.7 MB/s)                                                 [stream.hls][debug] Download of segment 3806 complete
[download][..-2021-07-13-18-11-49.ts] Written 45.3 MB (53s @ 1.9 MB/s)                                                 [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3807 to queue
[stream.hls][debug] Download of segment 3807 complete
[download][..-2021-07-13-18-11-49.ts] Written 47.5 MB (55s @ 1.6 MB/s)                                                 [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3808 to queue
[stream.hls][debug] Download of segment 3808 complete
[download][..-2021-07-13-18-11-49.ts] Written 49.4 MB (57s @ 1.4 MB/s)                                                 [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3809 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Download of segment 3809 complete
[download][..-2021-07-13-18-11-49.ts] Written 51.4 MB (1m4s @ 815.0 KB/s)                                              [stream.hls][debug] Adding segment 3810 to queue
[stream.hls][debug] Adding segment 3811 to queue
[stream.hls][debug] Adding segment 3812 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Download of segment 3810 complete
[download][..-2021-07-13-18-11-49.ts] Written 53.4 MB (1m6s @ 752.4 KB/s)                                              [stream.hls][debug] Adding segment 3813 to queue
[stream.hls][debug] Download of segment 3811 complete
[download][..-2021-07-13-18-11-49.ts] Written 55.4 MB (1m6s @ 746.2 KB/s)                                              [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3814 to queue
[stream.hls][debug] Adding segment 3815 to queue
[download][..-2021-07-13-18-11-49.ts] Written 57.6 MB (1m10s @ 710.6 KB/s)[stream.hls][debug] Download of segment 3812 complete
                                             [stream.hls][debug] Download of segment 3813 complete
[download][..-2021-07-13-18-11-49.ts] Written 59.6 MB (1m10s @ 796.4 KB/s)                                             [stream.hls][debug] Download of segment 3814 complete
[stream.hls][debug] Download of segment 3815 complete
[download][..-2021-07-13-18-11-49.ts] Written 63.8 MB (1m11s @ 1.6 MB/s)                                               [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3816 to queue
[stream.hls][debug] Download of segment 3816 complete
[download][..-2021-07-13-18-11-49.ts] Written 65.9 MB (1m13s @ 1.8 MB/s)                                               [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3817 to queue
[stream.hls][debug] Download of segment 3817 complete
[download][..-2021-07-13-18-11-49.ts] Written 68.0 MB (1m15s @ 1.5 MB/s)                                               [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3818 to queue
[stream.hls][debug] Download of segment 3818 complete
[download][..-2021-07-13-18-11-49.ts] Written 70.5 MB (1m17s @ 1.7 MB/s)                                               [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3819 to queue
[stream.hls][debug] Download of segment 3819 complete
[download][..-2021-07-13-18-11-49.ts] Written 72.9 MB (1m20s @ 1.3 MB/s)                                               [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3820 to queue
[stream.hls][debug] Download of segment 3820 complete
[download][..-2021-07-13-18-11-49.ts] Written 75.2 MB (1m22s @ 1.1 MB/s)                                               [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3821 to queue
[stream.hls][debug] Adding segment 3822 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3823 to queue
[download][..-2021-07-13-18-11-49.ts] Written 77.3 MB (1m27s @ 826.2 KB/s)                                             [stream.hls][debug] Download of segment 3821 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3824 to queue
[stream.hls][debug] Download of segment 3822 complete
[download][..-2021-07-13-18-11-49.ts] Written 79.3 MB (1m30s @ 793.1 KB/s)                                             [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3825 to queue
[stream.hls][debug] Download of segment 3823 complete
[download][..-2021-07-13-18-11-49.ts] Written 81.4 MB (1m31s @ 846.9 KB/s)                                             [stream.hls][debug] Download of segment 3824 complete
[download][..-2021-07-13-18-11-49.ts] Written 83.5 MB (1m32s @ 963.6 KB/s)                                             [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3826 to queue
[stream.hls][debug] Download of segment 3825 complete
[download][..-2021-07-13-18-11-49.ts] Written 85.6 MB (1m33s @ 986.2 KB/s)                                             [stream.hls][debug] Download of segment 3826 complete
[download][..-2021-07-13-18-11-49.ts] Written 87.8 MB (1m34s @ 1.5 MB/s)                                               [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3827 to queue
[stream.hls][debug] Download of segment 3827 complete
[download][..-2021-07-13-18-11-49.ts] Written 90.0 MB (1m36s @ 1.7 MB/s)                                               [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3828 to queue
[stream.hls][debug] Download of segment 3828 complete
[download][..-2021-07-13-18-11-49.ts] Written 92.2 MB (1m38s @ 1.4 MB/s)                                               [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3829 to queue
[stream.hls][debug] Adding segment 3830 to queue
[stream.hls][debug] Download of segment 3829 complete
[download][..-2021-07-13-18-11-49.ts] Written 94.4 MB (1m40s @ 1.3 MB/s)                                               [stream.hls][debug] Download of segment 3830 complete
[download][..-2021-07-13-18-11-49.ts] Written 96.1 MB (1m41s @ 1.3 MB/s)                                               [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3831 to queue
[stream.hls][debug] Download of segment 3831 complete
[download][..-2021-07-13-18-11-49.ts] Written 98.0 MB (1m42s @ 1.2 MB/s)                                               [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3832 to queue
[stream.hls][debug] Download of segment 3832 complete
[download][..-2021-07-13-18-11-49.ts] Written 100.0 MB (1m45s @ 1.1 MB/s)                                              [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3833 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3834 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Download of segment 3833 complete
[download][..-2021-07-13-18-11-49.ts] Written 102.0 MB (1m50s @ 829.0 KB/s)                                            [stream.hls][debug] Adding segment 3835 to queue
[stream.hls][debug] Download of segment 3834 complete
[download][..-2021-07-13-18-11-49.ts] Written 103.8 MB (1m54s @ 707.5 KB/s)                                            [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3836 to queue
[stream.hls][debug] Adding segment 3837 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3838 to queue
[stream.hls][debug] Download of segment 3835 complete
[download][..-2021-07-13-18-11-49.ts] Written 105.8 MB (1m57s @ 631.7 KB/s)                                            [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3839 to queue
[stream.hls][debug] Download of segment 3836 complete
[download][..-2021-07-13-18-11-49.ts] Written 107.8 MB (2m0s @ 569.2 KB/s)                                             [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3840 to queue
[stream.hls][debug] Download of segment 3837 complete
[download][..-2021-07-13-18-11-49.ts] Written 109.8 MB (2m3s @ 571.4 KB/s)                                             [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3841 to queue
[stream.hls][debug] Adding segment 3842 to queue
[stream.hls][debug] Download of segment 3838 complete
[download][..-2021-07-13-18-11-49.ts] Written 112.0 MB (2m5s @ 710.2 KB/s)                                             [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3843 to queue
[stream.hls][debug] Download of segment 3839 complete
[download][..-2021-07-13-18-11-49.ts] Written 114.1 MB (2m7s @ 838.5 KB/s)                                             [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3844 to queue
[stream.hls][debug] Download of segment 3840 complete
[download][..-2021-07-13-18-11-49.ts] Written 116.1 MB (2m8s @ 940.4 KB/s)                                             [stream.hls][debug] Download of segment 3841 complete
[download][..-2021-07-13-18-11-49.ts] Written 118.1 MB (2m9s @ 1.1 MB/s)                                               [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3845 to queue
[stream.hls][debug] Download of segment 3842 complete
[download][..-2021-07-13-18-11-49.ts] Written 120.2 MB (2m11s @ 1.3 MB/s)                                              [stream.hls][debug] Download of segment 3843 complete
[download][..-2021-07-13-18-11-49.ts] Written 122.4 MB (2m12s @ 1.5 MB/s)                                              [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3846 to queue
[stream.hls][debug] Download of segment 3844 complete
[download][..-2021-07-13-18-11-49.ts] Written 124.6 MB (2m13s @ 1.7 MB/s)                                              [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3847 to queue
[stream.hls][debug] Download of segment 3845 complete
[download][..-2021-07-13-18-11-49.ts] Written 126.8 MB (2m15s @ 1.6 MB/s)                                              [stream.hls][debug] Download of segment 3846 complete
[download][..-2021-07-13-18-11-49.ts] Written 128.9 MB (2m16s @ 1.6 MB/s)                                              [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3848 to queue
[stream.hls][debug] Download of segment 3847 complete
[download][..-2021-07-13-18-11-49.ts] Written 131.1 MB (2m17s @ 1.7 MB/s)                                              [stream.hls][debug] Download of segment 3848 complete
[download][..-2021-07-13-18-11-49.ts] Written 133.2 MB (2m18s @ 1.7 MB/s)                                              [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3849 to queue
[stream.hls][debug] Download of segment 3849 complete
[download][..-2021-07-13-18-11-49.ts] Written 135.3 MB (2m20s @ 1.4 MB/s)                                              [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3850 to queue
[stream.hls][debug] Adding segment 3851 to queue
[stream.hls][debug] Download of segment 3850 complete
[download][..-2021-07-13-18-11-49.ts] Written 137.4 MB (2m22s @ 1.4 MB/s)                                              [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3852 to queue
[stream.hls][debug] Download of segment 3851 complete
[download][..-2021-07-13-18-11-49.ts] Written 139.4 MB (2m24s @ 1.4 MB/s)                                              [stream.hls][debug] Download of segment 3852 complete
[download][..-2021-07-13-18-11-49.ts] Written 141.7 MB (2m25s @ 1.4 MB/s)                                              [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3853 to queue
[stream.hls][debug] Download of segment 3853 complete
[download][..-2021-07-13-18-11-49.ts] Written 143.9 MB (2m27s @ 1.2 MB/s)                                              [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3854 to queue
[stream.hls][debug] Download of segment 3854 complete
[download][..-2021-07-13-18-11-49.ts] Written 146.1 MB (2m29s @ 1.2 MB/s)                                              [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3855 to queue
[stream.hls][debug] Download of segment 3855 complete
[download][..-2021-07-13-18-11-49.ts] Written 148.1 MB (2m31s @ 1.2 MB/s)                                              [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3856 to queue
[stream.hls][debug] Download of segment 3856 complete
[download][..-2021-07-13-18-11-49.ts] Written 149.9 MB (2m34s @ 1.0 MB/s)                                              [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3857 to queue
[stream.hls][debug] Download of segment 3857 complete
[download][..-2021-07-13-18-11-49.ts] Written 151.9 MB (2m36s @ 933.2 KB/s)                                            [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3858 to queue
[stream.hls][debug] Download of segment 3858 complete
[download][..-2021-07-13-18-11-49.ts] Written 153.8 MB (2m38s @ 917.9 KB/s)                                            [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3859 to queue
[stream.hls][debug] Download of segment 3859 complete
[download][..-2021-07-13-18-11-49.ts] Written 155.8 MB (2m40s @ 891.5 KB/s)                                            [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3860 to queue
[stream.hls][debug] Download of segment 3860 complete
[download][..-2021-07-13-18-11-49.ts] Written 157.7 MB (2m43s @ 881.8 KB/s)                                            [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3861 to queue
[stream.hls][debug] Adding segment 3862 to queue
[stream.hls][debug] Download of segment 3861 complete
[download][..-2021-07-13-18-11-49.ts] Written 159.6 MB (2m45s @ 896.7 KB/s)                                            [stream.hls][debug] Reloading playlist
[stream.hls][debug] Download of segment 3862 complete
[download][..-2021-07-13-18-11-49.ts] Written 161.8 MB (2m46s @ 1.0 MB/s)                                              [stream.hls][debug] Adding segment 3863 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3864 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3865 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3866 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3867 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3868 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3869 to queue
[stream.hls][debug] Download of segment 3863 complete
[download][..-2021-07-13-18-11-49.ts] Written 163.7 MB (2m59s @ 482.0 KB/s)                                            [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3870 to queue
[stream.hls][debug] Adding segment 3871 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3872 to queue
[stream.hls][debug] Download of segment 3864 complete
[download][..-2021-07-13-18-11-49.ts] Written 165.6 MB (3m5s @ 414.9 KB/s)                                             [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3873 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3874 to queue
[stream.hls][debug] Download of segment 3865 complete
[download][..-2021-07-13-18-11-49.ts] Written 167.6 MB (3m8s @ 397.6 KB/s)                                             [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3875 to queue
[stream.hls][debug] Download of segment 3866 complete
[download][..-2021-07-13-18-11-49.ts] Written 169.7 MB (3m11s @ 384.3 KB/s)                                            [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3876 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Download of segment 3867 complete
[download][..-2021-07-13-18-11-49.ts] Written 171.8 MB (3m14s @ 354.9 KB/s)                                            [stream.hls][debug] Adding segment 3877 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3878 to queue
[stream.hls][debug] Download of segment 3868 complete
[download][..-2021-07-13-18-11-49.ts] Written 173.8 MB (3m17s @ 566.3 KB/s)                                            [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3879 to queue
[stream.hls][debug] Download of segment 3869 complete
[download][..-2021-07-13-18-11-49.ts] Written 176.1 MB (3m20s @ 713.3 KB/s)                                            [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3880 to queue
[stream.hls][debug] Adding segment 3881 to queue
[stream.hls][debug] Download of segment 3870 complete
[download][..-2021-07-13-18-11-49.ts] Written 178.3 MB (3m23s @ 732.3 KB/s)                                            [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3882 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3883 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3884 to queue
[stream.hls][debug] Download of segment 3871 complete
[download][..-2021-07-13-18-11-49.ts] Written 180.4 MB (3m29s @ 632.2 KB/s)                                            [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3885 to queue
[stream.hls][error] Failed to open segment 3872: Unable to open URL: http://pc-web.stream.afreecatv.com/live-stm-15/1920x1080/234482618-common-original-hls_3871_000000E9004A0043C2E95C7B736DF364.TS (400 Client Error: Bad Request for url: http://pc-web.stream.afreecatv.com/live-stm-15/1920x1080/234482618-common-original-hls_3871_000000E9004A0043C2E95C7B736DF364.TS?aid=.A32.7bbT56vyHM9fKZk.ujIgWbz_JRD2bakbLmEbyLwdpl_kaMpTx8tTzxmsJdJQ51Ik-1QZ2Z4rvq0EuFjgeCbQ41CuYAXVNDg5K1ZsqkfjoDxVz9eVRP9ReQ_6WtUy3ZEX_bloP-1OG9YSYWbN)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3886 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3887 to queue
[stream.hls][error] Failed to open segment 3873: Unable to open URL: http://pc-web.stream.afreecatv.com/live-stm-15/1920x1080/234482618-common-original-hls_3872_000000D0005300444F5E15C39FAFE806.TS (400 Client Error: Bad Request for url: http://pc-web.stream.afreecatv.com/live-stm-15/1920x1080/234482618-common-original-hls_3872_000000D0005300444F5E15C39FAFE806.TS?aid=.A32.7bbT56vyHM9fKZk.ujIgWbz_JRD2bakbLmEbyLwdpl_kaMpTx8tTzxmsJdJQ51Ik-1QZ2Z4rvq0EuFjgeCbQ41CuYAXVNDg5K1ZsqkfjoDxVz9eVRP9ReQ_6WtUy3ZEX_bloP-1OG9YSYWbN)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3888 to queue
[stream.hls][error] Failed to open segment 3874: Unable to open URL: http://pc-web.stream.afreecatv.com/live-stm-15/1920x1080/234482618-common-original-hls_3873_00000095000F00225DC5F82123243DB1.TS (400 Client Error: Bad Request for url: http://pc-web.stream.afreecatv.com/live-stm-15/1920x1080/234482618-common-original-hls_3873_00000095000F00225DC5F82123243DB1.TS?aid=.A32.7bbT56vyHM9fKZk.ujIgWbz_JRD2bakbLmEbyLwdpl_kaMpTx8tTzxmsJdJQ51Ik-1QZ2Z4rvq0EuFjgeCbQ41CuYAXVNDg5K1ZsqkfjoDxVz9eVRP9ReQ_6WtUy3ZEX_bloP-1OG9YSYWbN)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3889 to queue
[stream.hls][error] Failed to open segment 3875: Unable to open URL: http://pc-web.stream.afreecatv.com/live-stm-15/1920x1080/234482618-common-original-hls_3874_000000CD000C0085072D4AE02E821B41.TS (400 Client Error: Bad Request for url: http://pc-web.stream.afreecatv.com/live-stm-15/1920x1080/234482618-common-original-hls_3874_000000CD000C0085072D4AE02E821B41.TS?aid=.A32.7bbT56vyHM9fKZk.ujIgWbz_JRD2bakbLmEbyLwdpl_kaMpTx8tTzxmsJdJQ51Ik-1QZ2Z4rvq0EuFjgeCbQ41CuYAXVNDg5K1ZsqkfjoDxVz9eVRP9ReQ_6WtUy3ZEX_bloP-1OG9YSYWbN)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3890 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3891 to queue
[stream.hls][error] Failed to open segment 3876: Unable to open URL: http://pc-web.stream.afreecatv.com/live-stm-15/1920x1080/234482618-common-original-hls_3875_0000005F004C006708518931EED80A81.TS (400 Client Error: Bad Request for url: http://pc-web.stream.afreecatv.com/live-stm-15/1920x1080/234482618-common-original-hls_3875_0000005F004C006708518931EED80A81.TS?aid=.A32.7bbT56vyHM9fKZk.ujIgWbz_JRD2bakbLmEbyLwdpl_kaMpTx8tTzxmsJdJQ51Ik-1QZ2Z4rvq0EuFjgeCbQ41CuYAXVNDg5K1ZsqkfjoDxVz9eVRP9ReQ_6WtUy3ZEX_bloP-1OG9YSYWbN)
[stream.hls][debug] Adding segment 3892 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3893 to queue
[stream.hls][error] Failed to open segment 3877: Unable to open URL: http://pc-web.stream.afreecatv.com/live-stm-15/1920x1080/234482618-common-original-hls_3876_000000FA00B8006956A90668D67DA770.TS (400 Client Error: Bad Request for url: http://pc-web.stream.afreecatv.com/live-stm-15/1920x1080/234482618-common-original-hls_3876_000000FA00B8006956A90668D67DA770.TS?aid=.A32.7bbT56vyHM9fKZk.ujIgWbz_JRD2bakbLmEbyLwdpl_kaMpTx8tTzxmsJdJQ51Ik-1QZ2Z4rvq0EuFjgeCbQ41CuYAXVNDg5K1ZsqkfjoDxVz9eVRP9ReQ_6WtUy3ZEX_bloP-1OG9YSYWbN)
```

**Comment by bastimeyer** [comment] 2021-07-13 23:36
Duplicate of #3738

> 400 Client Error: Bad Request for url

Not a Streamlink bug. The server is responding with status code 400 and Streamlink can't retrieve the HLS segments.

The afreeca plugin got updated the last time in #3549, which was part of the `2.1.0` release, and the changes fixed #3538.

**Closed by bastimeyer** 2021-07-13 23:36 UTC
Labels: bug
