### ISSUE TITLE
[plugin issue] plugin.pandatv and URL with subdomain: Not a valid room url

### ISSUE THREAD

**Issue by stefan327** [streamlink/streamlink#1612] opened 2018-04-21 12:23 UTC
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description
Panda.tv changes more and more stream URLs, now using subdomains.
The pandatv plugin can´t handle the supdomain URLs.

### Actual behavior

Stream URL with subdomain does not work.
Error Message: [plugin.pandatv][info] ***Not a valid room url.***
(ex. URLs: https://xingyan.panda.tv/xingxiu.html)

Example:
[cli][info] Found matching plugin pandatv for URL https://xingyan.panda.tv/22571845
[plugin.pandatv][info] Not a valid room url.
error: No playable streams found on this URL: https://xingyan.panda.tv/22571845

### Environment

Operating system and version: Windows 7 x64
Newest streamlink

**Comment by Erk-** [comment] 2018-04-21 12:53
It is a bit of a mess, there are two differnt api's in use for the same set of urls. xingyan.panda.tv can be one of two api's, but both of them can be found by looking in the code of the html file. As far as I know you cant guess which one it is from the url alone.

**Comment by stefan327** [comment] 2018-04-21 16:48
@Erk-
Looking the html code of the new xingyan.panda.tv urls I cant find room_id, host_id, room_key and so on. But I can find the flv stream link directly. For example "http://flv-live-qn.xingxiu.panda.tv/panda-xingxiu/3a4da01471a2621fd062a42865647725.flv". 
Is there a possibility to use this information for streamlink to handle these streams?

**Comment by Erk-** [comment] 2018-04-21 22:59
I have not written anything for streamlink as I am not a big fan of the code in this project. I have worked on my own tool though. It should work for any panda.tv site. Be my guest and try it out https://gitlab.com/Erk/rsget There is an guide on how to install it in the reposetory.

**Comment by stefan327** [comment] 2018-04-22 15:02
Thank you @Erk- , at the next opportunity I will watch your project and try it out.

Nevertheless I'm interested in a solution with streamlink, maybe it is a simple plugin modification.
I wrote a software tool which uses streamlink as a helper task. It would the best for me streamlink can handle these new sites, so I would not have to change anything in my tool.

What I am wondering is that I can simply find the direct .flv links and download the files with firefox. Usually it's more complicated.

**Comment by unnutricious** [comment] 2018-04-24 12:06
As Erk mentioned, on first look, it seems that the xingyan subdomain has the flv link embedded in some json directly in the source starting with:
`<script>window.HOSTINFO=`

This seems to apply for both the 熊猫星秀  and 星颜 sections. So, even though the interface looks completely different, they seem to have the same backend design, which differs from the main site.

I was able to play one stream simply by passing in the flv url with no GET parameters. So, it seems like the logic could be fairly simple. Since the implementation for the rest of the site is fairly complicated, though, I wonder if we might need to do more to make it work reliably.

**Comment by fozzysec** [comment] 2018-06-18 19:27
When I was trying to fix another bug caused by indentation, I added the support for xingyan.panda.tv, the flash player directly use the http stream that embedded in the HTML source code.
#1822

**Comment by gravyboat** [comment] 2018-06-19 02:12
Closing since https://github.com/streamlink/streamlink/pull/1822 is merged.

**Closed by gravyboat** 2018-06-19 02:12 UTC
Labels: plugin issue
