### ISSUE TITLE
afreeca streams not working

### ISSUE THREAD

**Issue by vidje** [streamlink/streamlink#1180] opened 2017-08-20 15:01 UTC
So basically, I'm trying to watch some starcraft on afreeca via streamlink because via browser it's unwatchable, but I'm getting the following error:

```[cli][info] Found matching plugin afreecatv for URL afreeca.tv/byflash                                                  error: Unable to parse JSON: Expecting value: line 1 column 1 (char 0) ('<!DOCTYPE html>\n<html lang="GAFTV ...)```

streamlink 0.7.0
os: Win10

**Comment by gravyboat** [comment] 2017-08-20 20:01
Duplicate of https://github.com/streamlink/streamlink/issues/837

**Closed by gravyboat** 2017-08-20 20:01 UTC
