### ISSUE TITLE
Record an ongoing Twitch stream reactive?

### ISSUE THREAD

**Issue by anga83** [streamlink/streamlink#917] opened 2017-05-13 18:04 UTC
Hi there!

I wrote a simple bash script that uses streamlink and ffmpeg to either record a currently running stream (with ffmpeg) or to save a VOD into a file (using streamlink with -o).

So far, so good. Until I discovered a Windows tool called "Twitch Leecher" I settled for the fact that I cannot record a VOD of a currently running stream from the beginning; instead I have to wait until the stream ends and start the download then.

But, Twitch Leecher does allow me to download to download an ongoing live stream from the beginning (at least when the VODs on twitch are enabled). Am I just to stupid to find that in the documentation of streamlink or is this feature not implemented.

I'm not sure how Twitch Leecher works exactly, but it possible uses the HLS protocol to seek to the start of the stream. However, neither as download nor as playback in VLC I got streamlink to seek to the beginning - the parameter `--player-passthrough=hls` is of course enabled.

I hope you can help me.
Kind regards!

**Comment by gravyboat** [comment] 2017-05-14 02:02
Hmm, I'm not sure if this is something that we would consider in scope since we mostly want to focus on live content as opposed to supporting more recording logic, but we'll see what others think. What is the use case in this scenario if you don't mind me asking? I don't really see what the issue is with waiting for the VOD to be available or what is gained by starting the download from the beginning of the stream.

**Comment by beardypig** [comment] 2017-05-14 09:01
It's already supported in code by the HLSStream class, it would probably be quite straightforward to expose the functionality via command line option :-)

**Comment by anga83** [comment] 2017-05-14 09:44
Sure, waiting is always and option. But it would somehow complement the missing rewind option. I mean, if I watch a stream and missed the beginning, I could (while some less interesting game) play the missing part.
Also, there are this weird streamers who have VODs enabled, but delete them afterwards (I think they want a recording of the stream for themselves or for uploading on YT an eternity later, but not another OBS instance running).

Again, my use case surely isn't a reason why streamlink needs this feature. However, when this is rudimental implemented, is it already possible to try out?

Am 14.05.2017 um 04:02 schrieb Forrest <notifications@github.com<mailto:notifications@github.com>>:


Hmm, I'm not sure if this is something that we would consider in scope since we mostly want to focus on live content as opposed to supporting more recording logic, but we'll see what others think. What is the use case in this scenario if you don't mind me asking? I don't really see what the issue is with waiting for the VOD to be available or what is gained by starting the download from the beginning of the stream.

**Comment by bastimeyer** [comment] 2017-05-14 11:31
> missing rewind option

VOD seeking while watching is not supported right now.
https://github.com/streamlink/streamlink/issues/134
https://github.com/streamlink/streamlink/issues/614

What beardypig probably meant was an option to jump to a certain position defined by a parameter.

The idea proposed by @FurryFur here https://github.com/streamlink/streamlink/issues/134#issuecomment-264744116 could solve this issue, but this requires *a bit* of work, since it'd completely change streamlink's behavior.

**Comment by beardypig** [comment] 2017-05-14 13:02
I did already implement a skip feature, I'll submit a PR a some point...

**Comment by anga83** [comment] 2017-05-15 23:30
Update: I actually got it to work as-is with the following command `streamlink -o Stream.mp4 --hls-segment-threads 4 $1 source --player-passthrough=hls`

Just another question (which isn't wort another thread): Is it possible to show at which point of time the download currently is?

[download][Stream.mp4] Written 1.98 GB (7m19s @ 3.2 MB/s)

**Comment by back-to** [comment] 2018-01-04 20:42
the original question is a duplicate of #134

the skip feature got merged #1303

---

to your other question you can't see the time,
but you could use `-l debug` to see the segment number.
you can compare it with the livestream
#1209 might be usefull for this.

**Closed by back-to** 2018-01-04 20:42 UTC
Labels: question
