### ISSUE TITLE
Option --version-check outputs invalid input response

### ISSUE THREAD

**Issue by 404NetworkError** [streamlink/streamlink#94] opened 2016-10-18 16:08 UTC
### Expected Behavior

`[cli][info] Your Streamline version (0.0.2) is up to date!`
### Actual Behavior

```
usage: streamlink [OPTIONS] [URL] [STREAM]

Use -h/--help to see the available options or read the manual at http://docs.streamlink.io/
```
### Steps to reproduce the behavior

`streamlink --version-check`

**Comment by TheSneakySniper** [comment] 2016-10-18 18:19
Please use the correct command, --version.

**Comment by scottbernstein** [comment] 2016-10-18 18:26
--version-check is different than --version

--version-check calls back to the server to see if you have the latest version or not.
________________________________

**Comment by beardypig** [comment] 2016-10-18 18:33
This issue is caused by an Invalid version number in the PyPi json information endpoint for streamlink: https://pypi.python.org/pypi/streamlink/json
The offending version field...
```json
"version": "1.14.0rc1"
```
The `version_check` method uses `StrictVersion`, which disallows suffixes such as `rc1` which generates an `Exception`, which is silenced... Even if you change it to `LooseVersion`, which does permit `rc1`, `--version-check` will tell you that the latest version of streamlink is `1.14.0rc1` (lies).

```
[cli][info] A new version of Streamlink (1.14.0rc1) is available!
```

As to why the version is set to `1.14.0rc1`, one of the streamlink team may know and might be able to fix it :)

**Comment by beardypig** [comment] 2016-10-18 18:45
I have created a work-around that will get the latest version that has release information - it works, but the better solution would be to fix the PyPi entry if possible.

**Comment by gravyboat** [comment] 2016-10-18 19:27
There's a discussion going on over in #97 to discuss getting this fixed.

**Comment by beardypig** [comment] 2016-11-03 16:37
This is fixed now :)

**Closed** 2016-11-03 16:40 UTC
Labels: bug
