### ISSUE TITLE
streamlink==6.11.0 requires trio>=0.23 / py313: requires trio>=0.25

### ISSUE THREAD

**Issue by yashikada** [streamlink/streamlink#6243] opened 2024-10-13 13:21 UTC
### Checklist

- [x] This is a bug report and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [x] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [x] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [x] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Collaboration

- [x] [I will provide feedback should a pull request be opened with a fix for the problem](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#pull-request-feedback)

### Streamlink version

[cli][info] Your Streamlink version (6.11.0) is up to date!

### Description

I'm using the latest stable version installed via pip3 install on Linux Debian 12.
On my workstation I installed the packages distributed by Debian

```
ii python3-trio 0.22.0-0.2 all Python async concurrency and I/O library
ii python3-trio-websocket 0.9.2-2 all Server and client Python library of the WebSocket protocol (Python3 version)
```

Until version 6.10.0 I had no problems but with version 6.11.0 there are problems with the trio version.

If I install streamlink with pip package trio is already satisfied, but it's wrong, it should be a more updated version.
While I'm opening the issue the latest version of trio 0.26.2 has no issues

```
Collecting streamlink
  Using cached streamlink-6.11.0-py3-none-any.whl (530 kB)
Requirement already satisfied: certifi in /usr/lib/python3/dist-packages (from streamlink) (2022.9.24)
Requirement already satisfied: isodate in /usr/lib/python3/dist-packages (from streamlink) (0.6.1)
Requirement already satisfied: lxml<6,>=4.6.4 in /usr/lib/python3/dist-packages (from streamlink) (4.9.2)
Requirement already satisfied: pycountry in /usr/lib/python3/dist-packages (from streamlink) (22.3.5)
Collecting pycryptodome<4,>=3.4.3
  Using cached pycryptodome-3.21.0-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.3 MB)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/lib/python3/dist-packages (from streamlink) (1.7.1)
Requirement already satisfied: requests<3,>=2.26.0 in /usr/lib/python3/dist-packages (from streamlink) (2.28.1)
Requirement already satisfied: trio<1,>=0.22.0 in /usr/lib/python3/dist-packages (from streamlink) (0.22.0)
Requirement already satisfied: trio-websocket<1,>=0.9.0 in /usr/lib/python3/dist-packages (from streamlink) (0.9.2)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/lib/python3/dist-packages (from streamlink) (4.4.0)
Requirement already satisfied: urllib3<3,>=1.26.0 in /usr/lib/python3/dist-packages (from streamlink) (1.26.12)
Requirement already satisfied: websocket-client<2,>=1.2.1 in /usr/lib/python3/dist-packages (from streamlink) (1.2.3)
Installing collected packages: pycryptodome, streamlink
Successfully installed pycryptodome-3.21.0 streamlink-6.11.0
```

### Debug log

```
Traceback (most recent call last):
  File "/home/yashikada/streamlink/.python3/local/bin/streamlink", line 5, in <module>
    from streamlink_cli.main import main
  File "/home/yashikada/streamlink/.python3/local/lib/python3.11/dist-packages/streamlink_cli/main.py", line 22, in <module>
    from streamlink.stream.stream import Stream, StreamIO
  File "/home/yashikada/streamlink/.python3/local/lib/python3.11/dist-packages/streamlink/stream/__init__.py", line 1, in <module>
    from streamlink.stream.dash import DASHStream
  File "/home/yashikada/streamlink/.python3/local/lib/python3.11/dist-packages/streamlink/stream/dash/__init__.py", line 1, in <module>
    from streamlink.stream.dash.dash import DASHStream, DASHStreamReader, DASHStreamWorker, DASHStreamWriter
  File "/home/yashikada/streamlink/.python3/local/lib/python3.11/dist-packages/streamlink/stream/dash/dash.py", line 17, in <module>
    from streamlink.stream.ffmpegmux import FFMPEGMuxer
  File "/home/yashikada/streamlink/.python3/local/lib/python3.11/dist-packages/streamlink/stream/ffmpegmux.py", line 16, in <module>
    from streamlink.utils.processoutput import ProcessOutput
  File "/home/yashikada/streamlink/.python3/local/lib/python3.11/dist-packages/streamlink/utils/processoutput.py", line 10, in <module>
    class ProcessOutput:
  File "/home/yashikada/streamlink/.python3/local/lib/python3.11/dist-packages/streamlink/utils/processoutput.py", line 11, in ProcessOutput
    _send_channel: trio.MemorySendChannel[bool]
                   ~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/lib/python3.11/typing.py", line 344, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/typing.py", line 1807, in __class_getitem__
    _check_generic(cls, params, len(cls.__parameters__))
  File "/usr/lib/python3.11/typing.py", line 271, in _check_generic
    raise TypeError(f"{cls} is not a generic class")
TypeError: <class 'trio.MemorySendChannel'> is not a generic class

```

**Comment by bastimeyer** [comment] 2024-10-13 13:50
> I'm using the latest stable version installed via pip3 install on Linux Debian 12.
> On my workstation I installed the packages distributed by Debian
> If I install streamlink with pip package trio is already satisfied

You are mixing Python environments, which is bad and must be avoided. Use a clean virtual environment without mixing in Python packages from the system environment.
https://streamlink.github.io/install.html#virtual-environment

Also see pip's `--upgrade-strategy=eager` argument:
https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-upgrade-strategy

The error itself with `trio==0.22` has been fixed on master with recent typing annotation changes/fixes (16a1d843). Those changes however will only be included in the 7.0.0 release. There won't be a 6.x release.

```
$ pip list | grep trio
pytest-trio                   0.8.0
trio                          0.22.0
trio-typing                   0.10.0
trio-websocket                0.12.0.dev0
$ git describe --tags 
6.11.0-2-g16a1d843
$ pytest >/dev/null && echo OK
OK
```

----

Unrelated to that though, there appear to be issues when trying to run the tests on `py313` when using `trio<0.25`. Those issues seems to be caused by `pytest-trio`.

**Comment by bastimeyer** [comment] 2024-10-13 14:05
I guess we'll have to bump `trio` to `>=0.25 ` now, as there seem to be compatibility issues on Python 3.13 within trio itself. I can't find anything in their changelog though. Haven't checked their issue tracker yet.

----

As explained, the other issue with `trio<0.23` on `streamlink==6.11.0` has been resolved by 16a1d84386539c8c8e480b73a519e179fcb8703c. The issue was introduced via #6208 by not applying PEP 563 or quoting the typing annotations for postponed evaluation, causing runtime issues on the older `trio==0.22` version (which lacks the generics typing annotations of the memory-channels).

For any packager running into this potential issue, here's a diff that fixes the issue on `streamlink==6.11.0` with `trio==0.22`:
```diff
diff --git a/src/streamlink/utils/processoutput.py b/src/streamlink/utils/processoutput.py
index c82ff251..1640ed4e 100644
--- a/src/streamlink/utils/processoutput.py
+++ b/src/streamlink/utils/processoutput.py
@@ -1,3 +1,5 @@
+from __future__ import annotations
+
 import math
 from contextlib import suppress
 from functools import partial
diff --git a/tests/utils/test_processoutput.py b/tests/utils/test_processoutput.py
index 5a1016ce..6dab304b 100644
--- a/tests/utils/test_processoutput.py
+++ b/tests/utils/test_processoutput.py
@@ -1,3 +1,5 @@
+from __future__ import annotations
+
 import sys
 from typing import Awaitable, Callable, Optional, Tuple
 from unittest.mock import Mock, call
```

**Comment by yashikada** [comment] 2024-10-13 20:36
I think your PR #6244 resolve the issue easly.
I don't need version 0.22 of trio.

**Comment by bastimeyer** [comment] 2024-10-14 13:29
No, as explained, my PR has nothing to do with this issue here. It's about the other issue I mentioned in my comments.

Your issue which unfortunately made it into 6.11.0 has already been resolved on the master branch, regardless of the trio version defined in Streamlink's package metadata.

As said, use a clean virtual environment where there are no conflicts with your system's python environment, or update your trio dependency version by running `pip -U --upgrade-strategy=eager streamlink`, so all dependencies will be upgraded as well instead of just checking if they are compliant when installing/upgrading the streamlink package from PyPI.

**Closed by bastimeyer** 2024-10-14 13:29 UTC
Labels: bug, dependencies
