### ISSUE TITLE
FlexTV

### ISSUE THREAD

**Issue by chorong761** [streamlink/streamlink#4893] opened 2022-10-19 09:45 UTC
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

A livestream site similar to Twitch or afreecaTV, mainly for "just chatting" streams. Some streams require a log in due to minor protection laws (drinking, smoking etc.)

### Input URLs

https://www.flextv.co.kr/channels/92957/live
https://www.flextv.co.kr/channels/66401/live

**Comment by bastimeyer** [comment] 2022-10-19 09:59
Duplicate of #4135

Also
https://github.com/streamlink/streamlink/issues?q=flextv

**Closed by bastimeyer** 2022-10-19 09:59 UTC
Labels: plugin request
