### ISSUE TITLE
Installing Streamlink v1.1.1 deletes plugins!

### ISSUE THREAD

**Issue by GrayFace** [streamlink/streamlink#2433] opened 2019-04-19 12:58 UTC
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.

### Description

Installing version 1.1.1 of Streamlink has replaced a whole bunch of important plugins (e.g. Chaturbate) with zero-length files.

### Expected / Actual behavior

Plugins at the very least staying there. No malicious behavior of the installer.

### Reproduction steps / Explicit stream URLs to test

1. Have plugins from older version.
2. Install the .exe version of Streamlink v1.1.1.

### Log output

```
[cli][debug] OS:         Windows 7
[cli][debug] Python:     3.6.6
[cli][debug] Streamlink: 1.1.1
[cli][debug] Requests(2.21.0), Socks(1.6.7), Websocket(0.56.0)
error: No plugin can handle URL: https://chaturbate.com/test
```

### Additional comments, screenshots, etc.

While this isn't a bug report about porn plugins (it's about installer maliciously erasing files), I'd like to know if there is any rationale in the decision to ban development of them.

**Comment by bastimeyer** [comment] 2019-04-19 13:37
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests
> NSFW sites of a pornographic nature (cam sites, porn sites, etc.)

See #1838 and #2003, more specifically
https://github.com/streamlink/streamlink/pull/1838#issuecomment-459184294
https://github.com/streamlink/streamlink/pull/1838#issuecomment-460016268

Also a duplicate of
#2197, #2290
https://github.com/streamlink/streamlink/issues?utf8=%E2%9C%93&q=chaturbate

**Closed by bastimeyer** 2019-04-19 13:37 UTC

**Comment by beardypig** [comment] 2019-04-22 00:36
You can [sideload](https://streamlink.github.io/cli.html#sideloading-plugins) the old plugins, if they still work - they are all available in the GitHub history. However, these plugins are no longer being supported by the core developers.
