### ISSUE TITLE
Hello, was hoping to find some help regarding twitch ads.

### ISSUE THREAD

**Issue by gimli520** [streamlink/streamlink#3254] opened 2020-10-16 03:32 UTC
I've been on 1.5.0 since the day it was released and had minor issues with Twitch giving me these 15 second waiting screen before it loaded the stream. However while some streams would load fine, others would simply crash VLC and not start. I was able to mitigate this by fast forwarding when the timer on the ad went down to about 3 or less seconds. Thankfully the problem eventually went away.

I just upgraded to 1.6.0 and the ads are back but this time it's an actual 30 second Twitch ad. I then downgraded back to 1.5.0 and the problem happened there as well. It wasn't happening all this time until I installed 1.6.0. The problem is I the fast forwarding method I was doing is not working anymore and most streams are just crashing VLC, very few of them start. (Tried 6-7 different streams, only 2 load like normal after the ad).

I saw the thread about ads, but was a little lost. Sorry if this is trouble for you guys/gals.

Hoping someone knows a fix. Thank you.

**Comment by mkbloke** [comment] 2020-10-16 03:54
**Feedback/answer (see ticked items):**

* As requested in the plugin issue template:
* - [ ] Description and/or reproduction steps are insufficiently detailed
* - [ ] Streamlink version in use not specified
* - [ ] Full ```--loglevel debug``` log output not provided
* - [x] Research of prior issues/fixes appears to be insufficient [[1]]
* Other feedback:
* - [ ] Issue is out of scope and/or should be reported/help sought elsewhere
* - [x] Issue appears to unnecessarily duplicate another issue that is open/closed
* - [x] User appears to be using an outdated Streamlink version/plugin [[2]] [[3]]
* - [ ] Other (see below)
* Other: N/A

There have been a number of changes to the Twitch plugin since 1.6.0 was released.  Please only open a new issue if you're having a problem with the latest plugin version in master.

Please amend/close your issue accordingly and/or undertake the requested prior research before opening an issue in future.

[[1]] [Search all open/closed issues/pull requests][1]
[[2]] [Install the most recent version of Streamlink][2]
[[3]] [Check the master branch for plugin updates][3]

[1]: https://github.com/streamlink/streamlink/issues?q=
[2]: https://streamlink.github.io/install.html
[3]: https://github.com/streamlink/streamlink/tree/master/src/streamlink/plugins

**Closed** 2020-10-16 04:20 UTC

**Comment by gravyboat** [comment] 2020-10-16 04:22
@gimli520 Please don't open another issue on this, I know you said you looked through the pinned thread: https://github.com/streamlink/streamlink/issues/3210 but all discussion we've had so far on it is there, we're looking at options. You can try using the nightly build if you want: https://github.com/streamlink/streamlink/actions/runs/309669855
