### ISSUE TITLE
HLS + MPC-HC = Failed to render the file.

### ISSUE THREAD

**Issue by Bullet25fxbx** [streamlink/streamlink#263] opened 2016-12-06 22:42 UTC
When opening a stream with the "HLS" setting and Media Player Classic - Home Cinema the video does not load with MPC prompting "Failed to render the file."
This works fine if the stream setting is set to "HTTP".

HLS setting works faster for me to load streams and this worked fine with the last release of Livestreamer

...

Streamlink Twitch GUI v1.0.0
Streamlink v0.1.0
Windows 10 Pro
Media Player Classic - Home Cinema v 1.7.8.162 (installed via CCCP)

...

I'll post logs if somebody explains where to find them.

...

Video showing the interaction.
https://www.youtube.com/watch?v=bPIWZepxn9A

**Comment by beardypig** [comment] 2016-12-06 23:19
Are you able to try it using the Streamlink CLI (from the command prompt) by doing something like
```
streamlink twitch.tv/twitch best
``` 
and see if it works.

**Comment by Bullet25fxbx** [comment] 2016-12-07 12:58
Yes that plays correctly in VLC

**Comment by beardypig** [comment] 2016-12-07 17:07
Sounds like the stream is incompatible with the player, is there a more up to date version you can try? Or switch to VLC?

**Comment by Bullet25fxbx** [comment] 2016-12-07 19:18
Stills occurs in the most recent MPC-HC version (1.7.10)
Its weird that HLS works with both versions of MPC-HC using Livestreamer but not streamlink.

**Comment by Skibicki** [comment] 2016-12-07 21:43
Try a nightly version. https://nightly.mpc-hc.org/

**Comment by Bullet25fxbx** [comment] 2016-12-08 19:23
With the latest nightly it works.

**Comment by beardypig** [comment] 2016-12-08 19:42
@Bullet25fxbx did any other HLS streams work, or did they all fail with the same error?

**Comment by Bullet25fxbx** [comment] 2016-12-08 19:45
All streams when trying to play with HLS + Steamlink would fail on MPC-HC version installed from CCCP (1.7.8.162) or their main site (1.7.10). Nightly version works though (1.7.10.296).
All version would play HLS streams with livestreamer.

**Comment by beardypig** [comment] 2016-12-08 19:46
Does Livestreamer still work with the twitch streams?

**Comment by Bullet25fxbx** [comment] 2016-12-08 19:47
Yes.

**Comment by beardypig** [comment] 2016-12-08 19:48
Could you share some example links of streams that work in Livestreamer and play in MPC-HC but fail with Streamlink?

**Comment by Bullet25fxbx** [comment] 2016-12-08 19:49
Literally any stream.
https://www.twitch.tv/riotgames
https://www.twitch.tv/dotamajor
https://www.twitch.tv/yogscast
https://www.twitch.tv/firebat

**Comment by beardypig** [comment] 2016-12-08 20:05
On Windows Vista 32 bit with [MPC-HC 1.7.10 (df11f14)](https://binaries.mpc-hc.org/MPC%20HomeCinema%20-%20Win32/MPC-HC_v1.7.10_x86/MPC-HC.1.7.10.x86.exe). I was able to reproduce the error, but not consistently, only failed once in about 30 tries. 
```
C:\>streamlink https://www.twitch.tv/dotamajor best --player "C:\Program Files\MPC-HC\mpc-hc.exe"
```

**Comment by Bullet25fxbx** [comment] 2016-12-08 20:18
Okay. Well, it happens every time on two different Windows 10 x64 bit machines. Both home and work machines.

**Comment by beardypig** [comment] 2016-12-08 20:20
Yeah. I'm just trying to reproduce it, so that I can debug and fix it. I tried on a Windows 10 32 bit machine and a 64 Windows Server 2012 (which both 64bit and 32bit versions of MPC-HC). All of them worked so far ... 

I assume you're using the 64bit version of MPC-HC? Have you tried it with the 32bit version?

**Comment by Vangelis66** [comment] 2016-12-08 20:33
Portable edition of streamlink, portable installation of latest stable MPC-HC 1.7.10, 
Vista SP2 32bit, tried it 10 consecutive times and always succeeds: 

![untitled](https://cloud.githubusercontent.com/assets/9669492/21026612/18f0114a-bd96-11e6-9b09-f15334e3a193.jpg)

**Comment by Z-brah** [comment] 2017-01-14 19:17
Using this line: Streamlink https://www.twitch.tv/cohhcarnage/v/114418144 high,source
and these settings:
  twitch-oauth-token=*****************
  player="C:\Program Files\MPC-HC\mpc-hc.exe"
  player-continuous-http
  player-passthrough=hls
  player-no-close
i get same result: (translation: cant play file)
Win 10 x32, Mpc-hc 1.7.10

p.s. live translations works fine

![sl](https://cloud.githubusercontent.com/assets/20454759/21957448/43709b8c-daa7-11e6-8714-ed983ec75cc3.png)

**Comment by gravyboat** [comment] 2017-03-25 02:23
Since we haven't had an update on this thread in a while and can't reproduce the error I'm going to close it out. If there are additional details that have surfaced that would allows us to duplicate this reliably please re-open the issue!

**Closed by gravyboat** 2017-03-25 02:23 UTC
Labels: question

**Comment by Silun** [comment] 2024-06-16 14:00
I am encountering this issue. I am using Streamlink 6.7.4 on Windows 10. I use K-Lite Standard, version 18.4.0 and VLC 3.0.20.

When I try to use streamlink, like so: `streamlink https://www.zdf.de/live-tv 270p_alt` I get an error in MPC-HC saying `Failed to render the file`. VLC will not play it either, but be more verbose: `VLC is unable to open the MRL 'fd://0'. Check the log for details.` The log just says this: `filesystem error: read error: Bad file descriptor`

I have tried just about any CLI option that I thought might be related to the issue. The only thing that makes a difference seems to be `--fifo`, which changes the error message in both players:

In MPC-HC, with the `--fifo` switch it'll say `File not found`, and in VLC it changes to `VLC is unable to open the MRL 'file://./pipe/streamlinkpipe-18204-1-2023'. Check the log for details.`

I am a bit stumped on what the issue could be. I have tried different streamlink versions, both 6.7.3 and 5.5.1 but both are affected by the same issue. I have also tried a downgrade of K-Lite to 18.3.5 which also changed nothing. It almost looks like piping itself is somehow broken, but I am having trouble googling that. Piping itself does work for example with `| findstr /i something` so it isn't somehow disabled, I believe.

I have also tried numerous times to uninstall, clean install, install via winget, install manually etc. but to no avail. The issue also affects any and all Twitch streams, so it's not about the streams themselves, either.

**Comment by bastimeyer** [comment] 2024-06-16 14:14
You are bumping an issue that was closed **more than 7 years ago**. Going to lock this now...

If you're having a problem using Streamlink, then please open a new thread on the discussion forum where you can ask for help. This is not a Streamlink bug, as launching the player executable and piping the stream data works fine, same as named pipes, etc. Support/usability questions don't belong on the issue tracker.

What you have posted is also completely meaningless unless you include debug log output (`--loglevel=debug`) and also verbose player output (`--verbose-player`).

On top of that, MPC-HC has been dead since 2017. You should not be using it. Have a look at mpv.
https://streamlink.github.io/players.html
