### ISSUE TITLE
rasie AttributeError

### ISSUE THREAD

**Issue by adamac2** [streamlink/streamlink#3062] opened 2020-07-05 21:20 UTC
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.

### Description

I'm not sure what caused this error. I'm using an Arch-based distribution, and one day, I would imagine after a `pacman -Syu` whenever I run streamlink  I get some sort of `AttributeError` and I'm not sure what is causing it.

### Expected / Actual behavior

I would Image that after running `streamlink "{enter url here}"` the stream would open in mpv and play, but after it finds the matching plugin I get this error.

### Reproduction steps / Explicit stream URLs to test

1. `pacman -Syu` to use the latest version of streamlink available. (1.4.1-1)
2. Try using any link with `streamlink "{enter url here}"`

Some of the links I tried are:
[Destiny's Twitch Channel](https://www.twitch.tv/destiny)
[Formal's Twitch Channel](https://www.twitch.tv/formal)
[ABC News Live](https://www.youtube.com/watch?v=w_Ma8oQLmSM)
[Casualty's DLive Stream](https://dlive.tv/Casualty)

All give me a similar outout to the error below

### Log output

```
[milky@art ~vv]$ streamlink --loglevel debug "twitch.tv/destiny" 
[cli][debug] OS:         Linux-5.7.6-artix1-1-x86_64-with-glibc2.2.5 
[cli][debug] Python:     3.8.3 
[cli][debug] Streamlink: 1.4.1 
[cli][debug] Requests(2.24.0), Socks(1.7.1), Websocket(0.57.0) 
[cli][info] Found matching plugin twitch for URL twitch.tv/destiny 
[cli][debug] Plugin specific arguments: 
[cli][debug]  --twitch-disable-hosting=True (disable_hosting) 
[cli][debug]  --twitch-disable-ads=True (disable_ads) 
[cli][debug]  --twitch-low-latency=True (low_latency) 
[plugin.twitch][debug] Getting live HLS streams for destiny 
Traceback (most recent call last): 
  File "/usr/bin/streamlink", line 11, in <module> 
    load_entry_point('streamlink==1.4.1', 'console_scripts', 'streamlink')() 
  File "/usr/lib/python3.8/site-packages/streamlink_cli/main.py", line 1024, in main 
    handle_url() 
  File "/usr/lib/python3.8/site-packages/streamlink_cli/main.py", line 585, in handle_url 
    streams = fetch_streams(plugin) 
  File "/usr/lib/python3.8/site-packages/streamlink_cli/main.py", line 464, in fetch_streams 
    return plugin.streams(stream_types=args.stream_types, 
  File "/usr/lib/python3.8/site-packages/streamlink/plugin/plugin.py", line 317, in streams 
    ostreams = self._get_streams() 
  File "/usr/lib/python3.8/site-packages/streamlink/plugins/twitch.py", line 794, in _get_streams 
    return self._get_hls_streams("live") 
  File "/usr/lib/python3.8/site-packages/streamlink/plugins/twitch.py", line 733, in _get_hls_streams 
    streams = TwitchHLSStream.parse_variant_playlist( 
  File "/usr/lib/python3.8/site-packages/streamlink/stream/hls.py", line 405, in parse_variant_playlist 
    locale = session_.localization 
  File "/usr/lib/python3.8/site-packages/streamlink/session.py", line 514, in localization 
    return Localization(self.get_option("locale")) 
  File "/usr/lib/python3.8/site-packages/streamlink/utils/l10n.py", line 122, in __init__ 
    self.language_code = language_code 
  File "/usr/lib/python3.8/site-packages/streamlink/utils/l10n.py", line 147, in language_code 
    self.language, self.country = self._parse_locale_code(language_code) 
  File "/usr/lib/python3.8/site-packages/streamlink/utils/l10n.py", line 132, in _parse_locale_code 
    return self.get_language(parts[0]), self.get_country(parts[1]) 
  File "/usr/lib/python3.8/site-packages/streamlink/utils/l10n.py", line 176, in get_language 
    return Language.get(language) 
  File "/usr/lib/python3.8/site-packages/streamlink/utils/l10n.py", line 76, in get 
    return Language(lang.alpha_2, lang.alpha_3, lang.name, getattr(lang, "bibliographic", None)) 
  File "/usr/lib/python3.8/site-packages/pycountry/db.py", line 19, in __getattr__ 
    raise AttributeError 
AttributeError 
```

### Additional comments, screenshots, etc.

This seems like a pretty big issue, but I haven't seen someone post about it yet which leads me to believe this might just be a "me" thing. Either way, if there's some workaround or any solution I'm missing I would love to hear it.

Thank you for your time!

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment] 2020-07-06 00:26
This is a duplicate of https://github.com/streamlink/streamlink/issues/3058 and was fixed here: https://github.com/streamlink/streamlink/pull/3057, but still has to be fixed upstream in the package itself to work. You can manually install the latest dev version from the master branch which has the PR merged using these instructions: https://streamlink.github.io/install.html#pypi-package-and-source-code.

**Closed by gravyboat** 2020-07-06 00:26 UTC
Labels: duplicate

**Comment by bastimeyer** [comment] 2020-07-06 04:29
@adamac2 

> 1. `pacman -Syu` to use the latest version of streamlink available. (1.4.1-1)

Apart from what @gravyboat has said, you can also try to
- downgrade the [`python-pycountry` package to `19.8.18-3`](https://git.archlinux.org/svntogit/community.git/log/trunk?h=packages/python-pycountry)
- install the [`streamlink-git`](https://aur.archlinux.org/packages/streamlink-git) package from the AUR
- wait for @grazzolini to add a bugfix patch to the official streamlink package on Arch, as he's the maintainer of it
- patch it yourself with the following patch:
  https://github.com/streamlink/streamlink/commit/3c082049e954480dbf1eb12e1e54bb3ca1ccbbc9.patch

----

@gravyboat 

Well, we could publish a new release. It would be a bit awkward though considering that the changelog said that the current (previous) release was the last one with py2 support. :confused: 
https://github.com/streamlink/streamlink/compare/1.4.1...master

The pycountry issue affects all packages on Arch, Debian/Ubuntu and Gentoo. Waiting this out is not great.
