### ISSUE TITLE
There should be a way to make capture stop after a certain amount of time

### ISSUE THREAD

**Issue by kgor93** [streamlink/streamlink#1749] opened 2018-06-04 19:31 UTC
### Checklist

- [] This is a bug report.
- [x] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description
Right now when capturing a live stream, it just records indefinitely, up to 6 hours. After 6 hours, it stops. Making a script to restart capturing is trivial, but what ends up happening is that you end up with 6 hour chunks of video. This is much too long to easily go through.
...

### Expected / Actual behavior
Have a —split tag or something that allows you to set when it will stop in minutes. I.e. —split 120 will stop after 2 hours and leave you with a 2 hour video
...

**Comment by beardypig** [comment] 2018-06-04 22:01
If it’s an HLS stream you can use `--hls-duration`, works for live streams in the latest dev version.

**Comment by back-to** [comment] 2018-06-11 12:46
for `hls` see above

for other duplicate of #68

**Closed by back-to** 2018-06-11 12:46 UTC
Labels: duplicate
