### ISSUE TITLE
Parameter parsing bug on Windows

### ISSUE THREAD

**Issue by bastimeyer** [streamlink/streamlink#293] opened 2016-12-14 10:32 UTC
The parameter parser doesn't handle escaped characters correctly on Windows.

Running this works on Linux/MacOS, but fails on Windows:
```
streamlink -p /path/to/vlc -a "--input-title-format \"\\\"\" {filename}" STREAM best
```

This is related to chrippa/livestreamer#1337
(reported at streamlink/streamlink-twitch-gui#256 and streamlink/streamlink-twitch-gui#362)

I can't remember if Linux/MacOS were affected by this in Livestreamer. Didn't test it...

The error log:
```
[cli][info] Starting player: C:/Program Files (x86)/VideoLAN/VLC/vlc.exe
Traceback (most recent call last):
  File "C:\Program Files (x86)\Streamlink\bin\streamlink-script.py", line 12, in <module>
    main()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 899, in main
    handle_url()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 499, in handle_url
    handle_stream(plugin, streams, stream_name)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 382, in handle_stream
    success = output_stream(stream)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 259, in output_stream
    output.open()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\output.py", line 21, in open
    self._open()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\output.py", line 123, in _open
    self._open_subprocess()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\output.py", line 138, in _open_subprocess
    self.player = subprocess.Popen(self._create_arguments(),
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\output.py", line 116, in _create_arguments
    return shlex.split(cmd) + shlex.split(args)
  File "shlex.py", line 273, in split
  File "shlex.py", line 263, in __next__
  File "shlex.py", line 90, in get_token
  File "shlex.py", line 166, in read_token
ValueError: No closing quotation
```

**Comment by beardypig** [comment] 2016-12-14 12:24
That's a doozy... I started work here [windows-cmdline-fix](https://github.com/beardypig/streamlink/tree/windows-cmdline-fix), only works when you don't specific the `-p` option.

**Comment by bastimeyer** [comment] 2016-12-14 16:20
To me this looks like a bug in `shlex.split(..., posix=true)` on Windows.
[Removing the double backslashes](https://github.com/beardypig/streamlink/commit/bff83d495bceb4c0bc8388a97334c18614aaa079#diff-7c968f1e4289468e96529564e2b340fbL113) doesn't solve this problem and will require all Windows users to use double backslashes when specifying a player or paths in the player's arguments.

Should this issue be fixed by not parsing the arguments on Windows? Like described here:
https://stackoverflow.com/questions/33560364/python-windows-parsing-command-lines-with-shlex

**Comment by beardypig** [comment] 2016-12-14 16:48
That's what I had started doing, the problem is with parsing the path to the player. The path needs to be quoted and escaped correctly, which seems to be the reason for that code in the first place. I think I know how to it though..

**Comment by bastimeyer** [comment] 2016-12-14 19:04
A simple tokenizer is needed that splits the value of the --player parameter into two where the player arguments begin. I think this can be done this with shlex.split, but I'm not a python dev, so I might be wrong. If this can't be done with shlex.split, writing a custom tokenizer shouldn't be too difficult.
Then only use the first token (the player path) and use the remaining string as player arguments (untokenized). I don't know how ugly this can get, though. There could also be issues when trying to combine this with the `--player-args` param.

My suggestion would be changing the behavior of `--player` and only accept a path without params. It's just redundant and error-prone. A change would require a major version bump, since it would break old stuff.

Btw, the required `{filename}` var in `--player-args` could be made an implicit var which will be appended to the whole arguments string if missing. This makes it a bit easier for people who use this parameter incorrectly and don't care about the position of the player input parameter. That's totally unrelated to this issue, ofc...

**Comment by beardypig** [comment] 2016-12-14 23:41
I agree that the `player` argument should only take the path to the player, but it is a breaking change. Bah. 

I was hoping to avoid writing a tokenizer, but it might be the only way. `shlex.split` is designed to parse command lines as a shell would (posix and windows), but by the time the `player` and `player-args` get to that point they have already been parsed by the shell, so it doesn't do quite what we'd want in this case. The challenge is fixing this bug, but also keeping existing functionality working, cos let's face it, even if we bump the major version for a breaking change people will still report it as a bug...

**Comment by beardypig** [comment] 2016-12-15 20:58
Fixed in #300

**Closed by beardypig** 2016-12-15 20:58 UTC
Labels: bug

**Comment by bastimeyer** [comment] 2017-01-05 07:04
Having the same issue on Linux now...

This seems to be related to single quotes:
```bash
$ streamlink -p mpv -a "--title '\'' {filename}" twitch.tv/monstercat best
[cli][info] Found matching plugin twitch for URL twitch.tv/monstercat
[cli][info] Available streams: audio, mobile (worst), low, medium, high, source (best)
[cli][info] Opening stream: source (hls)
[cli][info] Starting player: mpv
Traceback (most recent call last):
  File "/usr/bin/streamlink", line 11, in <module>
    load_entry_point('streamlink==0.2.0', 'console_scripts', 'streamlink')()
  File "/usr/lib/python3.5/site-packages/streamlink_cli/main.py", line 899, in main
    handle_url()
  File "/usr/lib/python3.5/site-packages/streamlink_cli/main.py", line 499, in handle_url
    handle_stream(plugin, streams, stream_name)
  File "/usr/lib/python3.5/site-packages/streamlink_cli/main.py", line 382, in handle_stream
    success = output_stream(stream)
  File "/usr/lib/python3.5/site-packages/streamlink_cli/main.py", line 259, in output_stream
    output.open()
  File "/usr/lib/python3.5/site-packages/streamlink_cli/output.py", line 23, in open
    self._open()
  File "/usr/lib/python3.5/site-packages/streamlink_cli/output.py", line 123, in _open
    self._open_subprocess()
  File "/usr/lib/python3.5/site-packages/streamlink_cli/output.py", line 138, in _open_subprocess
    self.player = subprocess.Popen(self._create_arguments(),
  File "/usr/lib/python3.5/site-packages/streamlink_cli/output.py", line 116, in _create_arguments
    return shlex.split(cmd) + shlex.split(args)
  File "/usr/lib/python3.5/shlex.py", line 273, in split
    return list(lex)
  File "/usr/lib/python3.5/shlex.py", line 263, in __next__
    token = self.get_token()
  File "/usr/lib/python3.5/shlex.py", line 90, in get_token
    raw = self.read_token()
  File "/usr/lib/python3.5/shlex.py", line 166, in read_token
    raise ValueError("No closing quotation")
ValueError: No closing quotation
```

This works:
```
streamlink -p mpv -a "--title \"\\\"\" {filename}" twitch.tv/monstercat best
```

https://github.com/streamlink/streamlink-twitch-gui/issues/362#issuecomment-270432414

**Comment by beardypig** [comment] 2017-01-05 09:54
In the first case the error is correct, `"--title '\'' {filename}"` is equivalent to `"--title ''' {filename}"` (they are python string rather than shell parameters), which does has an unpaired quote mark. 

I would, however, have expected this to work, which it does not.
```sh
streamlink -p mpv -a "--title '\\'' {filename}" twitch.tv/monstercat best
```

These work as expected:
```sh
streamlink -p mpv -a "--title \"'\" {filename}" twitch.tv/monstercat best
streamlink -p mpv -a '--title "\'" {filename}' twitch.tv/monstercat best
```

**Comment by bastimeyer** [comment] 2017-01-05 10:14
The double backslash is ofc right in this example, I was thinking about "shell-unparsed"-parameters. And yes, it fails, which is exactly the error I was reporting :)

**Comment by beardypig** [comment] 2017-01-05 11:36
Right. As far as `shlex` is concerned this is the correct behaviour as it implements strict POSIX. From the [IEEE Std 1003.1-2008](http://pubs.opengroup.org/onlinepubs/9699919799/), specifically section [2.2.2](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_02_02). 

> 2.2.2 Single-Quotes
> Enclosing characters in single-quotes ( '' ) shall preserve the literal value of each character within the single-quotes. A single-quote cannot occur within single-quotes.

In fact, you can reproduce it in `sh`, `bash`, `zsh`, plus any other POSIX compatible shell; you will find that there is still an open quote on the second line:
```sh
bash-4.4$ echo 'foo\'s'
> '
foo\s
```

So the correct thing to do is to always use `"` :)
