### ISSUE TITLE
metube(dot)id

### ISSUE THREAD

**Issue by rollykaunang** [streamlink/streamlink#2035] opened 2018-08-26 18:17 UTC
## Plugin Request

- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Hello, Please someone can help to create the plugin for metube(dot)id, this site is based on indonesia live tv streaming and videos on demand. Actually it has static live tv streaming url but it returned error. Please anybody could help me to create plugin.. I do really appreciated for your help Thank You So Much

here is the error
streamlink hls://https://cdn-livetv2.metube.id/hls/jtv_480/index.m3u8 best
[console][info] Found matching plugin hls for URL hls://https://cdn-livetv2.metube.id/hls/jtv_480/index.m3u8
error: Unable to open URL: https://cdn-livetv2.metube.id/hls/jtv_480/index.m3u8 (502 Server Error: Bad Gateway for url: https://cdn-livetv2.metube.id/hls/jtv_480/index.m3u8)

### Example stream URLs

1. https://www.metube.id/live/iNewsTV
2. https://www.metube.id/live/GTV
3. https://www.metube.id/videos/13890493/laga-persahabatan-babak-i-indonesia-vs-islandia-1-0 (video on demand)

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment] 2018-08-27 23:02
Duplicate of #2031

**Closed by bastimeyer** 2018-08-27 23:02 UTC
