### ISSUE TITLE
plugins.pandatv: ROOM_API_V2 frequently returns "403 Forbidden"

### ISSUE THREAD

**Issue by TaoziDB** [streamlink/streamlink#1297] opened 2017-10-30 07:19 UTC
ROOM_API_V2 = "https://www.panda.tv/api_room_v2?roomid={0}&_={1}"

url = ROOM_API_V2.format(channel, ts)
res = http.get(url)

the http request frequently returns "403 Forbidden"
as following:
```
<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by steven7851** [comment] 2017-10-31 11:12
I think it’s caused by cdn, you can try another url:
```ROOM_API_V2 = "https://www.panda.tv/api_room_v21?token=&roomid={0}&_={1}"```

**Comment by TaoziDB** [comment] 2017-10-31 13:25
this one is better, but "403 Forbidden" still happens

**Comment by steven7851** [comment] 2017-10-31 14:32
You can use hosts file to change cdn ip, it can inquire from https://www.ipip.net/dns.php.
For overseas users suggestion: ```220.243.253.220 www.panda.tv```

**Comment by bastimeyer** [comment] 2017-10-31 17:40
Closing this thread, since it's a duplicate of #1285.
Please use the search function next time before opening a new thread, so that the discussion is not split between multiple threads.

**Closed by bastimeyer** 2017-10-31 17:40 UTC
