### ISSUE TITLE
Facebook : No playable streams found

### ISSUE THREAD

**Issue by appysrinath** [streamlink/streamlink#3681] opened 2021-04-08 05:31 UTC
## Issue

**Facebook : No playable streams found**

- [ ] This is not a bug report, feature request, or plugin issue/request.
- [ ] I have read the contribution guidelines.
- [x] I am using the latest development version from the master branch.

### Description

Facebook : No playable streams found

### Reproduction steps / Explicit stream URLs to test

1. ... Any Facebook Live/Uploaded Video
2. ...
3. ...

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment] 2021-04-08 05:35
Likely a duplicate of https://github.com/streamlink/streamlink/issues/3615 but since there's no information filled out there's nothing we can do.

**Closed by gravyboat** 2021-04-08 05:35 UTC
Labels: does not meet requirements, duplicate, invalid, more info required
