### ISSUE TITLE
Error unable to open Twitch URL

### ISSUE THREAD

**Issue by jermackle** [streamlink/streamlink#3346] opened 2020-11-19 08:26 UTC
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

I am a new user attempting to install with homebrew. I'm on Mac OS running Catalina trying to access any ongoing Twitch livestream and receiving errors.

### Reproduction steps / Explicit stream URLs to test

1. streamlink twitch.tv/channel

### Log output

```
$ streamlink https://www.twitch.tv/gassymexican
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/gassymexican
error: Unable to open URL: https://api.twitch.tv/api/channels/gassymexican/access_token (('Connection aborted.', PermissionError(13, 'Permission denied')))
$ brew uninstall streamlink
Uninstalling /usr/local/Cellar/streamlink/1.7.0... (2,128 files, 47.8MB)
$ brew update
Updated 1 tap (homebrew/core).
No changes to formulae.
$ brew install streamlink
==> Downloading https://homebrew.bintray.com/bottles/streamlink-1.7.0.catalina.b
Already downloaded: /Library/Caches/Homebrew/downloads/61247bed430a6e3c9f0712827e1d3c763bb6581a98effa45aa1f0ea59d61c279--streamlink-1.7.0.catalina.bottle.tar.gz
==> Pouring streamlink-1.7.0.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/streamlink/1.7.0: 1,712 files, 45.6MB
$ streamlink https://www.twitch.tv/gassymexican
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/gassymexican
error: Unable to open URL: https://api.twitch.tv/api/channels/gassymexican/access_token (('Connection aborted.', PermissionError(13, 'Permission denied')))
$ streamlink --loglevel debug https://www.twitch.tv/gassymexican
[cli][debug] OS:         macOS 10.15.7
[cli][debug] Python:     3.9.0
[cli][debug] Streamlink: 1.7.0
[cli][debug] Requests(2.24.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/gassymexican
[plugin.twitch][debug] Getting live HLS streams for gassymexican
error: Unable to open URL: https://api.twitch.tv/api/channels/gassymexican/access_token (('Connection aborted.', PermissionError(13, 'Permission denied')))

```

### Additional comments, etc.
I'm sure that I am doing something wrong.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment] 2020-11-19 08:50
I can't reproduce this with 1.7.0 using a German IP address.

> `api.twitch.tv/api/channels/CHANNEL/access_token`

Twitch is currently in the process of finally migrating parts of their old API endpoints to their new one. This includes the streaming access token which you need to watch streams. Streamlink's master branch has already been updated regarding that yesterday in #3344.

It's possible that Twitch has begun shutting down the old API, as mentioned in #3344, but not globally yet, and you're affected by this first. Where / Which region are you from?

Please try the latest version from the master branch and see whether it's working for you.
https://streamlink.github.io/latest/install.html#pypi-package-and-source-code

**Comment by arrowgent** [comment] 2020-11-19 12:45
dont you require adding --player and telling streamlink which player to use?
ie: --player mpv

**Comment by bastimeyer** [comment] 2020-11-19 13:23
@arrowgent Not sure why you're asking this, because this has to do with the request error shown above, but Streamlink defaults to VLC and tries to find it via the `PATH` env var or via a set of known default locations. Other than that, there are also config files which alter the behavior in addition to the provided CLI arguments.

**Comment by jermackle** [comment] 2020-11-19 14:44
I am located in Detroit, Michigan, US. I will try DLing directly from the master branch today. Are there any detailed instructions for installing this way? I have had more success using something like Homebrew because it does so much automatically, such as locating the build correctly with proper directory permissions etc.



On Nov 19, 2020, at 3:50 AM, Sebastian Meyer <notifications@github.com> wrote:

﻿

I can't reproduce this with 1.7.0 using a German IP address.

api.twitch.tv/api/channels/CHANNEL/access_token

Twitch is currently in the process of finally migrating parts of their old API endpoints to their new one. This includes the streaming access token which you need to watch streams. Streamlink's master branch has already been updated regarding that yesterday in #3344<https://github.com/streamlink/streamlink/pull/3344>.

It's possible that Twitch has begun shutting down the old API, as mentioned in #3344<https://github.com/streamlink/streamlink/pull/3344>, but not globally yet, and you're affected by this first. Where / Which region are you from?

Please try the latest version from the master branch and see whether it's working for you.
https://streamlink.github.io/latest/install.html#pypi-package-and-source-code

**Comment by jermackle** [comment] 2020-11-19 14:45
My assumption was streamlink would generate a list of all available formats for the livestream.


On Nov 19, 2020, at 7:46 AM, arrowgent <notifications@github.com> wrote:

﻿

dont you require adding --player and telling streamlink which player to use?
ie: --player mpv

**Comment by jermackle** [comment] 2020-11-19 15:59
I tried running it as a root and it works. Must be something to do with the permissions where homebrew is installing.

**Comment by gravyboat** [comment] 2020-11-19 19:31
Closing since this is resolved.

**Closed by gravyboat** 2020-11-19 19:31 UTC
