### ISSUE TITLE
error: Error when reading from stream: Read timeout, exiting

### ISSUE THREAD

**Issue by edcba1057344** [streamlink/streamlink#2057] opened 2018-09-08 19:31 UTC
My native language is not English.
I have never learned a computer language.

This is my command.
streamlink http://play.afreecatv.com/xxxxxxxxxxx/0 best --hls-segment-threads 10 --hls-live-edge 5 --ringbuffer-size 100M --retry-streams 1 --stream-segment-attempts 1000 --hls-segment-attempts 1000 --stream-segment-timeout 10 --hls-segment-timeout 10 --hls-timeout 1200 -o G:\Live\201809081942-6.mp4

The problem is that when the streamer finishes live, cmd stops and this message pops up.

error: Error when reading from stream: Read timeout, exiting

Downloaded video is audio only, screen is not displayed and it gets jammed.

Normal mp4 only works when I close the cmd window before the live broadcast is over.

Tell me how to fix it 
You may not understand the description exactly as you read in Google Translate.

before: streamlink http://play.afreecatv.com/xxxxxxxxxxx/0 best --hls-segment-threads 10 --hls-live-edge 5 --ringbuffer-size 100M --retry-streams 1 --stream-segment -attempts 1000 --hls-segment-attempts 1000 --stream-segment-timeout 10 --hls-segment-timeout 10 -hls-timeout 1200 -o G: \ Live \ 201809081942-6.mp4

after:

I would appreciate your explanation.

-201809121845 created
'streamlink' seems to have a bug against afreecatv.com
Originally this problem occurred because 'streamlink' had to disconnect 'together' with live broadcasting, but it could not.

This article uses a Google Translator.

---------------------------------------------
my native language is not English.
I have never learned computer language.

This is my command.
streamlink http://play.afreecatv.com/xxxxxxxxxxx/0 best --hls-segment-threads 10 --hls-live-edge 5 --ringbuffer-size 100M --retry-streams 1 --stream-segment-attempts 1000 --hls-segment-attempts 1000 --stream-segment-timeout 10 --hls-segment-timeout 10 --hls-timeout 1200 -o G:\Live\201809081942-6.mp4

The problem is that when the stramer ends live, the cmd stops and this message appears.

Error: Error when reading from stream: Read timeout, expiring

The video that I downloaded only sounds and the screen doesn't appear. 

Normal mp4 works normally when I close the cmd window only before live.

Let me know how to fix it.
Google translation may not accurately understand the explanation for reading.

before : streamlink http://play.afreecatv.com/xxxxxxxxxxx/0 best --hls-segment-threads 10 --hls-live-edge 5 --ringbuffer-size 100M --retry-streams 1 --stream-segment-attempts 1000 --hls-segment-attempts 1000 --stream-segment-timeout 10 --hls-segment-timeout 10 --hls-timeout 1200 -o G:\Live\201809081942-6.mp4

After :

I would appreciate your explanation.

-201809121845 Creates
I think there is a bug about 'streamlink' about afrecatv.
Originally, this problem was caused by the failure of 'streamlink' to be cut off from live broadcasting.

This article used a different translator.

**Comment by back-to** [comment] 2018-09-21 13:59
@edcba1057344 

If you get the 15 sec countdown use the command
`--hls-segment-ignore-names preloading`

see https://github.com/streamlink/streamlink/issues/2061

---


> The problem is that when the streamer finishes live, cmd stops and this message pops up.
error: Error when reading from stream: Read timeout, exiting

this is **normal**, because the stream does not go offline
on the end of afreeca they loop the last m3u8 playlist for a bit.

---

> The downloaded live mp3 file is broken.

can not reproduce

---

> If the live broadcast is lost, the cmd should also be disconnected, but it will not work.

you command has `--hls-timeout 600` which is a 10 minutes timeout


---

```
Please check

streamlink http://play.afreecatv.com/****/0 best --hls-segment-threads 10 --retry-streams 1 --retry-max 100 --hls-live-edge 5 --ringbuffer-size 100M --stream-segment-attempts 100 --hls-segment-attempts 100 --stream-segment-timeout 10 --hls-segment-timeout 10 --hls-timeout 600 -o G:\Live-test.mp4
```

you can remove the ` --stream-segment-` commands because `--hls-` is used here

---

but I don't really know what your real issue is, provide more details.

**Comment by edcba1057344** [comment] 2018-09-25 10:40
I saw it now.

--hls-segment-ignore-names preloading
I tested it by adding an additional command.
However, the end of the downloaded image is cut or the screen is broken.
Can you solve this problem with the '--player-no-close' command?

And

You can remove the --stream-segment-commands use --hls- is used here

://io/latest/cli.html
I used the command here on the site. I don't understand why it's being removed.

Could you tell me briefly by 'Before, After'?

before:
streamlink http://play afreecatv.com/****/0 Best --hls-segment-threads-threads 10 --retry-streams 1 --retry-max 100 --hls-live-edge 5 --ringbuff


After

**Comment by back-to** [comment] 2018-10-02 17:52
@edcba1057344 

> However, the end of the downloaded image is cut or the screen is broken.

Is this with a video editing software or which software do you use here?

If this is the last second of the stream, it is probably normal.

> Could you tell me briefly by 'Before, After'?

the command doesn't do anything when used with afreeca streams, so it can be removed.

**Comment by edcba1057344** [comment] 2018-10-04 07:29
Is this a video editing software or which software do you use here?

If this is the last second of the stream, it is probably normal.
--------------------------

I'm not a software problem. I used 'gomplayer, VLC media player'.

**Comment by edcba1057344** [comment] 2018-10-04 07:29
https://imgur.com/a/pFmVr18

**Comment by gravyboat** [comment] 2018-10-04 18:52
Can you try using a different player? We've been seeing a lot of issues with VLC as of late, especially on their latest release.

**Comment by gravyboat** [comment] 2018-10-10 19:29
Okay thanks for the update, I'm going to close this out.

**Closed by gravyboat** 2018-10-10 19:29 UTC
Labels: more info required, question

**Comment by joon612** [comment] 2024-09-16 12:34
Same issue here, I used this shell cmd: `/bin/bash -c 'timestamp=$(date +%Y/%m/%d/%H); streamlink "https://www.earthcam.com/usa/newyork/littleitaly/?cam=littleitaly" best --hls-duration 1h --stream-segment-attempts 5 --stream-segment-timeout 30 --hls-segment-queue-threshold 0 -o "/mnt/batch/tasks/fsmounts/videos/earthcam-test/littleitaly/${timestamp}.ts" -f && ffmpeg -i "/mnt/batch/tasks/fsmounts/videos/earthcam-test/littleitaly/${timestamp}.ts" -c copy "/mnt/batch/tasks/fsmounts/videos/earthcam-test/littleitaly/${timestamp}.mp4"'`

Log:
```
[cli][info] Found matching plugin earthcam for URL https://www.earthcam.com/usa/newyork/littleitaly/?cam=littleitaly
[cli][info] Available streams: 720p (worst, best)
[cli][info] Opening stream: 720p (hls)
[cli][info] Writing output to
/mnt/batch/tasks/fsmounts/videos/earthcam-test/littleitaly/2024/09/15/07.ts
[stream.hls][warning] Failed to reload playlist: Unable to open URL: https://videos-3.earthcam.com/fecnetwork/27777.flv/chunklist_w987041473.m3u8?t=PSVsWCb29%2Bfg%2B4kxWyBn6YsMXgufL1Zc7sUKdLx2dwBPULEbaBUgQPZKSTUeqYGk (404 Client Error: Not Found for url: https://videos-3.earthcam.com/fecnetwork/27777.flv/chunklist_w987041473.m3u8?t=PSVsWCb29%2Bfg%2B4kxWyBn6YsMXgufL1Zc7sUKdLx2dwBPULEbaBUgQPZKSTUeqYGk)
[cli][info] Stream ended
[cli][info] Closing currently open stream...
error: Error when reading from stream: Read timeout, exiting
```

**Comment by bastimeyer** [comment] 2024-09-16 12:56
> [stream.hls][warning] Failed to reload playlist

The HLS playlist has expired / become inaccessible and the server returned a 404 response, so no new data was written to Streamlink's ringbuffer because no new HLS segments could be queued, which means that reading the buffer resulted in an eventual timeout. This is the expected result and nothing unusual.

Expiring HLS playlist URLs are off-spec (i.e. custom server implementation) and explicitly need to be covered by plugins. The earthcam plugin however won't be updated anymore, because it violates the plugin rules (rule 11) and will be dropped as soon as it stops working. If you want to prevent playlist expirations, then you'll have to update the plugin yourself and sideload your plugin changes.

You're also commenting on a six-year-old and unrelated issue. I'm therefore locking this now...
