### ISSUE TITLE
streamlink keeps closing Twitch streams

### ISSUE THREAD

**Issue by elvar152** [streamlink/streamlink#1619] opened 2018-04-24 02:09 UTC
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*
*Also check the list of known issues before reporting an issue!*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

Whenever I launch streamlink against a Twitch.tv URL it closes the player at random times but always within a few minutes.

### Expected / Actual behavior

I would expect Streamlink to continue playing the stream

### Reproduction steps / Explicit stream URLs to test

1. `streamlink http://twitch.tv/STREAMNAME worst`

### Logs

_Logs are always required for a bug report, use `-l debug` [(help)](https://streamlink.github.io/cli.html#cmdoption-l)
Make sure to **remove username and password**
You can upload your logs to https://gist.github.com/ or_

```
~$ streamlink -l debug http://www.twitch.tv/STREAMNAME worst
[cli][debug] OS:         Linux-4.4.0-119-generic-x86_64-with-Ubuntu-16.04-xenial
[cli][debug] Python:     2.7.12
[cli][debug] Streamlink: 0.11.0
[cli][debug] Requests(2.9.1), Socks(1.6.7), Websocket(0.47.0)
[cli][info] Found matching plugin twitch for URL http://www.twitch.tv/STREAMNAME
[plugin.twitch][debug] Getting live HLS streams for STREAMNAME
[cli][info] Available streams: audio_only, 720p (worst, best)
[cli][info] Opening stream: 720p (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 8073; Last Sequence: 8091
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 8089; End Sequence: None
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 8089 to queue
[stream.hls][debug] Adding segment 8090 to queue
[stream.hls][debug] Adding segment 8091 to queue
[stream.hls][debug] Download of segment 8089 complete
[cli][info] Starting player: /usr/bin/vlc
[stream.hls][debug] Download of segment 8090 complete
[stream.hls][debug] Download of segment 8091 complete
[cli][debug] Writing stream to output
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 8092 to queue
[stream.hls][debug] Adding segment 8093 to queue
[stream.hls][debug] Download of segment 8092 complete
[stream.hls][debug] Download of segment 8093 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 8094 to queue
[stream.hls][debug] Adding segment 8095 to queue
[stream.hls][debug] Adding segment 8096 to queue
[stream.hls][debug] Download of segment 8094 complete
[stream.hls][debug] Download of segment 8095 complete
[stream.hls][debug] Download of segment 8096 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 8097 to queue
[stream.hls][debug] Adding segment 8098 to queue
[stream.hls][debug] Adding segment 8099 to queue
[stream.hls][debug] Download of segment 8097 complete
[stream.hls][debug] Download of segment 8098 complete
[stream.hls][debug] Download of segment 8099 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 8100 to queue
[stream.hls][debug] Adding segment 8101 to queue
[stream.hls][debug] Adding segment 8102 to queue
[stream.hls][debug] Download of segment 8100 complete
[stream.hls][debug] Download of segment 8101 complete
[stream.hls][debug] Download of segment 8102 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 8103 to queue
[stream.hls][debug] Adding segment 8104 to queue
[stream.hls][debug] Adding segment 8105 to queue
[stream.hls][debug] Download of segment 8103 complete
[stream.hls][debug] Download of segment 8104 complete
[stream.hls][debug] Download of segment 8105 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 8106 to queue
[stream.hls][debug] Adding segment 8107 to queue
[stream.hls][debug] Adding segment 8108 to queue
[stream.hls][debug] Download of segment 8106 complete
[stream.hls][debug] Download of segment 8107 complete
[stream.hls][debug] Download of segment 8108 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 8109 to queue
[stream.hls][debug] Adding segment 8110 to queue
[stream.hls][debug] Download of segment 8109 complete
[stream.hls][debug] Download of segment 8110 complete
[cli][info] Player closed
[stream.hls][debug] Closing worker thread
[stream.hls][debug] Closing writer thread
[cli][info] Stream ended
[cli][info] Closing currently open stream...

```

### Comments, screenshots, etc.

...

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment] 2018-04-24 02:38
I can't duplicate this at all, are you sure you don't have some sort of connection issue? Maybe try this option from the docs: https://streamlink.github.io/cli.html#cmdoption-hls-segment-timeout to see if the connection simply isn't waiting long enough.

**Comment by elvar152** [comment] 2018-04-24 02:50
Hi Gravyboat, thanks for the reply. I'm getting this from multiple servers located in different regions and networks. If I use passthrough with VLC I don't have a problem. I'll check out the link you posted.

Kind regards,

**Comment by elvar152** [comment] 2018-04-24 03:16
Hey Gravyboat, I've been testing using timeouts ranging from 20-60 and it doesn't seem to make a difference. Streamlink closes randomly anywhere from a few seconds to a few minutes.

**Comment by bastimeyer** [comment] 2018-04-25 21:44
According to your logs, there are no timeouts in the HLS requests. The reason why Streamlink is stopping is because the player got closed, either by a user action or by something else.
Can you try using the `-o` parameter and writing the stream to the file system instead of watching it in your player, so you can be sure this isn't an issue caused by the player?

**Comment by elvar152** [comment] 2018-04-26 02:11
Hi bastimeyer, when I used `-o /dev/null` I did not have any issues. I'm guessing this means I have something wrong with VLC on both my VPS boxes. Any suggestions on troubleshooting the issue between VLC and Streamlink? Thanks for the reply!

Cheers!

**Comment by bastimeyer** [comment] 2018-04-26 08:44
https://streamlink.github.io/cli.html#cmdoption-verbose-player

**Comment by bastimeyer** [comment] 2018-05-11 05:29
Can we close this issue?

**Comment by elvar152** [comment] 2018-05-11 05:30
Sure thing, thank you!!

**Closed** 2018-05-11 05:33 UTC
Labels: more info required, unconfirmed
