### ISSUE TITLE
Authentication for FilmOn Plugin - Required since 01.05.2017 even for SD streams

### ISSUE THREAD

**Issue by Aylon1** [streamlink/streamlink#1087] opened 2017-07-11 13:36 UTC
### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

As FilmOn has ceased to provide free SD streams since 01.05.2017, streamlink can only stream app. 2min of SD content. After that "taser"-time the reloading of the playlist will fail and produce a timeout error (see attachments).

Similar to Twitch & Co., would it be possible to add authentication to continue to use FilmOn? Even in HD after the login has completed?

### Environment details

Operating system and version: Windows 10 Pro
Streamlink and Python version: 0.7.0 (streamlink)

[stderr.txt](https://github.com/streamlink/streamlink/files/1138999/stderr.txt)
[stout.txt](https://github.com/streamlink/streamlink/files/1139000/stout.txt)

**Comment by beardypig** [comment] 2017-07-11 14:54
From the logs it seemed to run for 1h17m was the output file invalid? (By the way it should be `.ts`, no `.flv`)

**Comment by Aylon1** [comment] 2017-07-11 18:36
Hmmm, sorry about this, but I tested multiple times before and the streams (different channels) always broke off @ round about 2 - 2,5 minutes. Its automatically recording and this particular case did go through until the end for the first time in 48hrs. 

Here the log files from the next attempt which again failed:

[stderr.txt](https://github.com/streamlink/streamlink/files/1139894/stderr.txt)
[stout.txt](https://github.com/streamlink/streamlink/files/1139893/stout.txt)

Whereas it then seems to have nothing to do with the changes to filmon then. Rather that I have to play with the --hls-playlist-reload-attempts and possibly --hls-segment-timeout or --hls-timeout options.

Thanks for pointing out the .ts mistake!

This is an incredible program and thank you very much for the great support as well!

**Comment by gravyboat** [comment] 2017-07-12 01:01
@Aylon1 It seems like something is messed up with those text files you posted (I can't access them for some reason), can you post to gist.github.com if you're still seeing problems?

**Comment by Aylon1** [comment] 2017-07-12 11:36
@beardypig here the gist link https://gist.github.com/Aylon1/019d53e895e6d63080f0e164a35f9da0

Seems to be working sometimes and sometimes i get the reload attempt max exceeded and it stops.

**Comment by cirrusUK** [comment] 2017-08-05 19:47
i only get the timeout when using browser, streamlink keeps on truckin !

**Comment by back-to** [comment] 2018-05-17 19:39
a login is not required with streamlink

---

your other issue is a duplicate of #1231
which is a local issue

---

closing

**Closed by back-to** 2018-05-17 19:39 UTC
Labels: plugin request, question
