### ISSUE TITLE
Webcam plugins are down

### ISSUE THREAD

**Issue by rozzz333** [streamlink/streamlink#2674] opened 2019-10-30 11:19 UTC
## Plugin Issue

- [ ] This is a plugin issue and I have read the contribution guidelines.

### Description

Hello

 It seems since two days ago some plugin including camsoda and chaturbate has been down,
I've been using them on windows server 2012 for 2 years without any problem but over two days ago it doesn't work
please consider it.

### Reproduction steps / Explicit stream URLs to test

1. ...
2. ...
3. ...

### Log output

```
REPLACE THIS TEXT WITH THE LOG OUTPUT
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment] 2019-10-30 11:45
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests
> NSFW sites of a pornographic nature (cam sites, porn sites, etc.)

See #1838 and #2003, more specifically
https://github.com/streamlink/streamlink/pull/1838#issuecomment-459184294
https://github.com/streamlink/streamlink/pull/1838#issuecomment-460016268

Also a duplicate of
#2197, #2290, #2433
https://github.com/streamlink/streamlink/issues?utf8=%E2%9C%93&q=chaturbate

**Closed by bastimeyer** 2019-10-30 11:45 UTC
