### ISSUE TITLE
Youtube Plugin: "This plugin does not support protected videos" error on an unprotected video

### ISSUE THREAD

**Issue by scottbernstein** [streamlink/streamlink#564] opened 2017-02-10 15:31 UTC
### Checklist

- [x] This is a bug report.
- [ ] This is a plugin request.
- [ ] This is a feature request.
- [ ] I used the search function to find already opened/closed issues or pull requests.

### Description
The following request for an unprotected YouTube video gives an error stating "This plugin does not support protected videos, try youtube-dl instead":
streamlink https://www.youtube.com/watch?v=L3yTZQitI0c

You'll note that the video is not protected and totally public if you hit the URL in your browser

### Expected / Actual behavior
It should stream the video like it does most others

### Reproduction steps / Stream URLs to test

- https://www.youtube.com/watch?v=L3yTZQitI0c

### Environment details (operating system, python version, etc.)
Windows 7 64 bit, Python 2.7.2

**Comment by beardypig** [comment] 2017-02-10 15:52
It is a protected video. Protected doesn't mean that it is not public, it means that it has an extra layer of protection that stops `streamlink` from playing the stream. At some point we hope to add support for protected videos. 

This is a duplicate of #203.

**Comment by scottbernstein** [comment] 2017-02-10 16:18
Ah, ok. Thanks @beardypig

On Feb 10, 2017, at 10:52 AM, beardypig <notifications@github.com<mailto:notifications@github.com>> wrote:


It is a protected video. Protected doesn't mean that it is not public, it means that it has an extra layer of protection that stops streamlink from playing the stream. At some point we hope to add support for protected videos.

This is a duplicate of #203<https://github.com/streamlink/streamlink/issues/203>.

**Closed** 2017-02-10 16:21 UTC
Labels: duplicate, question
