### ISSUE TITLE
Some fields are missing in the file name (Twitch)

### ISSUE THREAD

**Issue by HellbringerOnline** [streamlink/streamlink#5289] opened 2023-04-13 16:55 UTC
### Checklist

- [X] This is a bug report and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

If I try to set the author's name before the stream has started, I get empty fields in the filename. If I enter the same command after starting the stream, then the filename is saved correctly. (channel name replaced with ******)

```
C:\Program Files\Streamlink>streamlink --retry-streams=3 --twitch-disable-hosting --ringbuffer-size 128M --stream-segment-attempts 60 --stream-segment-threads 10 --stream-segment-timeout 5 --stream-timeout 600 https://www.twitch.tv/****** audio_only -o "D:/Desktop/{time:%Y.%m.%d} {author} - {title} {id}.m4a
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/*****
[cli][info] Waiting for streams, retrying every 3.0 second(s)
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p60, 1080p60 (best)
[cli][info] Opening stream: audio_only (hls)
[cli][info] Writing output to
D:\Desktop\2023.04.13  -  .m4a
[download] Written 7.57 MiB to D:\Desktop\2023.04.13  -  .m4a (14s @ 533.28 KiB/s)   [stream.hls][warning] Encountered a stream discontinuity. This is unsupported and will result in incoherent output data.
 [download] Written 159.71 MiB to D:\Desktop\2023.04.13  -  .m4a (2h02m46s @ 17.33 KiB/s)
ccli][info] Stream ended
[cli][info] Closing currently open stream...
```

**Comment by bastimeyer** [comment] 2023-04-13 17:17
Duplicate of #4411 / #4783

It's a Twitch metadata issue when accessing streams too fast after they've started. We won't be implementing a workaround for that.

**Closed by bastimeyer** 2023-04-13 17:17 UTC
Labels: bug
