### ISSUE TITLE
huya don't work

### ISSUE THREAD

**Issue by OdinTemple** [streamlink/streamlink#4801] opened 2022-09-04 13:32 UTC
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

don't work

### Debug log

```text
X:\>streamlink  https://www.huya.com/15016236  best --loglevel debug
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.8.3
[cli][debug] Streamlink: 4.3.0
[cli][debug] Dependencies:
[cli][debug]  isodate: 0.6.0
[cli][debug]  lxml: 4.9.1
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.10.1
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.28.1
[cli][debug]  websocket-client: 1.3.3
[cli][debug] Arguments:
[cli][debug]  url=https://www.huya.com/15016236
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][info] Found matching plugin huya for URL https://www.huya.com/15016236
error: Unable to validate response text: ValidationError(NoneOrAllSchema):
  ValidationError(dict):
    Unable to validate value of key 'data'
    Context(AnySchema):
      ValidationError(dict):
        Unable to validate value of key 'gameLiveInfo'
        Context(dict):
          Unable to validate value of key 'liveId'
          Context(type):
            Type of '7139493134782371932' should be int, but is str
```

**Comment by bastimeyer** [comment] 2022-09-04 13:59
Duplicate of #4762

> [cli][debug] Streamlink: 4.3.0

Install the latest version from the master branch / from the latest nightly builds if you're on Windows
https://streamlink.github.io/latest/install.html

----

```
$ streamlink -l debug https://www.huya.com/15016236
[cli][debug] OS:         Linux-5.18.16-1-git-x86_64-with-glibc2.36
[cli][debug] Python:     3.10.6
[cli][debug] Streamlink: 4.3.0+47.g8a7717f5
[cli][debug] Dependencies:
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.1
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.14.1
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.28.1
[cli][debug]  websocket-client: 1.3.1
[cli][debug]  importlib-metadata: 4.8.1
[cli][debug] Arguments:
[cli][debug]  url=https://www.huya.com/15016236
[cli][debug]  --loglevel=debug
[cli][debug]  --player=mpv
[cli][info] Found matching plugin huya for URL https://www.huya.com/15016236
[plugins.huya][debug] QUALITY_WEIGHTS: {'source_al': 0, 'source_tx': -1, 'source_hw': 100}
Available streams: source_tx (worst), source_al, source_hw (best)
```

**Closed by bastimeyer** 2022-09-04 13:59 UTC
Labels: plugin issue
