### ISSUE TITLE
Save URL as an alias

### ISSUE THREAD

**Issue by JonnyCodewalker** [streamlink/streamlink#1246] opened 2017-09-25 19:34 UTC
### Checklist

- [ ] This is a bug report.
- [x] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description
Might be either out of scope or already implemented, in these cases please make me aware of it and excuse my poor Google-Fu.

Feature:
Adding the option to set aliases for URLs inside of streamlink, so that you don´t have to copy/type out URLs all the time. As well as an option to list and remove set aliases.

Possible commands:
```
streamlink alias URL name
streamlink remove (alias) name
streamlink list (alias) || streamlink alias
```
Example useage:
```
$ streamlink alias twitch.tv/riotgames riot
[cli][info] 'riot' added as alias for 'twitch.tv/riotgames'

$ streamlink list
[cli][info] Set aliases:
[cli][info] 'riot'      'twitch.tv/riotgames'

$ streamlink remove riot
[cli][info] Alias 'riot' for 'twitch.tv/riotgames' removed
```

This way instead of having to write out:
`streamlink twitch.tv/riotgames best`
You could just write:
`streamlink riot best`

While for the example URL not too useful, if you have smaller streamers who have longer URLs it would be a real blessing.

If that is not considered out of scope I would consider it low-priority, since you can already use  `alias` to achive similar results.

**Comment by bastimeyer** [comment] 2017-09-25 19:51
Duplicate of #777

This kind of feature doesn't belong into Streamlink. If you want to store stream "bookmarks", you should either set shell aliases, write a shell script or use separate streamlink config files with default stream url and quality parameters set that can then be uses as aliases.

If you only want to browse Twitch streams, why don't you simply use [Streamlink Twitch GUI](https://github.com/streamlink/streamlink-twitch-gui) which lets you browse your followed channels? If you don't like GUIs, there are a couple of CLI based wrappers out there, too.

**Closed** 2017-09-25 19:51 UTC
