### ISSUE TITLE
vidio plugin error [https://www.vidio.com/live/204-sctv]

### ISSUE THREAD

**Issue by rollykaunang** [streamlink/streamlink#4002] opened 2021-09-08 22:39 UTC
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

[cli][error] Try 1/1: Could not open stream <HLSStream

### Debug log

```text
C:\WINDOWS\system32>streamlink https://www.vidio.com/live/204-sctv best --logleve debug
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.9.6
[cli][debug] Streamlink: 2.4.0
[cli][debug] Requests(2.26.0), Socks(1.7.1), Websocket(1.2.1)
[cli][debug] Arguments:
[cli][debug]  url=https://www.vidio.com/live/204-sctv
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --rtmp-rtmpdump=rtmpdump.exe
[cli][debug]  --rtmpdump=C:\Program Files (x86)\Streamlink\rtmpdump\rtmpdump.exe
[cli][debug]  --ffmpeg-ffmpeg=C:\Program Files (x86)\Streamlink\ffmpeg\ffmpeg.exe
[cli][info] Found matching plugin vidio for URL https://www.vidio.com/live/204-sctv
[plugins.vidio][debug] Getting stream tokens
[plugins.vidio][debug] HLS URL: https://app-etslive-2.vidio.com/live/204/master.m3u8
[plugins.vidio][debug] Tokens: auth=aFErdkFlK1BDbXFMc3JNQ2p3QjFxbE1hTmwxQWViMUpLOHhjVmdYWVRnYlU3eUppNmhFR25HTHZUR1hXZnQxdkpxbHVJOW5XaTlPR2w2Q2lzM3R6ekh6OFY5a2VjQXJJV1d4bGc5OVNoZ0dlc0UyR3Z2OTVyaHRXR1gwbnRzK1dBZ0k4T0lhcEJoUDdYaFoyTko1anJzZFBJSGVmaGR5S3pvT0dQTWtWMHJvVkVWV1Y5RGRRY3NpRnRmSzVqYW9tWnpoTkVJVUJ4N1A3NURTS2U5Z3FGZWNBRld3Qjh3WnVVTVJ6WDdkL2hBY3liYklOMUsxLzFUMzJwMjVmWFZMRUFVUExvVVlWQkJlUzdPT1JIeXMxLzZzNFFVRDJ3bjRJVUpxOHFCejFlM25PWTdrRTlBcGFZWGxVRUY5cjIxZDdkQlYzbmJNcXlZSHFOQWVLVUhnR2JCd3F6N1dRQ1pZSmxxQVhTOGdBUWpWZkVhcUc4Z3Urb2Z4UjVLVk0rNHBBTHBhTnpzUDZIK1o5UHVMdmFhQnV1NTRXLzU1QjFNMkFjRkdLbmFxWE55Wjk5aVQ1Y1JWcnB6NGpONWUxU2ZhbWpNSmZDNWFjSGdKNFUyZ0MrZzJ2YUNmcXIzbHptZFljQ2dNSCtUZ1dWeDhFQXV0d1lsVHdmR1h0cFZPUm4xdkJWcHBHaUE4YVhLS0V6bExVY0JCNHYrb1NpTGFWL2l1KzFoZmc1K0RBYWVBdFlTYy8yZ1FmajVncVpDRjZvQmZhOVZCenBUc2U3d0pCejZaTEhmMUVkZlNDUE5xMEFWelFMa09BcUJiREx3Z2xOeGF3VlZ1MzVOUkhaYVZLby9ONk9yaCtQWEFDOWRrTGcvTTk4YXU3a0NLUGZXdVlIOEpCaTdjeTVuU1AwSnROTlRwQ1dvaUlWRHZCWlF0OTZkYzNYVnZLSTMvalcvb0YyM2Fnc092OFJtMjdXY0taQS9TaWF6c2IzQ0VUSURUeXptNnh0MWpHTVJ1MkxBZjBOb05LRE9SM3pqczFDaFJZbWVseHVUbmlhUT09&trace_id=1631140466926323223
[utils.l10n][debug] Language code: en_US
[cli][info] Available streams: 240p_alt (worst), 240p, 360p_alt, 360p, 480p_alt, 480p, 720p_alt, 720p (best)
[cli][info] Opening stream: 720p (hls)
[stream.hls][debug] Reloading playlist
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][error] Unable to open URL: https://etslive-2-vidio-com.akamaized.net/exp=1631155046~acl=%2Fhls-p%2Fingest_204_%2A%2F%2A~hmac=0e997de9e663f3930ddd70b066105ec07372b8ba96a635f5b533c78c52474c1a/hls-p/ingest_204_720p/index.m3u8 (403 Client Error: Forbidden for url: https://etslive-2-vidio-com.akamaized.net/exp=1631155046~acl=%2Fhls-p%2Fingest_204_%2A%2F%2A~hmac=0e997de9e663f3930ddd70b066105ec07372b8ba96a635f5b533c78c52474c1a/hls-p/ingest_204_720p/index.m3u8)
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[cli][error] Try 1/1: Could not open stream <HLSStream('https://etslive-2-vidio-com.akamaized.net/exp=1631155046~acl=%2Fhls-p%2Fingest_204_%2A%2F%2A~hmac=0e997de9e663f3930ddd70b066105ec07372b8ba96a635f5b533c78c52474c1a/hls-p/ingest_204_720p/index.m3u8', 'https://app-etslive-2.vidio.com/live/204/master.m3u8?auth=aFErdkFlK1BDbXFMc3JNQ2p3QjFxbE1hTmwxQWViMUpLOHhjVmdYWVRnYlU3eUppNmhFR25HTHZUR1hXZnQxdkpxbHVJOW5XaTlPR2w2Q2lzM3R6ekh6OFY5a2VjQXJJV1d4bGc5OVNoZ0dlc0UyR3Z2OTVyaHRXR1gwbnRzK1dBZ0k4T0lhcEJoUDdYaFoyTko1anJzZFBJSGVmaGR5S3pvT0dQTWtWMHJvVkVWV1Y5RGRRY3NpRnRmSzVqYW9tWnpoTkVJVUJ4N1A3NURTS2U5Z3FGZWNBRld3Qjh3WnVVTVJ6WDdkL2hBY3liYklOMUsxLzFUMzJwMjVmWFZMRUFVUExvVVlWQkJlUzdPT1JIeXMxLzZzNFFVRDJ3bjRJVUpxOHFCejFlM25PWTdrRTlBcGFZWGxVRUY5cjIxZDdkQlYzbmJNcXlZSHFOQWVLVUhnR2JCd3F6N1dRQ1pZSmxxQVhTOGdBUWpWZkVhcUc4Z3Urb2Z4UjVLVk0rNHBBTHBhTnpzUDZIK1o5UHVMdmFhQnV1NTRXLzU1QjFNMkFjRkdLbmFxWE55Wjk5aVQ1Y1JWcnB6NGpONWUxU2ZhbWpNSmZDNWFjSGdKNFUyZ0MrZzJ2YUNmcXIzbHptZFljQ2dNSCtUZ1dWeDhFQXV0d1lsVHdmR1h0cFZPUm4xdkJWcHBHaUE4YVhLS0V6bExVY0JCNHYrb1NpTGFWL2l1KzFoZmc1K0RBYWVBdFlTYy8yZ1FmajVncVpDRjZvQmZhOVZCenBUc2U3d0pCejZaTEhmMUVkZlNDUE5xMEFWelFMa09BcUJiREx3Z2xOeGF3VlZ1MzVOUkhaYVZLby9ONk9yaCtQWEFDOWRrTGcvTTk4YXU3a0NLUGZXdVlIOEpCaTdjeTVuU1AwSnROTlRwQ1dvaUlWRHZCWlF0OTZkYzNYVnZLSTMvalcvb0YyM2Fnc092OFJtMjdXY0taQS9TaWF6c2IzQ0VUSURUeXptNnh0MWpHTVJ1MkxBZjBOb05LRE9SM3pqczFDaFJZbWVseHVUbmlhUT09&trace_id=1631140466926323223')> (No data returned from stream)
error: Could not open stream <HLSStream('https://etslive-2-vidio-com.akamaized.net/exp=1631155046~acl=%2Fhls-p%2Fingest_204_%2A%2F%2A~hmac=0e997de9e663f3930ddd70b066105ec07372b8ba96a635f5b533c78c52474c1a/hls-p/ingest_204_720p/index.m3u8', 'https://app-etslive-2.vidio.com/live/204/master.m3u8?auth=aFErdkFlK1BDbXFMc3JNQ2p3QjFxbE1hTmwxQWViMUpLOHhjVmdYWVRnYlU3eUppNmhFR25HTHZUR1hXZnQxdkpxbHVJOW5XaTlPR2w2Q2lzM3R6ekh6OFY5a2VjQXJJV1d4bGc5OVNoZ0dlc0UyR3Z2OTVyaHRXR1gwbnRzK1dBZ0k4T0lhcEJoUDdYaFoyTko1anJzZFBJSGVmaGR5S3pvT0dQTWtWMHJvVkVWV1Y5RGRRY3NpRnRmSzVqYW9tWnpoTkVJVUJ4N1A3NURTS2U5Z3FGZWNBRld3Qjh3WnVVTVJ6WDdkL2hBY3liYklOMUsxLzFUMzJwMjVmWFZMRUFVUExvVVlWQkJlUzdPT1JIeXMxLzZzNFFVRDJ3bjRJVUpxOHFCejFlM25PWTdrRTlBcGFZWGxVRUY5cjIxZDdkQlYzbmJNcXlZSHFOQWVLVUhnR2JCd3F6N1dRQ1pZSmxxQVhTOGdBUWpWZkVhcUc4Z3Urb2Z4UjVLVk0rNHBBTHBhTnpzUDZIK1o5UHVMdmFhQnV1NTRXLzU1QjFNMkFjRkdLbmFxWE55Wjk5aVQ1Y1JWcnB6NGpONWUxU2ZhbWpNSmZDNWFjSGdKNFUyZ0MrZzJ2YUNmcXIzbHptZFljQ2dNSCtUZ1dWeDhFQXV0d1lsVHdmR1h0cFZPUm4xdkJWcHBHaUE4YVhLS0V6bExVY0JCNHYrb1NpTGFWL2l1KzFoZmc1K0RBYWVBdFlTYy8yZ1FmajVncVpDRjZvQmZhOVZCenBUc2U3d0pCejZaTEhmMUVkZlNDUE5xMEFWelFMa09BcUJiREx3Z2xOeGF3VlZ1MzVOUkhaYVZLby9ONk9yaCtQWEFDOWRrTGcvTTk4YXU3a0NLUGZXdVlIOEpCaTdjeTVuU1AwSnROTlRwQ1dvaUlWRHZCWlF0OTZkYzNYVnZLSTMvalcvb0YyM2Fnc092OFJtMjdXY0taQS9TaWF6c2IzQ0VUSURUeXptNnh0MWpHTVJ1MkxBZjBOb05LRE9SM3pqczFDaFJZbWVseHVUbmlhUT09&trace_id=1631140466926323223')>, tried 1 times, exiting
[cli][info] Closing currently open stream...
```

**Comment by bastimeyer** [comment] 2021-09-09 06:32
The HLS streams don't seem to be returning any data anymore and the site has switched to DASH streams.

I already had a go at rewriting the plugin but I ran into an issue with 403 HTTP responses when requesting the DASH manifest, and I haven't managed to figure out a solution yet. The DASH URL is correct and the headers don't matter when requesting a DASH manifest URL extracted from the browser via curl. This means there must be some additional condition when requesting the stream token (which includes an hmac).

Here's my diff so far:
https://github.com/streamlink/streamlink/compare/master...bastimeyer:plugins/vidio/rewrite

**Comment by back-to** [comment] 2021-09-09 12:02
> The HLS streams don't seem to be returning any data anymore

they still work, use Android User-Agent for a working example in the Browser

> I already had a go at rewriting the plugin but I ran into an issue with 403 HTTP responses when requesting the DASH manifest, and I haven't managed to figure out a solution yet. 

might be some **urllib3/requests** issue with the encoding `%2a%2f%2a` in the akamaized URL

`import urllib.request` works here

```py
import gzip
import urllib.parse
import urllib.request

import requests

# UPDATE url with your session
url = "https://etslive-2-vidio-com.akamaized.net/exp=XXX~acl=%2fhls-p%2fingest_204_%2a%2f%2a~hmac=XXX/hls-p/ingest_204_360p/index.m3u8"
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3558.1 Safari/537.36",
    "Accept-Encoding": "gzip, deflate",
}
req = urllib.request.Request(url, headers=headers)
html = gzip.decompress(urllib.request.urlopen(req).read()).decode('utf-8')
print(html[:200])

"""OUTPUT - OK
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:5937
#EXT-X-TARGETDURATION:6
#EXTINF:6.000,
1631187990000.ts
#EXTINF:6.000,
1631187996000.ts
#EXTINF:6.000,
1631188002000.ts
#EXTINF:6.000,
"""

res = requests.get(url, headers=headers)
print(res.text[:200])
"""OUTPUT - 403
<HTML><HEAD><TITLE>Error</TITLE></HEAD><BODY>
An error occurred while processing your request.<p>
Reference
</BODY></HTML>
"""
```

**Comment by back-to** [comment] 2021-09-09 12:17
Duplicate of https://github.com/streamlink/streamlink/issues/3361#issuecomment-733898857

it would work with `urllib3-1.24.2`
not sure if we can do something about this

**Comment by bastimeyer** [comment] 2021-09-09 21:53
The following diff monkeypatches the `PERCENT_RE.subn` call and never transforms percent-encodings to uppercase hex characters. This fixes the issue with this plugin and the DASH streams work fine.

Invalid characters which require percent-encoding will however still be converted with uppercase hex characters in the `_encode_invalid_chars`'s for-loop, but that's not relevant here and is the correct thing to do anyway.

How much sense does it make patching this on a global level? There are certainly cases where the original behavior is desired, as it conforms to the standard.

```diff
diff --git a/src/streamlink/plugin/api/http_session.py b/src/streamlink/plugin/api/http_session.py
index 6cd3764c..21ea9b96 100644
--- a/src/streamlink/plugin/api/http_session.py
+++ b/src/streamlink/plugin/api/http_session.py
@@ -1,3 +1,4 @@
+import re
 import time
 
 import requests.adapters
@@ -44,6 +45,17 @@ urllib3.connectionpool.HTTPConnectionPool.ResponseCls = _HTTPResponse
 requests.adapters.HTTPResponse = _HTTPResponse
 
 
+# disable urllib3's fixes for precent-encoded URLs
+# never convert precent-encoding to uppercase hex characters
+class PrecentReOverride:
+    @staticmethod
+    def subn(repl, string):
+        return string, string.encode("utf-8", "surrogatepass").count(b"%")
+
+
+urllib3.util.url.PERCENT_RE = PrecentReOverride
+
+
 def _parse_keyvalue_list(val):
     for keyvalue in val.split(";"):
         try:
```

**Comment by back-to** [comment] 2021-09-10 06:35
it will work again with https://github.com/streamlink/streamlink/pull/4003

**Closed by back-to** 2021-09-10 06:35 UTC
Labels: duplicate, out of scope, dependencies
