### ISSUE TITLE
WWE Network plugin issue

### ISSUE THREAD

**Issue by Swapnil-96** [streamlink/streamlink#2618] opened 2019-09-05 20:28 UTC
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

The WWE Network plugin hasn't been working since 04/09/19.

### Reproduction steps / Explicit stream URLs to test

1. streamlink -o "output.ts" https://watch.wwe.com/episode/SummerSlam-2019-102329 504p
2. ...
3. ...

### Log output

```
error: Unable to open URL: https://dve-streams.akamaized.net/ns-003/MjAxOQ/OA/M_jI/MTM5-OTYz_/SE-xT_/MQ/master.m3u8?hdnea=exp=1567713867~acl=/ns-003/MjAxOQ/OA/M_jI/MTM5-OTYz_/SE-xT_/MQ/*~id=ff71c696-eb69-464d-8159-08e8f959c3d4~hmac=ab772c2b7e1122fac3da3cb848b8468758551e7a30e2ec467d3d83edb6e4b642&cId=16&vId=90100&cc=IN&rId=&ua=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzc1LjAuMzc3MC4xNDIgU2FmYXJpLzUzNy4zNg%3D%3D&duuid=ff71c696-eb69-464d-8159-08e8f959c3d4 (HTTPSConnectionPool(host='dve-streams.akamaized.net', port=443): Read timed out.)

```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment] 2019-09-06 04:50
Duplicate of https://github.com/streamlink/streamlink/issues/2585. You'll have to wait for the next stable release or grab a copy of the latest version of the plugin from the master branch and [side load](https://streamlink.github.io/cli.html?highlight=side%20load#sideloading-plugins) it.

**Closed** 2019-09-06 04:50 UTC
Labels: duplicate
