### ISSUE TITLE
Skai TV plugin request

### ISSUE THREAD

**Issue by Twilight0** [streamlink/streamlink#1169] opened 2017-08-14 16:17 UTC
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*
*Also check the list of known issues before reporting an issue!*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

Request for a simple plugin for Skai TV from Greece. It depends on Youtube but changes id very frequently so it is mandatory to get id from their page.

### Expected / Actual behavior

...

### Reproduction steps / Explicit stream URLs to test

URL to test: http://www.skai.gr/player/tvlive/

### Environment details

Operating system and version: Windows 10
Streamlink and Python version: Streamlink 0.7.0 & python 2.7.12

...

### Comments, logs, screenshots, etc.

...

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by fozzysec** [comment] 2017-08-14 17:46
That live is a page that just embed youtube live. You can get the real youtube url and play it by searching the html source, there should be some code like this
```
$("#EnglishPlayer").html('<iframe width="660" height="374" src="http://www.youtube.com/embed/_jJt22AHqV0" frameborder="0" >f</iframe>')
$("#EnglishPlayer").html('<iframe width="660" height="374" src="http://www.youtube.com/embed/CSIM2RMpsps"  frameborder="0"></iframe>')
```
The http://www.youtube.com/embed/_jJt22AHqV0 and http://www.youtube.com/embed/CSIM2RMpsps are the actual url that streamlink can play.

**Comment by Twilight0** [comment] 2017-08-14 17:54
Exactly my point, this changes as frequently as three times a day. It 'd be nice this process to be automated through a plugin, load the page then extract the url and call youtube plugin.

**Comment by unlocKing** [comment] 2017-08-14 18:17
https://www.youtube.com/watch?v=IdGXE8Z6PDE

In the source, you can find the latest id:

**itemprop="contentUrl" href=**

**Comment by Twilight0** [comment] 2017-08-14 18:25
Yes, this is clear enough, I understand. But how can I turn this process into a plugin? The youtube stream changes quite frequently.

**Comment by fozzysec** [comment] 2017-08-14 19:43
@Twilight0 
Have a try on this, I only extracted the first youtube stream because I cannot read that language, I don't know if that is what you need or not/
https://gist.github.com/fozzysec/4172b438b24934a430ad8d3b60e528ce

**Comment by unlocKing** [comment] 2017-08-14 20:15
That doesn't work..

If you watch the live video on that page, you will see it does not match.

**Comment by Twilight0** [comment] 2017-08-14 20:20
@unlocKing Yes I noted this on a comment in the snippet gist page.

**Comment by Twilight0** [comment] 2017-08-14 21:01
I don't know if this follows your coding style & streamlink api, but here's my effort for completing the plugin: https://gist.github.com/Twilight0/7519ae985883e117cb12c53e4a93020e

**Comment by fozzysec** [comment] 2017-08-15 02:15
I don't have it tested on my computer because youtube was blocked in China, but I tested it on my server it seems to work.
```
streamlink http://www.skai.gr/player/tvlive/ best -O|ffmpeg -i pipe:0
ffmpeg version 2.8.11-0ubuntu0.16.04.1 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
[cli][info] streamlink is running as root! Be careful!
[cli][info] Found matching plugin skai for URL http://www.skai.gr/player/tvlive/
[cli][info] Available streams: audio_mp4, audio_webm, 144p (worst), 240p, 360p (best)
[cli][info] Opening stream: 360p (http)
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'pipe:0':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2013-09-15 17:35:00
  Duration: 02:25:53.25, start: 0.000000, bitrate: N/A
    Stream #0:0(und): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p, 640x360, 287 kb/s, 30 fps, 30 tbr, 60 tbn, 60 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 96 kb/s (default)
    Metadata:
      creation_time   : 2013-09-15 17:35:41
      handler_name    : IsoMedia File Produced by Google, 5-11-2011
At least one output file must be specified
error: Error when writing to output: [Errno 32] Broken pipe, exiting
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```
What is the problem you've got when using this script? It doesn't return the correct video or it doesn't return any video?

**Comment by beardypig** [comment] 2017-08-15 05:54
FYI, you can use `self.session.streams` to delegate to another plugin - it'll workout which plugin to use, no need to bind etc. (see the apac plugin). :-)

**Comment by fozzysec** [comment] 2017-08-15 06:16
Thanks I modified it to use `self.session.streams`, it is much more simple now.

**Comment by beardypig** [comment] 2017-08-15 10:36
Feel free to submit it as a PR.

**Comment by unlocKing** [comment] 2017-08-15 12:37
This still does not play..

Only get a frozen image on playback??

**Comment by fozzysec** [comment] 2017-08-15 13:52
It is very strange that it doesn't work, I'm trying to figure out the cause of the problem.

**Comment by back-to** [comment] 2017-08-15 14:09
use VLC 3 for youtube live

https://streamlink.github.io/players.html#youtube-live-does-not-work-with-vlc

**Comment by gravyboat** [comment] 2017-08-15 16:12
Closing since #1171 is merged.

**Closed by gravyboat** 2017-08-15 16:12 UTC
