### ISSUE TITLE
Sometimes Ctrl-C doesn't end the connection to Twitch

### ISSUE THREAD

**Issue by thinkpad4** [streamlink/streamlink#521] opened 2017-02-03 01:48 UTC
### Checklist

- [x] This is a bug report.
- [ ] This is a plugin request.
- [ ] This is a feature request.
- [ ] I used the search function to find already opened/closed issues or pull requests.

### Description
Sometimes when a stream cuts off, for tech reasons or twitch reasons I can't Ctrl-C the connection in command prompt.

### Expected / Actual behavior
To have Ctrl-C end a connection every time

### Reproduction steps / Stream URLs to test
It doesn't happen all the time so reproducing it is hard

### Environment details (operating system, python version, etc.)
Win7 64 bit latest nightly

**Comment by beardypig** [comment] 2017-02-03 10:50
Does it work if you press Ctrl-C again?

**Comment by gravyboat** [comment] 2017-02-03 17:26
I noticed this on my Linux box as well. @beardypig Yeah you just have to hit `Ctrl-C` again.

**Comment by beardypig** [comment] 2017-02-03 17:32
What does it print to the console when it doesn't work? 
It could be some exception handling grabbing `KeyboardInterrupt` when it shouldn't...

**Comment by gravyboat** [comment] 2017-02-03 17:33
Hmm, I just tested this on `0.3.1` and I'm not encountering the issue, it does hang for a split second because it's shutting everything down, but it does exit correctly with a single `Ctrl-C`. I'll do some more testing in the next day or two to see if I can duplicate. @beardypig when it was happening it just looked like:
```
^C^CInterrupted! Exiting...
[cli][info] Closing currently open stream...
```

**Comment by beardypig** [comment] 2017-02-03 17:39
Would it eventually quit? It could be the StreamWorker thread still chomping through the segments and not interrupting the download... 

Side note: There are quite a few issues with the Stream downloader classes... I have been redesigning them a bit :)

**Comment by gravyboat** [comment] 2017-02-03 17:46
I honestly don't know, it was never a big enough deal to me to wait it out so I just hit `Ctrl-C` again. It doesn't even happen all the time.

**Comment by beardypig** [comment] 2017-02-03 18:33
Fair enough, it's probably the threads just not stopping right away...

**Comment by thinkpad4** [comment] 2017-02-03 23:15
Like I said, it's not every single time, but it seems to be related to a stream going down quick, like if the streamer's pc rebooted and they didn't have time to click end

**Comment by thinkpad4** [comment] 2017-02-03 23:36
@beardypig and to answer your first question, no repeated Ctrl-C does not do anything, I have to close the command prompt to end it.  Mind you VLC closed already so it has to be some process in streamlink

**Comment by gravyboat** [comment] 2017-02-15 05:59
@thinkpad4 Is this still happening for you on `0.3.2`? I'm not encountering it any longer.

**Comment by thinkpad4** [comment] 2017-02-15 06:53
@gravyboat the problem is I don't know when it happens, i THINK it is when the streamer gets cut off without ending their stream gracefully, ie clicking end on OBS.  but I can't be sure.  And I have no way of testing it

**Comment by beardypig** [comment] 2017-02-15 07:17
Anyone able to set up a stream to test this on, at least so we can try and reproduce the issue. It might be easier to coordinate on gitter.im(?) for something like this.

**Comment by mtcjayne** [comment] 2018-05-12 12:09
Multiple Ctrl+C does not close Streamlink when called from a Cygwin terminal. It does work for me in a Windows command prompt but I'd like it to correctly respond.

**Comment by mtcjayne** [comment] 2018-05-12 12:43
@beardypig Can I duplicate my `C:\Program Files (x86)\Streamlink\` directory and modify `pkgs\streamlink\stream\segmented.py` in that duplicated directory to accomplish that?

**Comment by beardypig** [comment] 2018-05-12 12:46
You should be able to modify that file directly.

**Comment by mtcjayne** [comment] 2018-05-12 12:53
That does not resolve the issue. I still have to manually find the Python process and kill it.

**Comment by beardypig** [comment] 2018-05-12 14:10
OK, can you run it with `-ldebug` and show us the end of the log? It should say things about closing the stream, etc

**Comment by mtcjayne** [comment] 2018-05-15 06:42
Yeah I'll try to check that this week.

**Comment by mtcjayne** [comment] 2018-05-16 17:43
No change in behavior.

``[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.5.2
[cli][debug] Streamlink: 0.12.1
[cli][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.47.0)
[cli][info] Found matching plugin youtube for URL https://gaming.youtube.com/watch?v=Le7_KxcIK4s
[plugin.youtube][debug] get_video_info - 1: Found data
[plugin.youtube][debug] MuxedStream: v 137 a 251 = 1080p
[cli][info] Available streams: audio_mp4, audio_webm, 144p (worst), 180p, 360p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (muxed-stream)
[stream.][debug] Opening http substream
[stream.][debug] Opening http substream
[stream.mp4mux-ffmpeg][debug] ffmpeg command: C:\Program Files (x86)\Streamlink\ffmpeg\ffmpeg.exe -nostats -y -i \\.\pipe\ffmpeg-24012-700 -i \\.\pipe\ffmpeg-24012-37 -c:v copy -c:a copy -map 0 -map 1 -f matroska pipe:1
[stream.mp4mux-ffmpeg][debug] Starting copy to pipe: \\.\pipe\ffmpeg-24012-700
[stream.mp4mux-ffmpeg][debug] Starting copy to pipe: \\.\pipe\ffmpeg-24012-37
[cli][debug] Pre-buffering 8192 bytes
[cli][debug] Checking file output
[cli][debug] Writing stream to output``

Have to close the Python process manually. I hit Ctrl+C, Streamlink doesn't appear to have even noticed.

**Comment by beardypig** [comment] 2018-05-16 19:16
@mtcjayne using the latest PR version from today? #1658?

**Comment by beardypig** [comment] 2018-05-16 20:46
Are you using the standard Windows installer? Which shell did you say you were using Cgwin, cmd, powershell, or something more exotic? 
I’ll try to duplicate it on my Windows 10 VM.

**Comment by mtcjayne** [comment] 2018-05-16 23:54
I used the stable 0.12.1 installer and I'm using Cygwin with Bash 4.4.12(3).

**Comment by bastimeyer** [comment] 2018-05-17 04:13
@mtcjayne 
The stable installer doesn't include the changes mentioned by @beardypig (#1658). These changes haven't been merged into `master` yet, so you can't use a nightly Windows build and a new release also hasn't been published yet, so you can't use the latest stable build either.

You need to clone his streamlink fork, check out the branch of the linked pull request and build Streamlink from there. You should also be able to do this via pip.
```bash
git clone --branch thread-blocking-exit https://github.com/beardypig/streamlink.git
cd streamlink
python setup.py install

# or much more simple
pip install git+https://github.com/beardypig/streamlink.git@thread-blocking-exit
```

**Comment by mtcjayne** [comment] 2018-05-17 07:58
I've already merged those changes as discussed.

**Comment by mtcjayne** [comment] 2018-05-17 10:42
@bastimeyer I have merged both changes. I merged the first changes and experienced no difference 5 days ago, then merged the second changes and experienced no difference 15 hours ago.

@beardypig All streams that I have tried reliably produce this behavior. It's possible the streams themselves are somehow different, but I don't think that's the simplest explanation since I've grabbed random live streams to test each time I've tried something new.

**Comment by beardypig** [comment] 2018-05-17 11:15
Seems to be an issue with passing the Ctrl-C on to the Windows processes, Windows signals don't work like posix signals... So you can use `winpty` as a wrapper to call streamlink and that seems to fix it for me, but you gotta install `winpty` yourself.

```
$ winpty -- streamlink https://gaming.youtube.com/watch?v=Le7_KxcIK4s best
[cli][info] Found matching plugin youtube for URL https://gaming.youtube.com/watch?v=Le7_KxcIK4s
[cli][info] Available streams: audio_mp4, audio_webm, 144p (worst), 180p, 360p, 720p, 1080p (best)
[cli][info] Opening stream: 720p (http)
[cli][info] Starting player: "C:\Program Files\VideoLAN\VLC\vlc.exe"
[cli][info] Stream ended
Interrupted! Exiting...
[cli][info] Closing currently open stream...
```

**Comment by gravyboat** [comment] 2018-05-29 01:58
Closing since #1658 should address this, if it's still a problem after testing out the nightly/next release we can re-open.

**Closed by gravyboat** 2018-05-29 01:58 UTC
Labels: bug
