### ISSUE TITLE
--hls-live-restart not working

### ISSUE THREAD

**Issue by GiovanH** [streamlink/streamlink#2935] opened 2020-04-25 22:57 UTC
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.

### Description

I am trying to save a stream. It's marked as "live", but the actual video content has stopped streaming. The `--hls-live-restart` option should save each segment from the beginning of the stream until the stream reaches the end, and save that to a file. Instead, it saves the last few segments and then times out.

### Log output

```
$ streamlink -l debug --hls-live-restart -o "out.ts" https://www.youtube.com/watch?v=[ID] best
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.6
[cli][debug] Streamlink: 1.3.1
[cli][debug] Requests(2.22.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=[ID]
[plugin.youtube][debug] Video ID from URL
[plugin.youtube][debug] Using video ID: [ID]
[plugin.youtube][debug] get_video_info - 1: Found data
[plugin.youtube][debug] This video is live.
[utils.l10n][debug] Language code: en_US
[cli][info] Available streams: 144p (worst), 240p, 360p, 480p, 720p (best)
[cli][info] Opening stream: 720p (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 871; Last Sequence: 877
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 871; End Sequence: None
[stream.hls][debug] Adding segment 871 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 872 to queue
[stream.hls][debug] Adding segment 873 to queue
[stream.hls][debug] Adding segment 874 to queue
[stream.hls][debug] Adding segment 875 to queue
[stream.hls][debug] Adding segment 876 to queue
[stream.hls][debug] Adding segment 877 to queue
[stream.hls][debug] Download of segment 871 complete
[cli][debug] Checking file output
[cli][debug] Writing stream to output
[stream.hls][debug] Download of segment 872 complete
[stream.hls][debug] Download of segment 873 complete
[download][out.ts] Written 1.7 MB (0s @ 2.3 MB/s)                                                        [stream.hls][debug] Download of segment 874 complete
[stream.hls][debug] Download of segment 875 complete
[stream.hls][debug] Download of segment 876 complete
[stream.hls][debug] Download of segment 877 complete
[download][out.ts] Written 4.2 MB (1s @ 3.2 MB/s)                                                        [stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[stream.segmented][debug] Closing writer thread
[cli][info] Stream ended
Interrupted! Exiting...
[cli][info] Closing currently open stream...
```

**Comment by gravyboat** [comment] 2020-04-25 23:07
Doesn't work any more because the streams are dash. Duplicate of https://github.com/streamlink/streamlink/issues/2890, closing.

**Closed by gravyboat** 2020-04-25 23:07 UTC
