### ISSUE TITLE
Support for DingIt.tv

### ISSUE THREAD

**Issue by Brainzyy** [streamlink/streamlink#227] opened 2016-11-28 22:47 UTC
This is a continuation of https://github.com/chrippa/livestreamer/issues/974
I'm usually pretty good at figuring out stream links and all that stuff, but this one had me scratching my head.
All the talk about a extension being needed to play their streams is not true anymore.

**Comment by beardypig** [comment] 2016-11-28 23:06
Sounds like a fun challenge :-)

**Comment by Brainzyy** [comment] 2016-11-28 23:30
@beardypig Yeah, I thought so too ;) From what I could find out last time, they use a service which obfuscates all the trafic and makes it (for me at least ;) ) unsniffable.

**Comment by beardypig** [comment] 2016-11-29 11:09
It think it was quite simple to find the streams, maybe I missed something??
All the highlights or previous live events I tried were available in HLS. @Brainzyy do you know any streams that were ocshield (octoshape) only?

**Comment by beardypig** [comment] 2016-11-29 13:03
I created a PR which supports HLS, I was unable to find a stream that did not work. If you find one, let me know :)

**Comment by Brainzyy** [comment] 2016-11-29 14:56
Thank you very much @beardypig. Is there any way you could explain how you did this? Last time I tried, everything was obfuscated with ocshield.

**Comment by beardypig** [comment] 2016-11-29 15:09
Just fired up the good ol' Chrome developer tools... When looking at those streaming sites, I normally search in the network list for `m3u8`, `mpd`, etc. `master.m3u8` pops right out :) Working back from there, it was the `api/get_player_flashvars` call to get the stream url path. Poking around in the swf just confirmed that the HLS urls were hardcoded. I did a bit of mitmproxy foo to get the client to request the the `akaurl` based stream, by deleting the `pereakaurl` key from the response :) 

They might have changed it recently to move away from the octoshape stuff :)

**Comment by Brainzyy** [comment] 2016-11-29 15:33
Yeah, I'm sure I checked all that stuff last time :p It's been a while. Thank you for checking again and doing all that effort :) @beardypig

**Comment by gravyboat** [comment] 2016-11-29 17:28
Hey guys feel free to keep the discussion going but I'm going to close this since I merged the associated PR.

**Closed by gravyboat** 2016-11-29 17:28 UTC
Labels: plugin request
