### ISSUE TITLE
Install directory for Windows setup have changed between 0.8.1 and 0.9

### ISSUE THREAD

**Issue by Porkepix** [streamlink/streamlink#1340] opened 2017-11-22 01:54 UTC
### Description

On Windows, default installation path have changed between 0.8..1 and 0.9.
This may be wished, but I searched into changelog/release note and commits and couldn't find anything related.
Version 0.8.1 setup tryto install into `C:\Program Files (x86)\Streamlink` by default.
Version 0.9 setup tryto install into `C:\Users\%USER%\AppData\Local\Streamlink` by default

### Expected / Actual behavior

Installation path should be the same or change should have been visible somewhere.

### Reproduction steps / Explicit stream URLs to test

Just run both setups and take a look at the installation path

### Environment details

Tested on Windows 10, might be able to test W7 in the coming days if needed

This might also come from choices at the setup build step, but maybe this is not in the repository.

**Comment by thinkpad4** [comment] 2017-11-22 03:12
No, win7 does the same thing @Porkepix

**Comment by gravyboat** [comment] 2017-11-22 04:37
There haven't been any changes to the installer script that should cause this: https://github.com/streamlink/streamlink/blob/master/script/makeinstaller.sh

**Comment by bastimeyer** [comment] 2017-11-22 04:53
There was a new major release of pynsist (2.0.0) a month ago or so and it doesn't have a strict version set in the dev dependencies here, so this might be the cause of the issue... I'll have a look at the default nsis template privided by pynsist.

Could someone please check the different nightly builds and see when this started to happen? Thanks.
https://bintray.com/streamlink/streamlink-nightly/streamlink#files

**Comment by bastimeyer** [comment] 2017-11-22 05:16
https://pynsist.readthedocs.io/en/latest/releasenotes.html

> Pynsist installers can now install into a per-user directory, allowing them to be used without admin access.

**Comment by gravyboat** [comment] 2017-11-22 05:27
I guess we could set it back to the old directory just so people don't have to modify the path for future installations? It's not really a problem to me since I use an alternate install directory, but I imagine most people are using the default location.

**Comment by bastimeyer** [comment] 2017-11-22 05:34
So this change is responsible for the changes:
https://github.com/takluyver/pynsist/commit/a33a1daf7861bc283fda791d70b2033efca5638c

They are now using the `MultiUser` scripts of NSIS:
https://github.com/kichik/nsis/blob/master/Contrib/MultiUser/MultiUser.nsh
instead of setting the InstallDir explicitly:
https://github.com/takluyver/pynsist/commit/a33a1daf7861bc283fda791d70b2033efca5638c#diff-de7e4d7246a1813421fcd19a22f94a5bL32

In the pynsist config there's a custom install dir function defined:
https://github.com/takluyver/pynsist/blob/2.0/nsist/pyapp.nsi#L21
https://github.com/takluyver/pynsist/blob/2.0/nsist/pyapp.nsi#L209-L216
Maybe we can overwrite it and restore the previous $INSTDIR logic.

**Comment by bastimeyer** [comment] 2017-11-22 05:50
I think the issue is that `MULTIUSER_EXECUTIONLEVEL` is set to `highest` instead of `admin`, which makes the default MultiUser script choose the non-privileged install dirs.

https://github.com/takluyver/pynsist/blob/2.0/nsist/pyapp.nsi#L15
https://github.com/kichik/nsis/blob/master/Contrib/MultiUser/MultiUser.nsh#L249-L283

Let me check this (I need to set this all up again on my machine 😭)...

**Comment by bastimeyer** [comment] 2017-11-22 06:21
@beardypig 
Do you know how `MULTIUSER_INSTALLMODE_DEFAULT_CURRENTUSER` can be undefined here:
https://github.com/takluyver/pynsist/blob/2.0/nsist/pyapp.nsi#L16

Adding `!undef MULTIUSER_INSTALLMODE_DEFAULT_CURRENTUSER` after the pynsist file extension doesn't work (https://github.com/streamlink/streamlink/blob/0.9.0/script/makeinstaller.sh#L86), but removing it from the pynsist script is working fine and uses the old default install dirs.

Do we need to fork or make a PR for a configurable install dir?

**Comment by thinkpad4** [comment] 2017-11-22 06:50
@bastimeyer It started with  streamlink-0.8.1-20171101.exe

**Comment by Porkepix** [comment] 2017-11-22 09:26
I don't now if this can be related, but many Windows installers have a checkbox asking if the program should be installed for the current user only or for all users.
Maybe it can potentially cover both cases and options depending on that?

**Comment by beardypig** [comment] 2017-11-22 10:25
@bastimeyer, not sure how we can undefine that - maybe it's better to use an old version of `pynist`?

**Comment by bastimeyer** [comment] 2017-11-22 10:31
Sure, I don't see anything wrong with that. It's just a convenience wrapper for building the NSIS config file and nothing has changed on the NSIS side.

**Comment by thinkpad4** [comment] 2017-11-29 02:03
Is this fixed in the latest nightlies?

**Comment by beardypig** [comment] 2018-01-03 13:32
Including `!insertmacro MULTIUSER_PAGE_INSTALLMODE` in the `ui_pages` block gives the user the option to install for all users (current behaviour) or the current user (no admin rights required).

**Comment by bastimeyer** [comment] 2018-01-03 14:43
> Do you know how MULTIUSER_INSTALLMODE_DEFAULT_CURRENTUSER can be undefined here:

I don't know how I could have been this blind, but you can just add
`!undef MULTIUSER_INSTALLMODE_DEFAULT_CURRENTUSER`
to the `modernui` block which comes after the definition of this constant in the pynsist config file. This restores the old installer behavior.

> Including !insertmacro MULTIUSER_PAGE_INSTALLMODE in the ui_pages block gives the user the option to install for all users

If you add this macro without undefining the constant, the default install method will be the user-specific one (the unwanted behavior). However, if you undefine the constant, the default mode will be set to the global installation (the old behavior). This basically gives the user a choice where to install Streamlink while still having the old behavior restored. This would be a compromise.

Any opinions here?
1. Restore behavior entirely?
2. Set global installation as default method while giving the user a choice?

**Comment by beardypig** [comment] 2018-01-03 14:56
Option 2. sounds good to me. I assumed you had tried that already :) Cos you said it had to be undefined before MultiUser.nsh is loaded, and the modernui block is after :)

**Comment by bastimeyer** [comment] 2018-01-03 15:04
Yeah, I don't know what went wrong there when I first tried it...
Going to make a PR with the changes then.

**Comment by beardypig** [comment] 2018-01-03 15:09
Sounds good to me. I've been looking at adding the versioneer stuff @back-to suggested, requires a few changes to the build script but should make slightly nicer version info for nightlies :)

**Closed** 2018-01-04 17:36 UTC
Labels: dependency issue, packages
