### ISSUE TITLE
Pixiv: Unable to open URL, bad request for URL

### ISSUE THREAD

**Issue by JimmyWu1934** [streamlink/streamlink#3482] opened 2021-01-09 17:03 UTC
error: Unable to open URL: https://sketch.pixiv.net/api/lives.json (400 Client Error: Bad Request for url: https://sketch.pixiv.net/api/lives.json)

First encountered this problem on the 6th of Jan when I was trying to download a stream. The last time I successfully downloaded something was on the 2nd.

EDIT:
1) Description and/or reproduction steps
- CLI- streamlink --pixiv-sessionid ******* https://sketch.pixiv.net/@***** best -o "desktop/test.mp4" 
where ***** = my info/streamer name
- Enter device token
- Error.
2) Streamlink version 2.0.0
3) --loglevel debug (not sure what this is for)
-[cli][debug] OS:         Windows 10
-[cli][debug] Python:     3.8.6
-[cli][debug] Streamlink: 2.0.0
-[cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(0.57.0)
-usage: streamlink [OPTIONS] <URL> [STREAM]

**Comment by mkbloke** [comment] 2021-01-09 17:10
**Feedback/answer (see ticked items):**

* As requested in the issue template:
* - [x] Does not meet requirements for issue or feature/plugin request [[1]] [[2]] [[3]]
* - [x] Description and/or reproduction steps are insufficiently detailed
* - [x] Streamlink version in use not specified
* - [x] Full ```--loglevel debug``` log output not provided
* - [ ] Research of prior issues/fixes appears to be insufficient [[4]]
* Other feedback:
* - [ ] Issue is out of scope and/or should be reported/help sought elsewhere
* - [ ] Issue appears to unnecessarily duplicate another issue that is open/closed
* - [ ] User appears to be using an outdated Streamlink version/plugin [[5]] [[6]]
* - [ ] Use of discussions more appropriate (admin can/will convert to discussion) [[7]]
* - [ ] Other (see below)
* Other: N/A

Please amend/close your issue accordingly and/or undertake the requested prior research before opening an issue in future.

[[1]] [Reporting issues][1]
[[2]] [Feature requests][2]
[[3]] [Plugin requests][3]
[[4]] [Search all open/closed issues/pull requests][4]
[[5]] [Install the most recent version of Streamlink][5]
[[6]] [Check the master branch for plugin updates][6]
[[7]] [Streamlink discussions][7]

[1]: https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#reporting-issues
[2]: https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#feature-requests
[3]: https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests
[4]: https://github.com/streamlink/streamlink/issues?q=
[5]: https://streamlink.github.io/install.html
[6]: https://github.com/streamlink/streamlink/tree/master/src/streamlink/plugins
[7]: https://github.com/streamlink/streamlink/discussions

**Comment by back-to** [comment] 2021-01-10 08:32
this plugin works, get new

https://streamlink.github.io/cli.html#cmdoption-pixiv-sessionid
https://streamlink.github.io/cli.html#cmdoption-pixiv-devicetoken

```
$ streamlink --pixiv-devicetoken 123abc --pixiv-sessionid 123_ABC https://sketch.pixiv.net/@abc/lives/123 best
[cli][debug] OS:         Linux
[cli][debug] Python:     3.8.6
[cli][debug] Streamlink: 2.0.0+18.g1d5fb3a
[cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin pixiv for URL https://sketch.pixiv.net/@abc/lives/123
[cli][debug] Plugin specific arguments:
[cli][debug]  --pixiv-sessionid=******** (sessionid)
[cli][debug]  --pixiv-devicetoken=******** (devicetoken)
[plugins.pixiv][debug] Saved cookies: PHPSESSID, __cf_bm, __cfduid, device_token, p_ab_d_id, p_ab_id, p_ab_id_2
[plugins.pixiv][info] Successfully set sessionId and deviceToken
[plugins.pixiv][debug] Found 117 streams
[plugins.pixiv][debug] URL=https://hls.pixivsketch.net/123/123/index.m3u8
[cli][info] Available streams: 720p (worst), 1080p (best)
[cli][info] Opening stream: 1080p (hls)
```

**Closed by back-to** 2021-01-10 08:32 UTC
Labels: does not meet requirements, unconfirmed

**Comment by mkbloke** [comment] 2021-01-10 14:41
The interesting thing is, the OP appears to be using v2.0.0 and the Pixiv plugin has not been updated since that release.

Without full debug log output and fully specified URLs to the content causing the issue, it's impossible to do anything if it cannot be reproduced.

I wonder if the OP is side-loading an older plugin?  Again, full debug log output would help...

**Comment by JimmyWu1934** [comment] 2021-01-10 18:01
There is no specified URL that is causing the issue. I have a text file with the commands ready so I just copy and paste it in.

Here's an example of what I did or tried to do with the loglevel debug command
http://prntscr.com/wkdv7l

Am I the only one with this problem right now? I reinstalled Streamlink and the issue is still there

**Comment by back-to** [comment] 2021-01-10 18:11
@JimmyWu1934 
use ` --pixiv-purge-credentials` once https://streamlink.github.io/cli.html#cmdoption-pixiv-purge-credentials

also make sure that you use the correct `--pixiv-devicetoken` and  `--pixiv-sessionid`

if it doesn't work, get new cookies

https://streamlink.github.io/cli.html#cmdoption-pixiv-devicetoken
https://streamlink.github.io/cli.html#cmdoption-pixiv-sessionid

**Comment by JimmyWu1934** [comment] 2021-01-10 18:40
@back-to 
The purge works! But that's weird because after the purge, I reused the same cookie and device token and it still works. Why is that? Was something corrupt?
