### ISSUE TITLE
Yupptv.com how to ?

### ISSUE THREAD

**Issue by raulsifra** [streamlink/streamlink#1049] opened 2017-06-30 11:22 UTC
Code  Issues 122  Pull requests 5  Pulse
 Open
Add plugin: yupptv #506
@digitalcelery
digitalcelery opened this issue 5 months ago • edited 5 months ago
 plugin request
I am suspecting that cookies/token expires and I am no longer able to play the stream, not even a restart as it returns 403 Client Error: Forbidden

Example of the links I am getting:

http://hlsbanglanews-lh.akamaihd.net/i/ams54_russiatoday@349571/master.m3u8?hdnea=st%3d1485750135%7eexp%3d1485750495%7eacl%3d%2fi%2fams54_russiatoday%40349571%2f*%7edata%3d1814225%7ehmac%3da3a3c4227a1c121aca77c38e9c21252bd881a5a9d5c96d7851ac8f53bb56c2a7&dw=160

Streaming url:

http://hlsbanglanews-lh.akamaihd.net/i/ams54_russiatoday@349571/master.m3u8
Token?:

hdnea=st%3d1485750135%7eexp%3d1485750495%7eacl%3d%2fi%2fams54_russiatoday%40349571%2f*%7edata%3d1814225%7ehmac%3da3a3c4227a1c121aca77c38e9c21252bd881a5a9d5c96d7851ac8f53bb56c2a7&dw=160

Seems like there is linux epoch time that sets the expiry of the stream. So each time i need to login to the website and request new token.

I also know the following:
SWF: http://d3hprka3kr08q2.cloudfront.net/staticstorage/jwplayer/jw_7_8_2/jwplayer.loader.swf

Content of M3U8 file:

#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=87000,RESOLUTION=256x144,CODECS="avc1.66.30, mp4a.40.2"
http://hlsbanglanews-lh.akamaihd.net/i/ams54_russiatoday@349571/index_64_av-p.m3u8?sd=10&dw=160&rebase=on&hdntl=exp=1485836971~acl=%2fi%2fams54_russiatoday%40349571%2f*~data=hdntl~hmac=a18a639e66837c960067f07eae81b129b3d20804fd69aaec598f138ab9321128
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=226000,RESOLUTION=384x216,CODECS="avc1.66.30, mp4a.40.2"
http://hlsbanglanews-lh.akamaihd.net/i/ams54_russiatoday@349571/index_200_av-p.m3u8?sd=10&dw=160&rebase=on&hdntl=exp=1485836971~acl=%2fi%2fams54_russiatoday%40349571%2f*~data=hdntl~hmac=a18a639e66837c960067f07eae81b129b3d20804fd69aaec598f138ab9321128
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=403000,RESOLUTION=480x270,CODECS="avc1.66.30, mp4a.40.2"
http://hlsbanglanews-lh.akamaihd.net/i/ams54_russiatoday@349571/index_400_av-p.m3u8?sd=10&dw=160&rebase=on&hdntl=exp=1485836971~acl=%2fi%2fams54_russiatoday%40349571%2f*~data=hdntl~hmac=a18a639e66837c960067f07eae81b129b3d20804fd69aaec598f138ab9321128
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=647000,RESOLUTION=512x288,CODECS="avc1.66.30, mp4a.40.2"
http://hlsbanglanews-lh.akamaihd.net/i/ams54_russiatoday@349571/index_800_av-p.m3u8?sd=10&dw=160&rebase=on&hdntl=exp=1485836971~acl=%2fi%2fams54_russiatoday%40349571%2f*~data=hdntl~hmac=a18a639e66837c960067f07eae81b129b3d20804fd69aaec598f138ab9321128
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1233000,RESOLUTION=704x396,CODECS="avc1.66.30, mp4a.40.2"
http://hlsbanglanews-lh.akamaihd.net/i/ams54_russiatoday@349571/index_1100_av-p.m3u8?sd=10&dw=160&rebase=on&hdntl=exp=1485836971~acl=%2fi%2fams54_russiatoday%40349571%2f*~data=hdntl~hmac=a18a639e66837c960067f07eae81b129b3d20804fd69aaec598f138ab9321128
Also, few attributes such as "Referer" for the m3u8 stream.

**Comment by beardypig** [comment] 2017-06-30 12:03
This is an unnecessary duplicate of #506, please continue any discussion on that issue.

**Closed** 2017-06-30 12:47 UTC
Labels: duplicate

**Comment by princesf1** [comment] 2017-11-22 20:55
did you fix the problem ?
