### ISSUE TITLE
ffmpeg Pipe copy aborted error

### ISSUE THREAD

**Issue by beta2k** [streamlink/streamlink#3381] opened 2020-11-29 21:16 UTC
## Plugin Issue

- [ ] This is a plugin issue and I have read the contribution guidelines.
- [x] I am using the latest development version from the master branch.

### Reproduction steps / Explicit stream URLs to test

1. use this command:
> streamlink --loglevel debug --hls-live-restart -o test.mp4 "https://aivottjab-a.akamaihd.net/IAD/jab-assets/jab-prod-iad/out/v1/732334e942a4465b8af9b21077d4e61d/cenc-083bb0.mpd?encoding=segmentBase&amznDtid=AOAGZA014O5RE" best
2. wait until ~26GB are downloaded
3. see the following error message by ffmpeg.

### Log output

```
[19:48:27,437][stream.dash][debug] Download of segment: https://aivottjab-a.akamaihd.net/IAD/jab-assets/jab-prod-iad/out/v1/732334e942a4465b8af9b21077d4e61d/cenc_video_117_0_5791117.mp4 complete
[download][test.mp4] Written 25.97 GB (2h24m58s @ 1.0 MB/s)                                                         
[19:49:27,503][stream.ffmpegmux][error] Pipe copy aborted: \\.\pipe\ffmpeg-12796-364
[19:49:27,518][stream.ffmpegmux][error] Pipe copy aborted: \\.\pipe\ffmpeg-12796-967
```

### Additional comments, etc.

I am on Windows 10, Streamlink 1.7.0 and FFmpeg 4.3.1.

Could it have something to do with the duration of the video?
[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment] 2020-11-30 16:27
this stream won't work with Streamlink, it is CENC protected.

Duplicate of https://github.com/streamlink/streamlink/issues/2957

**Closed by back-to** 2020-11-30 16:27 UTC
Labels: duplicate
