### ISSUE TITLE
Process carries on but stream is down

### ISSUE THREAD

**Issue by savskii** [streamlink/streamlink#2449] opened 2019-04-27 07:21 UTC
Hello, When i run streamlink after a some time the stream stops in vlc and wont play again unless i manually kill process in linux and restart it. Then it works again.

Is there anyway to automatically detect when a stream is down for it to relaunch itself?

Thanks

**Comment by savskii** [comment] 2019-04-27 09:43
I saw in debug error " Failed to reload playlist "
Its constantly  giving that error over and over again till i end it and restart it

**Comment by back-to** [comment] 2019-05-04 11:41
> I saw in debug error " Failed to reload playlist "

your url expired and got invalid

---

>  Its constantly giving that error over and over again till i end it and restart it

[--hls-timeout](https://streamlink.github.io/cli.html#cmdoption-hls-timeout) probably set to high

---

also duplicate of https://github.com/streamlink/streamlink/issues/2198 and some other issues

**Closed by back-to** 2019-05-04 11:41 UTC
