### ISSUE TITLE
AppImage crashes with some plugins

### ISSUE THREAD

**Issue by 097115** [streamlink/streamlink#4602] opened 2022-06-16 08:28 UTC
### Checklist

- [X] This is a bug report and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

[AppImage](https://github.com/streamlink/streamlink-appimage/releases/tag/4.1.0-2) `streamlink-4.1.0-2-cp310-cp310-manylinux2014_i686.AppImage` (Ubuntu 16.04) core dumps with some plugins (and with some it does work OK).

### Debug log

```text
streamlink https://www.bloomberg.com/live/us -l debug
[cli][debug] OS:         Linux-4.15.18-041518-generic-i686-with-glibc2.23
[cli][debug] Python:     3.10.4
[cli][debug] Streamlink: 4.1.0
[cli][debug] Requests(2.27.1), Socks(1.7.1), Websocket(1.3.2)
[cli][debug] Arguments:
[cli][debug]  url=https://www.bloomberg.com/live/us
[cli][debug]  --loglevel=debug
[cli][info] Found matching plugin bloomberg for URL https://www.bloomberg.com/live/us
/tmp/.mount_streamnLEh4a/AppRun: line 5:  3153 Illegal instruction     (core dumped) "${PYTHON}" -m 'streamlink' "$@"
```

**Comment by bastimeyer** [comment] 2022-06-16 09:28
Wrong repo... Issues about packages/deployments other than Streamlink's sdist and wheels do not belong here.

The AppImage is also working fine. Just tested it in a fresh i686 Ubuntu 16.04.6 VM:

```
$ ./streamlink-4.1.0-2-cp310-cp310-manylinux2014_i686.AppImage https://www.bloomberg.com/live/us -l debug
[cli][debug] OS:         Linux-4.15.0-45-generic-i686-athlon-with-glibc2.23
[cli][debug] Python:     3.10.4
[cli][debug] Streamlink: 4.1.0
[cli][debug] Requests(2.27.1), Socks(1.7.1), Websocket(1.3.2)
[cli][debug] Arguments:
[cli][debug]  url=https://www.bloomberg.com/live/us
[cli][debug]  --loglevel=debug
[cli][info] Found matching plugin bloomberg for URL https://www.bloomberg.com/live/us
[plugins.bloomberg][debug] Found liveId: PHOENIX_US
[utils.l10n][debug] Language code: en_US
Available streams: 272p (worst), 360p, 720p_alt, 720p, 1080p (best)
```

Since you're experiencing crashes of the Python interpreter only with some plugins, this looks like it's caused by Streamlink's lxml dependency and its own libxml2 dependency, as not all plugins need to parse HTML/XML via this Python C-extension. However, the dependencies are all statically linked, so nothing should be interfering with system libraries. But without a proper error trace, nobody will be able to help.

As you can read in the docs, the appimage contents can be extracted via `--appimage-extract`. After you've done that, you can find the contents in the `./squashfs-root` directory and execute streamlink/python via `./squashfs-root/usr/bin/python -m streamlink ...`.

The following will execute python, load lxml and parse HTML. If this doesn't work, then you'll know the culprit and you can further debug the interpreter crash / segmentation fault.
```sh
./squashfs-root/usr/bin/python -c 'from lxml import etree; print(etree.HTML("<html>").tag)'
```

**Comment by bastimeyer** [comment] 2022-06-16 11:49
> Any hints on how to delve a bit deeper here may be? :)

Since you've extracted the appimage contents, you're now able to debug the python process and its crash, eg. via gdb. You'll have to google how to do that.

You should also take a look at the bloomberg plugin file in the `./squashfs-root/opt/python3.10/lib/python3.10/site-packages/streamlink/plugins/` directory and temporarily remove the following two lines of code:
https://github.com/streamlink/streamlink/blob/4.1.0/src/streamlink/plugins/bloomberg.py#L120-L121
If the plugin works fine after removing the two lines, then the issue lies within lxml, because the plugin is not parsing HTML and querying the parsed result anymore.

The code snippet I posted earlier was just an example of simple HTML parsing, without an XPath query, and without any real content, which is probably why it worked fine on your system, so it doesn't say much.

If the plugin still doesn't work after removing the two lines (I'm not suggesting that as a bugfix, btw), then I don't know why it's failing. The only dependencies of Streamlink with Python C-extensions are lxml and pycryptodome, and only lxml should be of relevance here. The only other options then would be an issue of the Python standard library, or the interpreter itself, but that would be weird considering that other plugins are working fine, as you said.

Either way, this is all I can do in order to help you. "Illegal instruction" suggests/implies that some instruction is not supported by your CPU, btw. Any reasons for using i686 in mid-2022 other than lack of awareness or using a CPU that's at least 15 years old?

**Comment by bastimeyer** [comment] 2022-06-16 19:47
> Seems like `streamlink.plugin.api.validate` is the culprit

No, as said, the Python interpreter crash occurs when parsing HTML/XML and querying the result via XPath, which is done via Streamlink's lxml dependency and its Python C-extension.

If you want to add some information, post the CPU model you're using. It's possible that it's too old, and the libs that lxml bundles in its wheel which the appimage includes rely on instructions that are unsupported on your system. There are lots of different x86 feature sets/levels. But I'm not an expert here.
https://www.google.com/search?q=Illegal+instruction+(core+dumped)

Going to close this, since I can't reproduce it and the appimage is working fine in a fresh VM on my system using the same OS config as yours. I have also given as much details as I can to help you debug this, and the issue was posted in the wrong repo anyway.

If you can't resolve this, the only option you have is installing Streamlink in a virtual environment and building lxml from source, which requires `libxml2-dev` and `libxslt-dev` to be installed on your system.
https://streamlink.github.io/install.html#pypi-package-and-source-code

```sh
python3 -m virtualenv ~/streamlink-venv
source ~/streamlink-venv/bin/activate
pip install -U pip
pip install --no-binary=lxml streamlink

~/streamlink-venv/bin/streamlink -l debug
```

You will have to install at least python 3.6 though, as Ubuntu Xenial defaults to 3.5.

Good luck.

**Closed by bastimeyer** 2022-06-16 19:47 UTC
Labels: question, packages, os: Linux
