### ISSUE TITLE
tvplayer.com plugin bug

### ISSUE THREAD

**Issue by johnthecracker** [streamlink/streamlink#866] opened 2017-05-01 10:35 UTC
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*
*Also check the list of known issues before reporting an issue!*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

streamlink.exe http://tvplayer.com/watch/cnninternationaleurope best

### Expected / Actual behavior

[cli][info] Found matching plugin tvplayer for URL http://tvplayer.com/watch/cnn
internationaleurope
error: No playable streams found on this URL: http://tvplayer.com/watch/cnninter
nationaleurope

### Reproduction steps / Explicit stream URLs to test

C:\>youtube-dl.exe -v -F --no-check-certificate http://tvplayer.com/watch/cnninternationaleurope
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', '--no-check-certificate', 'http://tvplayer.com/watch/cnninternationaleurope']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.05.01
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg n3.2.1, rtmpdump 2.4
[debug] Proxy map: {}
[TVPlayer] cnninternationaleurope: Downloading webpage
[TVPlayer] cnninternationaleurope: Downloading JSON context
[TVPlayer] cnninternationaleurope: Downloading JSON stream
[TVPlayer] cnninternationaleurope: Downloading m3u8 information
[info] Available formats for 286:
format code  extension  resolution note
214          mp4        unknown     214k
564          mp4        unknown     564k
1064         mp4        unknown    1064k
1864         mp4        unknown    1864k
2564         mp4        unknown    2564k  (best)

### Environment details

Operating system and version: ...
Streamlink and Python version: ...

...

https://github.com/rg3/youtube-dl/commit/b364c87c423cbc031cd64566a1b283097b560d59

...

**Comment by beardypig** [comment] 2017-05-01 10:58
Duplicate of #849. It has been fixed in #850, but has not been merged yet.

**Comment by gravyboat** [comment] 2017-05-01 16:05
Closing since #850 is merged.

**Closed by gravyboat** 2017-05-01 16:05 UTC
Labels: duplicate
