### ISSUE TITLE
Plugin 'reshet' changed URL

### ISSUE THREAD

**Issue by yegarti** [streamlink/streamlink#2996] opened 2020-05-28 14:49 UTC
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

Hi,
"reshet.tv" has changed to "13tv.co.il", making the plugin unuseable.
I suspect there are also changes to the API.

**Comment by mkbloke** [comment] 2020-05-31 04:07
It would appear that there is a static non geo-IP restricted URL:

```http://reshet-live-il.ctedgecdn.net/13tv-desktop/r13.m3u8```

**Comment by mkbloke** [comment] 2020-06-05 02:02
Hi, @yegarti 

Could you try my replacement plugin at: https://github.com/mkbloke/streamlink/blob/n13tv-plugin/src/streamlink/plugins/n13tv.py

Select 'Raw', then you can save it and copy into your plugins dir to test.  If you can test live and VODs and confirm that all appears to be working OK, that would be, great, thanks.

**Comment by yegarti** [comment] 2020-06-05 08:20
Hi, @mkbloke 
Tested the plugin on some videos, worked great for VODs and live.
It failed for short clips, the stream start, I see the first frames and then the stream immediately ends.
For example:
```
> streamlink -l debug https://13tv.co.il/item/mood/survivor/season-04-vip/clips/enbrm-2027273/ best
cli][debug] OS:         Linux-5.4.40-1-MANJARO-x86_64-with-glibc2.2.5
[cli][debug] Python:     3.8.3
[cli][debug] Streamlink: 1.4.1+16.g90e634e.dirty
[cli][debug] Requests(2.23.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin n13tv for URL https://13tv.co.il/item/mood/survivor/season-04-vip/clips/enbrm-2027273/
[plugin.n13tv][debug] Main JS path = /wp-content/themes/reshet_tv/build/static/js/main.9f10f8c1.js
[plugin.n13tv][debug] User ID = 45E4A9FB-FCE8-88BF-93CC-3650C39DDF28
[plugin.n13tv][debug] Video name = mood-survivor-season-04-vip-clips-11-part-10-next
[plugin.n13tv][debug] Media file = /media/iiscdn/2020/06/02/mood-survivor-season-04-vip-clips-11-part-10-next_,550,850,1400,.mp4
[plugin.n13tv][debug] VOD URL = https://reshet-vod-il.ctedgecdn.net/reshet-vod/_definst_/amlst:mediaroot/nana10/media/iiscdn/2020/06/02/mood-survivor-season-04-vip-clips-11-part-10-next_,550,850,1400,.mp4/playlist.m3u8?ctoken=c13079014b2fde1b073f1f22e74c808d459f87e99c0b1983beb7aafbca355baa&str=1591344586&exp=1591345786
[utils.l10n][debug] Language code: en_IL
[cli][info] Available streams: 550k (worst), 850k, 1400k (best)
[cli][info] Opening stream: 1400k (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 0; Last Sequence: 5
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 0; End Sequence: 5
[stream.hls][debug] Adding segment 0 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 1 to queue
[stream.hls][debug] Adding segment 2 to queue
[stream.hls][debug] Adding segment 3 to queue
[stream.hls][debug] Adding segment 4 to queue
[stream.hls][debug] Adding segment 5 to queue
[stream.segmented][debug] Closing worker thread
[stream.hls][debug] Download of segment 0 complete
[cli][info] Starting player: /usr/bin/vlc
[cli.output][debug] Opening subprocess: /usr/bin/vlc --input-title-format https://13tv.co.il/item/mood/survivor/season-04-vip/clips/enbrm-2027273/ -
[stream.hls][debug] Download of segment 1 complete
[stream.hls][debug] Download of segment 2 complete
[stream.hls][debug] Download of segment 3 complete
[cli][debug] Writing stream to output
[stream.hls][debug] Download of segment 4 complete
[stream.hls][debug] Download of segment 5 complete
[stream.segmented][debug] Closing writer thread
[cli][info] Stream ended
[cli][info] Closing currently open stream...

```

Beside this small issue (unimportant one?) it's working great, Thank you.

**Comment by mkbloke** [comment] 2020-06-06 19:27
Hi @yegarti,

Many thanks for testing the plugin and for providing the debug output with the clip.  I'm seeing the same thing as you.  On the website there are segments 0 to 5 also.  I seem to be finding that if I if I use the '-O' option and redirect stdout to a file that I get the whole 54 second clip.  It seems to me that perhaps the player is closing before the clip is over.  If you save to file can you get the whole clip?

Thanks again.

**Comment by yegarti** [comment] 2020-06-06 20:52
Hi @mkbloke,

Using '-O' does save the whole clip.

**Comment by mkbloke** [comment] 2020-06-07 19:37
Thanks again for your response.  I also seem to find that using the '-O' option and then piping into the player on the command line, e.g. '| vlc -' seems to result in the entire clip being played.

I can only conclude that this is an edge-case bug in streamlink, unless I'm missing something else here.  Cheers.

**Comment by back-to** [comment] 2020-06-14 15:38
@yegarti @mkbloke 

> I can only conclude that this is an edge-case bug in streamlink, unless I'm missing something else here. 

not a bug, you can use `--player-no-close`
https://streamlink.github.io/cli.html#cmdoption-player-no-close

**Comment by mkbloke** [comment] 2020-06-14 18:46
Ah!  Many thanks, @back-to, for the info on that.  Would it be worthwhile putting a log.info() into the plugin as a note to users?

**Comment by bastimeyer** [comment] 2020-06-14 20:12
> Would it be worthwhile putting a log.info() into the plugin

No.

Streamlink will send a SIGTERM signal to the player process as soon as the end of the stream has been reached. Depending on the player, it won't wait with the process termination until it has finished decoding and rendering the remaining content. Either do what @back-to said and set the `--player-no-close` Streamlink parameter, or tell your player to ignore SIGTERM (and SIGKILL) signals. In case of VLC, it's the `--no-play-and-exit` parameter and in case of MPV, it's the `--keep-open=<yes|always>` parameter.

**Comment by mkbloke** [comment] 2020-06-14 22:31
I think maybe there are just crossed wires here.  I was thinking about a ```log.info()``` message recommending usage of ```--player-no-close``` be used on the command line if necessary by the user, but I think what you're suggesting is to use ```self.set_option()``` within the plugin?  If that's the case, I had not realised it from back-to's reply.

**Comment by bastimeyer** [comment] 2020-06-14 22:41
Messages on how to use Streamlink don't belong into the log output. I'm also not suggesting to set any kind of output options via plugins, as it's up to the user to decide. I was merely explaining what you can do as a user to make the player stay open after Streamlink as finished reading and writing the stream data.

**Comment by mkbloke** [comment] 2020-06-14 22:45
OK, understood now.  Thank you.

**Closed** 2020-06-21 09:12 UTC
Labels: plugin issue
