### ISSUE TITLE
ESPN+ not working as authorization blocked

### ISSUE THREAD

**Issue by theewesking** [streamlink/streamlink#1931] opened 2018-07-12 15:40 UTC
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines. 

### Description

After seeing this thread (https://github.com/streamlink/streamlink/issues/1636) I tried to grab a ESPN+ stream but was not able to get the key mentioned.

When I try open the two links returned when searching for keys it opens a blank tab with the message "{ "errors": [ { "code": "access-token.invalid" } ] }". So I am not sure how to authenticate the stream in order to follow the steps mentioned in the other thread.

### Reproduction steps / Explicit stream URLs to test

1. ... The link to the key is https://playback.svcs.plus.espn.com/events/3684603d-b033-4638-94ba-559e48081adf/media/883f1ddb-4975-4319-81b4-c063ae3c131f/keys/7ed7e17b-bac4-4a18-b386-cd547f3d8cb3

2. ... m3u8 link 1 is https://aeng.svcs.plus.espn.com/settoken/redirect/v1?sect=espnplus:web:vod:en&ssess=2c7d41be-f5b8-48aa-8fc7-e4c888f6cf0d&trk=s&platform=web&app=espn&partnr=espn&uid={4FF60D4B-D364-4BC4-B60D-4BD3643BC4D5}&swid={4FF60D4B-D364-4BC4-B60D-4BD3643BC4D5}&cdn=AKAMAI-SECURE&corigin=CLT2&mediaurl=https://hlslive-akc-clt2.media.plus.espn.com/hdnts=exp=1531496041~acl=/*~id=804f39bc-946e-4546-b344-d365244bdac7~data=883f1ddb-4975-4319-81b4-c063ae3c131f~hmac=4d93596fc8da3fc86434e3bdefbb9e20277e259441b0feecd381892ca3b3eaa6/a20ee2a6ba3e4f73cdf5c3c352428a55/ls01/espn/event/2018/07/12/2018_FIL_World_Lacrosse_C_20180712_1531364848960/master_desktop_complete_aeng-trimmed.m3u8

3. ... m3u8 link 2 is https://hlslive-akc-clt2.media.plus.espn.com/hdnts=exp=1531496041~acl=/*~id=804f39bc-946e-4546-b344-d365244bdac7~data=883f1ddb-4975-4319-81b4-c063ae3c131f~hmac=4d93596fc8da3fc86434e3bdefbb9e20277e259441b0feecd381892ca3b3eaa6/a20ee2a6ba3e4f73cdf5c3c352428a55/ls01/espn/event/2018/07/12/2018_FIL_World_Lacrosse_C_20180712_1531364848960/2500K/2500_complete_aeng-trimmed.m3u8

### Logs

```
Microsoft Windows [Version 10.0.17134.165]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\******>streamlink.exe "hlsvariant://https://aeng.svcs.plus.espn.com/settoken/redirect/v1?sect=espnplus:web:vod:en&ssess=cde954b4-e8ac-4923-a860-ec48cd286e7b&trk=s&platform=web&app=espn&partnr=espn&uid={4FF60D4B-D364-4BC4-B60D-4BD3643BC4D5}&swid={4FF60D4B-D364-4BC4-B60D-4BD3643BC4D5}&cdn=AKAMAI-SECURE&corigin=CLT2&mediaurl=https://hlslive-akc-clt2.media.plus.espn.com/hdnts=exp=1531478250~acl=/*~id=804f39bc-946e-4546-b344-d365244bdac7~data=883f1ddb-4975-4319-81b4-c063ae3c131f~hmac=0f2124c397d618ba3acd9614f545a510eb438bdcdfc6aa8b170a19aed3abfa51/a20ee2a6ba3e4f73cdf5c3c352428a55/ls01/espn/event/2018/07/12/2018_FIL_World_Lacrosse_C_20180712_1531364848960/master_desktop_complete_aeng-trimmed.m3u8" 540p -o newzealand-spain-2018.ts
[cli][info] Found matching plugin stream for URL hlsvariant://https://aeng.svcs.plus.espn.com/settoken/redirect/v1?sect=espnplus:web:vod:en&ssess=cde954b4-e8ac-4923-a860-ec48cd286e7b&trk=s&platform=web&app=espn&partnr=espn&uid={4FF60D4B-D364-4BC4-B60D-4BD3643BC4D5}&swid={4FF60D4B-D364-4BC4-B60D-4BD3643BC4D5}&cdn=AKAMAI-SECURE&corigin=CLT2&mediaurl=https://hlslive-akc-clt2.media.plus.espn.com/hdnts=exp=1531478250~acl=/*~id=804f39bc-946e-4546-b344-d365244bdac7~data=883f1ddb-4975-4319-81b4-c063ae3c131f~hmac=0f2124c397d618ba3acd9614f545a510eb438bdcdfc6aa8b170a19aed3abfa51/a20ee2a6ba3e4f73cdf5c3c352428a55/ls01/espn/event/2018/07/12/2018_FIL_World_Lacrosse_C_20180712_1531364848960/master_desktop_complete_aeng-trimmed.m3u8
[cli][info] Available streams: 720p_alt2, 180p (worst), 216p, 288p, 360p, 504p, 540p, 720p (best)
[cli][info] Opening stream: 540p (hls)
[stream.hls][error] Failed to create decryptor: Unable to open URL: https://playback.svcs.plus.espn.com/events/3684603d-b033-4638-94ba-559e48081adf/media/883f1ddb-4975-4319-81b4-c063ae3c131f/keys/7ed7e17b-bac4-4a18-b386-cd547f3d8cb3 (401 Client Error: Unauthorized for url: https://playback.svcs.plus.espn.com/events/3684603d-b033-4638-94ba-559e48081adf/media/883f1ddb-4975-4319-81b4-c063ae3c131f/keys/7ed7e17b-bac4-4a18-b386-cd547f3d8cb3)
[cli][error] Try 1/1: Could not open stream <HLSStream('https://hlslive-akc-clt2.media.plus.espn.com/hdnts=exp=1531478250~acl=/*~id=804f39bc-946e-4546-b344-d365244bdac7~data=883f1ddb-4975-4319-81b4-c063ae3c131f~hmac=0f2124c397d618ba3acd9614f545a510eb438bdcdfc6aa8b170a19aed3abfa51/a20ee2a6ba3e4f73cdf5c3c352428a55/ls01/espn/event/2018/07/12/2018_FIL_World_Lacrosse_C_20180712_1531364848960/2500K/2500_complete_aeng-trimmed.m3u8')> (No data returned from stream)
error: Could not open stream <HLSStream('https://hlslive-akc-clt2.media.plus.espn.com/hdnts=exp=1531478250~acl=/*~id=804f39bc-946e-4546-b344-d365244bdac7~data=883f1ddb-4975-4319-81b4-c063ae3c131f~hmac=0f2124c397d618ba3acd9614f545a510eb438bdcdfc6aa8b170a19aed3abfa51/a20ee2a6ba3e4f73cdf5c3c352428a55/ls01/espn/event/2018/07/12/2018_FIL_World_Lacrosse_C_20180712_1531364848960/2500K/2500_complete_aeng-trimmed.m3u8')>, tried 1 times, exiting
[cli][info] Closing currently open stream...

```

### Comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by Ike348** [comment] 2018-07-13 01:22
You found the key. You just need to pass into streamlink the correct http-headers that enable you/streamlink to use the key and play the stream. If you have Google Chrome, you just be able to use their network url snooper to see the authorization header that you need.

**Comment by theewesking** [comment] 2018-07-13 06:02
Could you elaborate on what bit is the key, the authorization header and what the http-headers are?

I thought that using the URL snooper was to find the m3u8 link and the link when filtering by "keys" then using those two values with the command you mentioned in the other post.

I understand what to do once I have the authorization header, the second link I posted should be the usual m3u8 link but I'm still unsure on the authorization.

**Comment by Ike348** [comment] 2018-07-13 14:50
The key is a bit of encrypted text that enables you to play the stream. Your browser (or maybe more accurately, the video player) sees the key, and then uses it to decrypt the individual video segments that it reads from the m3u8 playlist. To open the stream with streamlink, streamlink needs the key, or else it will just be stuck with a bunch of video segments that it can't do anything with.

Since the key is usually listed in the m3u8 file, streamlink already knows where it is. It just can't download it because it is forbidden/unauthorized to open with just the URL. You need some kind of authorization token to prove that you are a user that can access the stream. For FOX Sports Go streams, you would need two cookies—`access_token` and `authorization`. For ESPN+ streams, its in the form of an `authorization` header that gets passed from your browser. Headers are how websites know, for example, what browser and/or device you're using, so that it can display the website appropriately. In this case, it's how the website knows that you are a logged in/subscribed user.

Now, you need to pass that header into streamlink, which means you need to know what it is. Google Chrome has a great "URL snooper," found in the Network tab of Developer Tools. I'm not sure for other browsers, but I'm sure you could find an add-on that would do the same. Reload the page, then once the stream appears, search for `key`. For some reason, I usually get two entries, but if you click on one, and scroll down, you'll see a _long_ string of what looks like random text. This is what you want. Copy it. Then, when you go back to streamlink. Your command should be `streamlink --http-header "authorization=*************************" "hlsvariant://https://aeng.svcs.plus.espn.com/settoken/redirect/v1?sect=espnplus:web:vod:en&ssess=2c7d41be-f5b8-48aa-8fc7-e4c888f6cf0d&trk=s&platform=web&app=espn&partnr=espn&uid={4FF60D4B-D364-4BC4-B60D-4BD3643BC4D5}&swid={4FF60D4B-D364-4BC4-B60D-4BD3643BC4D5}&cdn=AKAMAI-SECURE&corigin=CLT2&mediaurl=https://hlslive-akc-clt2.media.plus.espn.com/hdnts=exp=1531496041~acl=/*~id=804f39bc-946e-4546-b344-d365244bdac7~data=883f1ddb-4975-4319-81b4-c063ae3c131f~hmac=4d93596fc8da3fc86434e3bdefbb9e20277e259441b0feecd381892ca3b3eaa6/a20ee2a6ba3e4f73cdf5c3c352428a55/ls01/espn/event/2018/07/12/2018_FIL_World_Lacrosse_C_20180712_1531364848960/master_desktop_complete_aeng-trimmed.m3u8" best`, along with whatever other parameters you want passed in. Note that the authorization header will be much longer than what I put there. This enables streamlink, once it sees that it needs a key, to use that header to pretend like it is viewing the stream in the browser in order to get the key, and then it can decrypt the stream and play it/save it.

**Comment by back-to** [comment] 2018-07-19 11:59
duplicate of https://github.com/streamlink/streamlink/issues/1636

**Closed by back-to** 2018-07-19 11:59 UTC
Labels: duplicate
