### ISSUE TITLE
Volume control in VLC with the mousewheel behaves abnormally

### ISSUE THREAD

**Issue by BullHorn7** [streamlink/streamlink#1010] opened 2017-06-16 21:50 UTC
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

This is a bug since the days of Livestreamer. 
When using Streamlink with VLC, the mousewheel for changing volume behaves abnormally, usually reacting slowly to the input as well as ignoring some (for ex: spinning mwheel up 10 times results in volume going up 5 times, instead of 10).

### Expected / Actual behavior

Volume change with mousewheel when watching a stream via Streamlink should behave same as when viewing a local file.

### Reproduction steps / Explicit stream URLs to test

1. Load stream in VLC via Streamlink
2. Raise or lower volume with the mouse wheel

### Environment details

Operating system and version: Win10 64 Creator's Update
Streamlink and Python version: Streamlink 0.6 using the installer

**Comment by gravyboat** [comment] 2017-06-17 01:18
I've never encountered this issue on either my Windows 10 system, or my Ubuntu system, can you duplicate it in multiple VLC versions? What about the latest nightly from them? Have you been able to duplicate it on any other systems? This seems super weird to me.

**Comment by scottbernstein** [comment] 2017-06-17 03:36
Also NOT seeing this on my Windows 10 Creators Update Edition, with the latest Streamlink and a very recent VLC 3 nightly build


Frankly I can't see how Streamlink could be responsible for issues with the volume control in VLC

________________________________

**Comment by BullHorn7** [comment] 2017-06-17 06:18
It's happening with the latest nightly too.

I noticed something else - When I click the volume bar to change volume, there's a small delay between the click and the adjustment occurring and I think it's related. This delay is causing the mousewheel input to be ignored until the delay is over.

Then I went to streamlinkrc and removed this from VLC's startup lines: "--network-caching 5000" and the problem disappeared. I can still use a manual value with --file-caching without this problem, but --network-caching seems to be the source.

I use it because for months I'm having buffering issues with Twitch, probably due to ISP throttling.

**Comment by gravyboat** [comment] 2017-06-17 18:58
Have you been able to duplicate the slowness caused by VLC's `network-caching` option with any other tools besides Streamlink? It might be worth testing that to confirm whether this is simply VLC or not.

**Comment by BullHorn7** [comment] 2017-06-17 19:55
Unfortunately not. It also happens without `network-caching` in cases when the stream is lagging/buffering. It might just be a VLC bug...

**Comment by bastimeyer** [comment] 2017-06-28 23:20
It is very very unlikely that a tool like Streamlink is responsible for audio volume or keyboard input issues of VLC. Please try to isolate Streamlink from that issue by using a different input source.

> --network-caching 5000
> I use it because for months I'm having buffering issues with Twitch

Player parameters are unrelated to the stream data fetching of Streamlink (unless you're using the `--player-passthrough hls` option). The caching options of your player only influence the buffering when reading data from Streamlink, but do not influence Streamlink's own caching. If you're having buffering issues with any streaming service (eg. Twitch), you should try changing the values of `--hls-live-edge` and `--hls-segment-attempts` (or anything else related, based on the used protocol of the service):
https://streamlink.github.io/cli.html#cmdoption-hls-live-edge

**Comment by Ethenen** [comment] 2017-07-13 18:32
I'm more than sure that the issue is related to vlc 3.0
It was/is not present in 2.2.6 (at least for me), but when I upgraded to 3.0 (to be able to watch youtube streams) I've noticed that problem.

**Comment by gravyboat** [comment] 2017-09-09 02:37
Closing this since it's a VLC issue.

**Closed by gravyboat** 2017-09-09 02:37 UTC
Labels: unconfirmed

**Comment by casper** [comment] 2019-09-02 16:30
Leaving comment here because I found another workaround for this issue.
I just had this happen to me with VLC 3.0.8. 

The "fix" is to change the VLC audio output device from "Automatic" to "DirectX".
Now the mushy volume lag in the UI is gone. 
It is obviously a VLC bug, but is still not fixed even in 3.0.8.

**Comment by OmidGhotbi** [comment] 2023-02-19 21:34
The same problem for me here, when I use a wireless mouse and keyboard changing the volume is super slow and laggy.
