### ISSUE TITLE
https://www.tango.me Request an pulgin 

### ISSUE THREAD

**Issue by steamwork70** [streamlink/streamlink#3441] opened 2020-12-25 12:36 UTC
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.
- [x] I am using the latest development version from the master branch.

### Description
Tango Live is a live broadcast application similar to Bigo and Scope, it has two parts as free streams and premium broadcasts.It wouldn't be bad to use Streamlink to enter to the premium.With the M3u8 method, I can get images for 6 or 8 seconds with a simple VLC connection, but we failed when we got the same m3u8 link for Streamlink, someone else opened the same title, but could not explain it completely.It helps him too I hope we can bring this same system should come here as we come to bigo

### Reproduction steps / Explicit stream URLs to test

1. ...https://www.tango.me
2...https://www.tango.me/stream/mUdNpBeqmB7agUelEI_sdg

### Log output

```
streamlink https://www.tango.me/stream/mUdNpBeqmB7agUelEI_sdg
error: No plugin can handle URL: https://www.tango.me/stream/mUdNpBeqmB7agUelEI_sdg
```
 

### Additional comments, etc.
As other enthusiasts have said, there are those who do it in different ways, it is not impossible.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by mkbloke** [comment] 2020-12-25 14:08
Duplicate of #3436.

**Comment by cesaroscesars** [comment] 2020-12-25 15:14
man you are great thank you support

**Comment by steamwork70** [comment] 2020-12-25 15:17
> Kopyası [# 3436](https://github.com/streamlink/streamlink/issues/3436) .

Yes, I saw that the first person who opened the subject could not explain the incident, but I wanted to explain it properly because it was an inept experiment.

**Comment by mkbloke** [comment] 2020-12-25 15:19
This does better meet requirements.  @cesaroscesars, it may be better if you close your issue as there's no point having two open...

**Comment by cesaroscesars** [comment] 2020-12-25 15:23
yes from my explanation

> Bu, gereksinimleri daha iyi karşılar. @cesaroscesars , iki açık olmanın bir anlamı olmadığı için sorununuzu kapatmanız daha iyi olabilir ...

I must admit it explained better than me I removed my own request post, thanks.

**Comment by steamwork70** [comment] 2020-12-25 15:27
In the meantime, I would like to add that when I press the broadcast on the application again, it is shown again for 5-6 seconds, this confirms the event that the m3u8 codes we receive from this site change in 6 seconds. We could not access the m3u8 code for premium broadcasts, but of course, we need that part.

**Comment by steamwork70** [comment] 2020-12-25 15:29
In addition, in the old version of the program, it seems as if it is easy to solve when the premium broadcasts are paid for the gift that is required to appear frosted.It's not about the new version either

**Comment by cesaroscesars** [comment] 2020-12-25 16:40
I checked this information, you are right, but these are to prove that there is a solution, but it does not provide the solution, so what they said will not show us that broadcast via VLC.

**Comment by steamwork70** [comment] 2020-12-25 16:54
yes we are already here to find solutions, hope we find

**Comment by back-to** [comment] 2020-12-25 20:59
**4** and **5**
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

**Comment by steamwork70** [comment] 2020-12-25 20:59
I think this is not a plugin error so the topic has been moved to the plugin request section.

**Closed by back-to** 2020-12-25 20:59 UTC

**Comment by steamwork70** [comment] 2020-12-25 21:06
> **4** ve **5 **
> https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

I looked at the aforementioned situation, I think it does not violate the 4th item because the program does not work with the membership system, because it is a live broadcast application like bigo and scpoe. Item 5 may be correct, but My goal here is to get a pure broadcast video from my own broadcast. I think you should think about it again.

**Comment by cesaroscesars** [comment] 2020-12-25 22:07
> **4** ve **5 **
> https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

Come on, but there is no subscription and membership system in this application, what it calls the completely free premium part, it is not paid for the publisher to open a separate room for the names they love.

In addition, the application is the same as the Bigo application, how can it pass the bigo rules, Tango Live does not pass, the applications are exactly the same here, as in the bigo, pornographic content is blocked. 

The decision must be rethinked Please we need it in our publications
