### ISSUE TITLE
Plugin Request: Live TV on Plex

### ISSUE THREAD

**Issue by ReenigneArcher** [streamlink/streamlink#3458] opened 2020-12-28 04:44 UTC
## Plugin Request

- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.
- [x] I am using the latest development version from the master branch.

### Description

Request to add a plugin for Plex Live TV. Plex has recently added free to air channels in their app. There are roughly 130 live channels. Plex channels can be played with the hls protocol; however stream urls are complicated. Maybe it would be possible to create a plugin where the channels could be streamed similar to the pluto.tv plugin. i.e. instead of pluto's stitcher url a `pluto.tv/live-tv/<channelSlug>` url is used... possibly a plex equivalent would be `plex.tv/live-tv/<channelShortTitle>`

Plex provides the following attributes that could be used in the url for each channel in their api.
-channelIdentifier
-channelShortTitle
-channelTitle (channelVcn + channelShortTitle)... not recommended to use as channelVcn is more likely to change
-channelVcn... not recommended to use a channelVcn is more likely to change

They also provide an attribute named "protocol" where that is equal to "hls".

### Example stream URLs

Not all channels provide the same url format. Please see this m3u for example stream urls... https://github.com/Free-IPTV/Countries/blob/master/US06_USA_Plex.m3u

### Additional comments, etc.
I can try to provide additional details if needed. Thanks!

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment] 2020-12-28 05:32
Duplicate of https://github.com/streamlink/streamlink/issues/3179 which was already closed.

**Closed by gravyboat** 2020-12-28 05:32 UTC
Labels: plugin request
