### ISSUE TITLE
Request: Myfreecam, Amateur.tv + bug report

### ISSUE THREAD

**Issue by Polizo** [streamlink/streamlink#1279] opened 2017-10-16 20:47 UTC
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

... Myfreecam 
Amateur.tv

### Expected / Actual behavior

...

### Reproduction steps / Explicit stream URLs to test

1. ...error: No plugin can handle URL: https://www.cam4.es/xcolombiansx

2. ...[cli][info] Found matching plugin camsoda for URL https://www.camsoda.com/ninadunn
error: Unable to validate JSON: Key 'token' not found in {'status': 0, 'message': 'Access Denied'}
3. ...

### Environment details

Operating system and version: ... W10
Streamlink and Python version: ...

...

### Comments, logs, screenshots, etc.

...

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment] 2017-10-17 00:12
Please don't open a single thread for multiple issues. This is impossible to track for the developers in an issue tracker with that many open issues.

Regarding 1:
The cam4 plugin currently only matches .com URLs, as you can see here.
https://github.com/streamlink/streamlink/blob/0.8.1/src/streamlink/plugins/cam4.py#L10

Regarding 2:
Duplicate of #1271...

I don't know whether I want to close this thread or not, since you're requesting multiple plugins at once. One of them already had a couple of other discussions, but the plugin was never finalized by its creator as it looks like.

The amount of NSFW plugin requests/issues/discussions here is increasing rapidly and it's getting too much for my taste. Especially from newly created github accounts. This is slowly becoming a porn site ripping tool, which we should not let happen. Maybe we should move NSFW plugins into a different repo or so.

**Comment by ls117** [comment] 2017-10-17 01:39
there's a fine line between 'porn site ripping tool' and a backup tool. the way i see it, if im paying for a stream i should be able to save it. camsoda makes you pay extra to do so, and thats on top of the ticket show price. I dont see the point in not supporting a discussion/request on a plugin that already exists, and is only now having issues because of recent site changes. While I certainly understand the team being small and only able to focus on small things at a time, personal feelings on how the program is used shouldn't be part of the discussion. Why can't we have the same consideration someone would have with a youtube issue? This all might be considered a legal grey area, but the same potential for abuse is possible not just with a porn site, but with any site. So what's the issue that you have with nsfw plugin requests? Assuming that we're all adults here of course, obviously no one wants to help some 12 year old stream porn. I considered donating or being a sponsor because I wanted the plugin fixed in a timely manner, but I'm not sure if I should if the team considers nsfw plugin's distasteful. The way I see it, we just want to be able to stream and record, and have our issues treated with the same consideration as any other plugin. As far as requests for new plugins, I can't say much to disagree there. That's the kind of thing that can handled whenever someone has the time and intent to do so, but existing plugins shouldn't be treated with disdain.

**Comment by gravyboat** [comment] 2017-10-17 02:04
I'm going to close this one out since both issues seem addressed to me, and we will move the discussion to #1271.

**Comment by Polizo** [comment] 2017-10-24 07:36
amateur.tv video codeidk id this help
https://ams-edge2.vtsmedia.com/camchat_rep_185.212.201.18/TV_1494325_hls/media_w811970337_4464.ts?t=20171024073344984296-TV_1494325-1508830458776-40P0Y7CKomZkuASSGF1FlXWfQkvs%2F7kRvzffSnROgXY%3D

link https://www.amateur.tv/cam/amateur/tea_latina

https://ams-edge2.vtsmedia.com/camchat_rep_185.212.201.18/TV_1494325_hls/chunklist_w811970337.m3u8?t=20171024073344984296-TV_1494325-1508830458776-40P0Y7CKomZkuASSGF1FlXWfQkvs%2F7kRvzffSnROgXY%3D

**Comment by back-to** [comment] 2018-06-30 08:31
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

> Plugins which fall under the following categories will not be implemented or considered and the request will be closed:
> - 5 - NSFW sites of a pornographic nature (cam sites, porn sites, etc.)

**Closed by back-to** 2018-06-30 08:31 UTC
Labels: NSFW, plugin request, wontfix
