### ISSUE TITLE
Support VOD seeking

### ISSUE THREAD

**Issue by ghost** [streamlink/streamlink#134] opened 2016-11-07 05:30 UTC
It will be cool if VOD content become seekable, i mean for example we open a YouTube video like https://www.youtube.com/watch?v=YE7VzlLtp-4 but we cant seek tought the video, something esential for VOD.

**Comment by dojima** [comment] 2016-11-07 19:38
I can seek through that link just fine.

Something I would like, however, is the ability to seek through Twitch VODs while the broadcast is still live.  I don't know if it's possible, but since you can do it via the Twitch site itself, I don't see why not.

**Comment by RosadinTV** [comment] 2016-11-07 19:43
@dojima What player you are using ?

**Comment by dojima** [comment] 2016-11-07 19:44
@RosadinTV MPC-HC

**Comment by RosadinTV** [comment] 2016-11-07 19:56
In my case seeking didnt work with MPV and VLC.

**Comment by bastimeyer** [comment] 2016-11-07 20:40
> to seek through Twitch VODs

Seeking does only work if the player is able to request a certain byte range of the video file.

Since Twitch is using HLS, you can simply use the `--player-passthrough hls` parameter, which will pass Twitch's stream HLS link to your player which will then read the stream data on its own. This way it is able to request the correct byte range if you're jumping to a different position in the VOD. Your player needs to support HLS, though.

I don't know if it's possible to implement this behavior into streamlink if a different passthrough method or stdin is being used as player input. If it is, I would very much welcome such an addition, but I doubt that it's possible.

**Comment by RosadinTV** [comment] 2016-11-07 20:49
I think is posible to support seeking in --player-external-http .. for example Peerflix (a program to play torrent files) work with this output and support seeking .. is writed in another lenguage but almost sure is a way to do that in Python.

**Comment by dojima** [comment] 2016-11-08 03:17
@RosadinTV Weird, works fine here—Windows also.  Although I should mention that I'm still currently using Livestreamer.  I believe player-passthrough=http is necessary, as bastimeyer alluded to.

@bastimeyer Yeah, seeking works fine in Twitch VODs where the broadcast has already finished.  What I mean is, if a streamer is currently streaming and I click the latest VOD in their list of past streams on the Twitch website, it will begin playing the current stream from the beginning, and I have the ability to seek forward up to the current live time.  When opening the stream in Livestreamer (and I assume Streamlink), it just plays what's live without the ability to seek backwards.

**Comment by RosadinTV** [comment] 2016-11-08 03:44
The problem with player-passthrough is the player handle the stream, with that we lose one of the best purposes of the app.

**Comment by skulblakka** [comment] 2016-11-09 16:10
[This](https://github.com/chrippa/livestreamer/pull/1311) PR might be relevant.

**Comment by RosadinTV** [comment] 2016-11-09 20:30
@skulblakka Thanks, tested and working but is too bugy (only worked in VLC and HLS VOD didnt work) but is better than nothing.

**Comment by gravyboat** [comment] 2016-11-09 20:36
@FurryFur Do you still have any interest in developing this feature?

**Comment by RosadinTV** [comment] 2016-11-21 01:51
I will close the issue until some progress is made.

**Comment by gravyboat** [comment] 2016-11-21 05:35
@RosadinTV I think this one is okay to leave open. It's a legit (but difficult) enhancement, and I would rather contain all the discussion here where we already have links to previous PRs than have someone else open an issue.

**Comment by RosadinTV** [comment] 2016-11-21 06:25
You are right, reopened

**Comment by Victolabs** [comment] 2016-11-23 18:51
Here is a video of it happening: https://github.com/streamlink/streamlink/files/609707/SkyShare_20161123_122528_0.zip

**Comment by Victolabs** [comment] 2016-11-23 19:41
I managed to figure out a work around for this bug.

1. Open up your streamlinkrc or equivalent streamlink config file.
2. Look for this piece of text: 

> \# Use this if you want streamlink to only pass a URL to your player and
\# let it handle the transport of the stream itself.
\#player-passthrough=http,hls,rtmp

Remove the hashtag from `#player-passthrough=http,hls,rtmp` and save the config file. Volia, you can now seek.

I've attached a video as proof that this works: 
[SkyShare_20161123_133319_0.zip](https://github.com/streamlink/streamlink/files/609827/SkyShare_20161123_133319_0.zip)

**Comment by dojima** [comment] 2016-11-23 21:20
@Victolabs Yeah, the problem is that I think RosadinTV wanted to seek without using player-passthrough, although I'm not sure what the difference is between using player-passthrough and not.

**Comment by RosadinTV** [comment] 2016-11-23 22:35
@Victolabs @dojima The problem with player-passthrough is that the player handle the stream instead of Streamlink, this means the program only acts as a shortcut to send a url to the player, the management or download of stream is not involved (so options like --hls-segment-threads will not work)
Also seeking with the cache will be cool for live streams.

**Comment by Victolabs** [comment] 2016-11-23 22:45
@RosadinTV Thats kinda what i wanted the entire time. So hooray for me?

**Comment by RosadinTV** [comment] 2016-11-23 22:53
@Victolabs What do you mean? My english isn't good 😛

**Comment by FurryFur** [comment] 2016-12-05 00:26
@gravyboat I'm still interested in developing this feature. I don't have any time at the moment because of my new school. But holidays start in 2 weeks, so I might have time then. I'm thinking about making it a big change in a separate branch. Let me know what you guys think about this:

Major change for seek and multi-segment streaming support.

- Change Streamlinks behavior so it acts as a caching proxy server.
- Streamlink passes through all information it downloads from the server exactly as is, including HTTP or other protocol headers. This means that the receiving player must support the streaming protocol that is being proxied (such as RTMP/HLS/HTTP Progressive).
- This behavior would mean that specifying the transport method no longer makes sense (i.e. It doesn't make sense to output the stream to the player using a pipe or HTTP if the stream is an RTMP stream)
- Makes seek very easy as the player knows how to handle seeking for different streaming protocols. Streamlink just has to proxy requests from the player, and can make extra requests in parallel to accelerate downloads.

**Comment by MSxDOS** [comment] 2017-03-10 21:27
Looking forward to it. The inability to seek 1080p youtube videos even with passthrough enabled makes me sad.

**Comment by bastimeyer** [comment] 2017-04-15 23:19
@FurryFur 
Are you still interested in implementing this? Your last post is from early december.

**Comment by MSxDOS** [comment] 2017-04-17 18:30
FurryFur disappeared from github.

**Comment by gravyboat** [comment] 2017-04-17 18:40
The account is still there: https://github.com/FurryFur

**Comment by megapro17** [comment] 2017-12-31 23:32
any news?

**Comment by gravyboat** [comment] 2017-12-31 23:41
@megapro17 Not that I am aware of, I don't think there have been any developments past https://github.com/streamlink/streamlink/pull/1303

**Comment by alexqhj** [comment] 2018-03-21 08:50
For twitch, you can enable seeking by uncommenting this line in config

`#player-passthrough=http,hls,rtmp`

**Comment by bastimeyer** [comment] 2018-03-21 09:18
@alexqhj 
This bypasses Streamlink and your player is doing all the requests instead of Streamlink, which means that you're not able to configure buffering, etc. in Streamlink

- https://streamlink.github.io/cli.html#cmdoption-player-passthrough
- https://github.com/streamlink/streamlink/issues/134#issuecomment-258955841
- https://github.com/streamlink/streamlink-twitch-gui/issues/81#issuecomment-314374666

This has been talked about a million of times already, there really is no reason to bump this every couple of weeks...

**Comment by back-to** [comment] 2020-12-03 17:03
Most Likely won't happen.

**Closed by back-to** 2020-12-03 17:03 UTC
Labels: enhancement, wontfix

**Comment by megapro17** [comment] 2020-12-03 19:11
Why

**Comment by mkbloke** [comment] 2020-12-03 19:17
It's already been discussed above.  Nobody has implemented it in the last four years, so it's dead.
