### ISSUE TITLE
Streamlink does not show hls error (Max retries exceeded)

### ISSUE THREAD

**Issue by seiya-git** [streamlink/streamlink#924] opened 2017-05-16 01:35 UTC
### Checklist

- [x] This is a bug report.

### Description

Streamlink does not show hls error when failed to open segment (Max retries exceeded)

### Reproduction steps / Explicit stream URLs to test

https://www.daisuki.net/gb/en/anime/watch.eromangasensei.16681.html
ts filesize: 556 MiB (583 080 512 bytes)

### Environment details

Operating system and version: win10 x64 
Streamlink and Python version: 0.6.0 portable

### Comments, logs, screenshots, etc.

![log](https://i.imgur.com/U5RIdVf.png)

No errors in log, but ts file is not complete (broken) and size is 531 MiB.
If I use livestreamer, it shows this type of error:

![log](https://i.imgur.com/B4MKhvG.png)

Filesize is: 544 MiB

**Comment by beardypig** [comment] 2017-05-16 07:44
I cannot reproduce this, 
```
streamlink https://www.daisuki.net/gb/en/anime/watch.eromangasensei.16681.html 720p -o eromangasensei-test.mp4
```
I get a video file that is 00:23:46, here's the output from `ffmpeg`

```console
$ ffmpeg -i eromangasensei-test.mp4 -c copy  -f null -
Input #0, mpegts, from 'eromangasensei-test.mp4':
  Duration: 00:23:46.55, start: 0.100667, bitrate: 3269 kb/s
  Program 1
    Stream #0:0[0x100]: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709), 1280x720 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 90k tbn, 47.95 tbc
    Stream #0:1[0x101]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 234 kb/s
Output #0, null, to 'pipe:':
  Metadata:
    encoder         : Lavf56.40.101
    Stream #0:0: Video: h264 ([27][0][0][0] / 0x001B), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 23.98 fps, 23.98 tbr, 90k tbn, 90k tbc
    Stream #0:1: Audio: aac ([15][0][0][0] / 0x000F), 48000 Hz, stereo, 234 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[NULL @ 0x2035880] non-existing SPS 0 referenced in buffering period
frame=34202 fps=5681 q=-1.0 Lsize=N/A time=00:23:46.51 bitrate=N/A
video:517500kB audio:33434kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
```

@seiya-git can you run it again with `-ldebug` and see if that sheds any light. For reference, this is the output for my debug log: https://gist.github.com/beardypig/2d3ae83817f45079e3f9a82f91853a3b

**Comment by bastimeyer** [comment] 2017-05-26 15:44
> can you run it again with -ldebug

Let me post the correct param, just to make sure there's no confusion here. 😃 
`streamlink -l debug ...`

@seiya-git could you please help @beardypig here with a debug log, so that this issue can be resolved, if possible?

**Comment by beardypig** [comment] 2017-05-26 17:11
`-ldebug` doesn't work on Windows? I'm lazy and leave out the space :P

**Comment by seiya-git** [comment] 2017-05-27 08:07
It looks like the problem in my ISP, if I use VPN, then everything is fine.

**Comment by gravyboat** [comment] 2017-05-27 19:38
Thanks for investigating that and updating us @seiya-git, I'm going to close this out for now.

**Closed by gravyboat** 2017-05-27 19:38 UTC
Labels: more info required
