### ISSUE TITLE
Vaughnlive is not supported on streamlink?

### ISSUE THREAD

**Issue by Bluebuster116** [streamlink/streamlink#1101] opened 2017-07-17 03:23 UTC
This is some kind of continuation from an issue reported earlier on livestreamer. I tried to use it but it looks as other user reported that vaughnlive is not working with streamlink for recording live streams. Could it be that the existing plugin is no longer working because the security conditions have changed?.

**Comment by bastimeyer** [comment] 2017-07-17 03:34
Duplicate of #1034...

Please use the search function next time before opening new issues. The issue template already asks you to do this before submitting.
https://github.com/streamlink/streamlink/issues?q=Vaughnlive

**Closed by bastimeyer** 2017-07-17 03:34 UTC

**Comment by Bluebuster116** [comment] 2017-07-18 06:28
Alright.  ごめんなさい :)
