### ISSUE TITLE
hls-multi from arte.tv has seconds of hanging video

### ISSUE THREAD

**Issue by msdemlei** [streamlink/streamlink#4520] opened 2022-05-09 18:41 UTC
### Checklist

- [X] This is a bug report and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

When pulling video from arte, e.g.

```
streamlink --output o.mp4 \
  https://www.arte.tv/de/videos/108210-039-A/mit-offenen-karten-im-fokus/ \ 
  worst
```

the resulting video stream runs fine for a few seconds.  Then the video freezes, and mpv emits a few lines like

```
Invalid video timestamp: 5.960000 -> 5.920022
AV: 00:00:05 / 00:02:29 (3%) A-V:  0.041 Dropped: 48
```

I suppose the 48 refers to dropped frames; that would roughly coincide with the duration of the video freezes.  Video then resumes for a few seconds, then freezes again, etc (persumably once per HLS segment).  Audio is fine all the time in mpv.  Vlc stutters in both audio and video.

For me, that already has been the behaviour on streamlink 3.2.0 and 3.0.3.  2.0.0 as packagaged by Debian was fine (but its artetv plugin is now broken).

Since I suspect it matters here, ffmpeg version is 4.3.4-0+deb11u1.

### Debug log

```text
[cli][debug] OS:         Linux-5.16.16-x86_64-with-glibc2.31
[cli][debug] Python:     3.9.2
[cli][debug] Streamlink: 4.0.1
[cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(0.57.0)
[cli][debug] Arguments:
[cli][debug]  url=https://www.arte.tv/de/videos/108210-039-A/mit-offenen-karten-im-fokus/
[cli][debug]  stream=['216p']
[cli][debug]  --loglevel=debug
[cli][debug]  --output=o.mp4
[cli][info] Found matching plugin artetv for URL https://www.arte.tv/de/videos/108210-039-A/mit-offenen-karten-im-fokus/
[utils.l10n][debug] Language code: en_US
[stream.hls][debug] Using external audio tracks for stream 432p (language=de, name=VA)
[stream.hls][debug] Using external audio tracks for stream 720p (language=de, name=VA)
[stream.hls][debug] Using external audio tracks for stream 360p (language=de, name=VA)
[stream.hls][debug] Using external audio tracks for stream 216p (language=de, name=VA)
[cli][info] Available streams: 216p (worst), 360p, 432p, 720p (best)
[cli][info] Opening stream: 216p (hls-multi)
[cli][info] Writing output to
/media/video/o.mp4
[cli][debug] Checking file output
File o.mp4 already exists! Overwrite it? [y/N] y
[stream.ffmpegmux][debug] Opening hls substream
[stream.hls][debug] Reloading playlist
[stream.ffmpegmux][debug] Opening hls substream
[stream.hls][debug] Reloading playlist
[utils.named_pipe][info] Creating pipe streamlinkpipe-28165-1-6208
[utils.named_pipe][info] Creating pipe streamlinkpipe-28165-2-5994
[stream.ffmpegmux][debug] ffmpeg command: ffmpeg -nostats -y -i /tmp/streamlinkpipe-28165-1-6208 -i /tmp/streamlinkpipe-28165-2-5994 -c:v copy -c:a copy -map 0:v? -map 0:a? -map 1:a -f mpegts pipe:1
[stream.ffmpegmux][debug] Starting copy to pipe: /tmp/streamlinkpipe-28165-1-6208
[stream.ffmpegmux][debug] Starting copy to pipe: /tmp/streamlinkpipe-28165-2-5994
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] First Sequence: 1; Last Sequence: 26
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 1; End Sequence: 26
[stream.hls][debug] Adding segment 1 to queue
[stream.hls][debug] Adding segment 2 to queue
[stream.hls][debug] Adding segment 3 to queue
[stream.hls][debug] Adding segment 4 to queue
[stream.hls][debug] Adding segment 5 to queue
[stream.hls][debug] Adding segment 6 to queue
[stream.hls][debug] Adding segment 7 to queue
[stream.hls][debug] Adding segment 8 to queue
[stream.hls][debug] Adding segment 9 to queue
[stream.hls][debug] Adding segment 10 to queue
[stream.hls][debug] Adding segment 11 to queue
[stream.hls][debug] Segment initialization 1 complete
[stream.hls][debug] Adding segment 12 to queue
[stream.hls][debug] First Sequence: 1; Last Sequence: 26
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 1; End Sequence: 26
[stream.hls][debug] Adding segment 1 to queue
[stream.hls][debug] Adding segment 2 to queue
[stream.hls][debug] Adding segment 3 to queue
[stream.hls][debug] Adding segment 4 to queue
[stream.hls][debug] Adding segment 5 to queue
[stream.hls][debug] Adding segment 6 to queue
[stream.hls][debug] Adding segment 7 to queue
[stream.hls][debug] Adding segment 8 to queue
[stream.hls][debug] Adding segment 9 to queue
[stream.hls][debug] Adding segment 10 to queue
[stream.hls][debug] Adding segment 11 to queue
[stream.hls][debug] Segment 1 complete
[stream.hls][debug] Segment initialization 2 complete
[stream.hls][debug] Adding segment 13 to queue
[stream.hls][debug] Segment initialization 1 complete
[stream.hls][debug] Adding segment 12 to queue
[stream.hls][debug] Segment 2 complete
[stream.hls][debug] Segment initialization 3 complete
[stream.hls][debug] Adding segment 14 to queue
[stream.hls][debug] Segment 1 complete
[stream.hls][debug] Segment initialization 2 complete
[stream.hls][debug] Adding segment 13 to queue
[cli][debug] Writing stream to output
[stream.hls][debug] Segment 2 complete
[stream.hls][debug] Segment initialization 3 complete
[stream.hls][debug] Adding segment 14 to queue
[stream.hls][debug] Segment 3 complete
[stream.hls][debug] Segment initialization 4 complete
[stream.hls][debug] Adding segment 15 to queue
[stream.hls][debug] Segment 3 complete
[stream.hls][debug] Segment initialization 4 complete
[stream.hls][debug] Adding segment 15 to queue
[stream.hls][debug] Segment 4 complete
[stream.hls][debug] Segment initialization 5 complete
[stream.hls][debug] Adding segment 16 to queue
[stream.hls][debug] Segment 4 complete
[stream.hls][debug] Segment initialization 5 complete
[stream.hls][debug] Adding segment 16 to queue
[download][o.mp4] Written 1.0 MB (0s @ 1.7 MB/s)                                [stream.hls][debug] Segment 5 complete
[stream.hls][debug] Segment initialization 6 complete
[stream.hls][debug] Adding segment 17 to queue
[stream.hls][debug] Segment 5 complete
[stream.hls][debug] Segment initialization 6 complete
[stream.hls][debug] Adding segment 17 to queue
[stream.hls][debug] Segment 6 complete
[stream.hls][debug] Segment initialization 7 complete
[stream.hls][debug] Adding segment 18 to queue
[stream.hls][debug] Segment 7 complete
[stream.hls][debug] Segment initialization 8 complete
[stream.hls][debug] Adding segment 19 to queue
[stream.hls][debug] Segment 6 complete
[stream.hls][debug] Segment initialization 7 complete
[stream.hls][debug] Adding segment 18 to queue
[download][o.mp4] Written 1.7 MB (1s @ 1.5 MB/s)                                [stream.hls][debug] Segment 8 complete
[stream.hls][debug] Segment initialization 9 complete
[stream.hls][debug] Adding segment 20 to queue
[stream.hls][debug] Segment 7 complete
[stream.hls][debug] Segment initialization 8 complete
[stream.hls][debug] Adding segment 19 to queue
[stream.hls][debug] Segment 9 complete
[stream.hls][debug] Segment initialization 10 complete
[stream.hls][debug] Adding segment 21 to queue
[stream.hls][debug] Segment 10 complete
[stream.hls][debug] Segment initialization 11 complete
[stream.hls][debug] Adding segment 22 to queue
[stream.hls][debug] Segment 8 complete
[stream.hls][debug] Segment initialization 9 complete
[stream.hls][debug] Adding segment 20 to queue
[download][o.mp4] Written 2.4 MB (1s @ 1.4 MB/s)                                [stream.hls][debug] Segment 11 complete
[stream.hls][debug] Segment initialization 12 complete
[stream.hls][debug] Adding segment 23 to queue
[stream.hls][debug] Segment 9 complete
[stream.hls][debug] Segment initialization 10 complete
[stream.hls][debug] Adding segment 21 to queue
[stream.hls][debug] Segment 12 complete
[stream.hls][debug] Segment initialization 13 complete
[stream.hls][debug] Adding segment 24 to queue
[stream.hls][debug] Segment 13 complete
[stream.hls][debug] Segment initialization 14 complete
[stream.hls][debug] Adding segment 25 to queue
[stream.hls][debug] Segment 10 complete
[stream.hls][debug] Segment initialization 11 complete
[stream.hls][debug] Adding segment 22 to queue
[download][o.mp4] Written 3.1 MB (2s @ 1.3 MB/s)                                [stream.hls][debug] Segment 14 complete
[stream.hls][debug] Segment initialization 15 complete
[stream.hls][debug] Adding segment 26 to queue
[stream.hls][debug] Segment 15 complete
[stream.hls][debug] Segment initialization 16 complete
[stream.hls][debug] Segment 11 complete
[stream.hls][debug] Segment initialization 12 complete
[stream.hls][debug] Adding segment 23 to queue
[stream.hls][debug] Segment 16 complete
[stream.hls][debug] Segment initialization 17 complete
[stream.segmented][debug] Closing worker thread
[stream.hls][debug] Segment 17 complete
[stream.hls][debug] Segment initialization 18 complete
[stream.hls][debug] Segment 12 complete
[stream.hls][debug] Segment initialization 13 complete
[stream.hls][debug] Adding segment 24 to queue
[download][o.mp4] Written 3.8 MB (2s @ 1.3 MB/s)                                [stream.hls][debug] Segment 18 complete
[stream.hls][debug] Segment initialization 19 complete
[stream.hls][debug] Segment 13 complete
[stream.hls][debug] Segment initialization 14 complete
[stream.hls][debug] Adding segment 25 to queue
[stream.hls][debug] Segment 19 complete
[stream.hls][debug] Segment initialization 20 complete
[stream.hls][debug] Segment 20 complete
[stream.hls][debug] Segment initialization 21 complete
[stream.hls][debug] Segment 14 complete
[stream.hls][debug] Segment initialization 15 complete
[stream.hls][debug] Adding segment 26 to queue
[download][o.mp4] Written 4.5 MB (3s @ 1.2 MB/s)                                [stream.hls][debug] Segment 21 complete
[stream.hls][debug] Segment initialization 22 complete
[stream.hls][debug] Segment 15 complete
[stream.hls][debug] Segment initialization 16 complete
[stream.hls][debug] Segment 22 complete
[stream.hls][debug] Segment initialization 23 complete
[stream.hls][debug] Segment 23 complete
[stream.hls][debug] Segment initialization 24 complete
[stream.hls][debug] Segment 16 complete
[stream.hls][debug] Segment initialization 17 complete
[stream.segmented][debug] Closing worker thread
[download][o.mp4] Written 5.2 MB (4s @ 1.2 MB/s)                                [stream.hls][debug] Segment 24 complete
[stream.hls][debug] Segment initialization 25 complete
[stream.hls][debug] Segment 25 complete
[stream.hls][debug] Segment initialization 26 complete
[stream.hls][debug] Segment 17 complete
[stream.hls][debug] Segment initialization 18 complete
[stream.hls][debug] Segment 26 complete
[stream.segmented][debug] Closing writer thread
[stream.hls][debug] Segment 18 complete
[stream.hls][debug] Segment initialization 19 complete
[download][o.mp4] Written 5.9 MB (4s @ 1.2 MB/s)                                [stream.hls][debug] Segment 19 complete
[stream.hls][debug] Segment initialization 20 complete
[stream.hls][debug] Segment 20 complete
[stream.hls][debug] Segment initialization 21 complete
[stream.hls][debug] Segment 21 complete
[stream.hls][debug] Segment initialization 22 complete
[download][o.mp4] Written 6.9 MB (5s @ 1.3 MB/s)                                [stream.hls][debug] Segment 22 complete
[stream.hls][debug] Segment initialization 23 complete
[stream.hls][debug] Segment 23 complete
[stream.hls][debug] Segment initialization 24 complete
[stream.hls][debug] Segment 24 complete
[stream.hls][debug] Segment initialization 25 complete
[download][o.mp4] Written 7.9 MB (5s @ 1.4 MB/s)                                [stream.ffmpegmux][debug] Pipe copy complete: /tmp/streamlinkpipe-28165-2-5994
[stream.hls][debug] Segment 25 complete
[stream.hls][debug] Segment initialization 26 complete
[stream.hls][debug] Segment 26 complete
[stream.segmented][debug] Closing writer thread
[stream.ffmpegmux][debug] Pipe copy complete: /tmp/streamlinkpipe-28165-1-6208

[stream.ffmpegmux][debug] Closing ffmpeg thread
[stream.ffmpegmux][debug] Closed all the substreams
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

**Comment by bastimeyer** [comment] 2022-05-09 21:39
I can't reproduce this. Both "worst" and "best" streams of this URL are working fine.

The ArteTV plugin returns a `MuxedHLSStream`, which is a stream of two MPEG-TS streams which get remuxed into one MPEG-TS stream via the ffmpeg command shown in the debug log output.

I can't see any timestamp issues in the resulting output file, using the same German audio stream. Neither `ffprobe` nor `mpv` are returning any timestamp errors in the video container.

> For me, that already has been the behaviour on streamlink 3.2.0 and 3.0.3. 2.0.0 as packagaged by Debian was fine

Between 2.0.0 and 4.0.1, there hasn't been any change in the `MuxedStream` logic other than changes of the `NamedPipe` interface. And `MuxedHLSStream` didn't have any changes except documentation changes.

```sh
git diff 2.0.0...4.0.1 src/streamlink/stream/{ffmpegmux,hls}.py
```

This doesn't look like a Streamlink issue.

**Comment by msdemlei** [comment] 2022-05-10 20:03
> This doesn't look like a Streamlink issue.

Hm... perhaps, but it's still broken for me, and I'd love to get a handle on where whatever breaks breaks.  Suspecting ffmpeg, I set up an (rootless) podman with Debian unstable to try a newer ffmpeg, but regrettably a

```
streamlink --loglevel debug --output /tmp/o.mp4 https://www.arte.tv/de/videos/108210-039-A/mit-offenen-karten-im-fokus/ worst
```

fails with 

```
[cli][info] Writing output to
/tmp/o.mp4
[cli][debug] Checking file output
[stream.ffmpegmux][debug] Opening hls substream
The futex facility returned an unexpected error code.
Aborted
```

– which does not look much like streamlink's fault either (though it happens even before it spawns ffmpeg; but I give you a rootless podman isn't the easiest of environments).  Guessing getting to the bottom of this is another can of worms, I've decided that trying another ffmpeg is at least difficult at this point (a backport of Debian unstable's ffmeg to bullseye looks difficult, too).

So... do you have advice on where to start analysing the root causes instead?

I think arte won't sue me right away if I put up the (broken) stream as the above streamlink command writes it for me at http://www.tfiu.de/broken-stream.mp4 for a few days (which makes me notice that webkit's video player has yet another behaviour and drops all audio after the first segment).  Is it easy to see the differences between your working file and my broken one?  [lawyers: I'll take the file down again in a few days]

Any pointers on how I might approach this would be highly welcome.

**Comment by bastimeyer** [comment] 2022-05-10 21:57
Your FFmpeg build/version generates a broken file. The frames all have different timestamp values compared to mine using FFmpeg n5.0 (`ffmpeg 2:5.0-7` package from the Arch Linux repos).

I've tested it in my Fedora 35 and 36 VMs using ffmpeg 4.4.2 and 5.0.1 respectively, and with 4.4.2 it generates a file with the same sha256sum as yours, but with 5.0.1 it's the same sha256sum as mine.

As said, both files differ in frame timestamps, but also in stream duration.

```sh
# check the individual frame timestamps
ffprobe -v quiet -hide_banner -show_entries frame=best_effort_timestamp_time -of json "${file}" \
  | jq -r '.frames[] | .best_effort_timestamp_time'
```

```sh
# ffmpeg 5 file
ffprobe -v quiet -hide_banner -show_streams -of json arte.ts \
  | jq -r '.streams[0] | (.duration_ts, .duration)'
13518000
150.200000

# ffmpeg 4.4 file
ffprobe -v quiet -hide_banner -show_streams -of json broken-stream.ts \
  | jq -r '.streams[0] | (.duration_ts, .duration)'
13496400
149.960000
```

I don't know what FFmpeg 5.0 is doing differently here. Make sure that you're using the latest available FFmpeg version. There's not much else I can tell you.

This is however not an issue that can be fixed in Streamlink.

**Closed by bastimeyer** 2022-05-10 21:57 UTC
Labels: bug, unconfirmed

**Comment by amurzeau** [comment] 2022-05-17 23:57
For the record, I've found that the difference is here:

- the input mp4 file (after reconstruction from the HLS playlist info) contains:
  - one identical `sidx` box before each HLS fragment (repeated by streamlink according to HLS' `EXT-X-MAP` line, `sidx` being part of the Media Initialization Section)
  - one `tfdt` for each MP4 fragment (one HLS fragment contains 3 MP4 fragments)
- ffmpeg v4 uses timestamps from `sidx` box, which means that timestamp are reset on every HLS fragment (with a log like this: `found sidx time -9223372036854775808, using it for pts` and the next decode timestamp (DTS) set to 512)
- ffmpeg v5 ignores `sidx` boxes and only uses timestamps from `tfdt` box which contain correct timestamps as this box is not part of the Media Initialization Section.

This change is implemented only in v5.x from https://github.com/FFmpeg/FFmpeg/commit/071930de724166bfb90fc6d368c748771188fd94, and a new option was added `use_`tfdt`` for this, which is enabled by default (by a different commit: https://github.com/FFmpeg/FFmpeg/commit/c42d513ede6bc58b2cc7b0e47f90be27700843f8).

So really, ffmpeg v5.x is the only option here.

**Comment by bastimeyer** [comment] 2022-05-18 06:06
Thanks for the follow-up, @amurzeau!

The initialization section (`EXT-X-MAP`) gets written to the output for each HLS segment intentionally because of MPEG-TS streams, which is required compared to fragmented MPEG-4 streams:
https://datatracker.ietf.org/doc/html/rfc8216#section-3.2

> The Media Initialization Section of an MPEG-2 Transport Stream Segment is a Program Association Table (PAT) followed by a Program Map Table (PMT). [...] **Each Transport Stream Segment MUST contain a PAT and a PMT, or have an EXT-X-MAP tag ([Section 4.3.2.5](https://datatracker.ietf.org/doc/html/rfc8216#section-4.3.2.5)) applied to it.**  The first two Transport Stream packets in a Segment without an EXT-X-MAP tag SHOULD be a PAT and a PMT.

Unfortunately, there is no distinction that can be made between MPEG-TS and fragmented MPEG-4 in the HLS metadata because [only codec metadata is annotated](https://datatracker.ietf.org/doc/html/rfc8216#section-4.3.4.2). Streamlink would need to check HTTP headers or URL paths for certain patterns (eg. file name extensions), which is not reliable, or it would need to check the headers of the very first segment contents for figuring out the stream format, which would be reliable, but no one has bothered to do so because it's not trivial.

See #4310 / https://github.com/streamlink/streamlink/issues/4310#issuecomment-1021811520.

----

Since the HLS stream from Arte contains an external audio track via `EXT-X-MEDIA` (`AUTOSELECT=YES,DEFAULT=YES`), the available streams need to get remuxed via the `MuxedHLSStream` implementation, and this is why the FFmpeg issue occurs while playing the stream.
- https://github.com/streamlink/streamlink/blame/7591f294006f1ac905e2ba2005f147c10c6d6f53/src/streamlink/stream/hls.py#L681-L695
- https://github.com/streamlink/streamlink/blame/7591f294006f1ac905e2ba2005f147c10c6d6f53/src/streamlink/stream/hls.py#L446-L492
- https://github.com/streamlink/streamlink/blame/7591f294006f1ac905e2ba2005f147c10c6d6f53/src/streamlink/stream/ffmpegmux.py

**master**
```
#EXTM3U
#EXT-X-VERSION:7
#EXT-X-INDEPENDENT-SEGMENTS

#EXT-X-STREAM-INF:BANDWIDTH=1661320,AVERAGE-BANDWIDTH=1568336,VIDEO-RANGE=SDR,CODECS="avc1.4d401e,mp4a.40.2",RESOLUTION=768x432,FRAME-RATE=25.000,AUDIO="program_audio_0"
medias/108210-039-B_v432.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=2399048,AVERAGE-BANDWIDTH=2309088,VIDEO-RANGE=SDR,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=1280x720,FRAME-RATE=25.000,AUDIO="program_audio_0"
medias/108210-039-B_v720.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=963056,AVERAGE-BANDWIDTH=918552,VIDEO-RANGE=SDR,CODECS="avc1.4d401e,mp4a.40.2",RESOLUTION=640x360,FRAME-RATE=25.000,AUDIO="program_audio_0"
medias/108210-039-B_v360.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=445040,AVERAGE-BANDWIDTH=425656,VIDEO-RANGE=SDR,CODECS="avc1.42e00d,mp4a.40.2",RESOLUTION=384x216,FRAME-RATE=25.000,AUDIO="program_audio_0"
medias/108210-039-B_v216.m3u8

#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=1349200,AVERAGE-BANDWIDTH=754896,VIDEO-RANGE=SDR,CODECS="avc1.4d401f",RESOLUTION=1280x720,URI="medias/108210-039-B_v720_iframe_index.m3u8"
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=709880,AVERAGE-BANDWIDTH=396912,VIDEO-RANGE=SDR,CODECS="avc1.4d401e",RESOLUTION=768x432,URI="medias/108210-039-B_v432_iframe_index.m3u8"
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=551880,AVERAGE-BANDWIDTH=281248,VIDEO-RANGE=SDR,CODECS="avc1.4d401e",RESOLUTION=640x360,URI="medias/108210-039-B_v360_iframe_index.m3u8"
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=165640,AVERAGE-BANDWIDTH=89920,VIDEO-RANGE=SDR,CODECS="avc1.42e00d",RESOLUTION=384x216,URI="medias/108210-039-B_v216_iframe_index.m3u8"

#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="program_audio_0",LANGUAGE="de",NAME="VA",AUTOSELECT=YES,DEFAULT=YES,URI="medias/108210-039-B_aud_VA.m3u8"

#SPRITES: https://arte-cmafhls.akamaized.net/am/cmaf/108000/108200/108210-039-B/220509185705/medias/108210-039-B_SPR.vtt
```

**selected stream** (`EXT-X-STREAM-INF` - 1280x720)
```
#EXTM3U
#EXT-X-TARGETDURATION:6
#EXT-X-VERSION:7
#EXT-X-MEDIA-SEQUENCE:1
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-MAP:URI="108210-039-B_v720.mp4",BYTERANGE="1752@0"
#EXTINF:6.000,
#EXT-X-BYTERANGE:1595022@1752
108210-039-B_v720.mp4
#EXTINF:6.000,
#EXT-X-BYTERANGE:1679210@1596774
108210-039-B_v720.mp4
...
```

**external audio stream** (`EXT-X-MEDIA`)
```
#EXTM3U
#EXT-X-TARGETDURATION:6
#EXT-X-VERSION:7
#EXT-X-MEDIA-SEQUENCE:1
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-MAP:URI="108210-039-B_aud_VA.mp4",BYTERANGE="1680@0"
#EXTINF:5.991,
#EXT-X-BYTERANGE:100390@1680
108210-039-B_aud_VA.mp4
#EXTINF:5.991,
#EXT-X-BYTERANGE:97542@102070
108210-039-B_aud_VA.mp4
```

**Comment by amurzeau** [comment] 2022-05-18 15:36
> Unfortunately, there is no distinction that can be made between MPEG-TS and fragmented MPEG-4 in the HLS metadata because [only codec metadata is annotated](https://datatracker.ietf.org/doc/html/rfc8216#section-4.3.4.2). Streamlink would need to check HTTP headers or URL paths for certain patterns (eg. file name extensions), which is not reliable, or it would need to check the headers of the very first segment contents for figuring out the stream format, which would be reliable, but no one has bothered to do so because it's not trivial.

In fact, to me, the use of EXT-X-MAP for this case is valid, as explained in https://datatracker.ietf.org/doc/html/rfc8216#section-3.3.
It is used to ensure there is a minimal amount of metadata present in the resulting HLS stream, while avoiding duplication in the underlying file.

Streamlink is doing the right think here.

`sidx` box allows the stream to be seekable, which seems perfectly valid to have it in the original file. But I don't think it should have been included in the Media Initialization Section, as according to [ISO/IEC 14496-12:2015(E)](https://b.goeswhere.com/ISO_IEC_14496-12_2015.pdf), chapter 8.16.3 Segment Index Box:

> Segment Index boxes shall be placed before subsegment material they document, that is, before
any Movie Fragment (‘moof’) box of the documented material of the subsegment

As the segment index boxes are used to seek the media, and that the referenced media must be following the `sidx` box, and that HLS should also provide seeking with both #EXTINF and #EXT-X-BYTERANGE, I think that `sidx` should not be in the Media Initialization Section (especially because its content refer to the first HLS segment only, and not the start of each ones).

And I think that ffmpeg is right when trying to use `sidx` data when encountered in the input stream (as sidx reference the moof box right after).

To confirm this, according to ffmpeg documentation of option "global_sidx" for a DASH output:
> global_sidx global_sidx
>     Write global SIDX atom. **Applicable only for single file, mp4 output, non-streaming mode**.

Also, when testing ffmpeg HLS output with fragmented mp4 format, it generates one sidx box per HLS fragment with the appropriate earliest_presentation_time value for the given HLS fragment.

But the more I read about fragmented MP4, the more I think that it's rather complex and there is no One rule, many realities exists.
ffmpeg try its best to correctly understand every possible combination of boxes that might exist in the wild. And it got better in v5.x for the format used by arte.tv.

What a day for a deep dive into MP4 internals !

**Comment by amurzeau** [comment] 2022-05-18 15:41
As a side note, maybe streamlink plugins will need to be able to add specific options to ffmpeg, for example arte.tv would require use_tfdt (nothing to change here as it is the default in v5.x), but maybe a different plugin will need to disable it because of broken tfdt but good sidx.

This would obviously only make sense only if problematic formats requiring various ffmpeg options happen often.
