### ISSUE TITLE
huya.com plugin not working

### ISSUE THREAD

**Issue by nopsy** [streamlink/streamlink#3037] opened 2020-06-20 14:07 UTC
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Reproduction steps / Explicit stream URLs to test

1. open any stream on huya.com with streamlink

### Log output

```
streamlink https://www.huya.com/lingyic best -p mpv --loglevel debug
[cli][debug] OS:         Linux-5.7.3-arch1-1-x86_64-with-glibc2.2.5
[cli][debug] Python:     3.8.3
[cli][debug] Streamlink: 1.4.1
[cli][debug] Requests(2.24.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin huya for URL https://www.huya.com/lingyic
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (hls)
[stream.hls][debug] Reloading playlist
[cli][error] Try 1/1: Could not open stream <HLSStream("http://b''/")> (Could not open stream: Unable to open URL: http://b''/ (HTTPConnectionPool(host="b''", port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f42954b6100>: Failed to establish a new connection: [Errno -2] Name or service not known'))))
error: Could not open stream <HLSStream("http://b''/")>, tried 1 times, exiting

```

**Comment by bastimeyer** [comment] 2020-06-20 15:17
> Streamlink: 1.4.1

Duplicate of #3001

Use the **latest dev** version from the master branch.
https://streamlink.github.io/install.html

**Closed by bastimeyer** 2020-06-20 15:17 UTC
